### ISSUE TITLE
LessQL

### ISSUE THREAD

**Issue by morris** [thechangelog/ping#102]
A lightweight data access layer for SQL databases (PDO), similar to NotORM, with many improvements.

http://lessql.net/
https://github.com/morris/lessql

I've been using it for a long time personally, but never got around to polishing it for release. Would be happy to if you feature it!

**Comment by jerodsanto** [comment]
@morris we're including LessQL in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for letting us know about it! :beers:

**Comment by morris** [comment]
Great, thanks! :blush:
