### ISSUE TITLE
LoggerKit

### ISSUE THREAD

**Issue by igorastvorov** [thechangelog/ping#103]
This project is intended to ease developer's life. It provides a handy API that is automatically "removed" from the Release version of your application. However, in Debug mode you are able to use that API to log messages at certain levels (ASSERT, INFO, WARNING, ERROR). Such logs can also provide a line number, file where the logging API is invoked and a [function/method]-caller that invoked logging API.

[GitHub page](https://github.com/igorastvorov/LoggerKit)

**Comment by jerodsanto** [comment]
@igorastvorov we're including LoggerKit  in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe if you haven't already. You should see it hit your inbox this weekend. :)

Thanks for sharing! :beers:
