### ISSUE TITLE
readthis - redis based cache

### ISSUE THREAD

**Issue by sorentwo** [thechangelog/ping#105]
The fastest active support compliant persistent cache available. Backed by redis and focused on speed as well as quality, it is faster than dalli for all benchmarked operations.

Redis provides so much more than memcached, it should be the go-to cache store for rails applications!

More info, benchmarks, docs and specs at https://github.com/sorentwo/readthis

**Comment by jerodsanto** [comment]
@sorentwo we're including readthis in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by sorentwo** [comment]
@jerodsanto: Awesome, thanks!
