### ISSUE TITLE
episode focusing on Elixir?

### ISSUE THREAD

**Issue by alxndr** [thechangelog/ping#106]
Hey y'all,

The [Elixir](http://elixir-lang.org/) language released [version 1 in September 2014](http://elixir-lang.org/blog/2014/09/18/elixir-v1-0-0-released/). This new language runs on Erlang's virtual machine (and so can access Erlang code including the OTP framework) and has syntax partially inspired by Ruby. I think it'd be interesting to hear about putting together and/or using and/or learning a new language, especially with its foundation in Erlang.

Guest ideas?
* José Valim, the creator of the language, also a prolific contributor to Rails core
* Dave Thomas, of Pragmatic Bookshelf, wrote *Programming Elixir*
* authors of one/more of the active frameworks/libraries/clients available
* ...

Topic ideas?
* threading/processes/servers-and-clients as a first-class concept
* [a comment from José](https://news.ycombinator.com/item?id=8189186) which lays out how lessons learned from Dynamo made it into other frameworks/libraries, and also mentions some Elixir projects/tools which take inspiration from interesting sources
* what's OTP like
* are erlang's performance numbers real
* ...

**Comment by jerodsanto** [comment]
@alxndr we'd LOVE to do a show on Elixir! @josevalim would you – and/or others on the Elixir core team – be interested in joining us on The Changelog?

**Comment by SebastianSzturo** [comment]
+1

**Comment by jerodsanto** [comment]
Closing this as we've lined up an Elixir-related show in #130. Thanks for the suggestion!

**Comment by alxndr** [comment]
:+1:

**Comment by alxndr** [comment]
Whoa finally got around to listening to 147 and thanks for the shoutout!

(And high five for getting my last name right! :raised_hands:)

**Comment by SebastianSzturo** [comment]
Really great and interesting episode. Also thanks to my shoutout!
(And don't worry about not getting my lat name right :P)

**Comment by adamstac** [comment]
:+1: 

BTW episode 194 is with @josevalim :)
