### ISSUE TITLE
Crib — a dynamic way of quickly exploring REST APIs

### ISSUE THREAD

**Issue by rafalchmiel** [thechangelog/ping#107]
[Crib](https://github.com/rafalchmiel/crib) allows you to dynamically explore most REST APIs using an intuitive syntax that resembles a HTTP URI path. It uses [Sawyer](https://github.com/lostisland/sawyer) under the hood so things like authentication and passing certain headers to every request is simple.

*Crib takes a lot of its inspiration from [Blanket](https://github.com/inf0rmer/blanket) (a relatively new project that got popular quite quickly). The aim of this project is not to compete with Blanket, but to produce a very different _flavour_ of it.*

Install the latest version of Crib via RubyGems:

```bash
$ gem install crib
```

In the below example, we are using the Dribbble API to [get the name of the currently authenticated user](http://developer.dribbble.com/v1/users/#get-the-authenticated-user), then just a single user in order to demonstrate arguments:

```ruby
dribbble = Crib.api('https://api.dribbble.com/v1') do |http|
  http.authorization 'Bearer', '1aea05cfdbb92294be2fcf63ee11b412fd88c65051bd3144302c30ae8ba18896'
end

me = dribbble.user
me._get.name
 # => "Rafal Chmiel"

dan = dribbble.users('simplebits')
dan._get.name
 # => "Dan Cederholm"
```

Another, more complex example:

```ruby
dribbble = Crib.api('https://api.dribbble.com/v1') do |http|
  http.headers[:user_agent] = 'crib'
  http.authorization 'Bearer', '1aea05cfdbb92294be2fcf63ee11b412fd88c65051bd3144302c30ae8ba18896'
  http.response :logger # take note of this, it logs all requests in the following examples
end

dribbble.users('simplebits')._get.id
 # I, [2015-01-02T14:59:20.183319 #6990]  INFO -- : get https://api.dribbble.com/v1/users/simplebits
 # D, [2015-01-02T14:59:20.183436 #6990] DEBUG -- request: User-Agent: "crib"
 # Authorization: "Bearer 1aea05cfdbb92294be2fcf63ee11b412fd88c65051bd3144302c30ae8ba18896"
 # I, [2015-01-02T14:59:20.183742 #6990]  INFO -- Status: 200
 # D, [2015-01-02T14:59:20.183890 #6990] DEBUG -- response: server: "nginx"
 # date: "Fri, 02 Jan 2015 14:59:20 GMT"
 # content-type: "application/json; charset=utf-8"
 # (...)
 #
 # => 1
```

**Comment by jerodsanto** [comment]
@rafalchmiel cool stuff! We're including Crib in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe so you don't miss the coverage. :)

Thanks for letting us know about it! :beers:

**Comment by rafalchmiel** [comment]
Great, thanks a lot!
