### ISSUE TITLE
Noobs

### ISSUE THREAD

**Issue by drvinceknight** [thechangelog/ping#108]
Loving the podcast: thanks!

Over the past 3 years I've gone from complete OSS ignorant to humbly/shyly contributing to some projects. I still very much consider myself a noob and would have thought there are others like me.

I think a neat episode could be an overview of 'getting involved with OSS'. From the basics of a good language to learn, version control, to etiquette right up to pull requests etc...

I think this could be a helpful episode (not only for myself but) to all newcomers to OSS.

**Comment by tejasbubane** [comment]
Looks like @tenderlove wants to talk on OSS: https://twitter.com/tenderlove/status/556548218285461504. Topic for the next talk @thechangelog?

**Comment by jerodsanto** [comment]
Thanks for the heads up, @tejasbubane. We reached out to him on Twitter. Hopefully he's up for it!

**Comment by jerodsanto** [comment]
@drvinceknight I think the newbies show would be great, too. I just don't know who to join us for that...

**Comment by drvinceknight** [comment]
I know (https://github.com/evildmp): one of the Django core developers, he has a "Don't be afraid to commit" tutorial which he runs. I could approach him if he sounds appropriate?

**Comment by adamstac** [comment]
I think getting @beverlynelson on this show would awesome too, but she'd come with a Ruby based direction since that's where she applies her teaching skills.

**Comment by jerodsanto** [comment]
@drvinceknight I think what @sarony is doing with [CodeNewbie](http://www.codenewbie.org) addresses this need better than we could with a single episode of The Changelog.

I'm going to close this for now, but if Saron is interested we'd love to have her on the show to talk about what she's up to (and we'd be happy to join her on CodeNewbie as well).

**Comment by sarony** [comment]
@jerodsanto. I'd love to do a podcast swap! Feel free to shoot me an email and we can figure out scheduling :) saron@codenewbie.org

**Comment by jerodsanto** [comment]
@drvinceknight I know this wasn't _exactly_ what you were suggesting, but I wanted to let you know that this suggestion spawned TWO podcasts!

1. [Episode 176 of The Changelog: CodeNewbie and Community with Saron Yitbarek](http://chagelog.com/176)
2. [Episode 57 of CodeNewbie: Podcasting with Changelog](http://www.codenewbie.org/podcast/podcasting-with-changelog)

I hope you enjoy these shows. Thanks for the suggestion! :metal:

**Comment by drvinceknight** [comment]
Thanks! I'm just settling down to listen to them now :)
