### ISSUE TITLE
chef-runner - The fastest way to run Chef cookbooks

### ISSUE THREAD

**Issue by mlafeldt** [thechangelog/ping#109]
The goal of chef-runner is to speed up your [Chef](https://www.chef.io/) development and testing workflow by allowing you to change infrastructure code and get *immediate feedback*.

chef-runner was originally developed as a fast alternative to the painfully slow `vagrant provision`. The tool has since evolved and can now be used to rapidly provision not only local Vagrant machines but also remote hosts like EC2 instances.

To further shorten the feedback loop, chef-runner integrates with Vim so you don't have to leave your editor while hacking on recipes.

https://github.com/mlafeldt/chef-runner

**Comment by jerodsanto** [comment]
@mlafeldt we're including chef-runner in our next issue of [Weekly](http://thechangelog.com/weekly/). Cool stuff! :beers:

**Comment by mlafeldt** [comment]
That'd be totally awesome! Thank you!
