### ISSUE TITLE
Databound - providing Javascript a simple CRUD API to the Ruby on Rails backend

### ISSUE THREAD

**Issue by Nedomas** [thechangelog/ping#111]
I've open-sourced a Ruby gem (+ Javascript library) that will let you stop rewriting the CRUD glue between your Javascript and Rails backend. http://databound.me

Databound provides Javascript a simple CRUD API to the Ruby on Rails backend.
It lets you use methods like ``create``, ``update``, ``destroy`` in the front-end while handling all the setup and providing basic security out of the box.

Thank you! :rocket:

**Comment by jerodsanto** [comment]
@Nedomas we're featuring Databound in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe today and look for it to :ship: this weekend. Thanks for sharing! :beers:
