### ISSUE TITLE
Trello -> Newsletter workflow

### ISSUE THREAD

**Issue by jlecour** [thechangelog/ping#112]
Hi,

Did you post somewhere your workflow to build the newsletter from a Trello board?

I think it's a brilliant idea, and I'd like to do something similar.

Thanks

**Comment by studiomohawk** [comment]
I'd love to know that too!

**Comment by jerodsanto** [comment]
We hope to publish this real soon! I'd say the draft is 60% complete at the moment. Hopefully I'll have some time over the weekend to complete it. I'll definitely post here once it's ready for ya!

**Comment by studiomohawk** [comment]
Looking forward to it!

**Comment by jerodsanto** [comment]
Ask and you shall receive :smile: 

http://thechangelog.com/trello-as-a-cms/

Hope you get something out of it!

**Comment by adamstac** [comment]
:tada:

**Comment by jlecour** [comment]
Thanks you so much. :clap:
