### ISSUE TITLE
Github Pulse - OS X StatusBar app to help you remember to contribute every day on Github

### ISSUE THREAD

**Issue by tadeuzagallo** [thechangelog/ping#113]
I really believe contributing every day on OSS is one of the best practices a developer can keep, I try to keep it myself, but it happens that I forget to contribute on a busy day, or just keep pushing it till later... So I create [GithubPulse](https://github.com/tadeuzagallo/GithubPulse) to help me get some motivation and also remember me on busy days.

It's icon becomes red on the status bar if you haven't commited on the ongoing day yet, and once you've made some contribution it'll turn blue again. If the end of the day is approaching and you still haven't commited it'll show you a notification as an extra motivation/reminder (just to be clear, it'll only notify you once, and just if you haven't commited so far)

**Comment by jerodsanto** [comment]
@tadeuzagallo cool stuff! We [wrote you up](http://thechangelog.com/github-pulse-can-help-keep-streak-alive/) this morning. :beers:
