### ISSUE TITLE
Classified, A new moduler opensource css framework.

### ISSUE THREAD

**Issue by waleedq** [thechangelog/ping#114]
Classified is built to help web developers and UI designers to write more standard and less messy css code. The project generate a class name for most of the css attributes which will let the developers use the classes to apply the needed css attribute. 

normally in the common css styling attributes like (margines, paddings, font-size, borders....etc) we always use different values for each element which give us inconsistent styling where some elements will have 10px margin and others will have 13px margin.. and so on.

Using Classified we have generated a special classes for these casses which will give you the ability to add the "margin-top-10" class to the element of interst which will give you a 10px margin, using this class on the other elements would give you an consistent styling.

you can check out the project at classfied.org.

Thank You.

**Comment by jerodsanto** [comment]
@waleedq have a working link for us to check out?

**Comment by waleedq** [comment]
@jerodsanto here you go mate http://www.classfied.org

**Comment by jerodsanto** [comment]
@waleedq thanks! we're including Classified in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe and see! :beers:
