### ISSUE TITLE
Crafty.css | A lightweight pure CSS boilerplate for RWD projects

### ISSUE THREAD

**Issue by trlllst** [thechangelog/ping#115]
When I first saw [Skeleton](https://github.com/dhg/Skeleton) v2 by @dhg I was really impressed with its simplicity and how it allowed you to jump directly into a project with just enough default element styling and a basic grid - allowing you to bypass the process of choosing a larger framework, at least until you were ready to adopt one. I was already using something like this - basically a collection of LESS snippets  I gathered over the years to do almost the same thing whenever I started a new project, but it was a mess. No structure, poorly commented, etc. I thought about cleaning it up and open-sourcing it for a while and Skeleton gave me the motivation to push it through. Where I thought I could bring something new to the table was with the grid. I had been using a LESS port I wrote from Neat and Bourbon from Thoughtbot, Inc for a while and always loved their grid system. I used their methods to create a flexible, nestable grid in pure-css so it was plug-and play like the rest of what has become Crafty.css. All the credit for the grid goes to the folks who maintain that project - I just used it to build the grid. It added some weight but I found the trade-off to be well worth it.

**Comment by trlllst** [comment]
Hey everyone I just wanted to follow-up and let you know Crafty.css is revamped and moved to a new repo. The original has been deleted and the package was removed from Bower. I'll post a follow-up when  its successor is ready for prime time.

**Comment by jerodsanto** [comment]
ok let us know when the new thing is up!
