### ISSUE TITLE
Zebus | A lightweight Peer to Peer Service Bus in .NET

### ISSUE THREAD

**Issue by ablanchet** [thechangelog/ping#116]
Zebus is a lightweight peer to peer service bus, built with [CQRS](http://martinfowler.com/bliki/CQRS.html) principles in mind. It allows applications to communicate with each other in a fast and easy manner. Most of the complexity is hidden in the library and you can focus on writing code that matters to you, not debugging messaging code.

-----

Zebus is **peer to peer**, so it does not depend on a broker to dispatch messages between the peers. This allows it to reach a throughput of 140k msg/s and a roundtrip latency under 500µs (have a look at the [Performance page](https://github.com/Abc-Arbitrage/Zebus/wiki/Performance) on our wiki for details).

It is **resilient** thanks to the absence of a broker and an optional persistence feature that ensures that messages are not lost if a peer is down or disconnected.

It is **stable**, since we have been using it on a production environment for more than a year.

---

Repo : https://github.com/Abc-Arbitrage/Zebus
Nuget : https://www.nuget.org/packages/Zebus/

**Comment by jerodsanto** [comment]
@ablanchet we're including Zebus in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe so you don't miss it. Thanks for sharing! :beers:

**Comment by ablanchet** [comment]
Thanks ! :smile:
