### ISSUE TITLE
Trello as a CMS

### ISSUE THREAD

**Issue by jonknapp** [thechangelog/ping#117]
Loved the idea in your post and was looking for a similar solution for a group I run. I already curate content in Trello, so would be interested in generalizing the flow / output so that I can use it with Mailchimp or Mandrill.

Not sure of a timeline that I can provide, but was already going to open source the solution if I built it myself.

**Comment by rafalchmiel** [comment]
:+1: 

I read the article and also :heart: the idea. It'd be a pleasure to help you guys out with open sourcing it.

**Comment by jerodsanto** [comment]
@jonknapp awesome. MailChimp can consume raw HTML just like Campaign Monitor, so swapping in mailing list providers should be super easy.

@rafalchmiel glad to hear it!

**Comment by jonknapp** [comment]
https://github.com/niftylettuce/node-email-templates could be of some assistance.

**Comment by jonknapp** [comment]
requires quite a few things to be preinstalled though...

**Comment by jonknapp** [comment]
or the Ruby direction: https://github.com/premailer/premailer

**Comment by rafalchmiel** [comment]
I :+1: Premailer. I was guessing the project is going to be wrapped as a Ruby gem?

**Comment by jonknapp** [comment]
Depends on how it shakes out. I'm not sure of how we'll integrate with
other services at this point.

**Comment by jonknapp** [comment]
I started a project with a colleague over the weekend that we paired on for a local tech user group.  If people are interested, feel free to ping me if you'd like to get involved.

https://github.com/akron-io/trello-ems

I'm going to close out this issue so we move the conversation to the project.

**Comment by jerodsanto** [comment]
:+1: let us know when it's ready and we'll write about it!

**Comment by jonknapp** [comment]
Of course!  I'd be interested in chatting sometime about what requirements you have on your side too. We were having difficulty guessing what you used Middleman for and would like to talk about the possibility of different deployment methods.

**Comment by jerodsanto** [comment]
If we were building from scratch then we wouldn't have used Middleman. Adam had already built the newsletter w/ Middleman (for sass compilation, erb helpers, etc.) and it was less work to take it out than it was to simply integrate with it.

I literally hacked the first version together on a Sunday afternoon and that was "good enough" to get us publishing, so the drive to genericize and improve was quite low. :wink: 

(one reason we published the article was so others might take the initiative!)
