### ISSUE TITLE
#137 HuBoard

### ISSUE THREAD

**Issue by Anzumana** [thechangelog/ping#118]
Great show.
Definitely gonna try HuBoard.

Wouldn't it be great if the Shownotes would be a markdown file in a repo so that if there is something mentioned, that was not added to the shownotes we as listeners could add those links later.
Just a though.
Regards,
Anzumana

**Comment by jerodsanto** [comment]
@Anzumana I love the idea of collaborative show notes. Unfortunately, we are not set up for that just yet. We have a few ideas floating around on this front, but nothing has quite materialized yet.

Thanks for writing in!

**Comment by Anzumana** [comment]
yeah i just listend to episode 125 about jekyll.
@adamstac  explained why you use wordpress ( multiple author support as one of the main reasons).
and asked @parkr if there is something in the works for that.
@parker explained that there is a project that aims to solved that problem.
But the development team on that one ,is not rly active anymore.

**Comment by parkr** [comment]
Jekyll posts don't have authors built-in (you would specify it as a custom field and write your template to use it) so I'm not sure what the problem would be. One could specify `authors: [adam, jerod]` and list them out in the template. If there is more biographical data, provide a YAML or JSON data file with that data and display that, too.

If one means multi-access when they say "multiple authors," then that's a version control issue. Jekyll is just files. Files in, files out. Determining access to those files is up to the owners of the site. GitHub makes this easy with pull requests.

**Comment by darkpixel** [comment]
Loved the episode on Huboard.  Huboard needs a documentation on its features.

**Comment by jerodsanto** [comment]
@darkpixel thanks for writing in! @rauhryan some feedback for you here.

**Comment by rauhryan** [comment]
@darkpixel I've a gist with a ton of gif's on it [HuBoard gif style](https://gist.github.com/rauhryan/5f3eeb75fe1237a02a26) and the webhooks and label conventions are documented in the [wiki](https://github.com/rauhryan/huboard/wiki)

**Comment by darkpixel** [comment]
That's exactly what I was looking for.  Thanks @rauhryan.  It's a great app!

**Comment by jerodsanto** [comment]
Good feedback everyone, thanks!

**Comment by KevM** [comment]
I was just catching up on podcasts and saw @rauhryan talked to y'all. 

We love HuBoard and use it all the time. Ryan and crew are pretty great about feedback and taking suggestions and making them into features. 

Thanks for the look behind the scenes at HuBoard the show was really interesting.
