### ISSUE TITLE
[podcast suggestion] Known - a personal (indieweb) publishing platform

### ISSUE THREAD

**Issue by kylewm** [thechangelog/ping#119]
Known (https://withknown.com) is a publishing platform grown out of the @IndieWeb / IndieWebCamp movement, that is making a run as an open source business. The software is sort of like a self-hosted Tumblr, that integrates with the big social networks (e.g., Twitter, Facebook, Foursquare). The idea is you post first on your personal site and syndicate to the networks where your friends are.

There are a few aspects that I think could make it interesting
- Tech-wise, they chose PHP/MySQL for widest possible availability. Early on they were using Mongo and got lots of pushback from potential users, so decided to modify the database interface to support both (which is kind of crazy)
- Finding the limits of shared hosting, what can and can't be done. (worker queues, websockets)
- Wordpress.com-type business model with free and paid hosting and also an open source totally free self-hosted version.
- The co-founders (@benwerd and @erinjo) are smart and fun to talk to. Lots of experience and background in this area.
- Indiewebcamp (https://indiewebcamp.com) is pretty interesting in and of itself and would be great fodder for conversation (I'm biased :smile_cat:).

Thanks for your consideration!

**Comment by benwerd** [comment]
Oh wow. @kylewm, thank you so much for the submission!

**Comment by erinjo** [comment]
Awesome!  Thanks @kylewm.

**Comment by jerodsanto** [comment]
@kylewm thanks for the suggestion! Known was not previously on our radar.

@benwerd and @erinjo we'd love to have you on the show! Please email editors@changelog.com and we will iron out the details.

**Comment by physcocode** [comment]
as a known enthusiast myself I am bit excited of what happen to this podcast schedule since its already 2017
PS: I am big fan of known and indieweb moment in general :)

**Comment by pdurbin** [comment]
I met @benwerd and @erinjo at an IndieWebCamp a while back and I'd be happy to hear them on The Changelog too!

**Comment by jerodsanto** [comment]
We super dropped the ball on this show, y'all. Apologies! 

I was picking it back up this morning and it appears that Known has shifted its focus from a general-purpose publishing platform to an educational platform. Is it still relevant/best for this conversation around the Indie Web?

One other show we've considered (but never pulled the trigger on) is one w/ Manton Reece about micro.blog and JSON feed. I assume that would also fit under this umbrella, @kylewm?

**Comment by benwerd** [comment]
I would say it's still very relevant, fwiw. The business picked up a particular focus, but the open source project remains open, and powers a bunch of personal websites ([including my own](https://werd.io)). It continues to be under active development.

**Comment by physcocode** [comment]
[my website](http://physcocode.com) is powered by known to and the best example of overall indieweb implementation  i have seen till date is known . I would love to hear a known podcast <3

**Comment by jerodsanto** [comment]
Sounds good, folks. I just emailed Ben to get it scheduled. Thanks for your patience, hopefully it'll be rewarded! 😜
