### ISSUE TITLE
cargo: docker hub without docker

### ISSUE THREAD

**Issue by robinmonjo** [thechangelog/ping#120]
Hi,

I have written a command line tool to use the docker hub without docker. Meaning, LXC (or other) users can pull and push docker image on the docker hub.

Check the repo here: https://github.com/robinmonjo/cargo
And the how to here: https://gist.github.com/robinmonjo/f6ca0f85a204c8103e10

**Comment by jerodsanto** [comment]
@robinmonjo we're including _krgo_ (we noticed the name change) in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
