### ISSUE TITLE
JavaScript/node.js task runner/continuous integration

### ISSUE THREAD

**Issue by gmarland** [thechangelog/ping#121]
Hi,

I've been working on a JavaScript/node.js task runner/continuous deployment server I've called GhostRunner. You can string together scripts into sequences that can then either be scheduled to run at a certain time or started via an HTTP POST.

The repo is here: https://github.com/gmarland/GhostRunner
A site where an installer can be downloaded/example videos are is here: http://goghostrunner.com

I'd really appreciate any thoughts/feedback!

**Comment by jerodsanto** [comment]
@gmarland cool stuff! We're including GhostRunner in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by gmarland** [comment]
Thanks loads! I'm really excited! Just to say, I am currently working on a new version of it that will allow the controlling of multiple task runners on any OS from a centralized website.
