### ISSUE TITLE
SelectorGadget

### ISSUE THREAD

**Issue by cantino** [thechangelog/ping#122]
http://www.selectorgadget.com

Open source, 4 years old, but recently re-written in CoffeeScript and released as a Chrome extension.

**Comment by jerodsanto** [comment]
@cantino we're including SelectorGadget in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by cantino** [comment]
Awesome, thanks @jerodsanto!
