### ISSUE TITLE
Handy macros

### ISSUE THREAD

**Issue by igorastvorov** [thechangelog/ping#123]
I've created project that contains a collection of handy macros grouped by languages. Feel free to contribute. https://github.com/igorastvorov/handy-macroses

**Comment by jerodsanto** [comment]
@igorastvorov broken link. :frowning: 

Have one that works?

**Comment by igorastvorov** [comment]
@jerodsanto nope, I've removed that project.

**Comment by jerodsanto** [comment]
Fair enough. Don't hesitate to ping us again in the future!
