### ISSUE TITLE
Subtle.css

### ISSUE THREAD

**Issue by trlllst** [thechangelog/ping#124]
[Subtle.css](http://trlllst.github.io/subtle.css/) is a lightweight pure-css boilerplate with a fluid, fully nestable grid, some basic typography and common element styling. Much like the excellent, even lighter framework alternative [Skeleton](http://getskeleton.com) - it's purposely lightweight and meant to do a few things quickly and efficiently when starting a responsive design project. Normalize.css is now included as a dependency and a few upgrades to the code were added to make it even more user friendly out of the box. It stands pretty well on its own or it can be imported to any existing framework for some useful defaults and a rock-solid grid.  It's the spiritual successor to crafty.css, my first attempt at a boilerplate. I'd love to hear any feedback from the dev community.

**Comment by jerodsanto** [comment]
@trlllst we're including Subtle.css in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by trlllst** [comment]
Wow. That's amazing! Glad you guys dig it :)
