### ISSUE TITLE
Hound - A Lightning Fast Code Search Tool

### ISSUE THREAD

**Issue by jklein** [thechangelog/ping#125]
I just open sourced [Hound](https://github.com/etsy/Hound), and wrote a [blog post](https://codeascraft.com/2015/01/27/announcing-hound-a-lightning-fast-code-search-tool/) about it.

Hound uses a React front-end to talk to a Go backend that maintains an index of an arbitrary number of repositories to search. Thanks!

**Comment by jerodsanto** [comment]
@jklein we [linked you up](http://thechangelog.com/hound-lightning-fast-code-search-tool/) this morning. We'll also give you a shout in our next issue of [Weekly](http://thechangelog.com/weekly). Good stuff! :beers:

**Comment by jklein** [comment]
:clap: much appreciated!
