### ISSUE TITLE
asprom - assault profile monitor

### ISSUE THREAD

**Issue by daimoniac** [thechangelog/ping#126]
https://github.com/daimoniac/asprom

asprom is a firewall compliance scanner. You define a profile of which services your network(s) should offer to users. The scanner automatically and regularly portscans your networks using nmap and reports any aberrations from the defined profile.
Don't be afraid - it is easily installed, very user-friendly and doesn't require any knowledge besides basic tcp/ip concepts :-)
This functionality can be used to ascertain PCI-DSS, BSI-Grundschutz or DIN 27001 compliance of stateful firewalls.

**Comment by adamstac** [comment]
Woot! Thanks @daimoniac :stuck_out_tongue_winking_eye:

**Comment by daimoniac** [comment]
Hi Adam, hi changelog team,

i expanded a bit to make it easier for asprom to hit the market. Asprom got a homepage now.

http://www.asprom.de/

You can find screenshots and a virtual appliance to download there. It works right from the start, provided you have DHCP in your network.

I hope you find the time to try the software and you find it a pleasant experience.

With kindest regards,
Stefan

**Comment by jerodsanto** [comment]
@daimoniac we're including asprom in our next issue of [Weekly](http://thechangelog.com/weekly/). Cool stuff! :beers:
