### ISSUE TITLE
Zato 2.0 - ESB, SOA, REST, APIs and Cloud Integrations in Python

### ISSUE THREAD

**Issue by dsuch** [thechangelog/ping#127]
Hello,

I'm very happy to let you know that a new version of the Python-based
middleware platform and backend application server has just been released.

https://zato.io/docs

Version 2.0 brings dozens of interesting features building on and greatly enriching already existing capabilities.

Major additions include:

* A [Dockerfile](https://zato.io/docs/2.0/admin/guide/install-docker.html) to install a fully-operational cluster of 2 servers, load-balancer and web-admin in 10 minutes

* New connection types: Cloud [Amazon S3](https://zato.io/docs/web-admin/cloud/aws/s3.html) and [OpenStack Swift](https://zato.io/docs/web-admin/cloud/openstack/swift.html), [Cassandra](https://zato.io/docs/web-admin/conn-def/cassandra.html) [CQL](https://zato.io/docs/web-admin/query/cassandra.html), [Solr](https://zato.io/docs/web-admin/search/solr.html), [ElasticSearch](https://zato.io/docs/web-admin/search/es.html), [Odoo/OpenERP](https://zato.io/docs/web-admin/outgoing/odoo.html), [SMTP](https://zato.io/docs/web-admin/email/smtp.html) and [IMAP](https://zato.io/docs/web-admin/email/imap.html)

* Redis-based [REST publish/subscribe](https://zato.io/docs/pubsub/index.html)

* REST [services](https://zato.io/docs/progguide/rest/services.html), [channels](https://zato.io/docs/progguide/rest/channels.html), [outgoing connections](https://zato.io/docs/progguide/rest/outconns.html) and [a helper JSON adapter](https://zato.io/docs/progguide/rest/json-adapter.html)

* [HTTP GUI Audit Log](https://zato.io/docs/web-admin/audit-log/http/index.html) for requests and responses
* Asynchronous integration patterns: [fan-out/fan-in](https://zato.io/docs/progguide/patterns/fan-out-fan-in.html), [parallel execution](https://zato.io/docs/progguide/patterns/parallel-exec.html) and [invoke/retry](https://zato.io/docs/progguide/patterns/invoke-retry.html)

* [SQL](https://zato.io/docs/web-admin/notif/sql.html) and [OpenStack Swift](https://zato.io/docs/web-admin/notif/cloud/openstack/swift.html) notifications

* New security mechanisms: [RBAC](https://zato.io/docs/web-admin/security/rbac/overview.html) (Role-Based Access Control), [SSL/TLS](https://zato.io/docs/admin/guide/tls/overview.html), [OAuth](https://zato.io/docs/web-admin/security/oauth.html), [API Keys](https://zato.io/docs/web-admin/security/apikey.html), [XPath-based](https://zato.io/docs/web-admin/security/xpath.html), [NTLM](https://zato.io/docs/web-admin/security/ntlm.html), [Amazon AWS](https://zato.io/docs/web-admin/security/aws.html)

* Re-usable [JSON Pointer](https://zato.io/docs/web-admin/messages/json-pointer.html) and [XPath](https://zato.io/docs/web-admin/messages/xpath.html) expressions

* New Suds-based [SOAP connections](https://zato.io/docs/progguide/examples/soap.html#progguide-examples-soap-invoking-wsdl)

* [Redis HA](https://zato.io/docs/admin/guide/redis-ha/sentinels.html) with Sentinels

* [Distributed locks](https://zato.io/docs/progguide/dist-locks.html)

* Framework for [API testing](https://github.com/zatosource/zato-apitest) (zato-apitest - API Testing for Humans)

* [rc.d scripts and systemd integration](https://github.com/zatosource/zato-build/tree/master/init_scripts)

* New [SimpleIO](https://zato.io/docs/progguide/sio.html) data types:  CSV, Dict, Float, List, ListOfDicts, Opaque

* [HTML responses](https://zato.io/docs/progguide/html.html) with Django templates

* [Bash completion](https://github.com/zatosource/zato-build/blob/master/bash_completion/zato)

The [changelog] (https://zato.io/docs/project/changelog.html) lists all the updates that are on top of what Zato has had since the initial release: [clustering](https://zato.io/docs/architecture/overview.html), [scheduling](https://zato.io/docs/progguide/scheduler.html), [hot-deployment](https://zato.io/docs/admin/guide/installing-services.html), [GUI](https://zato.io/docs/web-admin/intro.html), [CLI](https://zato.io/docs/admin/cli/index.html), [statistics](https://zato.io/docs/stats/guide.html), [Plain HTTP](https://zato.io/docs/web-admin/channels/plain-http.html), [SOAP](https://zato.io/docs/web-admin/channels/soap.html), [AMQP](https://zato.io/docs/progguide/examples/amqp.html), [FTP(S)](https://zato.io/docs/web-admin/outgoing/ftp.html), [JMS WebSphere MQ](https://zato.io/docs/progguide/examples/jms-wmq.html), [ZeroMQ](https://zato.io/docs/progguide/examples/zmq.html) and more.

The principles behind the project are laid out in the [no-nonsense intro to ESB and SOA](https://zato.io/docs/intro/esb-soa.html).

Cheers!

**Comment by jerodsanto** [comment]
@dsuch we're including Zato 2.0 in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
