### ISSUE TITLE
The Changelog's 2015 Conference Scene

### ISSUE THREAD

**Issue by jerodsanto** [thechangelog/ping#129]
We attended [Keep Ruby Weird](http://keeprubyweird.com) last fall and had a blast. We shot some awesome video (more on that soon), handed out lots of swag, and met tons of great people.

We'd love to expand our conference attendance this year, but Adam and I both have family, so we need to plan ahead which conferences to go to so we can make it worth it. Ideally, we'd like to go to 4 conferences (roughly 1 per quarter).

Here are the confs currently on our radar (ordered by date):

- [x]  [Space City JS](http://spacecityjs.com/) in Houston, Texas - March 27-28
- [x]  [GopherCon](http://www.gophercon.com/) in Denver, CO - July 7-10th
- [x]  [NEJS Conf](http://nejsconf.com) in Omaha, Nebraska - August 7
- [ ]  <strike>[Strange Loop](https://thestrangeloop.com) in St. Louis, Missouri - Sept. 24-26</strike>

Some factors we'd like to optimize for:

- Polyglot, if possible - we don't want to focus too much on Ruby and JavaScript alone, which is possible, given our roots
* Keep it hacker - the harder core, the better
* Localish - we'd love to travel the world, but we have families and a budget, so closer to the midwest the more feasible.

How can you help us?

- Help us decide what to attend!
- Tell us what conferences you're attending this year
- If you're coordinating one, invite us to join (we'll bring our video gear and cover the event)

**Comment by bketelsen** [comment]
UM.  GOPHERCON!
http://gophercon.com

Gophers Rule.

**Comment by jerodsanto** [comment]
@bketelsen mid-July, Denver, and hacker for sure. Right in our wheelhouse. Thanks for the suggestion!

**Comment by adamstac** [comment]
Adding to the list http://devnexus.com/

@eisenbergeffect will be there as well https://twitter.com/EisenbergEffect/status/560915957267189760

**Comment by jerodsanto** [comment]
Add [GitHub Universe](https://github.com/blog/1955-get-ready-for-github-universe-october-1-2-in-san-francisco) to the list

**Comment by sjn** [comment]
We'd love to see you in Oslo, Norway, for the first instance of OSDC.no (Open Source Developer's Conference, Nordic). Dates are May 8-10th, 2015 (plus a few more days if you want to hang out at the hackathons?), and if this sounds interesting, we might be able to help with funding. :)

Check out http://osdc.no/cfp.html and/or get in touch with us at organizers@osdc.no :)

**Comment by adamstac** [comment]
@sjn OSDC sounds awesome, and thanks for the invite. We'll have to put this on the list for next year. This year we're focusing on US based conferences since it's our first year of touring. But next year we're planning make it abroad though, so please keep the invite open.

Get in touch here adam@changelog.com if there's anything else we can do to support you?

**Comment by sjn** [comment]
Adam Stacoviak said:
> 
> @sjn OSDC sounds awesome, and thanks for the invite. We'll have to put this
> on the list for next year. This year we're focusing on US based conferences
> since it's our first year of touring. But next year we're planning make it
> abroad though, so please keep the invite open.

Well, I wish you guys would reconsider. We're also organizing a Nordic Perl 
Workshop at the same time, and are planning on having a heavily Perl 6-laden 
schedule. I'd imagine there would be a *lot* of cool interview opportunities 
for you guys - especially considering Larry Wall's Perl 6 annoucement at 
FOSDEM (expexting prodcuction-readiness in 2015) and you guys saying you 
wanted more material from the Perl community. We've got several confirmed core 
developers already in our books. :)

Furthermore, Oslo is *quite* lovely in springtime. (hint, hint)


> Get in touch here adam@changelog.com if there's anything else we can do to
> support you?

If you really can't seize the opportunity, maybe you could help us a little 
with visibility? We're looking for good speakers that are located in northern 
Europe, and lots and lots of FLOSS geeks come visit. :)

We'd very much rather have you guys come visit, though. :D


- Salve J. Nilsen

-- 
#!/usr/bin/env perl
sub AUTOLOAD{$AUTOLOAD=~/.*::(\d+)/;seek(DATA,$1,0);print# Salve Joshua Nilsen
getc DATA}$"="'};&{'";@_=unpack("C*",unpack("u*",':50,$'.#    <sjn@foo.no>
'3!=0"59,6!`%%P\0!1)46%!F.Q`%01,`'."\n"));eval "&{'@_'}";  __END__ is near! :)

**Comment by adamstac** [comment]
I think we need to add this to the list too

http://opensourcebridge.org/

**Comment by adamstac** [comment]
@sjn we're doing US travel this year and some international next year. We're novices with traveling with expensive video gear. Put us on the contact list for next year please.

**Comment by adamstac** [comment]
Ok y'all, I've updated @jerodsanto's original post and conference list to drop CoreOS Fest and OSCON.

For CoreOS Fest we just weren't able to work out the budget to take the team to SF this year. We're working with the CoreOS team to work out the budget further in advance for next year.

For OSCON, July 20-24 collide with other events in our schedule. Again, next year on this one. By then we'll have our conference operations running better. We have families, so generally OSCON's late July timing just makes it hard.

We're pretty solid on GopherCon, NEJS Conf, and Strange Loop.

**Comment by gabesullice** [comment]
Might be too late, but [DrupalCon](events.drupal.org) would be really nice to have covered.

**Comment by adamstac** [comment]
@bketelsen do you have time this week or next to connect on getting a plan in place to have us at GopherCon?

**Comment by bketelsen** [comment]
@adamstac mostly open for the rest of this week - email gophercon@gopheracademy.com with some times that work.

**Comment by nicholaswyoung** [comment]
@adamstac @jerodsanto How about [Nodevember](http://nodevember.org)? It's a pretty cool conference, and extraordinarily well organized – even though it's only the second year. (I spoke at the inaugural event, and was exceptionally pleased with everything.)

I can link you up to the organizers if you would like.

**Comment by adamstac** [comment]
Do it @nicholaswyoung! We'd love to go to this conference.

You can CC editors@changelog.com and @jerodsanto and I will get pinged.

:beers: :tada: :sunglasses:

**Comment by jerodsanto** [comment]
We're closing down our conference tour for the year. Thanks to all for your suggestions! We'll see you in 2016! :cocktail: :beers: :fireworks:
