### ISSUE TITLE
[Guest Idea] Phoenix Framework

### ISSUE THREAD

**Issue by SebastianSzturo** [thechangelog/ping#130]
Please invite @chrismccord and talk with him about Elixir and the Phoenix Web Framework :)

**Comment by dbohdan** [comment]
Seconding this this idea. It would be great to hear more about Elixir and Phoenix on the podcast!

**Comment by SebastianSzturo** [comment]
I pinged him about it on #elixir-lang. He said he would be happy to talk about it! :)

**Comment by dbohdan** [comment]
Great! I will look forward to it.

**Comment by jerodsanto** [comment]
@SebastianSzturo good idea. We've been trying to put together an Elixir show, but hadn't gotten José to commit.

@chrismccord we'd love to have you! If interested, please email editors@changelog.com and we'll iron out the details.

**Comment by dbohdan** [comment]
Here is the podcast, released yesterday: http://thechangelog.com/147/.

**Comment by jerodsanto** [comment]
Yup! @chrismccord was a great guest and we've received great feedback on the show! Thanks for the recommendation!
