### ISSUE TITLE
Jim Tcl 0.76 

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#131]
A new version of Jim Tcl was released today; the release announcement is [here](http://jim.tcl.tk/fossil/doc/www/www/articles/jim-release-0-76/). Jim Tcl is a small-footprint programming language originally created in 2005 by Salvatore Sanfilippo (of [Redis](http://redis.io/) fame) based on Tcl. Jim Tcl can be used as a scripting language on a variety of platforms as well as embedded in other software. Its license (2-clause BSD) is friendly towards static linking.

Jim Tcl has, among others, the following features:
* Unicode (UTF-8) support
* Async file and socket I/O
* IPv4 and IPv6, TCP and UDP sockets
* Tail calls
* Optional OOP support
* SQLite bindings
* POSIX and Win32 bindings

Project homepage: http://jim.tcl.tk/
GitHub repo: https://github.com/msteveb/jimtcl

**Comment by jerodsanto** [comment]
@dbohdan neat, I'd never heard of Jim Tcl. we're including it in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
