### ISSUE TITLE
Hubot-tangocard-highfive

### ISSUE THREAD

**Issue by ben** [thechangelog/ping#133]
Most ChatOps robot plugins are about technical things, but our team decided to hack an HR process. We wrote a [Hubot](http://hubot.github.com/) plugin that allows you to give someone a high-five in a chat room, along with real money:

![](http://ben.straub.cc/images/chatops/!highfive.gif)

I wrote a [blog post](http://ben.straub.cc/2015/01/28/high-five/) about it, which does a better job of telling the story than I can here.

[hubot-tangocard-highfive](https://github.com/ben/hubot-tangocard-highfive)

**Comment by jerodsanto** [comment]
@ben neat idea. We're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
