### ISSUE TITLE
Gozer: A CSS preprocessor built on Gulp and Rework with all the bells and whistles.

### ISSUE THREAD

**Issue by trlllst** [thechangelog/ping#135]
I've been using Sass and Less.js (mostly Less) for a few years and generally loved the workflow, until I realized I may have been over-relying on some of its features. I did feel at times I was getting a little too far from the actual spec and I [wasn't the only one](https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06). Enter [Rework](https://github.com/reworkcss/rework), a framework for manipulating pure CSS and with the help of a handful of community driven plugins, allows you to write your own CSS preprocessor. I originally wrote it in javascript and used io.js to process my css files, but realizing most of the Rework plugins were also available as Gulp plugins really took the workflow into overdrive. This is how I process all my CSS and I'll never look back, at least until they update the official spec. I love the flexibility of defining my own mixins and the uncomplicated syntax. I really hope someone else finds it useful. [View on Github](https://github.com/trlllst/gozer)

**Comment by trlllst** [comment]
Project is being closed in favor of Myth.io. Great learning experience but myth is just so much further along at this point and does everything Gozer did. I really enjoyed building it and learning about how preprocessors work.

**Comment by adamstac** [comment]
Well, we certainly appreciate you sharing this with us @trlllst. Myth.io does look neat. That's nice work @ianstormtaylor and team.

**Comment by trlllst** [comment]
Myth really is the best preprocessor (for me). Even after writing my own with Rework it was clear Myth was much further along, being actively developed, and had syntax that was very close to they way I write CSS, so there was no reason not to switch. Props to @segmentio.

**Comment by ianstormtaylor** [comment]
Thanks guys :)
