### ISSUE TITLE
[podcast idea] CPAN PR Challenge

### ISSUE THREAD

**Issue by mcmillhj** [thechangelog/ping#136]
Neil Bowers[neil@bowers.com] is coordinating a [yearlong event](http://neilb.org/2014/11/29/pr-challenge-2015.html) inspired by December's 24pullrequests. The goal behind the challenge is to help people learn more about Perl and CPAN regardless of experience level, and to help some CPAN modules that need updates but maybe the author doesn't have time to work on them. Already there has been a [huge spike](http://neilb.org/2015/02/02/monthly-cpan-pr-graph.html) in PRs for Perl modules in the month of January. 

I think this goes along a similar vein as the podcast with Ovid, in that I think many people don't realize how active the Perl community is.

**Comment by jerodsanto** [comment]
@mcmillhj really cool. I'm not sure if there is enough meat here for an entire podcast episode, though. Feels more like an article on the website. @adamstac what do you think?

**Comment by mcmillhj** [comment]
Fair enough, I just wanted to bring it to your attention. I didn't mean this in my first comment, but as of now there are 300+ developers signed up for the challenge.

**Comment by jerodsanto** [comment]
@mcmillhj any interest in guest posting about this on the blog? If so, I encourage you to submit it to our [drafts](/thechangelog/drafts) repo!

**Comment by mcmillhj** [comment]
@jerodsanto Definitely! I will post that to the drafts repo in the next week or so.

**Comment by szabgab** [comment]
I think it would be worth to interview Neil. Not only about the PR challenge which continues this year as well, but also his other work on improving the Perl Ecosystem. Specifically he is talking about 'the cpan river' http://neilb.org/tag/cpan-river/ which started here http://neilb.org/2015/04/20/river-of-cpan.html using the river model for dependencies.
