### ISSUE TITLE
Open source project name checker

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#137]
http://ivantomic.com/projects/ospnc/

This online tool checks if a name for a FOSS project is already "taken". It is itself open source; the repository is at https://github.com/LogIN-/ospnc.

**Comment by jerodsanto** [comment]
:heart: this. Gonna :memo: it up soon. Thanks!

**Comment by jerodsanto** [comment]
@dbohdan [here it is](http://thechangelog.com/naming-open-source-project-start/)! Name dropped ya ;)
