### ISSUE TITLE
Lands - A world generator

### ISSUE THREAD

**Issue by ftomassetti** [thechangelog/ping#139]
Hi there, I am the maintainer of [Lands](https://github.com/ftomassetti/lands/), a world generator.

It simulates different physical phenomena: from plate tectonics, to erosion. It generates different kinds of maps and a file containing all sort of data about the generated world.

It has both a GUI and a command line interface. Among the others format it support google protobuf.

The project has a growing community and a few contributors.

**Comment by jerodsanto** [comment]
@ftomassetti we're including WorldEngine in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe and look for it this Saturday. 

Note: we noticed the merge w/ WorldSynth and are linking to WorldEngine instead of Lands. Thanks for sharing! :beers:

**Comment by ftomassetti** [comment]
It is great to hear that, looking forward to it!
