### ISSUE TITLE
cron-utils: human friendly cron and time utils

### ISSUE THREAD

**Issue by jmrozanec** [thechangelog/ping#140]
A Java library to parse, validate and get human readable descriptions for cron expressions, as well as get cron and date time interoperability (ex.: next/last execution, time from/to last/next execution). 
Also parses human readable descriptions as "Thursday, June 9, 2011" to the corresponding time pattern, so you no longer need to figure out "YYYY-MM-dd KK a" patterns. 
Is available at Maven central repository. 
More details are provided on README.
Check it and star [the repo](https://github.com/jmrozanec/cron-utils)!

**Comment by jerodsanto** [comment]
@jmrozanec we're including cron-utils in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe and look for it this Saturday. Thanks for sharing! :beers:
