### ISSUE TITLE
RVM / mpapis update

### ISSUE THREAD

**Issue by mpapis** [thechangelog/ping#141]
Hi I wrote two blog posts about [myself](http://niczsoft.com/2015/02/changes-in-my-open-source-life/) and [searching for RVM 1 maintainers](http://rvm.io/blog/2015/02/maintainers-needed-for-rvm1)

**Comment by jerodsanto** [comment]
@mpapis congrats on Try Catch and your new direction! I scheduled up a tweet today to ask everyone to help you find RVM 1 maintainers. Let us know if and how we can help you in the future!

Thanks for keeping is in the loop!
