### ISSUE TITLE
HapiGER Recommender System

### ISSUE THREAD

**Issue by grahamjenson** [thechangelog/ping#142]
My new open-source project is trying to make recommender systems a bit easier to use and integrate.

[HapiGER](http://www.hapiger.com/) is a Recommender System where you add user events and it tries to predict what else they might like to do. For example, Alice likes x-men and Bob likes x-men and iron-man, given Alice and Bob both like x-men, Alice might also like iron-man.  HapiGER is named because it uses the [Hapi.js](http://hapijs.com/) framework and [Good Enough Recommendations Engine](http://npmjs.org/package/ger).

Just looking for contributors, testers, users..., and thought I would share :)

**Comment by jerodsanto** [comment]
@grahamjenson we're including HapiGER in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe and look for it this Saturday. Thanks for sharing! :beers:
