### ISSUE TITLE
grunt-sanitize

### ISSUE THREAD

**Issue by christill** [thechangelog/ping#143]
Hi there,

I've created a little grunt plugin that sanitizes filenames by either removing or replacing spaces, forcing them to lowercase and removing any non alphanumeric characters.

I'd be grateful if people could check it out https://github.com/christill/grunt-sanitize and let me know their thoughts. Or contribute!

Thanks

Chris

**Comment by jerodsanto** [comment]
@christill we're including grunt-sanitize in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it on Saturday morning. Thanks for sharing! :beers:

**Comment by christill** [comment]
@jerodsanto That's great! Thanks.
