### ISSUE TITLE
jQuery plugin for visual numeric validation and formatting

### ISSUE THREAD

**Issue by ecommunities** [thechangelog/ping#144]
https://github.com/ecommunities/ecmsNumberFormat

Just a simple plugin that allows you to deal with inline validation of a number, and then on blur, ensure you leave the field properly validated. It uses valid/invalid classes for visual representation but only persists during editing.

Couldn't find anything that allowed me to validated against: min, max, precision (decimal places), fixed increments, in any combination.

Not sure if it fits the bill for your blog, but there are a few to-do's that would benefit from some other eyes.  If it's too early, no problem, let me know what might help elevate it to worthy, and I'll do my best.

Cheers,

Kevin.

**Comment by jerodsanto** [comment]
@ecommunities thanks so much for sharing this! We've grown a bit weary of jQuery plugins, so we rarely link them up unless they're MIND BLOWING. In this particular case, I think we're going to pass, but keep up the open source and hit us up gain with future work. :beers:
