### ISSUE TITLE
vagga -- the tool to create development environments

### ISSUE THREAD

**Issue by tailhook** [thechangelog/ping#145]
Some time ago I realized that setting up development environments must be even easier than what docker and vagrant provide. Vagga does the task. It's almost a year old now, but last week I released version 0.2 which is much better than 0.1.x series.

Basic concepts: https://medium.com/@paulcolomiets/managing-dependencies-with-vagga-79181046db66
And docs: http://vagga.readthedocs.org/en/latest/

**Comment by jerodsanto** [comment]
@tailhook we're including Vagga in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it tomorrow morning. Thanks for sharing it with us! :beers:
