### ISSUE TITLE
Plyr

### ISSUE THREAD

**Issue by SamPotts** [thechangelog/ping#146]
http://plyr.io and https://github.com/selz/plyr

We recently released Plyr, an accessible, customisable and lightweight HTML5 media player. We couldn't find a player that allowed us enough customisation for what we wanted to do so I wrote one. It supports VTT captions too and uses native elements for progress (&lt;progress&gt;) and volume (&lt;input type="range"&gt;). Best of all, it weighs in at just 4KB minified and gzipped (for the JS, default CSS is 2KB extra). 

It'd be great if you could feature it on the site and get the word out so we can make it even better. 

Cheers

**Comment by grahamjenson** [comment]
Nice :)

**Comment by jerodsanto** [comment]
@SamPotts very cool stuff, thanks for letting us know about it! We [linked you up](http://thechangelog.com/plyr-simple-html5-media-player-custom-controls-webvtt-captions/) today and expect a spot in the next [Weekly](http://thechangelog.com/weekly) as well. :) :beers:

**Comment by SamPotts** [comment]
Awesome cheers :)
