### ISSUE TITLE
airbrussh — Ruby gem that pretties up your SSHKit/Capistrano output

### ISSUE THREAD

**Issue by mattbrictson** [thechangelog/ping#148]
Airbrussh is a replacement log formatter for SSHKit that makes your Capistrano output much easier on the eyes. Just add it to your Capfile and enjoy concise, useful log output that is easy to read.

https://github.com/mattbrictson/airbrussh

**Comment by jerodsanto** [comment]
@mattbrictson we're including Airbrussh in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

(great name, btw!)
