### ISSUE TITLE
node-smtp-pipe - pipe any mail envelope input and output forward as SMTP client

### ISSUE THREAD

**Issue by lirantal** [thechangelog/ping#149]
SMTP Pipe - Node NPM package: https://www.npmjs.com/package/smtp-pipe

smtp-pipe is an smtp-aware node app that works like the GNU/Linux tee command - it accepts an smtp envelope as an input to STDIN and forwards it to an email server through SMTP.

Example of usage scenario where you would pipe an e-mail message (envelope) as an input stream to smtp-pipe:
```
  cat email-message.txt | smtp-pipe
```

**Comment by jerodsanto** [comment]
@lirantal neat. We're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it on Saturday morning. Thanks for sharing! :beers:

**Comment by lirantal** [comment]
awesome, thanks!
I'm subscribed since months back, the newsletter is great :)
