### ISSUE TITLE
[Guest idea] Sarah Mei

### ISSUE THREAD

**Issue by mattbrictson** [thechangelog/ping#150]
Has Sarah been on the show before? Her recent blog post on the gender gap in OSS seems like it could generate a lot of good discussion:

https://devmynd.com/blog/2015-2-mind-the-gap

**Comment by adamstac** [comment]
Hey @mattbrictson, thanks for the suggestion. We haven't had @sarahmei on the show yet, but we do have plans in the works on a show with another Sarah -- Sarah Allen (aka @ultrasaurus) -- fellow co-founder of RailsBridge.

We would like to do a show soon that focuses on the gender gap in OSS Sarah talks about her post. We'll leave this issue open and post updates back here as we make progress.

**Comment by adamstac** [comment]
@mattbrictson - heads up too, we'll be including @saramei's post you mentioned in the upcoming issue of Weekly -- http://thechangelog.com/weekly/

**Comment by sarahmei** [comment]
I'd be happy to contribute. Let me know how I can help. :)

**Comment by adamstac** [comment]
Awesome! @sarahmei any chance you're open this Friday? I can email you with more details if so.

**Comment by sarahmei** [comment]
I'll be at a conference on Friday, but not speaking, so I could sneak an hour or two away. Dicey wifi tho. 

Otherwise next week my schedule is pretty open. Take this to email? sarah at devmynd dot com. :)

**Comment by adamstac** [comment]
Let's do next week then, March 6th. I'll get an email to you with the details and all that.

**Comment by jerodsanto** [comment]
This show went live this morning! :tada: 

http://thechangelog.com/146/

@mattbrictson thanks for the suggestion and a huge thanks to @sarahmei for joining us! :beers:

**Comment by mattbrictson** [comment]
Great episode. Thanks @sarahmei !
