### ISSUE TITLE
payform - a tool for building / formatting / validating credit card forms

### ISSUE THREAD

**Issue by jondavidjohn** [thechangelog/ping#151]
It is a fork of the ever popular jQuery.payment plugin from stripe, but it's built to be consumed on many more platforms including npm + browserify, node, bower, and also does not hold a jQuery requirement (though it still ships with a jQuery plugin shim similar to the jQuery.payment interface).

http://jondavidjohn.github.io/payform/

**Comment by jerodsanto** [comment]
@jondavidjohn we're including payform in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it tomorrow morning. Thanks for sharing! :beers:
