### ISSUE TITLE
The State of Docker Orchestration

### ISSUE THREAD

**Issue by dscape** [thechangelog/ping#152]
Would love to suggest an episode on this topic. I think we could cover it from three different perspectives:

* Networking, in products like weave
* Docker, as an organization of open source tools to serve the purpose
* Developer, as the view about approaches that use the operative system (coreos) or things like Kubernetes, Dokku or Paz.

Would be willing to help get experts involved if required.

**Comment by adamstac** [comment]
Thanks for the suggestion @dscape.

We had a show just a few weeks back with Alex Polvi from CoreOS, [episode #138](http://thechangelog.com/138/) - did you have a chance to check that one out?

We're due for a deeper look at Docker for sure though.

**Comment by adamstac** [comment]
@dscape seems paz made the list today http://nightly.thechangelog.com/2015/02/27/

**Comment by dscape** [comment]
Great news. Someone posted about PAZ in HN and apparently people like the concept

**Comment by jerodsanto** [comment]
@dscape we are working hard on putting together another show on Docker. I'm closing this (just pruning the Ping hedges today), but I'll post a link if/when it's published. You can also keep up on [Twitter](https://twitter.com/changelog) or by subscribing to [Weekly](https://changelog.com/weekly), of course. 🍻
