### ISSUE TITLE
Lua meets Node.js - Luaw, Nonblocking HTTP server for Lua 

### ISSUE THREAD

**Issue by raksoras** [thechangelog/ping#153]
https://github.com/raksoras/luaw

Event driven, non blocking HTTP app server for Lua inspired by Node.js. Uses Lua coroutines in place of nested callbacks to simplify application code.

**Comment by jerodsanto** [comment]
@raksoras we're including Luaw in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe if you haven't. Thanks for sharing! :beers:
