### ISSUE TITLE
Amok - Live Editing for JavaScript

### ISSUE THREAD

**Issue by caspervonb** [thechangelog/ping#154]
Repository: https://github.com/caspervonb/amok
Npm: https://www.npmjs.com/package/amok

A short introduction article, http://caspervonb.github.io/javascript/tools/live-editing-javascript-amok/

**Comment by caspervonb** [comment]
Project page is available over at http://amokjs.com

**Comment by jerodsanto** [comment]
@caspervonb very cool. We're including Amok in our next issue of [Weekly](http://thechangelog.com/weekly/), which ships tomorrow. Thanks for sharing! :beers:

**Comment by caspervonb** [comment]
Awesome, looking forward to it :+1:
Thanks guys.
