### ISSUE TITLE
ZBatt

### ISSUE THREAD

**Issue by amagura** [thechangelog/ping#155]
https://github.com/amagura/zelda-battery

ZBatt is a Legend of Zelda inspired battery meter for Shell prompts and, recently, Taskbars.  ZBatt was, originally, written as an alternative to having to glance at my taskbar to see how much battery power I had left while working extensively at the command-line.  ZBatt aims to support most window managers and taskbars.  

I'd really appreciate it if yall could feature this on yall's site, however, any feedback at all would be equally appreciated.

**Comment by jerodsanto** [comment]
@amagura this is hilarious and awesome! We're going to shoot a tweet your way and include you in our next issue of [Weekly](https://thechangelog.com/weekly). Subscribe and watch for it shipping this weekend! :beers:

**Comment by amagura** [comment]
Thank you very much! :)
