### ISSUE TITLE
m2bk - Send your mongodb dumps to AWS S3

### ISSUE THREAD

**Issue by axltxl** [thechangelog/ping#157]
*m2bk* is command line tool that performs a number of **mongodb database backups via mongodump**, compresses them into a gzipped tarball and finally sends them to an **AWS S3 bucket**.

https://github.com/axltxl/m2bk

**Comment by jerodsanto** [comment]
@axltxl we're including m2bk in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
