### ISSUE TITLE
chalk - colorize strings in the terminal

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#159]
@jbnicolai and I released chalk 1.0.0 last week. Lots of work went into making it faster, more stable and working around a Windows issue.

https://github.com/sindresorhus/chalk/releases/tag/v1.0.0

https://github.com/sindresorhus/chalk

> - Highly performant
- Doesn't extend `String.prototype`
- Expressive API
- Ability to nest styles
- Clean and focused
- Auto-detects color support
- Actively maintained
- [Used by ~3000 modules](https://www.npmjs.com/browse/depended/chalk)

**Comment by adamstac** [comment]
Thanks @sindresorhus for sharing this. Looks like chalk AND to-fast-properties made it on [Changelog Nightly for March 4th](http://nightly.thechangelog.com/2015/03/04/).

We're including chalk in this week's issue of [Changelog Weekly](http://thechangelog.com/weekly/) as well. :beers:

**Comment by jbnicolai** [comment]
:beers:
