### ISSUE TITLE
Jet - Realtime Message Bus for the Web

### ISSUE THREAD

**Issue by lipp** [thechangelog/ping#160]
Jet is an open protocol for building Reatime Apps with implementations for Node.js / Browser, Lua and Arduino.

http://jetbus.io

**Comment by jerodsanto** [comment]
@lipp we're including Jet in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe today and watch for it to :ship: this weekend. Thanks for sharing! :beers:

**Comment by lipp** [comment]
@jerodsanto Great! Thanks! I am looking forward to it!
