### ISSUE TITLE
Rx Koans

### ISSUE THREAD

**Issue by omo** [thechangelog/ping#161]
In context of http://thechangelog.com/a-huge-list-of-koans/,
There is "Reactive Extensions (Rx) Koans" which covers original (C#) RX. https://rxkoans.codeplex.com/

**Comment by adamstac** [comment]
Thanks @omo! I've updated the post to include that Koans as well.

**Comment by omo** [comment]
\o/

**Comment by ahmdrefat** [comment]
I've created a list of koans https://github.com/ahmdrefat/awesome-koans/blob/master/koans-en.md
