### ISSUE TITLE
[Guest Idea] Epic Games (specifically the Unreal Tournament team at Epic)

### ISSUE THREAD

**Issue by ESWAT** [thechangelog/ping#162]
Would be cool to hear how the team at Epic Games is getting along with using GitHub to create their first community-made game [Unreal Tournament](http://www.unrealtournament.com/), especially now that anyone can register for UE and work on the game.

**Comment by jerodsanto** [comment]
@ESWAT Sorry for letting this sit for so long. I completely agree with you. Do you have any connections or even a specific person who we should reach out to line this show up?

**Comment by ESWAT** [comment]
@jerodsanto no worries. Unfortunately I have no personal connections and not really sure who would be the main contacts at Epic to contact about UT development now. I’m guessing either their [community manager](https://twitter.com/flak) or the project lead Steve Polge (who I’m not sure how you’d contact directly).

**Comment by jerodsanto** [comment]
@ESWAT it's a long shot, but I went the grassroots route:

1. https://github.com/EpicGames/Signup/issues/8
2. https://twitter.com/changelog/status/668988423823228928

I'm gonna close this issue, but I'll post follow-ups here if they are open to joining us. Thanks again for the suggestion!
