### ISSUE TITLE
Markers.js: Animated marker clusters for Google, Mapbox and Bing maps

### ISSUE THREAD

**Issue by WearyMonkey** [thechangelog/ping#163]
http://wearymonkey.github.io/markers.js/ and https://github.com/WearyMonkey/markers.js 

Markers.js is allows for nicely animated marker clusters on a web map. 

The main features it has over alternatives like Google Marker Manager is that the clusters animate as they expand and collapse, and lines can be drawn between the clusters which also animate. Markers.js is also not tied to a single map provider and currently has support for Google, Mapbox and Bing maps.

Some example use cases might be a travel agency showing package tours with routes on a map or showing a large amount of social data like instagram photos on a map.

**Comment by jerodsanto** [comment]
@WearyMonkey we're including Markers.js in our next issue of [Weekly](http://thechangelog.com/weekly/). 

Subscribe now and watch for it to :ship: this weekend! :beers:

**Comment by WearyMonkey** [comment]
Wow thanks! :smile_cat:
