### ISSUE TITLE
Axelrod' evolution of cooperation (Game Theory) on github

### ISSUE THREAD

**Issue by drvinceknight** [thechangelog/ping#164]
In the 1980s a Professor of Political Sciences held a computer tournament inviting everyone to contribute strategies to a game theoretic tournament called an iterated prisoner's dilemma. That experiment (and another one that followed) has been used to describe how cooperation can evolve out of complex situations. You can read about this [here](https://egtheory.wordpress.com/2015/03/02/ipd/)

I've put up a version of this tournament implemented in Python: https://github.com/drvinceknight/Axelrod inviting strategies to be contributed via PRs.

This has had (by my humble projects' standard) quite a lot of pull requests but it would be great to have even more (more strategies, tidying up code, docs etc...). 

This is also a pretty easy opportunity for a first pull request if anyone is looking for one of those (simple concepts that only require simple Python code).

(I'm a Mathematician at Cardiff University and would love to talk about this further if anyone is interested :))

**Comment by jerodsanto** [comment]
@drvinceknight is the linked repo the canonical one or is it [this one](https://github.com/Axelrod-Python/Axelrod)?

**Comment by drvinceknight** [comment]
Hi @jerodsanto, it is indeed the other one: https://github.com/Axelrod-Python/Axelrod

Thanks for checking (we transferred the repo to an organisation a while ago and I forgot to update this issue).

**Comment by jerodsanto** [comment]
@drvinceknight we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/), which ships tomorrow morning. Thanks for sharing! :beers:

**Comment by drvinceknight** [comment]
That's awesome: thanks! :fireworks:
