### ISSUE TITLE
GoMedia: Upload pictures from Tweetbot to your own S3 repository

### ISSUE THREAD

**Issue by matiaskorhonen** [thechangelog/ping#165]
GoMedia (https://github.com/matiaskorhonen/gomedia) is a [custom media endpoint](http://tapbots.net/tweetbot/custom_media/) for Tweetbot, written on Go. It lets you use your own S3 bucket as your photo storage.

Additionally you can use it as a WebDAV endpoint for Monosnap (and possibly other compatible screenshot apps).

**Comment by jerodsanto** [comment]
@matiaskorhonen we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it tomorrow morning. Thanks for sharing! :beers:
