### ISSUE TITLE
Gallerist: A web application to browse Apple Photos libraries

### ISSUE THREAD

**Issue by koraktor** [thechangelog/ping#166]
A web application that allows you to browse Apple Photos libraries from other devices using nothing more than a browser.

https://github.com/koraktor/gallerist

**Comment by jerodsanto** [comment]
@koraktor cool idea. Have any screenshots or even a list of use cases where Gallerist would really shine?

**Comment by koraktor** [comment]
I'll try to put some screenshots in the README, but I'll have to create a dummy library with non-private photos for that first.

But here's a list of use cases that I think Gallerist is good for:

 * View a library from a non-OSX system
 * View a library remotely without the need to copy the whole library
 * Serve the library from e.g. a Raspberry. I didn't test this yet, but there should be no problem running the app on non-OSX systems
 * Or simply view a second library. Photos still only supports opening one library at a time.

**Comment by koraktor** [comment]
@jerodsanto Ok, I added some screenshots [in the wiki](https://github.com/koraktor/gallerist/wiki/Screenshots).

**Comment by jerodsanto** [comment]
@koraktor thanks for the extra info! We [gave you a shout](http://thechangelog.com/gallerist-browse-an-apple-photos-library-from-the-web/) on the site this morning. Keep up the open source! :beers:
