### ISSUE TITLE
intercooler.js

### ISSUE THREAD

**Issue by carsongross** [thechangelog/ping#167]
Hi There,

I've been working on a javascript library, intercooler.js, for building AJAX-enabled web apps with muhc less code than the current MVC frameworks require.  It uses HTML partials and is based on pjax and the 37signals approach to building basecamp 2.

I recently released v0.4.9, and though you might be interested in looking at it.  You can read the docs here:

http://intercoolerjs.org/docs.html

**Comment by jerodsanto** [comment]
@carsongross we're including intercooler.js in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and watch for it Saturday morning. Thanks for sharing! :beers:
