### ISSUE TITLE
ResearchKit from Apple

### ISSUE THREAD

**Issue by rafaeldalpra** [thechangelog/ping#168]
Their new effort in healthcare is the ResearchKit, which enables any iPhone user on the world to be part of medical research.

I think that's HUGE and it's OSS!

**Comment by jerodsanto** [comment]
@rafaeldalpra I agree with you! We [tweeted about it](https://twitter.com/TheChangelog/status/574986989059047424) yesterday. Anything else we should do with regard to coverage?

**Comment by rafaeldalpra** [comment]
Well, I don't know how much information is already out there since it has not been launched, but it's something to keep an eye on. An OSS approach from Apple is a big deal!

**Comment by jerodsanto** [comment]
@rafaeldalpra agree 100%! Please open a new issue if you come across anything super tangible that we can write about or link to. :beers:
