### ISSUE TITLE
Add Ruby the Huge List of Koans

### ISSUE THREAD

**Issue by yellow5** [thechangelog/ping#169]
Ruby can be added to the [Huge List of Koans](http://thechangelog.com/a-huge-list-of-koans/):

http://rubykoans.com/

It provides online and local options.

**Comment by yellow5** [comment]
Derp... I noticed that the main paragraph mentions Ruby already.

Disregard!

**Comment by adamstac** [comment]
No, I agree Ruby's should be listed in the list below as well. I added it. Thanks for the heads up on that. :beers:
