### ISSUE TITLE
SystemJS, ES6 modules, jspm

### ISSUE THREAD

**Issue by johnraz** [thechangelog/ping#170]
I've been doing some searching and there is a lot to say about these subjects and I think and it would make and awesome show topic ;-)

**Comment by adamstac** [comment]
@johnraz awesome suggestion. Can you give us more detail on what you'd like to see covered, or anything specific to give us some guidance on what you'd like to hear about?

**Comment by johnraz** [comment]
Sure.

I was mainly thinking of having Guy Bedford on the show to talk about the state of ES6 modules, its availability as of today in current browsers / real life projects and how SystemJS and jspm play into that. 
I'm also curious about the features and limits of the system.

That's basically it.

**Comment by netaisllc** [comment]
Guy is the guy, so to speak. What's interesting is his motivation for his projects. Guy started out positioning his work as an 'experiment' about what a better JS module loader could be.  Fertile ground to probe what the pain was that motivated a fresh stake in the ground.

The project has moved past that stage IMHO into a real thing. Note that Rob Eisenberg has adopted it as the "preferred" loader out-of-the-box, though he is wise enough to support other loaders as well. There is an opportunity here to really bring the 'call to arms' to bring about good, in terms of devs pressing for this type of unified approach.

**Comment by jerodsanto** [comment]
Thanks for the idea @johnraz and the input @netaisllc (and sorry for letting this linger for over a year!). At this point, the state of module loading in JS land is so unstable that we think a show on it will be quickly outdated.

Keep pinging us with your ideas. We appreciate you both and your involvement in the Changelog community. 🍻
