### ISSUE TITLE
[Guest idea] Al Tsang - Co-founder and CTO of StrongLoop

### ISSUE THREAD

**Issue by coffeepunk** [thechangelog/ping#171]
Think Al might have a lot of good input on building a company based on Open Source and lot of juicy technical details regarding NodeJS and how to create platforms and build API's.

**Comment by jerodsanto** [comment]
I think this might be a good one for sometime this Fall @adamstac.

**Comment by jerodsanto** [comment]
I don't know if IBM's purchase of StrongLoop makes this a more interesting conversation or a less interesting conversation? What's your take, @coffeepunk?

**Comment by coffeepunk** [comment]
Neither do I @jerodsanto. I played around with StrongLoop and got in touch with Al and we talked a bit over Skype, seemed like a friendly dude with some good stories. My angle or take on it was more on the business side and how to use and build open source products and a company at the same time, much the way Elastic Search and now even Capistrano have done. How open source projects as turned into cloud services backed by legit companies (good or bad trend?, guess it depends if you are in the "get paid" team or not :D ).

It might have been better to have him @adamstac Founders Talk :) Of course it would be very interesting to hear about the IBM purchase and what the path inside the big blue could look like, along with all the why and hows, but all of the juice details are most likely wrapped up in red tape?

I would still like to see him on the show, but I'll leave the "journalistic" angle on it and if it is a good fit or not up to you guys. It is your incredible sense of good topics and guests that makes the ChangeLog such a good show and success.

**Comment by jerodsanto** [comment]
@coffeepunk sorry just looping (pun!) back around to this. I lol'd at your "get paid" reference. You _do_ listen to the show! :grin: 

I think we're gonna pass on this topic for The Changelog, but I'll say this: _if_ we were considering bring Founders Talk back and _if_ we were making a list of possible guests for said comeback, we _might_ add Al to such a list.

...
