### ISSUE TITLE
CouchDB 2.0

### ISSUE THREAD

**Issue by cmnstmntmn** [thechangelog/ping#172]
there's going to be a a huge step for Apache's CouchDB project and NoSQL DBs, since the're going to launch 2.0 version with clustering support and other extra features.

[more on the blog](http://blog.couchdb.org/)

**Comment by jerodsanto** [comment]
@cmnstmntmn this is interesting, but where do we get details? Is there a projected release date?

**Comment by cmnstmntmn** [comment]
well, not really; there is no release date, but there are plenty of new features, like:

* Clustering and Big Data Capabilities
* new backend interface, build on React js named Fauxton

all these available in [Developer Preview](https://couchdb.apache.org/developer-preview/2.0/)

a reason could also be the fact that brands like Apple, IBM Cloudant, CERN are powered by CouchDB

**Comment by jerodsanto** [comment]
Sounds like some cool stuff coming down the pipeline. Do us a favor? Keep an eye out for 2.0 and ping us again when the release is imminent. Thanks!
