### ISSUE TITLE
theca - Rust based CLI note taking tool

### ISSUE THREAD

**Issue by rolandshoemaker** [thechangelog/ping#173]
I recently released the first *stable-ish* version of a CLI note taking tool written in Rust called `theca` and thought you guys might be interested.

https://github.com/rolandshoemaker/theca

I also wrote a blog post about it here https://www.bracewel.net/introducing-theca/

![main](https://cloud.githubusercontent.com/assets/5080674/6632293/33f0c656-c8f1-11e4-9065-cbcd9bd90a72.png)

**Comment by jerodsanto** [comment]
@rolandshoemaker cool stuff! We're including  in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and watch for it Saturday morning. Thanks for sharing! :beers:

(btw, did you listen to [our recent episode](https://thechangelog.com/151/) on Rust? What did you think?)
