### ISSUE TITLE
`hub` 2.2.0 is powered by Go

### ISSUE THREAD

**Issue by jingweno** [thechangelog/ping#174]
More about this on the [2.2.0 release note](https://github.com/github/hub/releases/tag/v2.2.0).

**Comment by adamstac** [comment]
Thanks for sharing this @jingweno. We're linking this up in the next issue of [Changelog Weekly](http://thechangelog.com/weekly/). :beers:

**Comment by jingweno** [comment]
:+1: Huge fan of your show!
