### ISSUE TITLE
medium.com style confirm dialog

### ISSUE THREAD

**Issue by brijeshb42** [thechangelog/ping#175]
medium.com style confirm dialog [demo](http://bitwiser.in/medium-style-confirm/) and [project](https://github.com/brijeshb42/medium-style-confirm) .

**Comment by jerodsanto** [comment]
@brijeshb42 we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and watch for it Saturday morning. Thanks for sharing! :beers:
