### ISSUE TITLE
terminal-emojify

### ISSUE THREAD

**Issue by as-cii** [thechangelog/ping#176]
First off, thank you for The Changelog: it's one of the newsletters I enjoy the most :beers: 

Recently, I have released a toy utility which helps converting emoji aliases to raw unicode characters. I decided to create it for [displaying a beautiful git history](https://github.com/as-cii/terminal-emojify#beautiful-git-history), but I am sure people will come up with other interesting usages.

Not a disruptive tool, I know, but I spend 50% of my time in a terminal and it's nice to have colors and emojis in there too :rainbow: 

https://github.com/as-cii/terminal-emojify :sunglasses: 

Thanks!

**Comment by jerodsanto** [comment]
@as-cii funny, I saw this hit [Nightly](http://nightly.thechangelog.com/2015/03/17/) the other day and thought it looked neat. We're going to link you up in Saturday's [Weekly](http://thechangelog.com/weekly/) and look for a tweet sometime real soon, too. Thanks for sharing! :beers:

**Comment by as-cii** [comment]
@jerodsanto: great to know that!

Thank you and keep up the awesome work! :fire:
