### ISSUE TITLE
[Guest Idea] [Not JavaScript] Carin Meier, author of "Living Clojure"

### ISSUE THREAD

**Issue by netaisllc** [thechangelog/ping#177]
#### File this in the We-Are-Sick-Of-JS-Guests dropbox. 

Carin is (a) a woman {yay}, (b) a working dev, and (c) an articulate voice for the Clojure language and 'mindset'.   

What is that mindset?, how does one transition it to it from a different dev mindset? why would I or my org benefit is trying it? Can Clojure exist in a polyglot enterprise stack, and --- you get the idea.  Her new book below, I believe it is her first.

Living Clojure
An Introduction and Training Plan for Developers
By Carin Meier
Publisher: O'Reilly Media
Release Date: January 2015
Pages: 232

**Comment by jerodsanto** [comment]
@netaisllc good call, Carin looks like she'd make a great guest. We reached out to her. Going to close this for now to keep things tidy, but will post more info here as things progress!

**Comment by jerodsanto** [comment]
@netaisllc ICYMI! https://changelog.com/171/ :tada:

**Comment by netaisllc** [comment]
Yeah it was a really great episode. +1

On Fri, Sep 4, 2015 at 2:12 PM, Jerod Santo <notifications@github.com>
wrote:

> @netaisllc <https://github.com/netaisllc> ICYMI!
> https://changelog.com/171/ [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/177#issuecomment-137854825>.
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>
