### ISSUE TITLE
XCActionBar Xcode plugin

### ISSUE THREAD

**Issue by pdcgomes** [thechangelog/ping#179]
I've release [XCActionBar](https://github.com/pdcgomes/XCActionBar), a general purpose productivity plugin for Xcode.
Submitting it for your consideration.

Thank you.
Pedro.

**Comment by jerodsanto** [comment]
:+1: this actually made [Nightly last night](http://nightly.thechangelog.com/2015/03/20/) and we have it queued up for a tweet today.

**Comment by pdcgomes** [comment]
Oh, somehow I missed that! Anyway, that's great news then, thank you :)
