### ISSUE TITLE
uSched - A remote command-line scheduler with an almost-natural language interpreter.

### ISSUE THREAD

**Issue by ucodev** [thechangelog/ping#181]
uSched is a young opensource project that's currently on its first public beta release [v0.1-beta-06](https://github.com/ucodev/usched/releases/tag/v0.1-beta-06).

It aims to provide a natural language to schedule tasks, a client/server support with encrypted connections, and to provide an easy-to-use integration through a client library (developed in C) with bindings for Java, C#, Python and PHP.

It's currently looking for contributions in any form: ideas, code, testing, bugfixes... anything is very welcome at this stage.

Project GitHub page: https://github.com/ucodev/usched

Project Home page: http://www.usched.org

FAQ: https://github.com/ucodev/usched/wiki/FAQ

Wiki: https://github.com/ucodev/usched/wiki

**Comment by jerodsanto** [comment]
@ucodev we're including uSched in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe now and look for it tomorrow morning. Thanks for sharing! :beers:
