### ISSUE TITLE
restifydb - Expose databases as REST web services

### ISSUE THREAD

**Issue by thenewsmachine** [thechangelog/ping#182]
Ping!

restifydb is an open-source framework that is able to automatically map databases (from all major database engine providers) to REST web services. The web services can output XML or JSON. It leverages data discovery. 

It has advanced capabilities such as automatic query expansion (joining based on foreign keys), automatic inward references, automatic data discovery, filtering, sorting and out of the box CRUD operations (create, read, update and delete data). Most of these features are used by the demo applications built using restifydb. It also features an administration panel which makes configuring it 
quite easy.

Project homepage: https://restifydb.com/

Some screenshots: 

![restify-02](https://cloud.githubusercontent.com/assets/5477645/6805056/501d4832-d241-11e4-919a-f337dd12b0d4.png)
![restify-09](https://cloud.githubusercontent.com/assets/5477645/6805058/501efca4-d241-11e4-81f9-7d0a095d05cc.png)
![restify-10](https://cloud.githubusercontent.com/assets/5477645/6805055/501c3154-d241-11e4-9351-67b49b0b1a9c.png)
![restify-11](https://cloud.githubusercontent.com/assets/5477645/6805057/501ee8d6-d241-11e4-941f-7bf61f773cb4.png)

**Comment by jerodsanto** [comment]
@thenewsmachine we're including restifydb in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
