### ISSUE TITLE
Awesome Data Science

### ISSUE THREAD

**Issue by hmert** [thechangelog/ping#183]
Hi,
We're collecting and categorizing  Data Science materials in our awesome-datascience repo. Maybe The Changelogers want to know about that :)

https://github.com/okulbilisim/awesome-datascience

**Comment by jerodsanto** [comment]
@hmert we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/), which ships tomorrow. Subscribe now if you haven't. Thanks for contributing! :beers:

**Comment by hmert** [comment]
Thank you :) 👏
