### ISSUE TITLE
Shout — The web IRC client

### ISSUE THREAD

**Issue by samyakbhuta** [thechangelog/ping#184]
Stumbled upon this. Looks neat - https://github.com/erming/shout

> ##### What is it?
>Shout is a web IRC client that you host on your own server.

> ##### What features does it have?

> * Multiple user support
> * Stays connected even when you close the browser
> * Connect from multiple devices at once
> * Responsive layout — works well on your smartphone
> * .. and more!

**Comment by jerodsanto** [comment]
@samyakbhuta nice find! We're tweeting this and putting it in Weekly as well. :facepunch: :+1:

**Comment by samyakbhuta** [comment]
Awesome.
