### ISSUE TITLE
Corefines – a convenient way to use Ruby refinements and more

### ISSUE THREAD

**Issue by jirutka** [thechangelog/ping#185]
I’ve released new gem called [corefines](https://rubygems.org/gems/corefines).

Corefines is a collection of general purpose _refinements_ for extending the core capabilities of Ruby’s built-in classes. It’s like Facets or ActiveSupport, but doesn’t pollute the global scope (when run on Ruby that supports refinements).

However, it’s not just about core extensions. Corefines also provides some “syntactic sugar” for more convenient using of refinements and compatibility mode for rubies that don’t support refinements (yet)!

[Read more…](https://github.com/jirutka/corefines)

**Comment by jerodsanto** [comment]
@jirutka we're including Corefines in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by jirutka** [comment]
Great, thank you! :smile_cat:
