### ISSUE TITLE
Suplemon — Console text editor with multicursor support written in Python.

### ISSUE THREAD

**Issue by richrd** [thechangelog/ping#186]
Suplemon is an intuitive console text editor with multicursor support. It mimics the ease of use of nano and the power of SublimeText. It also supports extensions to allow easy customization. It's written in Python. See it at https://github.com/richrd/suplemon . What do you think?

Main features:
* Proper multi cursor editing
* Easy Undo/Redo
* Multiple files in tabs
* Powerful Go To feature for jumping to files and lines
* Find and Find next
* Copy & Paste, with multi line support
* Mouse support
* Extensions (easy to write your own)

**Comment by jerodsanto** [comment]
@richrd we're including Suplemon in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by richrd** [comment]
Awesome, thanks! :+1:
