### ISSUE TITLE
Ra

### ISSUE THREAD

**Issue by oahmad04** [thechangelog/ping#187]
Program in your native tongue

Ra is an alternative syntax for the .NET language Cobra that allows you to program in non-English languages.

Website: http://oahmad04.github.io/ra/
GitHub: https://github.com/oahmad04/ra

**Comment by jerodsanto** [comment]
@oahmad04 we're including Ra in our next issue of [Weekly](http://thechangelog.com/weekly/), which :ship:s tomorrow morning. Thanks for sharing! :beers:
