### ISSUE TITLE
[Guest idea] Ryan Bates of RailsCasts

### ISSUE THREAD

**Issue by coffeepunk** [thechangelog/ping#188]
Would be awesome to have Ryan Bates on the show just talking about everything from Ruby, Rails, the time off, future of RailsCasts, the state of online video tutorials or just to get to know him a bit.

I see him and Geoffrey Grosenbach as pioneers in pod and screencasting.

**Comment by haraldringvold** [comment]
:+1:

**Comment by benoittgt** [comment]
Good idea. Love to hear it.

**Comment by grahamjenson** [comment]
Great Idea.

**Comment by ryanb** [comment]
For now I am keeping my interactions only on Twitter to ease into the community and to keep me from getting overwhelmed. But perhaps sometime in the future. :)

**Comment by adamstac** [comment]
Thanks for chiming in here @ryanb. We certainly want to see you be healthy, and we're here to support you however we can. When the timing is right, we'll still be here for you.

**Comment by jerodsanto** [comment]
I'm going to close issue this just as a matter of house cleaning, but I'm with Adam that @ryanb you are welcome on our show whenever you're ready. :+1:
