### ISSUE TITLE
Gisto

### ISSUE THREAD

**Issue by morsdyce** [thechangelog/ping#189]
A cross platform snippet manager on top of GitHub Gists which adds many missing features.
We just released v0.3 along with GitHub Enterprise support.

https://github.com/Gisto/Gisto 
http://www.gistoapp.com/

Built with nw.js and AngularJS

**Comment by jerodsanto** [comment]
@morsdyce we're including Gisto  in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:
