### ISSUE TITLE
WebRx

### ISSUE THREAD

**Issue by oliverw** [thechangelog/ping#190]
## <img src="http://webrxjs.org/images/Logo.png" height="24" /> WebRx Framework

WebRx is a Javascript MVVM-Framework built on ReactiveX for Javascript (RxJs) that combines functional-reactive programming with observable-powered declarative Data-Binding, Templating and client-side Routing.

An introduction to the framework along with full documentation and code examples can be found at the project [website](http://webrxjs.org).

Feel free to drop me a message [here](https://github.com/oliverw) or on [Twitter](https://twitter.com/webrxjs) if you have any further questions.

**Homepage:** [http://webrxjs.org/](http://webrxjs.org/)
**Source:** https://github.com/oliverw/WebRx
**TodoMVC:**: https://t.co/sxd7H1xhb9

**Comment by jerodsanto** [comment]
@oliverw we're including WebRx in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:
