### ISSUE TITLE
multiplex.js

### ISSUE THREAD

**Issue by KamyarNazeri** [thechangelog/ping#191]
*multiplex.js* is a set of data-structures and implementation of .Net LINQ methods in JavaScript which adds data querying capabilities to JavaScript objects.

Currently supports most .Net data-structures: `List`, `Dictionary`, `Collection`, `ReadOnlyCollection`, `HashSet`, `SortedList`, `LinkedList`, `Queue`, `Stack` and `Lookup`. And also more than 90 LINQ methods.

source: https://github.com/multiplex/multiplex.js

**Comment by jerodsanto** [comment]
@KamyarNazeri cool stuff. we're including Multiplex in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. 

I also queued up a tweet your way. Cheers! :beers:
