### ISSUE TITLE
mysql-cli - A CLI for MySQL that can do auto-completion and syntax highlighting

### ISSUE THREAD

**Issue by amjith** [thechangelog/ping#192]
Kikcstarter: https://www.kickstarter.com/projects/1839007321/mysql-cli

mysql-cli is a command line client for MySQL database that can do auto-compeltion as you type and syntax highlighting of SQL statements. 

This is an alternative to the [pgcli](http://pgcli.com) tool for Postgres.

The application will be written in Python and the goal is to make is cross-platform compatible. The initial target will be Linux and OS X with possible Windows support.

The software will be released (in July 2015) under the BSD license. 

The kickstarter campaign will help fund the development costs.

**Comment by jfernandez** [comment]
:+1:

**Comment by gabesullice** [comment]
Why release it in July, why not make the repo public from your initial
commit onward?

**Comment by amjith** [comment]
Because the mysql-cli code base as it stands right now is not usable. It does keyword completions but no table/column completions. The output formatting needs more work. If I open it right now, it'll be pulled in many different directions and I'll be left fielding questions before reaching an MVP.

The goal is to make the repo available to the kickstarter backers in June at which point the basic feature set will be ready.

Kickstarter campaign is critical to get the necessary funding to keep working on the project and compensate for developer resources (hosting, testing infrastructure, development time etc).

**Comment by amjith** [comment]
Any update on this?

**Comment by jerodsanto** [comment]
@amjith we're going to feature `pgcli` (with a mention of mysql-cli and your kickstarter) in our next [Weekly newsletter](https://thechangelog.com/weekly). Subscribe today and look for it this weekend. Best of luck to you! :beers:
