### ISSUE TITLE
Provide RSS feeds for newsletters

### ISSUE THREAD

**Issue by leafac** [thechangelog/ping#193]
I love the contents of [The Changelog](https://thechangelog.com) newsletters [Changelog Nightly](https://thechangelog.com/nightly/) and [Changelog Weekly](https://thechangelog.com/weekly/). But I hate newsletters! I use e-mail for one-to-one communication and RSS for news. Thus, I'd love to have the content available through a feed, the same way the rest of [The Changelog](https://thechangelog.com) already is.

Thanks!

**Comment by jerodsanto** [comment]
@leafac we've had RSS on our radar for Nightly [a little while](https://github.com/thechangelog/nightly/issues/12) now. Weekly is a little tougher, but we are in the middle of reworking it so this will be a possibility.

Curious, if RSS feeds for our newsletters were a [members-only](https://thechangelog.com/membership/) benefit, would it compel you to join? (Not saying we're going to do this, but we've thrown the idea around.)

**Comment by leafac** [comment]
Hi, @jerodsanto.

The [issue you mentioned](https://github.com/thechangelog/nightly/issues/12#issue-59415619) is still open. I believe newsletters are not available for [Changelog Nightly](https://thechangelog.com/nightly/) yet.

It was nice to learn about http://emails2rss.appspot.com/, though. I was looking for something like that.

But that's a hack and requires a Google account, which I prefer to don't have. I'd love to see the newsletters having a native RSS feed.

Besides reading the mailing lists, I also listen to the podcast and I'm considering becoming a member of [The Changelog](https://thechangelog.com/). Part of the reason is that I know you're putting great free content out there and I want to support that. A paywall around RSS feeds would be detrimental to that freedom and it would dissuade me from signing up.

Thanks for the conversation and for [The Changelog](https://thechangelog.com/). You're welcome to close this issue if you'd like.

Best.

**Comment by jerodsanto** [comment]
@leafac thanks for your feedback on the members-only idea. I wouldn't think of it as a paywall. Like you said, all of our content is already freely given. Instead, think of it as a yet-another perk of membership: additional means of consumption.

As for the RSS issue on Nightly, yes it is still open. Like I said, it's been on our _radar_ for awhile. Here's a deal for you: if you send us a PR that adds RSS support to Nightly, I'll see that it gets deployed and published alongside the newsletter! :sparkles: 

I am going to close this issue, but feel free to keep the conversation going on the Nightly RSS issue.

Thanks for listening and participating! We really do appreciate it! :facepunch:

**Comment by leafac** [comment]
I'm going to give it a try :smile:

**Comment by jerodsanto** [comment]
:+1:

**Comment by leafac** [comment]
Hi, @jerodsanto.

I think I have a working solution.

I wanted a more general solution than adding RSS support for The Changelog newsletters - though that's still an interesting project that I may try in the future if time allows. There are other newsletters without RSS feeds for which I was signed up.

I tried http://emails2rss.appspot.com/, but I ruled it out because:

1. It requires signing up for the service, which means they can track my information and connect it back to me. I don't see a good reason for such a strong commitment from the user for such a low profile application.
2. It requires a Google account. I [proudly don't own one](https://www.leafac.com/writings/how-i-do-my-computing/#saas).
3. It simply didn't work. I create a temporary Google account to try it out and it errored on me, saying that the developers were notified.

I don't mean to bash on http://emails2rss.appspot.com/, in fact, I love the idea so much I created my own version of it.

I'd like to introduce the service I created inspired by this issue: [Kill the newsletter!](http://kill-the-newsletter.com/).

More information and instructions are available on the [service webpage](http://kill-the-newsletter.com/). Of course, it's free software and the source is available and open for improvements [on GitHub](https://github.com/leafac/kill-the-newsletter).

Feel free to point other people that are interested in a RSS feed to the service if you feel like it.

Thanks again for The Changelog. Best.

**Comment by jerodsanto** [comment]
@leafac way to scratch your own itch! :beers:

**Comment by apiarian** [comment]
Is that "Kill the newsletter!" service the way to go, or are there still plans to enable RSS for the weekly/nightly newsletters?

**Comment by jerodsanto** [comment]
@apiarian we are rebuilding our website to host editorialized news, which then turns in to Weekly at the end of each week. This will have an RSS feed, so that may suit your needs for a Weekly feed. We have no plans to build an RSS feed for Nightly (but will accept a PR that does so), so yes you should use Kill the Newsletter if you want a feed for that.
