### ISSUE TITLE
Translation to the documents

### ISSUE THREAD

**Issue by kentaro0919** [thechangelog/ping#194]
I posted an issue to ember guides
https://github.com/emberjs/guides/issues/188
After that I am looking for a good sample of start the foundation of documentation translate.
There are some tools about translations dedicated to GUI or text inside of the application.
But I cannot find a good solution for the documentation.
I am interested in how open source projects deals with this problem.

**Comment by jerodsanto** [comment]
@kentaro0919 translation is indeed an interesting and difficult problem for open source projects. A few things that might interest you:

* [How io.js built a 146 person, 27 language localization effort… in one day](https://medium.com/@mikeal/how-io-js-built-a-146-person-27-language-localization-effort-in-one-day-65e5b1c49a62)
* [Episode 143](https://thechangelog.com/143/) where we discuss that challenge w/ Darcy Clarke, who deals with it on his [popular project](https://github.com/h5bp/Front-end-Developer-Interview-Questions)

The great thing about translation as a multi-lingual person is it's a beneficial and non-technically intimidating way to contribute to open source. Hope this helps you on your way!
