### ISSUE TITLE
Django-material - Material Design for Django forms and admin

### ISSUE THREAD

**Issue by DariaKnyazeva** [thechangelog/ping#195]
[Django-material](https://github.com/viewflow/django-material) provides Material Design for Django forms and Administration with easy template driven rendering. Consistent, beautiful design makes large and complex forms look natural.

Admin site is on initial stage but it has already become really handy on phones for the form widgets fit the screen very well. 

Demo is at [http://forms.viewflow.io/](http://forms.viewflow.io/)

**Comment by jerodsanto** [comment]
@DariaKnyazeva we're including this in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. Cheers! :beers:
