### ISSUE TITLE
ScrollWatch

### ISSUE THREAD

**Issue by edull24** [thechangelog/ping#196]
ScrollWatch is an open source library to easily add lazy loading, infinite scrolling, or any other dynamic interaction based on scroll position, with no dependencies.

[https://edull24.github.io/ScrollWatch/](https://edull24.github.io/ScrollWatch/)

Some notable features include:

- Watch any scrolling element, not just the window
- Supports multiple instances and nested containers
- Executes callbacks when elements enter/leave view
- Tracks the first time something enters/leaves view or every time
- Watches vertical and horizontal scrolling
- Supports infinite scrolling out of the box
- UMD wrapper for use in AMD, CommonJS or global environment
- Scroll/Resize handlers are throttled, so your cpu lives to see tomorrow
- No dependencies
- Modern browser support and IE10+ (IE9+ with [classList.js](https://github.com/eligrey/classList.js/) polyfill)
- < 2k gzipped and minified

**Comment by jerodsanto** [comment]
@edull24 we're including ScrollWatch in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:

**Comment by edull24** [comment]
Thank you!
