### ISSUE TITLE
fiveby - open source browser testing lib from Dow Jones

### ISSUE THREAD

**Issue by scott2449** [thechangelog/ping#197]
https://github.com/dowjones/fiveby

Just released 2.0.0. Getting some good attention from lots of big companies (see stars) and we use it to test many of our sites at DJ. It just makes setting up and using selenium much easier. Aside from simplifying usage it also has simple docs and we do a lot of work with selenium and other libraries to fix bugs and improve usability.

Check it out and let us know what you think!

**Comment by jerodsanto** [comment]
@scott2449 we're including Fiveby  in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Thanks for sharing! :beers:

**Comment by scott2449** [comment]
Sweet, thanks @jerodsanto!
