### ISSUE TITLE
apiwave - discover and track Java APIs

### ISSUE THREAD

**Issue by andrehora** [thechangelog/ping#200]
While it is easy to know how “popular” is a project in number of contributors or fans, it’s quite hard to know how many clients are actually using it. 
To cover that, we performed an analysis on the most used APIs in top 500 GitHub java projects. On apiwave you can dig into this data, and explore how more than 250K frameworks/packages/APIs are actually being used. 

http://apiwave.com
https://apiwave.wordpress.com

**Comment by jerodsanto** [comment]
@andrehora we're including apiwave in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by andrehora** [comment]
That's great! 
thanks !!
