### ISSUE TITLE
New .Net framework for distributed execution with distributed memory

### ISSUE THREAD

**Issue by tony-dinucci** [thechangelog/ping#201]
I'd be really gateful if you could take a look at this new OSS project and and help me spread the word!  It's a very ambitious undertaking (its functional at the minute but still lots to do!). I'm currently trying to get the word out and get the community involved.  Also if you have any feedback I'd love to hear it.

https://github.com/tony-dinucci/Ovule.Nomad

Thanks!

**Comment by jerodsanto** [comment]
@tony-dinucci I can't give you specific feedback, but we're including this in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:
