### ISSUE TITLE
Vimsert - Chrome plugin to edit any textarea with vim

### ISSUE THREAD

**Issue by gabesullice** [thechangelog/ping#202]
I spent a day hacking on [this](https://github.com/gabesullice/vimsert). Vimsert is an open-source chrome extension. It allows you to open up an Ace editor in vim-mode for any textarea in the browser. It's especially nice when you have to clean up WYSIWYG markup and what-not.

**Comment by jerodsanto** [comment]
@gabesullice neat. We'll shoot a [tweet](https://twitter.com/thechangelog) your way. Also look for a shout out in Saturday's [Weekly](https://thechangelog.com/weekly). :beers:
