### ISSUE TITLE
CSS Filters are awesome!

### ISSUE THREAD

**Issue by mdibaiee** [thechangelog/ping#203]
An introduction to CSS Filters with a demo of the new CSS Filter Editor of Firefox Developer Tools and a lot of demos to mess with.

**Comment by jerodsanto** [comment]
@mdibaiee I can haz link?

**Comment by mdibaiee** [comment]
Oh, sorry, it seems I forgot it. http://dibaiee.ir/css-filters/

**Comment by jerodsanto** [comment]
@mdibaiee pretty cool stuff! I had no idea you can do so much with CSS filters. I queued up a tweet your way. :beers:
