### ISSUE TITLE
The Ultimate Minitest Configuration for Rails

### ISSUE THREAD

**Issue by pusewicz** [thechangelog/ping#204]
Thanks for the brilliant podcast and newsletter!

This project aims to create The Ultimate Minitest Configuration for Rails :smile: 

https://github.com/pusewicz/ultimate-minitest-rails

Have a look and let me know what you think!

**Comment by jerodsanto** [comment]
@pusewicz thanks for the kind words!

We're including this in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:
