### ISSUE TITLE
The most Comprehensive randomizer library for PHP

### ISSUE THREAD

**Issue by omranjamal** [thechangelog/ping#205]
This Project aims to provide a comprehensive API for securely generating Pseudo Random Numbers in PHP. It also has a few other features that allow it to generate random strings or floating point numbers or to randomize arrays.

https://github.com/solidew/Casus

So what do you think? :smiley:

**Comment by jerodsanto** [comment]
@omranjamal we're including Casus in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday! :beers:
