### ISSUE TITLE
Proper architecture for iOS apps

### ISSUE THREAD

**Issue by rlopezdiez** [thechangelog/ping#206]
Please have a look to my open source projects, aimed at having properly architected iOS apps, following the SOLID principles while avoiding common pitfalls. They address two of the main sources of concern when modelling an iOS app: navigation and table views.

**RLDNavigation**
https://github.com/rlopezdiez/RLDNavigation
Decouple navigation from view controllers using navigation command objects to define the possible navigation flows of your app. Objective-C and Swift version available.

**RLDTableViewSuite**
https://github.com/rlopezdiez/RLDTableViewSuite
Reusable table view controller, data source and delegate for all your UITableView needs.

Regards,

Rafa

**Comment by jerodsanto** [comment]
@rlopezdiez we're including these  in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by rlopezdiez** [comment]
Thanks!
