### ISSUE TITLE
Decorum: general purpose decorators for Ruby

### ISSUE THREAD

**Issue by erikcameron** [thechangelog/ping#207]
Hi all. Writing to introduce Decorum, a general purpose Decorator/Chain of Responsibility gem for Ruby. It's small, fast, and has no dependencies outside of the standard library. I've been using it in production for over a year now, and it has proved quite usable---time to share, I figure.

https://github.com/erikcameron/decorum

Decorum lets you add functionality to objects on the fly, or implement full Chain of Responsibility type things, while preserving your object references, existing overrides of `#method_missing`, and so on. See the README and test suite for full docs. In the meantime, the short version:

```ruby
class BirthdayParty
  include Decorum::Decorations
end

bp = BirthdayParty.new
bp.respond_to?(:shoot_confetti) # <= false
bp.decorate(Confetti)
bp.shoot_confetti # <= "boom, yay!"
```

Thanks! Hoping it will be useful to others.
-Erik
https://github.com/erikcameron

**Comment by jerodsanto** [comment]
@erikcameron looks nice. We're going to include this in our next issue of [Weekly](https://changelog.com/weekly/). :beers:

**Comment by erikcameron** [comment]
Awesome! Thanks.
