### ISSUE TITLE
Grafana 2.0 stable Relased

### ISSUE THREAD

**Issue by torkelo** [thechangelog/ping#208]
Grafana 2.0 stable was released last Monday. 2.0 is is big release and major advance for this project as it now has its own backend, multi-tenant user & organization model and lots of enhancements for graphs and dashboards and new sharing options. 

- [Blog post](http://grafana.org/blog/2015/04/20/Grafana-2-Released.html)
- [What’s new In Grafana 2.0](http://docs.grafana.org/guides/whats-new-in-v2/) article

**Comment by jerodsanto** [comment]
@torkelo we're including Grafana 2.0  in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by torkelo** [comment]
Great :)
