### ISSUE TITLE
PHP API Client for Moonclerk, recurring payment processor

### ISSUE THREAD

**Issue by karllhughes** [thechangelog/ping#209]
Moonclerk lets you create and embed payment forms that help you easily set up recurring payments. The nice thing is that it's super easy for even non-technical people to set up. They currently have a read-only API, but no clients, so I put one together for PHP and Composer:

https://github.com/JobBrander/moonclerk-php

**Comment by jerodsanto** [comment]
@karllhughes we'll include this in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by karllhughes** [comment]
:+1: Thanks!
