### ISSUE TITLE
Roslyn and C#

### ISSUE THREAD

**Issue by mariusschulz** [thechangelog/ping#210]
After listening to [show 152](https://changelog.com/152/) where you talked about TypeScript with Anders Hejlsberg and Jonathan Turner, I think it would be great to talk about [Roslyn](https://github.com/dotnet/roslyn) and C# next. The compiler and language services have been open source for a while now, too. I think it would be great to have [Mads Torgersen](https://twitter.com/madstorgersen) and [Dustin Campbell](https://twitter.com/dcampbell) on the show!

**Comment by jerodsanto** [comment]
@mariusschulz thanks for the suggestion! I think we're going to pass on a C# specific show at this time. Definitely ping us again in the future with more ideas. 💚
