### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#212]
Atom-shell, the shell used by Atom editor was recently renamed to [Electron](http://electron.atom.io/). It's a really great platform to build cross-platform desktop apps in JavaScript. Would be nice to have a mention of it.

It already has a [lot of big companies using it](https://github.com/sindresorhus/awesome-electron#example-apps) and it's [moving quickly](https://github.com/atom/electron/releases).

-

I've also made a list of [useful resources](https://github.com/sindresorhus/awesome-electron) and a [boilerplate](https://github.com/sindresorhus/electron-boilerplate) for it to make it easier to get started.

**Comment by jerodsanto** [comment]
@sindresorhus yup we gave Electron and your list a shout on Twitter last week. We'll also include it in Saturday's issue of [Weekly](https://changelog.com/weekly/). :beers:

**Comment by sindresorhus** [comment]
:cocktail:
