### ISSUE TITLE
Syntax Highlighting `cat`

### ISSUE THREAD

**Issue by jingweno** [thechangelog/ping#213]
`ccat` - syntax highlighting `cat`: https://github.com/jingweno/ccat

![demo](https://dl.dropboxusercontent.com/u/1079131/ccat.gif)

**Comment by jerodsanto** [comment]
@jingweno saw this make the rounds last week. Very cool! We'll be featuring it in [Weekly](https://changelog.com/weekly/) tomorrow morning. :beers:

**Comment by jingweno** [comment]
:beers:
