### ISSUE TITLE
Framework based on Symfony2 & AngularJS - Aisel

### ISSUE THREAD

**Issue by ivanproskuryakov** [thechangelog/ping#214]
## Aisel
Aisel is an ambitious innovative framework which allows you to create indefinite project possibilities including e-commerce solutions for retailers and CRM/ERP for business needs. 

Project Github page: https://github.com/ivanproskuryakov/Aisel
Website: http://aisel.co/

<img width="400" class="homepage-image" src="https://camo.githubusercontent.com/358238a20f995762540cbf4b1fc8d34eea59c425/687474703a2f2f616973656c2e636f2f73637265656e73686f74732f66726f6e74656e645f70726f647563745f766965772e706e67">

**Comment by jerodsanto** [comment]
@ivanproskuryakov we're including Aisel  in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by ivanproskuryakov** [comment]
@jerodsanto awesome :+1:
