### ISSUE TITLE
Torba: Bundler for Sprockets/Rails asset pipeline

### ISSUE THREAD

**Issue by nashbridges** [thechangelog/ping#215]
This gem allows to download remote JS/CSS libraries and prepare them for being used in Rails asset pipeline (or, generally speaking, with Sprockets, so a Sinatra app may also benefit from it) without relying on Bower/npm.

Github page: https://github.com/torba-rb/torba

The project was battle tested and extracted from halalbooking.com project.

**Comment by jerodsanto** [comment]
@nashbridges we're including Torba in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Thanks for sharing! :beers:

**Comment by nashbridges** [comment]
Thank you for spreading the word!
