### ISSUE TITLE
Scala By Example

### ISSUE THREAD

**Issue by apranav19** [thechangelog/ping#216]
Hi, 

I came across your [Learning by Example](https://changelog.com/learning-by-example/) post. I have often referred to this book by Martin Odersky, [Scala By Example](http://www.scala-lang.org/docu/files/ScalaByExample.pdf) (PDF), and I felt it would be an awesome addition to your existing list.

Thanks,
Pranav

**Comment by jerodsanto** [comment]
@apranav19 added it to the post. Thanks for letting us know about it! :beers:
