### ISSUE TITLE
Ruby on Windows Guides

### ISSUE THREAD

**Issue by bosko** [thechangelog/ping#217]
New version of [Ruby On Windows Guides Book](http://rubyonwindowsguides.github.io) is released. 

There are number of changes compared to previous version. ConEmu is used for better and easier work in Command Prompt, Uru is now main Ruby version manager.

Default Ruby is now 2.2.1, Rails is updated to 4.2.1 and chapters about SQlite, MS SQL, MySQL and PostgreSQL all use latest versions.

Finally whole site has new look and feel.

**Comment by jerodsanto** [comment]
@bosko nice work! We'll link you up in the next issue of [Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. Cheers! :beers:

**Comment by bosko** [comment]
:beers:
