### ISSUE TITLE
Android IMSI-Catcher Detector (AIMSICD)

### ISSUE THREAD

**Issue by SecUpwN** [thechangelog/ping#218]
[![AIMSICD-Banner](https://spideroak.com/share/IFEU2U2JINCA/GitHub/home/SecUpwN/SpiderOak/PROMOTION/AIMSICD-Banner_Small.png)](https://secupwn.github.io/Android-IMSI-Catcher-Detector/)

Good morning everyone! I have just read your [awesome blogpost](https://changelog.com/top-ten-reasons-why-i-wont-use-your-open-source-project/) and it motivated me to give you a hint here about our open source project to *detect fake base stations*, the [Android IMSI-Catcher Detector](https://secupwn.github.io/Android-IMSI-Catcher-Detector/).

---

[IMSI-Catchers](https://en.wikipedia.org/wiki/IMSI-catcher) are false mobile towers (base stations) acting between the target mobile phone(s) and the real towers of service providers. As such they are considered a Man-In-The-Middle (MITM) attack. In the USA the IMSI-Catcher technology is known under the name "[StingRay](https://en.wikipedia.org/wiki/Stingray_phone_tracker)". Our app shall detect the attacks.

We're currently **seeking contributors** and would be very happy if you'd help us finding a few Android developers with **heart-blood** for hardcore FOSS since we're [standing strong against GooglePlay](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/FAQ#q-why-wont-you-upload-your-app-to-the-google-play-store).

---

**What it does**

>AIMSICD attempts to detect IMSI-Catchers through detection methods such as these:

>* Check tower information consistency
>* Prevent silent app installations
>* Check LAC/Cell ID consistency
>* Check Neighbouring Cell Info
>* Signal strength monitoring
>* Look for silent SMS
>* Detect FemtoCells

>See our [app goals](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status#application-goals) and [development status](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Development-Status)!

**Why use it**

>The FBI or local police regularly deploys IMSI-Catchers hidden in vehicles at protests to obtain a record of everyone who attended with a cell phone (leave your phones at home by all means if you really have to attend). IMSI-Catchers also allow adversaries to intercept your conversations, text messages, and data. Police can use them to determine your location or to find out who is in a given geographic area at what time. Identity thieves can use freely available tools to monitor and manipulate communications from a parked car in your residential neighborhood; notably for stealing passwords or credit card data from people nearby who make purchases on their phones.

>The reason IMSI-Catchers are so commonly used is that it is very easy to get away with using them traceless. This app aims to make it possible to detect the IMSI-Catchers so that using them becomes a risky proposition. It also aims to make users safer by alerting on possible interception and tracking.

**Useful links:**

* [Website](https://secupwn.github.io/Android-IMSI-Catcher-Detector/)
* [Repo](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector)
* [Twitter](https://www.twitter.com/AIMSICD)
* [WIKI](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki)
* [Press](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Press-Releases)
* [Media](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Media-Material)

Constructive criticism and improvement suggestions are always welcome, please drop me an email.

**Comment by jerodsanto** [comment]
@SecUpwN thanks for sharing this! We're going to include it in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly) and we'll be sure to put a note in there that you're seeking contributors. Keep up the good work! :beers:

**Comment by SecUpwN** [comment]
@jerodsanto, from behalf of our whole team: **THANK YOU** for including us! We really hope that a few more Android developers will help us beautifying our code, fixing bugs and adding features. Cheers! :beer:

**Comment by SecUpwN** [comment]
@TheChangelog and @jerodsanto, would you please craft and release another message with below content on [Changelog Weekly](https://changelog.com/weekly) as well as on Twitter using the hashtags `#AIMSICD` and `#IMSICatcher`?

* We've moved to a new organization named `CellularPrivacy`
* We're still seeking Android developers with love for open source
* Developers will tackle bugs faster with [Bountysource donations](https://www.bountysource.com/teams/android-imsi-catcher-detector/issues)
