### ISSUE TITLE
Protractor for AngularJS: Writing end-to-end tests has never been so fun

### ISSUE THREAD

**Issue by ramonvictor** [thechangelog/ping#219]
Open-source slides aimed to explain step-by-step how to use [Protractor E2E testing](http://angular.github.io/protractor/) with practical examples. This documentation covers tips and tricks from beginner to advanced level.

Online slides: http://ramonvictor.github.io/protractor/slides/
Github repo: https://github.com/ramonvictor/rv-protractor

**Comment by jerodsanto** [comment]
@ramonvictor thanks for sharing! Slide decks aren't typically something we cover, but I'd suggest submitting this to [JavaScript Live](https://jslive.com)!

**Comment by ramonvictor** [comment]
Thanks for your feedback, @jerodsanto!
