### ISSUE TITLE
Uniform - A Yeoman generator for building full stack data capture forms

### ISSUE THREAD

**Issue by christill** [thechangelog/ping#220]
A Yeoman generator for building full stack data capture forms.

This will scaffold a full stack application built with the following:

- Nodejs
- Express
- MongoDB
- Handlebars
- jQuery
- Underscore
- Gulp
- Browserify

https://github.com/christill/generator-uniform

**Comment by jerodsanto** [comment]
@christill we're including Uniform in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly/). Cheers! :beers:

**Comment by christill** [comment]
@jerodsanto That's great! Thanks.
