### ISSUE TITLE
Crossplatform crypto library Themis: safe storage and secure messaging

### ISSUE THREAD

**Issue by cossacklabs** [thechangelog/ping#221]
C-written, cross-platform (apple*, android, linux, windows, mac os) library implementing:
* high-level security primitives for secure messaging (standard and session wise) 
* encrypted storage (format preserving and some others)

It has simple wrappers for Python, PHP, Ruby, Objective C (both iOS and MacOSX), Java/Android (both Android and Cyanogen). 

Would be very happy to be featured in any of your lists. We read Weeklies ourselves and dreamt to see our link there when we did Themis ;) 

here's our github rep: https://github.com/cossacklabs/themis
here's a blog post explaining more in-depth matters: http://www.cossacklabs.com/01-introducing-themis.html

**Comment by jerodsanto** [comment]
@cossacklabs we're including Themis in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:
