### ISSUE TITLE
BloomingMenu: A configurable and animated radial menu. BloomingMenu is a port of AwesomeMenu for the web.

### ISSUE THREAD

**Issue by caiogondim** [thechangelog/ping#222]
I ported one Obj-C library to JavaScript with amazing performance and highly configurable.
Maybe you could help spread the word =)
https://github.com/caiogondim/blooming-menu

**Comment by jerodsanto** [comment]
@caiogondim we're including BloomingMenu in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:

**Comment by caiogondim** [comment]
This is amazing.
Thanks guys.

Cheers.
