### ISSUE TITLE
DBLX Database ported to C#

### ISSUE THREAD

**Issue by dblxadmin** [thechangelog/ping#223]
We just completed porting the DBLX database to C#! 
The port is compatible with VisualStudio and Mono (Xamarin) so you can run a database where you need it. 
This port will expand the platforms and devices that DBLX will run on. 
We will continue to maintain both the Java version and the C# version of DBLX going forward. 
Expect a new release of DBLX 3.0 around September.
http://www.dblxdatabase.com/howitworks.html

**Comment by jerodsanto** [comment]
@dblxadmin nice work! we're including this news in our next issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
