### ISSUE TITLE
Pin.js - pin elements as you scroll

### ISSUE THREAD

**Issue by mauriciosoares** [thechangelog/ping#224]
http://github.com/mauriciosoares/pin.js

This is a dependency free plugin to pin elements as you scroll... works smoothly on mobile devices as well (safari on IOS and chrome on Android)

**Comment by jerodsanto** [comment]
@mauriciosoares we're including Pin.js in our next issue of [Changelog Weekly](https://changelog.com/weekly/). Cheers! :beers:

**Comment by mauriciosoares** [comment]
😎Thanks!
