### ISSUE TITLE
Open-source Xcode project template for building HTML/iOS apps

### ISSUE THREAD

**Issue by cptdanko** [thechangelog/ping#225]
https://github.com/cptdanko/IonicStarterAppWithSwift

**Comment by jerodsanto** [comment]
@cptdanko we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by cptdanko** [comment]
Cheers guys,appreciate it and long live open-source!
