### ISSUE TITLE
FP with Haskell

### ISSUE THREAD

**Issue by pascalw** [thechangelog/ping#227]
Would be great to hear a show about Haskell.
Perhaps the author of http://learnyouahaskell.com would make a good guest to talk about Haskell.

**Comment by jerodsanto** [comment]
@pascalw thanks for the suggestion! We'd love to put a Haskell show together.

**Comment by pascalw** [comment]
Awesome! Let me know if there's anything I can do to help facilitate that.

**Comment by jerodsanto** [comment]
@pascalw I sent an email to Miran about coming on the show, but haven't heard back yet. If you know of a better way to get in touch, please let us know!

**Comment by pascalw** [comment]
@jerodsanto I don't unfortunately. Alternatively maybe consider reaching out to Bryan O'Sullivan and/or Don Stewart. They're the authors of another popular Haskell book Real World Haskell.

**Comment by jerodsanto** [comment]
@pascalw well, I'm going to close this for now as the suggestion has been received and acted upon. I'm not gonna give up the search, just gonna close to keep the repo tidy.

I'll post updates here as the occur. Thanks so much for the suggestion!
