### ISSUE TITLE
DeliveryTruck - a lightweight deployment tool for developers

### ISSUE THREAD

**Issue by Nessphoro** [thechangelog/ping#228]
Hiya!

I created a very easy to use deployment tool for use in projects of all size to simplify code deployment -- I primarily use it for Meteor, but it is geared towards all sorts of frameworks. It's pretty easy to use and I'm looking to get the word out there.

**Comment by jerodsanto** [comment]
@Nessphoro we're including Delivery Truck in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
