### ISSUE TITLE
[JavaScript] if-exp - conditional expressions for JavaScript

### ISSUE THREAD

**Issue by FGRibreau** [thechangelog/ping#229]
Some languages implement conditionals (and other well known statements) as expressions, so we can write:

```
val res = if(condition){
    'result 1'
} else if(secondCondition) {
    'result 2'
} else if(thirdCondition) {
    'result 3'
} else {
    'result 4'
}
```

While in JavaScript, conditional expressions can be achieve using ternary operators. Multiple conditions are sometimes hard to read using ternary:

```javascript
var res = condition ?  'result 1' : 
    (secondCondition ? 'result 2' : 
        (thirdCondition ? 'result 3' : 'result 4'));
```

Here is how to write the same thing with iff:

```javascript
var res = iff(condition)
            .then('result 1')
        .elseIff(secondCondition)
            .then('result 2')
        .elseIff(thirdCondition)
            .then('result 3')
        .otherwise('result 4');
```

https://github.com/FGRibreau/iff

**Comment by jerodsanto** [comment]
@FGRibreau is `iff` a library that you wrote? Have a link for more info? Thanks!

**Comment by FGRibreau** [comment]
@jerodsanto indeed, here is the link https://github.com/FGRibreau/iff :)

**Comment by jerodsanto** [comment]
@FGRibreau cool, cool. We'll include this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by FGRibreau** [comment]
Awesome @jerodsanto, thanks!
