### ISSUE TITLE
LoopDrop Javascript

### ISSUE THREAD

**Issue by grahamjenson** [thechangelog/ping#230]
[Loop Drop](http://loopjs.com/) is an [open-source](https://github.com/mmckegg/loop-drop-app) looper, modular synth and sampler designed for improvisation and live performance of music.

**Comment by jerodsanto** [comment]
@grahamjenson we're including Loop Drop in our next issue of [Changelog Weekly](https://changelog.com/weekly/). Thanks for the ping! :beers:
