### ISSUE TITLE
Introducing Empire: A self-hosted PaaS built on Docker & Amazon ECS

### ISSUE THREAD

**Issue by phobologic** [thechangelog/ping#231]
My team @ http://remind.com open sourced our internal PaaS yesterday. 

Blog post announcing it: http://engineering.remind.com/introducing-empire/
Github Repo: https://github.com/remind101/empire

Thanks!  Love the Changelog! :)

**Comment by jerodsanto** [comment]
@phobologic very cool! We're going to feature this in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly/). Thanks for sharing! :beers:

**Comment by phobologic** [comment]
Awesome!  Thanks!
