### ISSUE TITLE
Frontend Cheatsheets

### ISSUE THREAD

**Issue by logeshpaul** [thechangelog/ping#232]
Handpicked collection of cheat sheets for your frontend needs & reference

https://github.com/logeshpaul/Frontend-Cheat-Sheets

**Comment by jerodsanto** [comment]
@logeshpaul we'll shoot [a tweet](https://twitter.com/changelog) your way later this afternoon! :beers:

**Comment by logeshpaul** [comment]
Thanks a lot :+1:
