### ISSUE TITLE
WTF with Python?!?

### ISSUE THREAD

**Issue by cclauss** [thechangelog/ping#233]
Guys...  Love the show but [what up with Python](https://changelog.com/tagged/python)?!?  Not one single podcast on the topic.  It is personal or what?  Did you have a bad trip when experimenting with Python in your youth?  There is plenty of cool innovation in the Python space but not a peep on your podcast.

**Comment by jerodsanto** [comment]
@cclauss definitely not personal! I spent ~6 months writing Python a few years back and enjoyed it very much.

The truth is that it's just a bit outside our natural radars. We used to have some Python-focused contributors to the blog, but that fizzled out over time.

I'm definitely open to having some Python-oriented shows on the podcast. What exactly would you like to hear? Have specifics for us?

**Comment by cclauss** [comment]
Perhaps an interview with [Armin Rigo](https://fr.wikipedia.org/wiki/Armin_Rigo) and the other [people](http://pypy.org/people.html) of [PyPy](http://pypy.org) on the technical and political challenges of [making a language host itself](https://en.wikipedia.org/?title=Self-hosting).  Your [podcast on Go self-hosting](https://changelog.com/148/) was fascinating and it would be cool to hear prospectives on that topic from Python and other language communities.

---

If you could get him, an interview with [Ole Zorn](https://twitter.com/olemoritz) who creates [Pythonista](http://omz-software.com/pythonista), a full featured Python 2.7 IDE on the iPad or iPhone. and [Editorial](http://omz-software.com/editorial)

https://omz-forums.appspot.com/pythonista/post/6187778610036736
Pythonista User Forums: http://omz-forums.appspot.com (the community)
Python-Tools: https://github.com/Pythonista-Tools/Pythonista-Tools (Collection of community contributed code on GitHub)
Ole on GitHub: https://github.com/omz

My EuroPython talk on Pythonista: http://www.youtube.com/watch?v=4BbjSXZnjBo

---

On a separate topic, I would be cool if in your padcasts you could ask your guests a few questions on licensing:

* Under which license do you release your OSS?
* Have you always used that license or did you use other licenses in the past?
* What are the pros and cons of the license that you use?
* Do potential contributors / users of your OSS ever complain about the license that you chose?

**Comment by jerodsanto** [comment]
@cclauss thanks for all the suggestions! We'll try to get a Python-related show lined up soon. Good idea on the licensing bit. I remember we talked about curl's licensing on [episode 153](https://changelog.com/153/) and it was super interesting. We'll definitely keep that in mind for future shows!

**Comment by jerodsanto** [comment]
@cclauss we've tried to line up shows with Guido as well as Ole, but nothing has panned out. 

_(Worth mentioning, licensing was discussed at length in [the latest episode](https://changelog.com/201) due to SQLite's public domain (non)license.)_

I'm going to close this issue, but we'll keep our eyes peeled on a Python-related show we can put together. In the meantime, if you have any more specific show ideas, feel free to open a new issue. ✊
