### ISSUE TITLE
Asynchronous RESTful framework for C++11

### ISSUE THREAD

**Issue by ben-crowhurst** [thechangelog/ping#234]
We're excited to announce the release of Restbed 2.0.  With this release the asynchronous RESTful framework is capable of HTTP 1.1 compliance.

https://github.com/corvusoft/restbed

Corvusoft Solutions is a young (open-source) start-up looking to make a name for its self with middle-tier architectural components.  The Restbed framework is the core of a suite of applications we will be releasing over the coming months.

https://twitter.com/corvusoft
https://google.com/+CorvusoftCoUkSolutions

**Comment by jerodsanto** [comment]
@ben-crowhurst we're including Restbed in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Keep up the good work! :beers:
