### ISSUE TITLE
chandler syncs your CHANGELOG entries to GitHub's release notes

### ISSUE THREAD

**Issue by mattbrictson** [thechangelog/ping#235]
I just released a new Ruby project that might be useful to the community, and would appreciate a mention. Thanks!

> **chandler syncs your CHANGELOG entries to GitHub's release notes so you don't have to enter release notes manually.** For Ruby projects, you can even add chandler to your gem's Rakefile to make this an automatic part of your release process!

https://github.com/mattbrictson/chandler

**Comment by jerodsanto** [comment]
@mattbrictson we're going to feature this in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly). I also just queued up a tweet your way! :beers:

**Comment by mattbrictson** [comment]
Thank you!
