### ISSUE TITLE
An episode about spacemacs

### ISSUE THREAD

**Issue by khebbie** [thechangelog/ping#236]
I have been using spacemacs as my primary editor for about a month now, and it is really great.
I think it is a really great layer of configuration around emacs to make it a lot easier to step into.
Especially coming from vim it is a joy to use.

So it would be great if you could get Sylvain Benner on the show and ask him about his experience with emacs and how he ended up doing spacemacs.

**Comment by jerodsanto** [comment]
Good idea! Spacemacs could be our one hope to end the Editor Wars once and for all. :wink:

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
