### ISSUE TITLE
fkill - Kill processes

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#237]
[<img width="300" src="https://rawgit.com/sindresorhus/fkill/master/media/logo.svg" align="right">](https://github.com/sindresorhus/fkill)

I made a module that makes it easier to kill processes.

You can kill by either process name or ID, and you can supply multiple names/IDs in one call.

Can be used from the command-line or Node.js.

Works on OS X, Linux, Windows.

CLI: https://github.com/sindresorhus/fkill-cli
Node.js API: https://github.com/sindresorhus/fkill

**Comment by jerodsanto** [comment]
@sindresorhus this looks like a good one for [Changelog Weekly](https://changelog.com/weekly). :beers:
