### ISSUE TITLE
run.sitespeed.io - an online version of sitespeed.io

### ISSUE THREAD

**Issue by soulgalore** [thechangelog/ping#238]
I've made a new project that's a Docker based online version of sitespeed.io (a cli based web performance tool). You can use it to test your sites against web performance best practice rules and collect timing metrics from Firefox/Chrome.

You can test it out at: https://run.sitespeed.io
Source: https://github.com/sitespeedio/run.sitespeed.io

![sitespeedio cat - superman 1](https://cloud.githubusercontent.com/assets/540757/8443502/999db080-1f87-11e5-9f9a-cd38c60dc0d0.png)

**Comment by jerodsanto** [comment]
@soulgalore we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by soulgalore** [comment]
thanks @jerodsanto :) FYI: also wrote a blog post about the setup: http://www.peterhedenskog.com/blog/2015/07/learnings-deploying-sitespeed.io-online-using-docker/
