### ISSUE TITLE
Prevent broken builds from slowing your team down with mergeq

### ISSUE THREAD

**Issue by aaronjensen** [thechangelog/ping#239]
Howdy, I just released some scripts to help set up pre-tested commits (merges, really) with any git repo and any CI service.

http://substantial.com/blog/2015/6/24/introducing-mergeq/
https://github.com/aaronjensen/mergeq

![comic](http://substantial.com/assets/images/blog/2015/06/mergeq-comic.png)

Thanks!

**Comment by jerodsanto** [comment]
@aaronjensen we're including mergeq in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:

**Comment by aaronjensen** [comment]
Awesome, thanks!


Aaron
