### ISSUE TITLE
Most used UI Components — of web applications

### ISSUE THREAD

**Issue by logeshpaul** [thechangelog/ping#240]
https://github.com/logeshpaul/UI-Components

Almost most of the UI components you use in your web applications as a collection.

**Comment by jerodsanto** [comment]
@logeshpaul we're including your UI Components repo in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. Cheers! :beers:

**Comment by logeshpaul** [comment]
Thanks a lot :+1:
