### ISSUE TITLE
Storeman - personal asset tracking

### ISSUE THREAD

**Issue by smwa** [thechangelog/ping#242]
[Storeman](https://github.com/smwa/storeman)(MIT License) is an Angular.js webapp that allows you to quickly manage where you've stored assets.

You define locations, and put items into the locations or containers. It supports QR codes to physically attach to the containers to see what's inside; and uploading images to help you find things.

A full demo is running at [smwa.me](http://smwa.me)

**Comment by jerodsanto** [comment]
@smwa we're including Storeman in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
