### ISSUE TITLE
rtail(1) - Terminal output to the browser in seconds, using UNIX pipes

### ISSUE THREAD

**Issue by kilianc** [thechangelog/ping#243]
https://github.com/kilianc/rtail - http://rtail.org/

#### Terminal output to the browser in seconds, using UNIX pipes.

rtail is a command line utility that grabs every line in stdin and broadcasts it over UDP. That's it. Nothing fancy. Nothing complicated. Tail log files, app output, or whatever you wish, using rtail broadcasting to an rtail-server – See multiple streams in the browser, in realtime.

**Comment by jerodsanto** [comment]
@kilianc pretty rad. I love how simple-yet-powerful it is. We're going to link this up in tomorrow's [Changelog Weekly](https://changelog.com/weekly). :beers:
