### ISSUE TITLE
Hopper Test 

### ISSUE THREAD

**Issue by jvrmaia** [thechangelog/ping#244]
"Hear proposals from the developer community - specially from women - about creating a test that assesses women friendly companies"

https://github.com/HopperTest/HopperTestProposals

**Comment by jerodsanto** [comment]
I'm not sure I understand what this is.

**Comment by jvrmaia** [comment]
Like [Joel Test](http://www.joelonsoftware.com/articles/fog0000000043.html) but...  

["Hopper Test is a checklist that a company must provide to have a diversity-friendly enviroment where people feel included." ](https://github.com/HopperTest/HopperTestProposals/blob/master/English/hopper_test.md#hopper-test-proposals)

If I understand the purpose of this repository, I think will be nice The Changelog share this project.

From a listener of Podcast and reader of Weekly and Nightly. :smile:

**Comment by jerodsanto** [comment]
@jvrmaia thanks. We'll include this in this Saturday's issue of Weekly. :beers: and thanks for listening/reading!

**Comment by jvrmaia** [comment]
@jerodsanto thanks! :smile: :beers:
