### ISSUE TITLE
Better searches for Github

### ISSUE THREAD

**Issue by xcambar** [thechangelog/ping#245]
Hi,
I've just launched a small browser extension (Chrome, FF) that lets you save (and sync) your searches in Github.
As a project/community manager, it saves a lot of time as you don't have to type the same search terms again and again.

Here it is: http://xcambar.github.io/github-better-filters

Cheers,

**Comment by jerodsanto** [comment]
@xcambar pretty nice. I just queued up a tweet in your direction and we'll be featuring this in the next issue of [Changelog Weekly](https://changelog.com/weekly) as well. :beers:

**Comment by xcambar** [comment]
Yay, thanks a lot!
