### ISSUE TITLE
Where can I get podcast transcriptions in english ?

### ISSUE THREAD

**Issue by IBIT-ZEE** [thechangelog/ping#246]
Anywhere where I can get transcriptions in text format (english version)
There is to much information in some podcasts I prefer to read the content...

Thanks

**Comment by jerodsanto** [comment]
@IBIT-ZEE we don't currently offer transcriptions. It's an expensive and difficult thing to put together. We are open to transcriptions if enough people want them, but we're not sure that they do (you are first person to ask for transcriptions since I began co-hosting the show).
