### ISSUE TITLE
brightness - Change screen brightness

### ISSUE THREAD

**Issue by kevva** [thechangelog/ping#247]
![](https://github.com/kevva/brightness-cli/raw/master/screenshot.png)

brightness is a module that makes it easy to change screen brightness. Useful for laptops that doesn't have a keyboard with shortcuts that allows you to do it.

Can be used from the command-line or using the API. And it works cross-platform.

CLI: https://github.com/kevva/brightness-cli
API: https://github.com/kevva/brightness

**Comment by sindresorhus** [comment]
:+1:

**Comment by jerodsanto** [comment]
@kevva :+1:. We'll include this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
