### ISSUE TITLE
TiddlyWiki

### ISSUE THREAD

**Issue by FND** [thechangelog/ping#248]
Going through the podcast archives, I realized that @tiddlywiki (http://tiddlywiki.com - created by @Jermolene) would make for an excellent topic for the show.

TiddlyWiki was one of the earliest single-page applications and is in many ways both unusual and thought-provoking. Its latest incarnation was rewritten from scratch, taking advantage of the JavaScript community's modern tooling.

I'm certain @Jermolene would make for an excellent interviewee.

**Comment by jerodsanto** [comment]
@FND looks cool to me. Thanks for the idea!

**Comment by jerodsanto** [comment]
@Jermolene we'd _love_ to have you on the show to talk about TiddlyWiki! If interested, please email editors@changelog.com and we'll line it up. :beers:

**Comment by jerodsanto** [comment]
@FND this show is now live! :tada: 

https://changelog.com/196/

We gave you a shout out on the show, but we had to say F N D because your name is nowhere online! :stuck_out_tongue_winking_eye:

**Comment by FND** [comment]
Thanks, I appreciate the update.

> your name is nowhere online

Mission Accomplished
