### ISSUE TITLE
Phabricator, an open source, software engineering platform

### ISSUE THREAD

**Issue by samyakbhuta** [thechangelog/ping#25]
Here is the link : http://phabricator.org. Loved the humour.  Like ...

> You can write text.
> That text stays there.
> You can read it later.
> You can make text bold. Bold text wins arguments!

and 

> Companies probably using Phabricator

**Comment by Zarokka** [comment]
I'm neither involved nor a user of phabricator, but saw kolab and kde using it:

https://git.kolab.org/
https://phabricator.kde.org/

and would love to here an episode about it
