### ISSUE TITLE
AMAs

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#250]
I'm sure you're aware of the [AMA thing on Reddit](https://www.reddit.com/r/AMA/).

I decided to try one for myself using a GitHub issue tracker. Actually similar to what you're doing with `ping` here. Some other people wanted to try it out, so I made a recipe and a list of all the AMAs people made: https://github.com/sindresorhus/amas The list is now huge!

Lots of interesting AMAs in that list. Might be worth mentioning.

**Comment by jerodsanto** [comment]
@sindresorhus we'd love to do an AMA with you on the show :grin:

**Comment by sindresorhus** [comment]
@jerodsanto Thanks for the invite, but I prefer listening to the show than being on it ;)

**Comment by adamstac** [comment]
I agree with @jerodsanto. We'd love to have you on the show @sindresorhus.

**Comment by jerodsanto** [comment]
@sindresorhus well the offer stands, just let us know when you're ready. :)

I'm going to close this, but it has given me an idea for a longer post. Keep up the prolific openness! :beers:
