### ISSUE TITLE
Introducing MarkupKit

### ISSUE THREAD

**Issue by gk-brown** [thechangelog/ping#254]
MarkupKit is a framework for simplifying development of iOS applications. It allows developers to construct user interfaces declaratively using a human-readable markup language, rather than programmatically in code or interactively using a visual modeling tool such as Interface Builder.
 
Building an interface in markup makes it easy to visualize the resulting output as well as recognize differences between revisions. It is also a metaphor that many developers are comfortable with, thanks to the ubiquity of HTML and the World Wide Web.

https://github.com/gk-brown/MarkupKit

See the project README for more information. An abridged introduction to the framework can be found here:

https://gkbrown.wordpress.com/2015/07/14/introducing-markupkit/

**Comment by jerodsanto** [comment]
@gk-brown very cool. We included MarkupKit in yesterday's issue of [Changelog Weekly](https://changelog.com/weekly).

(:boom: [Check it out here](http://email.changelog.com/t/t-E3FCCD1BFEFBDDCD) :boom:)

Keep up the good work! :beers:

**Comment by gk-brown** [comment]
Excellent - thanks!
