### ISSUE TITLE
Pig: Wishlist for the next version

### ISSUE THREAD

**Issue by rafael-santiago** [thechangelog/ping#255]
Hi,

I am planning the next version of this [tool](https://github.com/rafael-santiago/pig). I would appreciate some suggestions for it. I openned an [issue](https://github.com/rafael-santiago/pig/issues/4) to get this wishes.

Thanks!

**Comment by jerodsanto** [comment]
@rafael-santiago we'll give you a shout in tomorrow's [Changelog Weekly](https://changelog.com/weekly/). Hopefully that'll help you get some suggestions. :beers:

**Comment by rafael-santiago** [comment]
It is ok. Thank you!
