### ISSUE TITLE
PR Log: Turn Pull Requests into Changelog Entries

### ISSUE THREAD

**Issue by tf** [thechangelog/ping#256]
[tf/pr_log](https://github.com/tf/pr_log) (MIT license) is a small command line tool which fetches  recent pull requests from a GitHub repository and inserts changelog items. It encourages handcrafted changelogs and plays nicely with existing changelog content. It uses GitHub milestones and labels to filter items and insert custom prefixes like "Bug fix". In most cases it can parse its configuration automatically from the project's gemspec.

It can be an alternative to [skywinder/github-changelog-generator](https://github.com/skywinder/github-changelog-generator) if you wish to write your changelog by hand, but still want some automation and high consistency with your gem's GitHub issue tracker.

**Comment by jerodsanto** [comment]
@tf we're including PR Log in our next issue of [Changelog Weekly](https://changelog.com/weekly/). Watch for it to It :ship: tomorrow. :beers:

**Comment by tf** [comment]
:+1: Thanks!
