### ISSUE TITLE
minigrid: minimal 2kb zero dependency cascading grid layout

### ISSUE THREAD

**Issue by henriquea** [thechangelog/ping#257]
Hey guys, I just built this little thing called [minigrid](http://henriquea.github.io/minigrid) a minimal 2kb zero dependency cascading grid layout.

Cheers,
H

**Comment by jerodsanto** [comment]
@henriquea we included minigrid in this morning's issue of Changelog Weekly. [Check it out](http://email.changelog.com/t/t-941CBC07EAEFEB09)! :beers:

**Comment by henriquea** [comment]
Nice one @jerodsanto thanks! 🙌
