### ISSUE TITLE
Vantage.js: CLI + SSH + REPL for Node

### ISSUE THREAD

**Issue by dthree** [thechangelog/ping#258]
Hey guys.

Recently made a Node module - Vantage.js. In short, it turns your Node app into an interactive CLI that can be remotely accessed as well as locally. The project homepage has a GIF that shows you a bit better:

https://github.com/dthree/vantage

This last week, I was very lucky in that it blew up on HN and was the no. 1 pjt on github two days ago. If you guys like it, I think it would be awesome if you could throw it into your weekly newsletter.

Thanks!

David

ps: love thechangelog - subscribe to daily & weekly

**Comment by jerodsanto** [comment]
@dthree we saw this the other day and [shot you a tweet](https://twitter.com/changelog/status/626750953191014400) as well!

Vantage looks really nice. We'll definitely include it in tomorrow's Weekly. :beers:

**Comment by dthree** [comment]
Hey, thanks for doing that! Glad you like it: you guys are the best! :beers:
