### ISSUE TITLE
Knock: JWT authentication for Rails

### ISSUE THREAD

**Issue by nsarno** [thechangelog/ping#259]
Hi guys,

I recently released a gem called Knock for Rails to help with JWT authentication. It's already used by [Auth0](https://auth0.com/docs/server-apis/rails) and got some exposure in [RubyWeekly](http://rubyweekly.com/issues/256). I thought it would be nice to submit it here.

- [Check out Knock on github](https://github.com/nsarno/knock)
- [Check out Knock on rubygems](https://rubygems.org/gems/knock)

Let me know what you think!

Thanks :)

**Comment by jerodsanto** [comment]
@nsarno very cool! We're going to link this up in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:

**Comment by nsarno** [comment]
Thanks! :tada:
