### ISSUE TITLE
dush: minimal 1.5kb zero dependency event handling for >=IE8 and nodejs

### ISSUE THREAD

**Issue by tunnckoCore** [thechangelog/ping#260]
Hi! That is [tunnckoCore/dush](https://github.com/tunnckoCore/dush)
Just published minimal event handling library, more minimal than http://npm.im/dual-emitter which is almost the same (4kb) and in it can view the API docs.

### features
- minimal, yet simple to use
- just 1.5kb minified - no jQuery, no dependencies
- works on the browser (even IE8)
- works on the server, just install it and require it
- plays well with browserify
- can emit (trigger or whatever you call it) DOM events manually
- have `.on`, `.off`, `.once` and .`emit` methods

**Comment by jerodsanto** [comment]
@tunnckoCore we included dush in this morning's issue of Changelog Weekly. [Check it out](http://email.changelog.com/t/t-941CBC07EAEFEB09)! :beers:
