### ISSUE TITLE
mycli - A mysql command line client with auto-completion and syntax highlighting

### ISSUE THREAD

**Issue by amjith** [thechangelog/ping#261]
Home page: http://mycli.net

Mycli is a command line interface to MySQL database with modern features such as context aware auto-completion and syntax highlighting.

The goal of this project is to provide a pleasant user experience for MySQL users out of the box. 

![main](https://cloud.githubusercontent.com/assets/49260/9055061/09959474-3a3c-11e5-9a48-b4a5a4b631e9.gif)

Screenshots: http://mycli.net/screenshots

This open source project was funded through [Kickstarter](https://www.kickstarter.com/projects/1839007321/mysql-cli). 

Postgres equivalent: http://pgcli.com

**Comment by jerodsanto** [comment]
@amjith we included mycli in this morning's issue of Changelog Weekly. [Check it out](http://email.changelog.com/t/t-941CBC07EAEFEB09)! :beers:
