### ISSUE TITLE
disable_with_spinner (Rails) - Replace contents of a button with animated spinner with an ease

### ISSUE THREAD

**Issue by mib32** [thechangelog/ping#262]
Hello! This is my new project - https://github.com/mib32/disable_with_spinner
I missed that kind of gem for a long time, and haven't found any plug`n`play alternative yet.

**Comment by jerodsanto** [comment]
@mib32 we included disable_with_spinner in this morning's issue of Changelog Weekly. [Check it out](http://email.changelog.com/t/t-941CBC07EAEFEB09)! :beers:
