### ISSUE TITLE
haxe: the compile-to-everything language

### ISSUE THREAD

**Issue by andyli** [thechangelog/ping#263]
Hi!

Not sure have you heard of Haxe?
It is a language that compiles to JavaScript.. as well as Java, C#, C++, Python, PHP, Flash...
A few days ago I've published [a blog post comparing TypeScript and Haxe](http://blog.onthewings.net/2015/08/05/typescript-vs-haxe/) and it showed up on the hacker new front page for a day and I can see that people are interested in the comparison.
Would be great if you could check it out and spread the info about this cool language :)

Haxe website: http://haxe.org/
Github: https://github.com/HaxeFoundation/haxe

**Comment by jerodsanto** [comment]
@andyli we included Haxe in yesterday's issue of [Changelog Weekly](https://changelog.com/weekly), and we even linked up your log post comparing it to TypeScript. :beers: 

(:boom: [Check out the issue here](http://email.changelog.com/t/t-E3FCCD1BFEFBDDCD) :boom:)
