### ISSUE TITLE
iTermocil - Create pre-defined window/pane layouts and run commands in iTerm 

### ISSUE THREAD

**Issue by TomAnthony** [thechangelog/ping#264]
Hi guys,

I recently released a tool for developers who use iTerm, and having read your "Top ten reasons why I won’t use your open source project" I thought I'd post it here.

iTermocil allows you setup pre-configured layouts of windows and panes in iTerm2, having each open in a specified directory and execute specified commands. The layout files are fully compatible with teamocil files if you are a tmux user.

https://github.com/TomAnthony/itermocil

I hope you guys find it interesting.

Thanks. :)

**Comment by jerodsanto** [comment]
@TomAnthony we included iTermocil in our last issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:d yesterday. :beers:

(:boom: [check out the issue here](http://email.changelog.com/t/t-E3FCCD1BFEFBDDCD) :boom:)
