### ISSUE TITLE
Kattappa - A block based Rich Text editor created using React

### ISSUE THREAD

**Issue by brijeshb42** [thechangelog/ping#265]
Kattappa is a block based rich text editor created using React.
It uses Quilljs for rich text support.

Checkout the demo @ http://bitwiser.in/kattappa/demo.html
Source @ https://github.com/brijeshb42/kattappa
Docs @  http://bitwiser.in/kattappa/

**Comment by jerodsanto** [comment]
@brijeshb42 we're including Kattappa in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
