### ISSUE TITLE
A refactoring of an OSS project (single class)

### ISSUE THREAD

**Issue by ledestin** [thechangelog/ping#266]
Hi there,

I wrote a post about refactoring a class from an open-source project (Ruby). People say it's interesting, so you might like it.
http://rubyclarity.com/2015/08/paginatedresource-refactoring/

Thanks.

**Comment by jerodsanto** [comment]
@ledestin we'll link this up in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
