### ISSUE TITLE
Easy Reporting Tool

### ISSUE THREAD

**Issue by klauscam** [thechangelog/ping#267]
Hi guys,
After reading your guidelines on why you won't use my open source project through your article (which btw was very helpful), I decided to get in contact with you on a project I've just released. It's called Easy Reporting Tool. It is a web based product which lets users create queries in sql, save them, and publish the result on a web page. End users can then run the query simply by accessing the url. There are similar products for php/mysql stack but I could not find any for Sql Server so I decided to build one and share it with the world. It is hosting at http://klauscam.github.io/EasyReportingTool

Hope you like my product and if you feel like criticising it, you are more than welcome.

Thanks.

**Comment by jerodsanto** [comment]
@klauscam we're including your Easy Reporting Tool in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
