### ISSUE TITLE
The Neo4j.rb Project

### ISSUE THREAD

**Issue by cheerfulstoic** [thechangelog/ping#268]
I'm one of the maintainers of the Neo4j.rb project (which is primarily the `neo4j` and `neo4j-core` gems).  The gems allow you to use the Neo4j graph database from Ruby.  I've also recently created a series of RubyTapas-style screencasts as an introduction to the project.

https://www.youtube.com/playlist?list=PL5klM3mD6alLUhNTPTbj5a3GBjU7oZN0t

If you're already familiar with things like ActiveRecord and Mongoid you'll probably want to start with episode four.  Those last three episodes were featured on the Neo4j blog recently, so you can read a summary of them here:

http://neo4j.com/blog/advanced-ruby-on-rails-with-neo4j/

The summary of Neo4j is that it is a (open source!) graph database which means that it makes exploring the relationships between entities in a database really simple and fast.  This comes up as particularly useful in applications such as recommendation engines and social networks, but in my opinion it makes for a good general purpose database too because of it's natural style of data modeling.

The Neo4j.rb project brings the same sort of niceties that you would expect from ActiveRecord/Mongoid but to Neo4j.  In addition, though, thanks to Neo4j's natural querying abilities you can do some great things which you can't do with an RDMS or MongoDB.  I wrote a SitePoint article demonstrating some of how this works recently:

http://www.sitepoint.com/why-you-should-use-neo4j-in-your-next-ruby-app/

You can find out more information about the Neo4j.rb project on our website and in our readthedocs docs:

http://neo4jrb.io/

http://neo4jrb.readthedocs.org/

If you have any questions we also hang out on Gitter a lot:

https://gitter.im/neo4jrb/neo4j

I'd be happy to do an interview if you wanted to do a show about Neo4j and/or the Neo4j.rb project.

**Comment by cheerfulstoic** [comment]
Oh, and as a point of human interest: I'm also currently traveling around the world with my wife and son.  You can read more about our trip here: http://www.grandadventures-householdchores.com/about-us/

**Comment by jerodsanto** [comment]
@cheerfulstoic sorry, we let this one slip through the cracks on us. I thought you did a great job on RR a couple weeks back, and I'm not sure if we could cover much more ground than they did. I'm going to link that one up here in case anybody is looking for a show on the topic. :beers: 

https://devchat.tv/ruby-rogues/236-rr-neo4j-with-brian-underwood

**Comment by cheerfulstoic** [comment]
No problem, cheers ;)
