### ISSUE TITLE
Armada Platform - new docker based PaaS

### ISSUE THREAD

**Issue by karamazi** [thechangelog/ping#269]
Hi, I’m one of developers of Armada Platform. We have developed it as an internal tool at Ganymede and, recently, open sourced it to share it with others and get some feedback on what could be improved. :smiley: 

Armada is a docker-based solution in which we integrated a lot of cool features, such as service-discovery, load balacing, clustering, configuration management, services repository and meaningful health checks of services.  We designed it to be easy to use and flexible allowing developers not familiar with docker to dive into the world of containers, and enabling advanced docker users to select which features they want to use. 

[Armada on Github](https://github.com/armadaplatform/armada)
[Armada website](http://armada.sh)

**Comment by jerodsanto** [comment]
@karamazi cool stuff. We'll link this up in tomorrow morning's [Changelog Weekly](https://changelog.com/weekly/). :beers:
