### ISSUE TITLE
Perfectionist generator that scaffolds out different types of Frontend apps

### ISSUE THREAD

**Issue by logeshpaul** [thechangelog/ping#270]
**Features**
Different Projects; One Generator - Create your type of project in fairly simple steps
Highly Maintainable - Uses SMACSS approach (BEM, OOCSS, ITCSS in backlog)
Readymade — Directory structure, Naming convention, Linking your app done right.
Speedy Workflow - CSS Preprocessor (Sass), Partials, Browser Sync, Live reload.
Performance Matters - Minify HTML, CSS, & JS. Optimize Images.
Quick Commands - Generate Build, Clean up, Zip project, Angular commands and lot more to come.

**App Types**
Simple Web App — Sometimes you just need a gulp server(localhost), scss compiler & browser-sync(live reload). Well that's exactly what this app is for.
Full Pack Web App - Thinking of creating a solid frontend base with proper structure, well optimization; choose this applicaton type which comes with power features.
Angular App - Angular app with basic configurations and quick commands for creating controllers, directives, services and filters. More to come!
Restify App - API developer? Want to create REST API services with mongodb, This app type got your back which scaffolds basic files like models, controller, routes, db & config.
Admin Web App - Create an Admin app with bootstrap integrated. Pages: Dashboard, Sidebar, Notfication, Forms, Tabular Data and Bootstrap Elements for quick use.

Github: https://github.com/FuelFrontend/generator-smacss
NPM: https://www.npmjs.com/package/generator-smacss

**Comment by jerodsanto** [comment]
@logeshpaul we included this in [today's issue of Changelog Weekly](http://email.changelog.com/t/t-D4E0966AA0002771). :beers:
