### ISSUE TITLE
A free, open source e-commerce platform for static websites

### ISSUE THREAD

**Issue by christophercliff** [thechangelog/ping#271]
https://json.expert/flatmarket/

Flatmarket is a free, open source e-commerce platform for static websites. Its simple architecture makes it extremely reliable, secure, and inexpensive to operate.

The platform uses [Stripe](https://stripe.com/) for payment processing and is built on the latest web technologies like [hapi](http://hapijs.com/), [React](http://facebook.github.io/react/), and [Webpack](http://webpack.github.io/).

At its core is a batteries-included CLI to help you get started quickly. Modules are also packaged individually so you can customize your rig.

**Comment by jerodsanto** [comment]
@christophercliff we're including Flatmarket in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
