### ISSUE TITLE
The show is amazing...

### ISSUE THREAD

**Issue by dkovach** [thechangelog/ping#272]
I just discovered you all after semi-suffering through listening and getting informed via another podcast's backlog of a few years of shows on a specific technology -- to then hear one show from you, and it was a revelation! I have been deep in a project, working endlessly, and joy of sitting solo for so much of my life is greatly extended by getting time to listen to something so professional, well-informed, well-prepared, thoughtful, sometimes funny, always professional, and always aware of you are getting time in my life and world -- and you don't misuse that by pompously thinking your jokes or personality might be the point of why I am listening or that it is should be all that prominent. That is what makes something clearly on another level. 

I mean I go from Marc Maron to you guys and back to Maron. And he interviewed the President. 

But, to me - these shows and where I started my Changelog journey have been incredibly powerful, informing and makes me I guess feel less alone even. We sit here working and to hear your consistent voices and approach, and then guests that have a lot to say on a topic and in life, and in doing what we all do and why. 

It is simply something you all should be paid $xxx,xxx to do not unlike high priced quality commentators, news people or morning radio jocks of yesteryear. 

It is an amazing service you all are doing for the whole of the tech world.

Shows I started with -

no. 91 Discover Meteor.js ----- A+ ... Sacha is amazing. Literally minutes later spent $90 for his premium offering of his book. Footnote: Bought a related buy as well from Arunoda -- another guy you all should have on, followed by Abigail Watson -- she is doing applied work wth Meteor in the clinical drug trial management realm and has a Meteor working group setup for it. Powerful stuff.

no. 169 Middleman ---- A ... Amazing interview and informing. Something I was totally unaware of, but kinda in a simple way - mind expanding.

no. 155 Future of Node w/ Scott Hammond --- A++++ Wow, that whole situation... this was like the 60 Minutes interview if there was one on the topic. You all went for the tough questions and pushed the limits, it was impressive.

no. 132 Buckets CMS ---- B- Amazing interview, but then I was kinda pissed to see Buckets alittle dried up right now, not your fault. Interview was great w/ a really different personality, coming off the more executive Scott Hammond interview.

no. 164 Semantic UI --- A+++++ It's tough to say, but this might be my favorite interview. It hit things more deeply and profoundly about life. But, Semantic UI kicks ass -- Bootstrap is like a difficult toy at some point a kid will loose interest in because it makes little sense in holisitic terms/comparatively. 

no. 139 Rise of IO.JS --- B- See my pattern with node...? I wish I had listened in reverse chronological order as this was getting or feeling long to listen to, because the outcome is now so different, but oddly - he indicated where it was they wanted, and the geeks won! You all covered it, this stuff is must listen to material.

Keep up the amazing work and thank you for assisting making my work easier to get through hours on end and informing all of us and doing so with tip top quality production and being professional and really conscientious of what listeners really need and want.

- David

**Comment by adamstac** [comment]
@dkovach I can't thank you enough for sharing this feedback. Hearing this makes what we do worth it. I just don't what to say. I'm at a loss for words. No one has ever been so generous with their thoughts and feedback on what we do here. I really, really appreciate it.

Thank you!

**Comment by panoysia** [comment]
I learned so much about the happenings in the open-source community, plus the wonderful articles and tutorials curated by Changelog. Truly indispensable. More power to Changelog!

**Comment by jerodsanto** [comment]
@dkovach wow, this is our best ping ever :heart: 

The per-episode feedback is really helpful. I'm curious, how do you listen? Pick and choose your way through our back catalog? Are you subscribed for new episodes? If so, how do you subscribe?

**Comment by dkovach** [comment]
Hi all -

Just catching up, and I got in over on #slack as well, I think I paid you guys right??! Can't recall now.

My pleasure giving you all feedback, I wish in this world more took the time to do so, as it is hard to gauge success sometimes, as it certainly is not about purely page views, or # of listens.

@jerodsanto Yea definitely can answer these and in some ongoing manner as well. I think I need to give some context though of what or where I was coming from, too. Which I think will only further illustrate how accidentally or on purpose PRO you all w/ Changelog.

Best -

DK01 aka David

**Comment by jerodsanto** [comment]
@dkovach I'm going to close this now that we have you in Slack (direct access to your feedback!). Thanks again for your thoughtful input. :green_heart:
