### ISSUE TITLE
alex: Catch insensitive, inconsiderate writing

### ISSUE THREAD

**Issue by wooorm** [thechangelog/ping#273]
“[**alex**](https://github.com/wooorm/alex) ([demo](http://alexjs.com)) catches insensitive, inconsiderate writing. Whether your own or someone else’s writing, alex helps you find unequal phrasing.”

I’ve worked with @sindresorhus on this for the past month. It’s really powerful and I hope it helps the programming/tech community to be a bit more sensitive!

I hope there’s a spot to include alex on the Changelog, I would really appreciate it! :+1:

**Comment by sindresorhus** [comment]
:+1:

**Comment by jerodsanto** [comment]
@wooorm we're including alex in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
