### ISSUE TITLE
Funding open source software

### ISSUE THREAD

**Issue by bestan** [thechangelog/ping#274]
Hi

I'm co-founder of MinoHubs where we're trying to figure out sustainable monetization models for open source software. I've recently discovered Changelog and how awesome it is. Got super excited after listening to a podcast with Mike Perham of Sidekiq and hearing an interesting discussion on this topic.

We've recently blogged about our thoughts and ideas: http://blog.minohubs.com/minohubs/
What do you think about the argument we're making? What are your own views?

**Comment by jerodsanto** [comment]
@bestan I agree that this is an interesting topic. If you listen to the show much you'll hear us talk about sustainability often.

This is definitely a problem that needs to be addressed. I'm not sure what you're building at MinoHubs. As of now the site looks down. Is this an active project?
