### ISSUE TITLE
Cycligent.js: A micro-library for async script loading and classic OOP

### ISSUE THREAD

**Issue by Brian-Whipple** [thechangelog/ping#275]
Just wanted to show you guys this project. Asynchronous script loading, including lazy loading for Angular.js, classic object model, and more. https://github.com/cycligent/cycligent.js

**Comment by jerodsanto** [comment]
@Brian-Whipple we included this in [issue 72 of Changelog Weekly](http://email.changelog.com/t/t-ED37CA82BE561D51). Keep up the good work! :beers:

**Comment by Brian-Whipple** [comment]
@jerodsanto Thanks for the mention.
