### ISSUE TITLE
New Project: HORK Object Relational toolKit

### ISSUE THREAD

**Issue by horkmaster** [thechangelog/ping#276]
HORK is an open-source Object Relational Mapping (ORM) toolkit for database systems.
HORK supports SQL Server, and we will be adding support for other databases as the project moves along.

   http://www.saladforkranchsoftware.com/HORK/index.html

HORK was designed by developers that use ORM frameworks every day. HORK will eventually provide everything needed in an ORM, but will have to retain its low complexity and very good performance.
HORK only contains the features needed to move data to and from the database. Unlike other ORM's, HORK does not add features that replace things the database already can do.

**Comment by jerodsanto** [comment]
@horkmaster we included HORK in [issue 72 of Changelog Weekly](http://email.changelog.com/t/t-ED37CA82BE561D51). Thanks for the ping! :beers:
