### ISSUE TITLE
Interview Request: Tommi Mäkitalo / Tntnet

### ISSUE THREAD

**Issue by reklis** [thechangelog/ping#278]
http://www.tntnet.org/
https://github.com/maekitalo/tntnet
https://github.com/maekitalo/cxxtools
https://github.com/maekitalo/tntdb

**Comment by jerodsanto** [comment]
@reklis any context you can add to this request? Specifically: 

* What is Tntnet and why is it interesting to you?
* Why do you think Tommi would be a good guest?
* What are some specific topics/questions that you'd like to hear discussed?

Thanks!

**Comment by reklis** [comment]
For one I find it a fascinating use of C++. Most folks are afraid of C++ on the web but this seems to make it approachable.

I would like to know more about the project, the original goals, how that changed over time, the background of the interviewee and how the story of how they ended up needing to make the library. In the C++ community a library like this would usually a commercial product, why open source it? 

From a technical perspective what kind of performance improvements can be gained by going native? What are the trade offs?  What are the benefits?

And as fodder for any trolls... Is C++ itself in a renaissance period, or singing a swan song?

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
