### ISSUE TITLE
aero php micro-framework

### ISSUE THREAD

**Issue by ryanxada** [thechangelog/ping#279]
Big fan and current member here. I just wanted to drop you a line and mention that I released the [lightest-weight php framework I have ever seen](https://github.com/ryanxada/aero). It's pretty sparse but comes with some powerful features thanks to the package creators of the software it's built on. It was created for when I'm needing to build a smaller-scale site and WordPress or Laravel/Lumen is overkill, but I still want things like templating, routing and environment variables. I hope it helps someone else too. It takes about 1 minute to set up and is ready out of the box.

Congrats on all the success. I haven't pinged this repo since I dropped subtle.css a while back so it feels good to do something new.

Love the show! Cheers.

**Comment by jerodsanto** [comment]
@ryanxada happy to hear you enjoy the show and thanks for supporting us with your membership! We included aero in [issue 72 of Changelog Weekly](http://email.changelog.com/t/t-ED37CA82BE561D51). Cool stuff! :beers:
