### ISSUE TITLE
Hacker News desktop app powered by Electron and Node

### ISSUE THREAD

**Issue by jingweno** [thechangelog/ping#280]
Huge fan of your show. Just wanna share https://hackermenu.io :). It's a Hacker News read companion. It's written in Electron and Node, and it's open source at https://github.com/jingweno/hacker-menu.

**Comment by jerodsanto** [comment]
Super cool stuff, @jingweno! As you noted on Twitter, we highlighted this in issue 71 of Weekly. :beers:
