### ISSUE TITLE
[Podcast Suggestion] Evan Czaplicki - designer, developer of ELM lang

### ISSUE THREAD

**Issue by netaisllc** [thechangelog/ping#281]
Yeah, so, why not get with the FRP bandwagon (that's _functional reactive programming_ for Adam) which is so much, all the rage. Think of Elm, as "Haskell for Humans" and if you've ever used **Prezi** you've probably experienced Evan's work.

Let's talk pure functions, immutability FTW, JS interop, and why no one is looking at this like they should...

SF-based, of course. :+1:

**Comment by adamstac** [comment]
Interesting. Ping @evancz...

**Comment by adamstac** [comment]
Links:

- http://evan.czaplicki.us/
- https://github.com/evancz
- http://elm-lang.org/guide/core-language

**Comment by netaisllc** [comment]
Also,
http://venturebeat.com/2013/07/26/why-i-designed-a-front-end-programming-language-from-scratch/
https://www.youtube.com/watch?v=oYk8CKH7OhE ("Let's be mainstream! User-focused design in Elm", CURRY ON conference, Prague, July 6-7, 2015)

**Comment by netaisllc** [comment]
Also,
http://bendyworks.com/elm-frontend-right-now/

### Summary from the blog post cited above

>Elm, even though it is new, even though it is different, offers a real and substantial alternative to MV*-style frameworks like Angular and Ember. Code in Elm is cleaner, more maintainable, and simpler than the alternatives. It improves upon JS by nearly eliminating runtime crashes, meaning no more "undefined is not a function."

>Instead of CSS and HTML, you get a composable, programmable layout language that really works. I sat in a presentation on Elm back at the 2012 Emerging Languages Camp. During his presentation, Evan Czaplicki, Elm's author, vertically centered a page element and the room cheered. The message I got was clear, "this is how weak our current tools of HTML and CSS are."

>The landscape of innovation on the frontend is wide open. The dominance of mutable, imperative, OO-style frameworks is not predestined. JavaScript is as much (or more) a functional language as anything else. We can use innovative techniques that we've learned in the time since the early 90's (JavaScript, Java, Ruby, Python, etc.) to build better stuff. Let's do it."

**Comment by netaisllc** [comment]
@rtfeldman can fill-in as EvanCz is buried.

![10-14-2015 4-19-48 pm](https://cloud.githubusercontent.com/assets/1242423/10500767/b523b006-728f-11e5-84c0-c968c26a0ce4.jpg)

**Comment by VadimBrodsky** [comment]
+1

**Comment by trizko** [comment]
:+1:

**Comment by rtfeldman** [comment]
If there's still interest in having me on, here's an example of the sort of Elm-related speaking I've done:

* [Ruby Rogues podcast - Elm](https://devchat.tv/ruby-rogues/212-rr-elm-with-richard-feldman-and-evan-czaplicki) with Richard Feldman and Evan Czaplicki
* [JS Jabber podcast - Elm](http://www.stitcher.com/podcast/ruby-rogues/javascript-jabber/e/175-jsj-elm-with-evan-czaplicki-and-richard-feldman-40348361) with Evan Czaplicki and Richard Feldman
* [Make the Back-End Team Jealous: Elm in Production](https://www.youtube.com/watch?v=FV0DXNB94NE) - talk at Strange Loop 2015

**Comment by trizko** [comment]
@rtfeldman @adamstac listened and watched all those and still want more lol

**Comment by jerodsanto** [comment]
@rtfeldman we'd love to have you on! We actually have an open slot to record tomorrow afternoon, if you can make that work. If not, we totally understand. Short notice.

Please email editors@changelog.com and we will discuss the particulars.

**Comment by rtfeldman** [comment]
@jerodsanto email sent!

**Comment by rafaelrinaldi** [comment]
:+1:

**Comment by jerodsanto** [comment]
This show is now live! 

https://changelog.com/191/

Thanks to all involved!
