### ISSUE TITLE
[Podcast Suggestion] Andreas Håkansson - creator and core contributor of Nancy 

### ISSUE THREAD

**Issue by Arashikage** [thechangelog/ping#282]
Hi, long time listener, first time writer :)

I think that [Nancy](http://nancyfx.org/) would be a great topic for your show. It's got a lot of traction lately in different places. 

[ThoughtWorks Technology Radar](https://www.thoughtworks.com/radar/languages-and-frameworks/nancy)

[tretton37 blog post](http://blog.tretton37.com/2015/09/17/we/)

The company tretton37's views on OSS is also something that could be brought to light but that might be a whole other story ;)

_Disclaimer:_ I'm working for tretton37

**Comment by jerodsanto** [comment]
@Arashikage thanks so much for pinging us! Nancy looks cool, but we're going to pass on featuring it on the show at this time. However, I just queued up [a tweet](https://twitter.com/changelog) in its direction and we'll get this in to this Saturday's issue of [Weekly](https://changelog.com/weekly). :beers:
