### ISSUE TITLE
[Podcast Suggestion] Matthew Holt, Caddy HTTP/2 Web Server

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#283]
@carlisia and I both agree that Matthew Holt (@mholt) would be a great guest on The Changelog.  He is a very young and talented software engineer who wrote a HTTP/2 Web Server in Go shortly after the HTTP/2 protocol spec was finished.

I talked to him via email and he is looking forward for an intro to @adamstac and @jerodsanto to see if a show can be produced around his project [Caddy](https://github.com/mholt/caddy).

**Comment by carlisia** [comment]
:+1:  I am soooo looking forward to this podcast!!! Not only I'm looking forward to learning more about Matt's work in general, but also about how Caddy was designed to be a modern web framework. That it was made in Go is totally icing on the cake!

**Comment by guilhermebr** [comment]
:+1:

**Comment by pedronasser** [comment]
:+1: Caddy is a promising intuitive and extensive alternative for Nginx.
Also @mholt is a very professional and dedicated software engineer.

**Comment by bketelsen** [comment]
+1

**Comment by mholt** [comment]
Wow, yeah, this would be fun. There's a lot of excitement about http2, and even though I haven't implemented it myself (Caddy uses an existing library by @bradfitz), there are some things web developers should understand about the transition to it. But there's a lot of interesting aspects to the project (e.g. Let's Encrypt) and its community, so it doesn't have to be all about http2.

**Comment by davecheney** [comment]
+1, i'd love to hear this podcast

(aside: what happened to all the b roll footage your team shot at Gophercon?)

**Comment by pzurek** [comment]
:+1:

**Comment by dvrkps** [comment]
+1

**Comment by haraldringvold** [comment]
:+1:

**Comment by jerodsanto** [comment]
I think the :+1:s have spoken. :smiley: 

(I love seeing this kind of support on ping.)

@mholt we'd love to have you on the show! We did a pretty good (imo) [episode on HTTP2 with Ilya Grigorik](https://changelog.com/161/) in June, but I think if we focus on you, Caddy, and the Let's Encrypt stuff it'd be all good.

Please email editors@changelog.com and we'll get it scheduled!

**Comment by mholt** [comment]
Sounds great, I'll do that. Thanks :smile:

**Comment by bketelsen** [comment]
\o/

**Comment by jerodsanto** [comment]
This show is now live! :tada: :dancers: :tada:

Thanks to everyone who helped make it happen. Y'all got multiple shout outs as a great community during the show. Here is the official show page for you to share with your network of friends:

https://changelog.com/179/

Or, you can simply retweet our announcement tweet:

https://twitter.com/changelog/status/660474048279875586

:beers: :metal:

**Comment by jdorfman** [comment]
Great show thanks for the shoutout =)

**Comment by jerodsanto** [comment]
:clap: all around!
