### ISSUE TITLE
What is new in Rails 5?

### ISSUE THREAD

**Issue by mariochavez** [thechangelog/ping#284]
Rails 5 is a greater version of Ruby On Rails, this implicate that Rails API and requirements can change to deprecate, add new and improve existing API but also to take advantage of importante changes in Ruby language as well.

http://blog.michelada.io/whats-new-in-rails-5

**Comment by benoittgt** [comment]
Are you sure about your `or` request ?

```ruby
Book.where(‘status == 1’).or(Post.where(’status == 3’))
# => SELECT * FROM books WHERE (status = 1) OR (status = 3)
```

**Comment by mariochavez** [comment]
@benoittgt thanks for catching this, it should be a single `=` not `==` and second model is incorrect. Fixed!

```sql
Book.where('status = 1').or(Book.where('status = 3'))
# => SELECT * FROM books WHERE (status = 1) OR (status = 3)
```

**Comment by adamstac** [comment]
I love it! Our issues being used for code review...

Thank y'all. Logging this to our upcoming issue of Changelog Weekly - https://changelog.com/weekly/

**Comment by mariochavez** [comment]
Great! thanks @adamstac

**Comment by jerodsanto** [comment]
This made it in to [Issue 73](http://email.changelog.com/t/t-D4E0966AA0002771) :sparkles:
