### ISSUE TITLE
RailsStuff gem

### ISSUE THREAD

**Issue by printercu** [thechangelog/ping#285]
Hi there!

I've released RailsStuff gem with some different useful modules for ruby and rails: https://github.com/printercu/rails_stuff
There is also small post about one of the features: https://medium.com/@maxmelentiev/resourcescontroller-inheritedresources-without-unnecessary-magic-a5da26671ca5

Can you please add it to news?

**Comment by jerodsanto** [comment]
@printercu we included this in [today's issue of Changelog Weekly](http://email.changelog.com/t/t-D4E0966AA0002771). :beers:

**Comment by printercu** [comment]
thanks! :+1:
