### ISSUE TITLE
TastyIgniter - open source restaurant ordering and reservation system.

### ISSUE THREAD

**Issue by sampoyigi** [thechangelog/ping#287]
http://tastyigniter.com

TastyIgniter is a free, open source restaurant ordering and management platform for developers and restaurants. TastyIgniter has kitchen management, order management, customer and staff management, store management, table reservations and internationalisation already built in. Free lifetime support and updates are provided.

You can easily install, select your template, add menus and you’re ready to start accepting orders. Modules are also packaged individually so you can customize easily. If you’re tired of expensive, proprietary software and complicated systems, then TastyIgniter might be a good fit.

**Comment by jerodsanto** [comment]
@sampoyigi hmm the page is 404ing at the moment. :frowning:

**Comment by sampoyigi** [comment]
I updated the URL to http from https

**Comment by jerodsanto** [comment]
@sampoyigi we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:

**Comment by sampoyigi** [comment]
Yayyy! Thank you!
