### ISSUE TITLE
New Screencast for Gophers

### ISSUE THREAD

**Issue by arschles** [thechangelog/ping#288]
I've been writing Go for about 2 years now in various capacities. Since the community has been so awesome to me (and still is) I decided to try and give back. So, I started a weekly podcast called "Go in 5 Minutes" where I try to present one short, self-contained pattern, best practice or library for 5 minutes each week.

The first screencast is on YouTube at https://youtu.be/mk4BCLimksY and the accompanying code & outlines are on Github at https://github.com/arschles/go-in-5-minutes.

**Comment by jerodsanto** [comment]
@arschles we included this in the Videos section of [today's Changelog Weekly](http://email.changelog.com/t/t-D4E0966AA0002771). :beers:

**Comment by arschles** [comment]
thanks @jerodsanto !

**Comment by arschles** [comment]
@jerodsanto here's a particularly useful screencast that explains [Gorilla Mux](http://www.gorillatoolkit.org/pkg/mux) : https://www.youtube.com/watch?v=6Pl5Xrrne2c. Can this make it into a newsletter?
