### ISSUE TITLE
Open Source Design is doing a survey for their logo

### ISSUE THREAD

**Issue by simonv3** [thechangelog/ping#289]
https://open-source-design-logo.herokuapp.com/manage

It'd be awesome to have that in the newsletter. We'd love to get as much of the open source community's opinion. 

The original issue and concepting is here: https://github.com/opensourcedesign/opensourcedesign.github.io/issues/18

**Comment by jerodsanto** [comment]
@simonv3 hmm, it appears that we missed the window to promote this. I was just going to add it to this week's newsletter. :frowning: 

 Sounds like you got some help anyhow! :beers:
