### ISSUE TITLE
City entry autocomplete widget with Geolocation API support by Teleport

### ISSUE THREAD

**Issue by joonathan** [thechangelog/ping#291]
We at Teleport have released cities autocomplete widget built on top of our own public API's (no API keys required).

https://github.com/teleport/autocomplete

Some of the features to highlight:
* Find city by city name or alternate name
* Find city by administrative division and/or country
* Initially populate the field using the browsers Geolocation API if available

There is also a working demo page available on our developer site — https://developers.teleport.org/api/autocomplete_widget/

**Comment by jerodsanto** [comment]
@joonathan we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
