### ISSUE TITLE
deppbot (for Ruby projects)

### ISSUE THREAD

**Issue by winston** [thechangelog/ping#292]
Hi!

We built a tool call [deppbot](https://www.deppbot.com/) which ensures that your Ruby applications are kept updated, always. 

Depending on the set schedule, deppbot will run `bundle update` on your Ruby applications periodically and send the result as a Pull Request to GitHub (an example https://github.com/ruby-bench/ruby-bench-web/pull/122).

deppbot is free for all public repos but requires a paid subscription for private repos.

We have also written a blog post to explain the rationale behind deppbot here https://github.com/jollygoodcode/jollygoodcode.github.io/issues/3

Thank you!

**Comment by jerodsanto** [comment]
@winston we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:

**Comment by winston** [comment]
Thank you @jerodsanto ! :heart:
