### ISSUE TITLE
Dasherize - Open-Source Dashboard for Project Health Status 

### ISSUE THREAD

**Issue by winston** [thechangelog/ping#293]
Dasherize was created as an alternative to Pivotal's ProjectMonitor and Shopify's Dashing that can display Continuous Integration status, and GitHub Pull Requests and Issues count out of the box.

https://github.com/jollygoodcode/dasherize

Service version available at http://www.dasherize.com

![screen shot 2015-10-06 at 5 24 06 pm](https://cloud.githubusercontent.com/assets/2112/10304826/1e3a9470-6c4f-11e5-8364-07d07017a5b5.png)

**Comment by jerodsanto** [comment]
@winston I think we'll pass on this one since we're including deppbot this week and we've covered a lot of projects similar to this. Keep up the good work, though! :beers:

**Comment by winston** [comment]
No worries @jerodsanto. Thank you once again! :smile:
