### ISSUE TITLE
Advanced Simulation Library - OpenCL-based multiphysics simulation software

### ISSUE THREAD

**Issue by AvtechScientific** [thechangelog/ping#294]
Hi,

I would like to bring our library to your attention:
https://github.com/AvtechScientific/ASL
http://asl.org.il

Check the performance in the benchmark section!

Thanks!

**Comment by jerodsanto** [comment]
@AvtechScientific we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:

**Comment by AvtechScientific** [comment]
Thanks!
