### ISSUE TITLE
Vorpal - Node's first framework for interactive CLIs.

### ISSUE THREAD

**Issue by dthree** [thechangelog/ping#295]
Hey there - love you guys :+1: 

A bit ago you were kind enough to feature [Vantage](https://github.com/dthree/vantage) on your weekly newsletter. 

I've since extracted out from and built off of all of the CLI functionality of Vantage to make a versatile framework for building immersive CLI applications in Node: [Vorpal](https://github.com/dthree/vantage).

I'm really excited about this as it's got a really wide field of application, and I'm hoping will enable a ton of Javascript developers to start building powerful CLIs that they just weren't possible before.

Vorpal blew up to no. 4 on Hacker News yesterday, so I thought it was a good time check if you guys were interested in bringing it up!

I'd love to talk about its and examples of its usage in a podcast even, but it looks like your podcast requests are super bloated, so I'm probably not gonna bother you there :)

**Comment by sindresorhus** [comment]
:+1:

**Comment by jerodsanto** [comment]
@dthree you're quite right that our podcast schedule is pretty full these days. However, Vorpal looks quite cool and we'll give it a prominent spot in tomorrow morning's issue of [Weekly](https://changelog.com/weekly/). :beers:

**Comment by dthree** [comment]
Hey thanks! :)
