### ISSUE TITLE
Jables. Write database schema in JSON. (for Laravel5)

### ISSUE THREAD

**Issue by omranjamal** [thechangelog/ping#296]
Hi! We've created a small library that integrate into the Laravel Framework (PHP). It lets you write your Database Schema in JSON files which it later parses to produce the desired database structure.

[http://hedronium.github.io/Jables/](http://hedronium.github.io/Jables/)

Hope this is relevant enough.
Thanks! :smile:

**Comment by jerodsanto** [comment]
@omranjamal relevant enough, indeed! We're including Jables in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:
