### ISSUE TITLE
Crowdwriting site: Collabowrite

### ISSUE THREAD

**Issue by freedmand** [thechangelog/ping#297]
[collabowrite.io](http://www.collabowrite.io/)

This November, let's write a book together. Collabowrite is a site to crowdsource book creation. Each day, users will be able to write pages and upvote submissions for that day. The highest voted page each day gets added into the book. By the end of the month, we'll have a short novel fueled by many creative people's talents.

### A collaborative writing platform

November is just the beginning. We plan to support multiple books being written at once with different epoch times for page submissions. In addition, users will be able to create their own books or topical communities in which content can be written.

### Open source

In collaborative fashion, the project is open source to truly involve the community at the root.

[https://github.com/freedmand/collabowrite](https://github.com/freedmand/collabowrite)

**Comment by jerodsanto** [comment]
@freedmand sounds like fun. We'll give this a shout out in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
