### ISSUE TITLE
Civilizer - Personal Knowledge Management Tool to efficiently manage your data/knowledge/idea

### ISSUE THREAD

**Issue by suewonjp** [thechangelog/ping#298]
Hi!

I recently released my first open source project - [Civilizer](https://github.com/suewonjp/civilizer/wiki).

It is a Personal Knowledge Management (PKM) tool.

Many people might not know yet what PKM is all about, but, you don't have to care.
Every activity that can efficiently enhance your knowledge/expertise/skill can be called PKM. 
(e.g., taking notes about something on your diary...)
You can see Civilizer  as a sophisticated note application or document manager for personal data.
So I think Civilizer will be useful for coders like us or other experts or researchers, writers, and any one who gets new knowledges every day and needs to manage them for their jobs and careers.

I'm heavily using it day to day to enhance my skills and expertise for my job.
I'm personally depending on the tool anyway so it will be updated and stable in a persistent manner.
(I hope many people use it and will give feature requests so it would not evolve in a biased way for only one person)

Civilizer is a web based app so it runs under web browsers.
and it can be run every desktop or laptop where Java Virtual Machine is installed.

You can download it at:
https://github.com/suewonjp/civilizer
https://sourceforge.net/projects/civilizer/?source=navbar

And documentations at:
https://github.com/suewonjp/civilizer/wiki

Civilizer blog for PKM topics:
https://sourceforge.net/p/civilizer/blog/?source=navbar

Thank you!

**Comment by jerodsanto** [comment]
@suewonjp interesting. We'll give this a shout in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
