### ISSUE TITLE
Visionaray

### ISSUE THREAD

**Issue by szellmann** [thechangelog/ping#299]
[Visionaray](https://github.com/szellmann/visionaray) is a ray tracing library that embraces C++-11 coding style and that aims at code reuse. _Kernels_ describe how a ray is traversed based on some data; _schedulers_ help to create rays efficiently and in parallel. This distinction between algorithm and initial ray setup allows the same kernels to be executed on CPUs, GPUs, FPGAs (wip) and on PC clusters. The kernel/scheduler concept is simply demonstrated with a few lines of code:

```C++
// Visionaray's main namespace.
using namespace visionaray;

// Define some convenience types.
typedef basic_ray<float>       ray_type;
typedef simple_sched<ray_type> sched_type;
typedef vector<4, float>       color_type;

// Scheduler instance, probably a class member
// in a real-world example.
sched_type sched;
sched_params<decl_type(render_target)> sparams
{
    camera,
    render_target // e.g. a pixel-buffer object for
                  // real-time ray tracing
};

// In this example, the kernel is passed to the
// scheduler as a lambda. It specifies the code
// path that a single ray or a ray packet executes.
sched.frame([=](ray_type r) -> color_type
{
    // traversal code in here
    // ...

    // the result will be written to the render target
    // at pixel position associated with the ray.
    return color_type(1.0, 1.0, 1.0, 1.0);
},
sparams);
```

Inside the kernel, the user can do basically anything. Additional [example programs](https://github.com/szellmann/visionaray/wiki/More-examples) demonstrate more "real-world" kernels written with Visionaray.

Visionaray comes with a wealth of highly optimized _intrinsic_ functions: state of the art split-BVH ray traversal structure, math library for efficient SIMD packet traversal, intrinsics for texture filtering with up to cubic interpolation, numerous types of physically based BRDFs, ...

Visionaray is MIT-licensed. Visionaray was originally developed at the University of Cologne to accomplish code reuse of several ray tracing-based algorithms that were independently implemented with CUDA and with SSE. We believe that Visionaray could be helpful for other programmers as well and would love it if you could include it in your newsletter.

**Comment by szellmann** [comment]
Some visuals and a video may also be found on Visionaray's [new Facebook Page](https://www.facebook.com/visionaray?ref=hl).

**Comment by jerodsanto** [comment]
@szellmann we're including Visionaray in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:

**Comment by szellmann** [comment]
Great to hear, thanks a lot!
