### ISSUE TITLE
[Podcast suggestion] Otto - Development and Deployment Made Easy

### ISSUE THREAD

**Issue by SebastianSzturo** [thechangelog/ping#300]
I would love to hear about Hashicorp's otto (the succesor to vagrant) in the podcast.

https://ottoproject.io/
https://github.com/hashicorp/otto
@mitchellh

**Comment by jerodsanto** [comment]
@SebastianSzturo oh boy, our [schedule](https://changelog.com/schedule) has a surprise for you :wink: 

![2015-10-20 at 8 33 am](https://cloud.githubusercontent.com/assets/8212/10608594/54819fcc-7705-11e5-843c-1e65035cd86a.png)

**Comment by SebastianSzturo** [comment]
Great! Can't wait :)

**Comment by jerodsanto** [comment]
@SebastianSzturo it's alive! [IT'S ALIVE!](https://changelog.com/180/)

**Comment by SebastianSzturo** [comment]
:heart:
