### ISSUE TITLE
HEYMon 3.7 Released, full source code available

### ISSUE THREAD

**Issue by dblxadmin** [thechangelog/ping#301]
Salad Fork Ranch Software just released HEYMon 3.7!

This release includes the final full integration of the HMSQL query language, and has a lot of bug fixes and performance improvements.
HEYMon is the only cross-platform Systems and Applications Monitoring solution that can be managed using simple SQL commands.

http://www.saladforkranchsoftware.com/HEYMon/hmsqlht.html

**Comment by jerodsanto** [comment]
@dblxadmin we're including HEYMon in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
