### ISSUE TITLE
asdf - extendable version manager

### ISSUE THREAD

**Issue by HashNuke** [thechangelog/ping#304]
Hello,
I wrote "asdf" to replace the versions managers I installed for every language.
<https://github.com/HashNuke/asdf>

* Support for each language comes as a plugin
* Extendable with [super-simple API](https://github.com/HashNuke/asdf/blob/master/docs/creating-plugins.md) to support more languages
* Can lock versions in projects with a `.tool-versions` file like [this](https://github.com/HashNuke/firebrick/blob/master/.tool-versions)

**Comment by jerodsanto** [comment]
@HashNuke we're including asdf  in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by HashNuke** [comment]
@jerodsanto Thank you Jerod ~!
