### ISSUE TITLE
Alchemist - Elixir Tooling Integration Into Emacs

### ISSUE THREAD

**Issue by tonini** [thechangelog/ping#305]
Hi,

I'm the creator of [Alchemist](https://github.com/tonini/alchemist.el) an Emacs package to integrate the great Elixir Tooling into Emacs.

Alchemist comes with a bunch of features, which are:

* Mix integration
* Compile & Execution of Elixir code
* Inline code evaluation
* Inline macro expanding
* Documentation lookup
* Definition lookup
* Powerful IEx integration
* Smart code completion
* Elixir project management
* [Phoenix](http://www.phoenixframework.org/) web framework support
* Integration with [company-mode](http://company-mode.github.io/)

Thanks

PS: I love your TheChangelog show. <3

**Comment by tejasbubane** [comment]
:+1:

**Comment by rrrene** [comment]
:+1:

**Comment by jerodsanto** [comment]
@tonini nice! I just buffered up a tweet in your direction. Expect that tomorrow sometime. Also, we'll link this up in Saturday's issue of [Weekly](https://changelog.com/weekly/). :beers:

**Comment by tonini** [comment]
@jerodsanto many thanks for the shout out! <3

**Comment by jerodsanto** [comment]
@tonini happy to. Hit us up in the future if you have more cool OSS :smile:
