### ISSUE TITLE
Aisel - Full-stack based on AngularJS, PHP(Symfony2) & MongoDB

### ISSUE THREAD

**Issue by ivanproskuryakov** [thechangelog/ping#306]
Hello Changelog,

Almost two years I'm working on my own Framework based on PHP and AngularJS.
For now Aisel contains best practices both for PHP and AgularJS, until this moment I didn't think about getting in touch with media resources and bloggers and didn't write about it, just was focused on coding. 
I have stable version that works, and I actually don't know what else to do. For me its done, now is time to introduce it. 
Can we post review of Aisel on changelog.com ?

btw, stars and forks on github shows that people are interested
https://github.com/ivanproskuryakov/Aisel

Thank you,
Ivan

About me:
LinkedIn: https://ru.linkedin.com/in/ivanproskuryakov

Technically I’m a software engineer specialising in information systems with extensive experience both in backend & frontend development with a large amount of experience in eCommerce.
Creator of http://aisel.co - CMS based on Symfony2 & AngularJS 
Founder at http://www.magazento.com - solutions for e-commerce based on Magento CMS

**Comment by jerodsanto** [comment]
@ivanproskuryakov two years is a long time! We're going to mention this in tomorrow morning's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
