### ISSUE TITLE
Writing websocket servers in Go

### ISSUE THREAD

**Issue by arschles** [thechangelog/ping#307]
I just published the 5th episode of Go In 5 Minutes, which shows how to write a chat server using [the Gorilla Websockets Library](http://www.gorillatoolkit.org/pkg/websocket).

The example code is on Github here: https://github.com/arschles/go-in-5-minutes/tree/master/episode4

The screencast is on YouTube here: https://www.youtube.com/watch?v=DJiOrGRsIKo

**Comment by jerodsanto** [comment]
@arschles we're happy to link up "Go in 5 Minutes" from time-to-time, but I think the frequency is a bit too high at the moment.

If you're interested in more persistent/permanent promotion, we do have [sponsorship options](https://changelog.com/sponsorship/). :smile: 

Keep up the good work! :beers:

**Comment by arschles** [comment]
Fair enough. Figured I'd keep pinging until this :)

Can I submit new episodes and you can decide if/when to link?
