### ISSUE TITLE
[Podcast suggestion] Ahmad Nassri, Kong

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#308]
I think it would be great to hear the story behind [Kong](https://getkong.org/), an open-source management layer for APIs.

cc: @ahmadnassri

**Comment by ahmadnassri** [comment]
thanks @jdorfman 

happy to chat any time :)

**Comment by jerodsanto** [comment]
@jdorfman sounds cool to us! @ahmadnassri please email editors@changelog.com and we'll iron out scheduling details. :beers:

**Comment by ahmadnassri** [comment]
done.

**Comment by jerodsanto** [comment]
Just recorded this show. :boom: 

:shipit: on Friday!

**Comment by jdorfman** [comment]
:+1:

**Comment by jerodsanto** [comment]
:tada: :confetti_ball: https://changelog.com/185/ :confetti_ball: :tada:

**Comment by jdorfman** [comment]
Such a good episode.  I was blown away to hear from @ahmadnassri that it was illegal to connect to the Internet in Syria when he was growing up.  Makes you put things in perspective.

Thanks for the shout out @jerodsanto.
