### ISSUE TITLE
speed-test - Test your internet connection speed from the command-line

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#309]
[![](https://github.com/sindresorhus/speed-test/raw/master/screenshot.gif)](https://github.com/sindresorhus/speed-test)

https://github.com/sindresorhus/speed-test

**Comment by jerodsanto** [comment]
@sindresorhus we already got you covered :smile: 

This was mentioned in [Weekly 66](http://email.changelog.com/t/t-941CBC07EAEFEB09) and I think we tweeted about it back then as well.

:metal:

**Comment by sindresorhus** [comment]
Oh, awesome. I didn't realize :)

**Comment by sindresorhus** [comment]
Looks like the archive is not indexed by Google: https://www.google.com/search?q=site%3Achangelog.com+speed-test

**Comment by jerodsanto** [comment]
Sadly, the newsletter archive is not hosted on changelog.com. It's auto-generated and hosted by Campaign Monitor. That's something that we'd like to change, for this and other reasons. But for now, it is what it is.
