### ISSUE TITLE
Laravel: The PHP Framework for Web Artisans

### ISSUE THREAD

**Issue by KLVTZ** [thechangelog/ping#31]
Hey everyone,

Wanted to pitch an idea of a future show. Laravel has been gaining some serious attention in the open-source community. Arguably, it has created a modern path for PHP to follow. If you can, be sure to check out [Laravel.com](http://laravel.com/) but, more importantly, consider the idea of having [Taylor Otwell](https://twitter.com/taylorotwell), [Dayle Rees](https://twitter.com/daylerees), or even [Jeffrey Way](https://twitter.com/jeffrey_way) on the show! 

Take Care!

**Comment by taylorotwell** [comment]
I'm down for whenever. :smile:

**Comment by KLVTZ** [comment]
@adamstac @beverlynelson @taylorotwell  super excited, can't wait to listen :D

**Comment by adamstac** [comment]
@taylorotwell email adam atchangelog dotcom. We’re thinking this Monday if possible.

**Comment by jerodsanto** [comment]
@KLVTZ we [published](http://thechangelog.com/142/) this show on Friday! :smile: 

Thanks for the recommendation. If you listen to the end you'll hear us give you a shout out for the idea. :beers:
