### ISSUE TITLE
[Podcast suggestion] Data streaming

### ISSUE THREAD

**Issue by carlisia** [thechangelog/ping#310]
Is there any interest in having someone talk about data streaming? I have a few choices of people and any would be an excellent guest to talk about the subject, architecture involved, network protocol used, gotchas, trade-offs, etc.

Anyone else interested?

:+1:

**Comment by sethetter** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by carlisia** [comment]
LOL I was just gonna suggest we close this! Let's do it!

**Comment by carlisia** [comment]
We need to find a good open source project and find someone related to that project to be a host on the show. @sethetter do you know of any? I started searching for that today and a quick search provided zero luck.

**Comment by bridgetkromhout** [comment]
> So, we need to find a good open source project and find someone related to that project to be a host on the show.

I enjoy both geeking out about logs & hosting podcasts, and have at least one other co-worker at Pivotal who also hosts multiple podcasts. And we have engineers working on Cloud Foundry who can speak more about logs. Let me know if I can help! Thanks.

**Comment by carlisia** [comment]
So how about bringing in @kicombs and @bridgetkromhout to talk about  :point_right: https://github.com/cloudfoundry/loggregator

**Comment by bridgetkromhout** [comment]
> So how about bringing in @kicombs and @bridgetkromhout to talk about  :point_right: https://github.com/cloudfoundry/loggregator

I approve this message!

**Comment by adamstac** [comment]
@bridgetkromhout @kicombs let's make it happen!

I don't see email addresses on your profiles, so would one of you mind emailing editors@changelog.com so we can coordinate scheduling?

🍻 @carlisia 👏🔥💯🎉

**Comment by carlisia** [comment]
Hm @bridgetkromhout @kicombs, is this happening??!!  :)

**Comment by bridgetkromhout** [comment]
I've taken this to email - thanks.

**Comment by jerodsanto** [comment]
Closing in favor of https://github.com/GoTimeFM/ping/issues/10
