### ISSUE TITLE
[Podcast suggestion] Kris Borchers, jQuery Foundation

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#311]
@kborchers is the Executive Director of the jQuery Foundation where he helps lead the mission to improve the open web, making it accessible for everyone, through the development and support of open source software and collaboration with the development community. He is also a member of the jQuery UI team.

I would love to hear a more in depth backstory about the jQuery & Dojo Foundation merger as I am sure many others do too.

**Comment by adamstac** [comment]
@jdorfman, another good recommendation!

@kborchers please email editors@changelog.com and we'll iron out scheduling details. :beers:

**Comment by jdorfman** [comment]
@adamstac what can I say? I'm on a roll. =p

**Comment by jerodsanto** [comment]
Not sure if this one will ever come to be, but we've spoken with Kris about scheduling so I'm going to close this issue. Thanks again @jdorfman, you da 👨
