### ISSUE TITLE
Mappersmith - isomorphic, dependency-free, rest client mapper for javascript

### ISSUE THREAD

**Issue by tulios** [thechangelog/ping#312]
I released mappersmith some time ago and it's been really useful for my team and me, so I hope it might be useful for others.

https://github.com/tulios/mappersmith

**Comment by jerodsanto** [comment]
@tulios we're including Mappersmith in our next issue of [Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by tulios** [comment]
:beers:
