### ISSUE TITLE
ScalaFunctional 0.4: Python library for data pipelines, LINQ, and Functional Programming

### ISSUE THREAD

**Issue by EntilZha** [thechangelog/ping#313]
I just released the [`0.4` version](https://github.com/EntilZha/ScalaFunctional/releases/tag/v0.4.1) of [ScalaFunctional](https://github.com/EntilZha/ScalaFunctional), a python library that makes working with data easy. It takes inspiration from Scala collections, Apache Spark RDDs, LINQ, and functional programming. The most common use case is data exploration and data science. Here is the simple example, but the project README contains many more:

```python
from functional import seq

seq(1, 2, 3, 4)\
    .map(lambda x: x * 2)\
    .filter(lambda x: x > 4)\
    .reduce(lambda x, y: x + y)
```

* PyPi: `pip install scalafunctional`
* Documentation: [scalafunctional.readthedocs.org](http://scalafunctional.readthedocs.org/en/v0.4.1/)
* Library is well tested with ~100 unit tests providing full coverage to all code paths (run on TravisCI)

**Comment by jerodsanto** [comment]
@EntilZha we're including ScalaFunctional in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by EntilZha** [comment]
Nice! Looking forward to seeing it.
