### ISSUE TITLE
[Podcast suggestion] Vue.js 1.0

### ISSUE THREAD

**Issue by yyx990803** [thechangelog/ping#314]
I'm the author of Vue.js and this is basically me asking to be a guest of the show :)

- Vue.js recently released 1.0 and received very positive feedback on HN: https://news.ycombinator.com/item?id=10455812

- It currently has 9.1k+ stars on GitHub: https://github.com/vuejs/vue and likely to break 10k by end of year;

- Here's a high-level overview of what it offers (and how it differs from Angular/React/Web Components): http://blog.evanyou.me/2015/10/25/vuejs-re-introduction/

- The Laravel community has been adopting Vue.js very fast since May 2015, due to its author Taylor Otwell and prominent community members singing praise of Vue. They also talked about it in the latest [laravel podcast](http://www.laravelpodcast.com/episodes/19454-episode-37-i-love-the-things-you-are-saying).

**Comment by Vorror** [comment]
+1

**Comment by jerodsanto** [comment]
@yyx990803 you make a compelling argument! Please email editors@changelog.com and we can talk details.

**Comment by stephenhowells** [comment]
I would love to hear a Changelog podcast on Vue! I was just coming to this repo to open an issue and suggest having Evan on to discuss Vue. It's so much more elegant than many other JS frameworks. Additionally, it's becoming beloved in the Laravel community as the front-end framework of choice.

**Comment by jerodsanto** [comment]
This episode is now live! :boom: :clap: 

https://changelog.com/184/
