### ISSUE TITLE
RabbitIO - Unified authentication for PlayerIO

### ISSUE THREAD

**Issue by Decagon** [thechangelog/ping#315]
RabbitIO is a C# library that automatically chooses the right authentication type based on the users' credentials to PlayerIO.

In the past developers had to code five different login dialogues (the user having to choose the right one) and add 60+ lines of code just to allow all users from PlayerIO to login to their app. Sometimes, developers would only support just a couple of logins, leaving many users unable to use their app.

With RabbitIO, you only need one login dialogue, and just one line of code to allow all users to login. It's that simple.

https://github.com/Decagon/Rabbit

**Comment by jerodsanto** [comment]
@Decagon we're linking to RabbitIO in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow! :beers:

**Comment by Decagon** [comment]
Thanks for linking to it! I'd love to link your podcast/writeup to Rabbit so that other people can find it, but I wasn't able to find the link. Do you know where I could find it @jerodsanto ?

**Comment by jerodsanto** [comment]
We included it in Changelog Weekly issue 82. Here is the archive page:

http://email.changelog.com/t/t-2BE0C2EFD2E2BD1F
