### ISSUE TITLE
What's new in Ceylon 1.2

### ISSUE THREAD

**Issue by chochos** [thechangelog/ping#316]
Ceylon is a modern, modular, statically typed programming language for the Java and JavaScript virtual machines. The language features a flexible and very readable syntax, a unique and uncommonly elegant static type system, a powerful module architecture, and excellent tooling.

We just released version 1.2 at the end of October, with many new features, along with the IDE (an eclipse plugin). Please check our announcement at the official site.

http://ceylon-lang.org/blog/2015/10/29/ceylon-1-2-0/

**Comment by jerodsanto** [comment]
@chochos we're linking to Ceylon in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by chochos** [comment]
Great! Thank you very much!
