### ISSUE TITLE
[Guest idea] Dan Abramov (Redux)

### ISSUE THREAD

**Issue by netaisllc** [thechangelog/ping#317]
Consider interviewing **Dan Abramov** (@dan_abramov),  project lead/mastermind of Redux (http://redux.js.org/, a predictable state container for JavaScript apps.)

> It helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test.  On top of that, it provides a great developer experience, such as live code editing combined with a time traveling debugger.

Basically, a better _Flux architecture_ than Flux itself.

The origin story: "Dan Abramov - Live React: Hot Reloading with Time Travel" 
https://www.youtube.com/watch?v=xsSnOQynTHs

He is very articulate, too. :)

**Comment by gaearon** [comment]
Thanks @netaisllc. Happy to chat with you folks.

**Comment by adamstac** [comment]
@gaearon You just got a mention on episode #182 which ships this Friday.

**Comment by jerodsanto** [comment]
@gaearon we'd absolutely love to have you on. Please email editors@changelog.com and we will schedule it!

@netaisllc :+1:

**Comment by jerodsanto** [comment]
This show is now live!

:tada: :confetti_ball: https://changelog.com/187 :confetti_ball: :tada: 

Thanks for the suggestion, @netaisllc! Adam gave you a shout to on the show. :facepunch:
