### ISSUE TITLE
Hookah smoke testing library build on top of PHPUnit

### ISSUE THREAD

**Issue by geshan** [thechangelog/ping#319]
Hookah is a small smoke testing command line library for any web application. As it is just a sanity check it checks if the given URL returns back the right response code, and body is not empty. 

https://github.com/younginnovations/hookah

**Comment by jerodsanto** [comment]
@geshan :+1: love the name :)

**Comment by jerodsanto** [comment]
@geshan we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by geshan** [comment]
Thanks
