### ISSUE TITLE
Changelog podcast has been featured

### ISSUE THREAD

**Issue by geshan** [thechangelog/ping#320]
Changelog podcast has been featured here : http://geshan.com.np/blog/2015/11/3-weeklies-every-software-engineer-slash-developer-should-subscribe-to/

Hope you can include it in the next weekly, thanks.

**Comment by jerodsanto** [comment]
@geshan thanks so much for featuring us! I think linking to this from Weekly would be a bit redundant, but keep up the good work and let us know when you have more articles worth featuring! :beers:
