### ISSUE TITLE
Introducing AKABeacon - a data binding framework for iOS

### ISSUE THREAD

**Issue by mutech** [thechangelog/ping#322]
# [AKA Beacon](https://github.com/mutech/aka-ios-beacon)

Beacon lets you work with Interface Builder the same way you do with XAML and Knockout:

You create your view hierarchies with Interface Builder the same way you do now (if you use IB), but instead of manually setting up the content of view or implementing delegates to hook up inputs and behavior to your view controllers and app logic, you can now assign binding expressions right in the inspector panel.

Beacon currently (pre-release) supports the most important view types, like UILabel, UITextField, UITextView, UISlider, UIStepper, et. al. It will cover all standard UI views and a couple of custom view provided by beacon. Beacon is designed for extensibility, so its perfectly possible to add bindings for your own reusable views.

Beacon is not intrusive. You can use it in addition you your current view controller logic and just bind some views and control others any way you like. However, if you use the Beacon infrastructure, it takes of all the ugly work of handling scroll views, strange edge cases and other unpleasant effects that usually eat up our weekends.

Check it out, it's a great framework with a notorious ADS. We could do with some feedback before we fix the API for the first version that's probably coming out at the end of the year.

**Comment by jerodsanto** [comment]
@mutech I just queued up a [tweet](https://twitter.com/changelog) in your direction. We're also including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:
