### ISSUE TITLE
KeeWeb - unofficial KeePass web app

### ISSUE THREAD

**Issue by antelle** [thechangelog/ping#323]
[KeeWeb](https://github.com/antelle/keeweb) is an open-source password manager capable to work with KeePass databases, written entirely in JavaScript. It's distributed as single HTML file which doesn't require any server or additional resources.
The app can run either in browser, or as a desktop app. Desktop apps created with GitHub electron for Mac OS X, Windows and Linux.
If offers full support of KeePass format, Dropbox sync and fast key encryption using WebCrypto with speed close to native apps.
KeePass files are loaded and saved with [kdbxweb](https://github.com/antelle/kdbxweb), javascript library for reading kdbx files in browser or node.js.
App features on one page: https://github.com/antelle/keeweb/blob/master/features.md
[App Screenshot](https://camo.githubusercontent.com/0a70160ae9244fd517d1e54fe099f4ffbcdc60c8/68747470733a2f2f686162726173746f726167652e6f72672f66696c65732f6266622f3531652f6438642f62666235316564386431393834376438616662383237633466626666376464352e706e67)
Web app: https://antelle.github.io/keeweb/
GitHub project: https://github.com/antelle/keeweb

**Comment by jerodsanto** [comment]
@antelle looks rad. I just queued up a tweet your way. We're also including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:
