### ISSUE TITLE
Open-source app for organizing and automatically retrieving information about your Digital Movie Collection - 

### ISSUE THREAD

**Issue by lacymorrow** [thechangelog/ping#324]
Hi Changelog!
I've just released a new NodeJS or OSX desktop application for organizing movies on your local hard drive called Cinematic. 

Cinematic scans the movie folder on your computer and downloads every bit of information available about each film, organizing it into an easy-to-navigate interface. It will even parse torrent-style `Movies.That.Look.Like.This.2015.HDRip.XviD.XXX-XXX.AVI`.

Plot, ratings, IMDB info, movie poster and art, trailers, and much more information is collected to make it easy to filter through and find something to watch. Filter movies by genre, and sort by popularity, release date, runtime, or randomly.

It is a Meteor app built on NodeJS and packaged with Electron using Electrify. Cinematic works on any machine that can run Node. Currently it is being distributed only as an OSX app, however Windows and Linux versions will be available shortly.

Check it out at [lacymorrow/cinematic](https://github.com/lacymorrow/cinematic).

It was developed as an exercise to learn Meteor, and completed in 10 days. It is completely open-source and free. I created it because my personal digital movie collection has become very large and unweildy, and choosing a movie became a time-consuming task involving much searching on Google and IMDB.
Cinematic has made choosing a movie a breeze.

Thanks for taking a look!

**Comment by jerodsanto** [comment]
@lacymorrow cool stuff! We're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by lacymorrow** [comment]
Solid, thanks @jerodsanto

**Comment by lacymorrow** [comment]
BTW I released Linux binaries as well, found at https://github.com/lacymorrow/cinematic/releases
