### ISSUE TITLE
[Shameless Plug!] A handy tool for opening files from command output

### ISSUE THREAD

**Issue by ciaran** [thechangelog/ping#326]
I recently pushed this up and I’m finding it incredibly helpful in personal use: https://github.com/ciaran/pls

Simply add 'pls' in front of your compiler/linter/etc. command, and when the command completes you can choose a file/line number from its output to open in your editor.

The idea was prompted when I first saw Yank, which came to me via the changelog :)

**Comment by jerodsanto** [comment]
@ciaran shot you a [tweet](https://twitter.com/changelog/status/668989620156108800) using dat gif and will also include this in Saturday's issue of [Weekly](https://changelog.com/weekly). :beers:
