### ISSUE TITLE
Document store with transactions on top of any database

### ISSUE THREAD

**Issue by mvila** [thechangelog/ping#327]
I have been working on the following project for several months and today I think it is mature enough to be unveiled to the world! :)

https://github.com/object-layer/document-store

Basically, it is a Document Store like MongoDB but with two important benefits: it supports ACID transactions and it is designed to work on top of any database or key-value store (supporting transactions).

It is written in JavaScript and composed of a dozen of modules.

**Comment by jerodsanto** [comment]
@mvila interesting...

We're going to link this up in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:

**Comment by mvila** [comment]
@jerodsanto Thank you! :)
