### ISSUE TITLE
vimrcfu - Share your best vimrc snippets

### ISSUE THREAD

**Issue by florianbeer** [thechangelog/ping#328]
Hi, I'd like to tell you about one of my projects that might be of interest for your readers: http://vimrcfu.com

This site gathers useful snippets of configuration for the popular Vim text editor. There is already quite a bit of interesting data on it but of course it will get more useful, the more people are using (and contributing to) it.

The webapp is written from scratch in Laravel and open sourced on my GitHub page: https://github.com/florianbeer/vimrcfu
Everyone is welcome to submit pull requests to add to its functionality and wipe out bugs.

Thanks for your consideration to add this to your newsletter.
- Flo

**Comment by jerodsanto** [comment]
@florianbeer very cool! We're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by florianbeer** [comment]
Awesome! Thank you very much :+1:
