### ISSUE TITLE
Testing async ActionMailer jobs with ActiveJob in Minitest

### ISSUE THREAD

**Issue by manuelmeurer** [thechangelog/ping#329]
Hi there,

I just published a post on testing async mail sending via ActiveJob with Minitest:
https://www.krautcomputing.com/blog/2015/11/22/testing-async-actionmailer-jobs-with-activejob-in-minitest/

Cheers,
Manuel

**Comment by jerodsanto** [comment]
@manuelmeurer this is just a _tad_ too specific/focused to be of general interest to our audience. We're gonna pass this time, but please do ping us again in the future! :beers:

**Comment by manuelmeurer** [comment]
Ok, will do! :smile_cat:
