### ISSUE TITLE
Hi please check out my new (pretentious) gem 

### ISSUE THREAD

**Issue by jedld** [thechangelog/ping#330]
Characterization testing for Ruby

https://github.com/jedld/pretentious

Comments and opinions are most welcome.

**Comment by jerodsanto** [comment]
@jedld we're including Pretentious in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by jedld** [comment]
Great! Thanks!
