### ISSUE TITLE
Service Worker Reading List Suggestions

### ISSUE THREAD

**Issue by brandonrozek** [thechangelog/ping#333]
Hello,

Here are a couple more service worker articles that I recommend.

Nicolas Bevacqua’s [“Making a Simple Site Work Offline with ServiceWorker”](https://ponyfoo.com/articles/serviceworker-revolution)

The Guardian's ["Building an offline page for theguardian.com"](https://www.theguardian.com/info/developer-blog/2015/nov/04/building-an-offline-page-for-theguardiancom)

I also have written a response to Jeremy Keith's cache-limiting article.

Brandon Rozek's ["Limiting the Cache in Service Workers Revisited"](https://brandonrozek.com/2015/11/limiting-cache-service-workers-revisited/)

Have a nice day!
Brandon Rozek

**Comment by adamstac** [comment]
Thanks for getting in touch and sharing @brandonrozek. We're linking up your post in [the next issue of Changelog Weekly](https://changelog.com/weekly/) and adding the others you mentioned to the post.

:beers: :100:
