### ISSUE TITLE
SafeFinder

### ISSUE THREAD

**Issue by st0012** [thechangelog/ping#334]
Hi, I want to share a gem I wrote, it's called [SafeFinder](https://github.com/st0012/SafeFinder), which is a Ruby gem that integrates `Null Object` pattern with `ActiveRecord`.
What it does is that instead of getting a `nil`, you will get a null object when you use `find_by` methods and finds nothing (for example, a `NullPost` instance if you're querying a `Post`). And you can also define that `NullObject`'s behavior using simple DSL. The goal is to let you avoid checking `nil` but check the object type in your conditions.

**Comment by jerodsanto** [comment]
@st0012 nice! I'm a big fan of the null object pattern. We're including SafeFinder in our next issue of [Changelog Weekly](https://changelog.com/weekly/). :shipit: tomorrow! :beers:

**Comment by st0012** [comment]
@jerodsanto thanks!
