### ISSUE TITLE
A hybrid(Ionic) mobile app that talks to a RESTful backend: full solution code sample

### ISSUE THREAD

**Issue by cptdanko** [thechangelog/ping#335]
When I started building a hybrid mobile app using the [Ionic] framework that communicates with a RESTful backend, I realised that it was big problem composed of a number of independent sub-problems. While I managed to find a solution to all those subproblems, I wished that I could see some sample code somewhere which showed me the overall solution(Big picture) i.e. sample code for both the RESTful backend and app front-end which demonstrates how it all works together. [IonicAppWithRestBackend] aims to do exactly that, it provides sample code for what a RESTful backend looks like and what the code for the Ionic app that communicates with it looks like. The README for the repo also provides links to 2 blog posts that explain the solution and provide instructions on how to run both the backend and the app front-end and how to test it locally.

[Ionic]: http://ionicframework.com/
[IonicAppWithRestBackend]: https://github.com/cptdanko/IonicAppWithRestBackend

**Comment by jerodsanto** [comment]
@cptdanko thanks for sharing! We'll this up in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
