### ISSUE TITLE
Comodojo extender 1.0

### ISSUE THREAD

**Issue by marcogiovinazzi** [thechangelog/ping#336]
Comodojo extender is a daemonizable, database driven, multiprocess, (pseudo) cron tasks scheduler written in PHP.

It is designed to work out of the box under most common *nix systems and could be easily installed using composer.

Main links:

- [project homepage](https://extender.comodojo.org)
- [GitHub repo](https://github.com/comodojo/extender.framework)
- [documentation](https://docs.comodojo.org/projects/extenderframework/en/latest/)
- [apidocs](https://api.comodojo.org/extender/)

Thanks for your consideration!

**Comment by jerodsanto** [comment]
@marcogiovinazzi cool stuff. We're including Comodojo extender  in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:

**Comment by marcogiovinazzi** [comment]
Thank you!!!
