### ISSUE TITLE
deepstream.io

### ISSUE THREAD

**Issue by WolframHempel** [thechangelog/ping#337]
Hi,

I'd love to share deepstream.io, an open-source server for realtime webapps that provides data-sync, pub-sub, WebRTC and other features.

Please find it here http://deepstream.io/

**Comment by jerodsanto** [comment]
@WolframHempel we just queued up a tweet in your direction and we're including deepstream.io in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by WolframHempel** [comment]
Thanks, looking forward to it
