### ISSUE TITLE
Go 102 Workshop Material

### ISSUE THREAD

**Issue by timblair** [thechangelog/ping#338]
A couple of weeks ago I ran an after-work introduction-to-Go workshop for some of my colleagues.  After getting feedback on the material I created from Bill Kennedy (trainer at Ardan Labs + GoBridge, author of [Go in Action](https://www.manning.com/books/go-in-action)) which included the phrase "I was trying to explain how difficult a deck like this is to develop ... you honestly nailed it" (which _totally_ made my day) I thought I'd send it your way in case it's something you feel is worth sharing.

The majority of the material is in the [GitHub repo](https://github.com/timblair/go-102) (under a CC BY-SA licence), and covers the following topics:

* an introduction to the basics (types, variable declaration, functions and custom types);
* OO-style development (methods, interfaces, embedding and composition); and
* concurrency (goroutines and channels).

Sections have detailed content (descriptions, examples, code walkthroughs etc) plus an exercise at the end of each (with example solutions).  All the exercises have templates on the Go Playground so it doesn't even need a local Go install to work through.

It's (hopefully) a nice resource for an individual to get going with Go, but combined with the [slide deck](https://speakerdeck.com/timblair/go-102-a-workshop) means that anyone who knows the basics should be able to run a similar workshop of their own.

**Comment by carlisia** [comment]
:+1:

**Comment by jerodsanto** [comment]
@timblair awesome stuff. If Bill Kennedy said good things about it, it _has to be_ good. :smile:. We're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:

(Hopefully in the future this kind of stuff will be covered by our [Go Time](http://gotime.fm) team :rocket: )
