### ISSUE TITLE
Elixir v1.2 and Ecto v1.1

### ISSUE THREAD

**Issue by georgeguimaraes** [thechangelog/ping#339]
Can I suggest reinviting @josevalim to talk about the upcoming release of both [Elixir](https://github.com/elixir-lang/elixir) and [Ecto](https://github.com/elixir-lang/ecto).

Disclosure: I'm José's co-worker at Plataformatec and a fan of the show! :)

**Comment by jerodsanto** [comment]
@georgeguimaraes we would :heart: :heart: :heart: to have José on the show to talk about Elixir! Last time around we couldn't get a hold of him to get him on.

You're an insider, can you help us hook with him?! :pray:

**Comment by josevalim** [comment]
Let's do this!

**Comment by jerodsanto** [comment]
@josevalim yes! Please email editors@changelog.com (or provide us your email address) and we'll get it scheduled!

Thanks, @georgeguimaraes!

**Comment by georgeguimaraes** [comment]
You're welcome!

**Comment by adamstac** [comment]
Stoked! :tada:

**Comment by jerodsanto** [comment]
It's alive! IT'S ALIVE!!

https://changelog.com/194

@georgeguimaraes you'll be happy to hear we gave you a shout out on the show, but I had to let @josevalim pronounce your last name for me. :grin:

**Comment by georgeguimaraes** [comment]
Hahaha tks for trying! :smile:
great episode!
