### ISSUE TITLE
Italy on Rails

### ISSUE THREAD

**Issue by olistik** [thechangelog/ping#340]
6 people will travel across Italy and while working remotely on their own projects and on an open source project as well.
Submissions are open for both candidates and open source projects.
This project aims to build a team as diverse as possible.

http://www.italyonrails.com/

**Comment by jerodsanto** [comment]
@olistik we'll link to this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:
