### ISSUE TITLE
[Podcast Suggestion] Snowdrift.coop and FLOSS funding

### ISSUE THREAD

**Issue by renato-zannon** [thechangelog/ping#342]
Hi!

I think it could be interesting to have the people behind [Snowdrift.coop](https://snowdrift.coop/p/snowdrift/w/en/intro) on the podcast to discuss approaches to free software (and culture) funding. The snowdrift platform has a novel take on the topic, and certainly have thought long and hard about the alternatives.

**Comment by jerodsanto** [comment]
@renato-zannon this is pretty interesting. Are you associated with the project or just a casual observer?

**Comment by renato-zannon** [comment]
@jerodsanto Just a casual (interested) observer! Maybe @wolftune would be interested in chiming in :)

**Comment by wolftune** [comment]
Hi there, not heard of thechangelog before, but I've been a guest on several podcasts (more around free-culture music stuff typically) and would be happy to participate in others that get into the issues around funding of FLO works and Snowdrift.coop's vision etc.

**Comment by jerodsanto** [comment]
@renato-zannon @wolftune we just released an episode about OSS funding. Please give it a listen and let us know what you think!

https://changelog.com/193/

I think this will be the only show we do on the topic for awhile, but we appreciate the suggestion and please keep us in the loop as Snowdrift makes moves. :beers:

**Comment by wolftune** [comment]
@jerodsanto thanks for the note. We indeed have a lot of work to do to get Snowdrift.coop fully going. I'll check out the podcast. I appreciate some Nadia's research. I do think she's mostly bringing to attention in a somewhat organized way things that many of us have known all along. The research on Snowdrift.coop already covers much of this, and I hope that people who care about this issue will join us in working to do something about all this. Please stay in touch!
