### ISSUE TITLE
[open source] - Open Data Sample project 

### ISSUE THREAD

**Issue by niklongstone** [thechangelog/ping#343]
Hi, 
I would like to share this repo mainly useful for test and language independent. 
Below the project description:

The Open Data Sample project wants to provide different sample data in an organized way.
You can find lists of names, surnames, cities, jobs and other useful data in many languages.
The project follows some specification standards to assure the overall quality. 
Contributions are very welcome.

https://github.com/niklongstone/open-data-sample

**Comment by jerodsanto** [comment]
@niklongstone we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:

**Comment by niklongstone** [comment]
thanks a lot  :smiley:

**Comment by niklongstone** [comment]
Hi, I didn't see the project on the Issue #89  (Saturday the 23th).
Will be on the next one? @jerodsanto

**Comment by jerodsanto** [comment]
@niklongstone bah! I put it in there, but forgot to copy/paste the link so the issue generator skipped that one. Sorry about that. It'll be in this week's for sure!
