### ISSUE TITLE
http://thechangelog.com is down

### ISSUE THREAD

**Issue by jimothyGator** [thechangelog/ping#344]
Your website is not responding at http://thechangelog.com. https://changelog.com is up, but not the old domain name.

**Comment by jerodsanto** [comment]
@adamstac maybe that old VPS was doing the thechangelog.com => changelog.com redirect and now it's broken?

**Comment by jimothyGator** [comment]
Looks like this has been resolved.

**Comment by adamstac** [comment]
Thanks for reporting this @jimothyGator I fixed it except for https which would require renewed certs. Silly you can redirect SSL to SSL without the SSL. We have a valid SSL cert for changelog.com, but not thechangelog.com becuase why would we renew it?

@jerodsanto do you have any thoughts on that issue?

**Comment by jerodsanto** [comment]
Yeah, I'm pretty sure we'd need a cert to do that. Might be a good opportunity to give [LE](https://letsencrypt.org) a spin. 

It's also worth noting that we'd need to use SNI, which would exclude anybody running Windows XP. But that's probably a minuscule amount of our audience (could confirm/deny that by looking at GA).
