### ISSUE TITLE
[open source] - ImageTracer: Public Domain raster image to SVG library in JavaScript or Java

### ISSUE THREAD

**Issue by jankovicsandras** [thechangelog/ping#345]
Hi,

You might be interested in ImageTracer: a simple image tracing and vectorizing library, which can convert from raster formats to SVG.

There are three versions:
imagetracer.js can run from the browser: https://github.com/jankovicsandras/imagetracerjs
ImageTracer.java can run as a desktop Java program or can be included in Java projects: https://github.com/jankovicsandras/imagetracerjava
ImageTracerAndroid.java can be included in Android projects: https://github.com/jankovicsandras/imagetracerandroid

All of them are Unlicensed (Public Domain), so 100% free to use.

**Comment by jerodsanto** [comment]
@jankovicsandras we're including ImageTracer in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:
