### ISSUE TITLE
A PHP library to standardize access to job board APIs (13 job boards are already available)

### ISSUE THREAD

**Issue by karllhughes** [thechangelog/ping#346]
While there are tons of job boards that will give you access to their data, every one of them returns that data in its own special way, making it hard to compare, store, or read data from lots of job boards. We figured, "Why not give devs one simple set of clients to access job board data?"

We have already added support for 13 job boards, and we have documentation and demos for each of the at the documentation site: http://code.jobbrander.com/

**Comment by jerodsanto** [comment]
@karllhughes I feel like it'd be even more powerful as a unified HTTP-based API than as a PHP library, but cool nonetheless. We'll link it up  in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:
