### ISSUE TITLE
[Podcast Suggestion] NodeOS

### ISSUE THREAD

**Issue by junland** [thechangelog/ping#347]
Would like to see if TCL could do a show talking about [NodeOS] (https://github.com/NodeOS/NodeOS), looks like a pretty interesting project. Would love to hear from the maintainers. It seems that it's mainly maintained by 3 [people] (https://github.com/NodeOS).

Thanks! :)

**Comment by adamstac** [comment]
Thanks @junland :clap: 

@piranna @groundwater @juliangruber y'all interested?

**Comment by junland** [comment]
No prob @adamstac, just helping out the community!

**Comment by piranna** [comment]
Hi guys :-) I would be glad to talk about NodeOS someday, but not also I don't have too much time at this moment but also I need to practice a little bit my speaking but most important my listening (I'm a native spanish speaker :-P ). Don't know how this would be a problem, but we could try :-) What were you thinking I could talk about? :-)

**Comment by jerodsanto** [comment]
@piranna we've had issues in the past with non-native English speakers, especially when they have a hard time understanding our questions. Keep up the great work, but I think we're going to pass on this show for now. Give us a holler when you've gotten your confidence up! :beers:
