### ISSUE TITLE
[Podcast Sugestion] Unikernels

### ISSUE THREAD

**Issue by chrismatheson** [thechangelog/ping#348]
I've been reading and researching quite a bit into this subject but haven't made the jump yet, I think it could make for an interesting discussion as the idea seems to challenge a lot of the status quo around application stacks and deployment etc 

Major projects that I know of are mirageOS and Rumprun Unikernel

**Comment by renato-zannon** [comment]
:+1: 
[Runtime.js](http://runtimejs.org/) is another example

**Comment by jerodsanto** [comment]
@chrismatheson sorry we slept on this one too long. I feel like unikernels haven't taken off and there's not much interest from me on the subject. We're going to pass on this one, and sorry again for not answering sooner!

Please ping us again in the future with other ideas you have. 💚
