### ISSUE TITLE
[open-source] match-when - Pattern Matching for Modern JavaScript

### ISSUE THREAD

**Issue by FGRibreau** [thechangelog/ping#349]
[match-when](https://github.com/FGRibreau/match-when), a clear, succinct and safe syntax for Pattern Matching using modern JavaScript.

```js
[2, 4, 1, 2].map(match({
  [when(1)]: "one",
  [when(2)]: "two",
  [when()]: "many"
}));

// [ 'two', 'many', 'one', 'two' ]
```

```js
function fact(n){
  return match({
    [when(0)]: 1,
    [when()]: (n) => n * fact(n-1)
  })(n);
}

fact(10); // 3628800
```

**Comment by jerodsanto** [comment]
@FGRibreau I've been loving pattern matching in Elixir and can see how this could be super useful in JS. I just queued you up a tweet and we're including match-when in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by FGRibreau** [comment]
@jerodsanto perfect, thanks!
