### ISSUE TITLE
Nito: Minimal component library for jQuery, inspired by React and Riot

### ISSUE THREAD

**Issue by morris** [thechangelog/ping#350]
https://github.com/morris/nito

- Create reusable components with jQuery or Zepto
- Promotes one-way data flow
- One simple factory, a few functions, <500 lines
- Supports isomorphic/universal apps

**Comment by jerodsanto** [comment]
@morris neato. :wink: 

I just queued up a tweet your way. We'll also include this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s on Saturday morning. :beers:

**Comment by morris** [comment]
Thanks and a happy new year :beers:!
