### ISSUE TITLE
Supercollider

### ISSUE THREAD

**Issue by geoffroymontel** [thechangelog/ping#351]
Dear Jerod and Adam,

I am a big fan of your show and I have a suggestion.

You may know [Supercollider](http://supercollider.github.io/), it's a language for realtime audio and comprises of a client and a server. It was created in _1996_ by James McCartney. The client language, SCLang, is very neat, very expressive, it combines elements of OOP programming and functional programming. It reminds me a bit of Ruby !

Example :

``` supercollider
[1, 2, 5, 10, -3].collect { |elem, idx| elem * idx };
```

It runs on Windows, Mac and Linux. Due to the client/server architecture, there are also alternative clients such as [Overtone](http://overtone.github.io/), based on Clojure.

It used to be closed-source, but was opensourced around 2001 (I don't know the exact date).
Version 3.7 is in beta right now and should be out very soon.

Plenty of things to discuss I guess !

To contact the mainteners, there's a [developer mailing list](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SuperCollider-Developers-New-Use-this-f2681767.html) and a [Github repo](https://github.com/supercollider/supercollider). 

Sorry for my English !

All the best

Geoffroy

**Comment by jerodsanto** [comment]
@geoffroymontel thanks for your kind words and for pointing us to SuperCollider. This had never even crossed my radar. It appears to have had a long and storied history (which I'm a sucker for)!

We'll consider doing a show on the subject, but I think we'd set a constraint that the interviewee must be James McCartney himself. Do you know if he's still actively involved with the software? How would we reach him?

Thanks again! 🍻

**Comment by geoffroymontel** [comment]
Dear Jerod

Glad you're interested in that wonderful piece of OSS !
James McCartney is on Facebook and very approchable I guess.
You can see him reading the new book about Supercollider on the Supercollider user groups
https://www.facebook.com/groups/supercollider
He's lurking the Supercollider users mailing list too
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SuperCollider-Users-New-Use-this-f2676391.html

Thanks again for your great show, I'm learning every week thanks to you both

Geoffroy

**Comment by jerodsanto** [comment]
Hmm, I was never able to pull this show together. Sorry about that, Geoffroy. 💚
