### ISSUE TITLE
do-automatinator

### ISSUE THREAD

**Issue by bessbd** [thechangelog/ping#353]
I have written a little tool to quickly "archive" and "restore" Digitalocean droplets.
It's available at https://github.com/bessbd/do-automatinator. And a quick draft for a post at http://bessbd.github.io/butprofessor/0002-do-automatinator.html.

Thought it might save a few minutes or dollars for others, too.

**Comment by jerodsanto** [comment]
@bessbd good stuff. You know we're big DO fans here at the Changelog. we're including your Automatinator in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:
