### ISSUE TITLE
vagrant-centos

### ISSUE THREAD

**Issue by astrostl** [thechangelog/ping#354]
Howdy, and thanks as always for the newsletter!

https://github.com/astrostl/vagrant-centos is a tool for creating trusted CentOS 6 or 7 base boxes for Vagrant + VirtualBox. It creates a VM, installs CentOS to Vagrant standards using a Ruby-hosted Kickstart automated installation script, and packages it up as a Vagrant box for re-use.

I find customization a breeze, and it teaches some VirtualBox/Vagrant/Kickstart along the way.

**Comment by jerodsanto** [comment]
@astrostl we're including vagrant-cantos in our next issue of [Changelog Weekly](https://changelog.com/weekly/). :shipit: tomorrow. :beers:
