### ISSUE TITLE
Searchkit

### ISSUE THREAD

**Issue by joemcelroy** [thechangelog/ping#355]
Hey guys!

Im one of the authors to searchkit.co. Searchkit is a suite of UI components built in react. The aim is rapidly create beautiful search applications using declarative components, and without being an ElasticSearch expert. Its really quick to both the developer getting up and running and quick for the user to search. 

Its written in Typescript.
http://github.com/searchkit/searchkit
http://searchkit.co
http://demo.searchkit.co

Hope you guys like this project.

Thanks!
Joe

**Comment by willchen90** [comment]
+1 I've worked with the two primary authors of searchkit (on another project) and they are fantastic software engineers with deep expertise on web apps.

**Comment by joemcelroy** [comment]
thanks @willchen90 for the kind words :)

**Comment by jerodsanto** [comment]
@joemcelroy good stuff! we're including Searchkit  in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow. :beers:
