### ISSUE TITLE
Cuv'ner

### ISSUE THREAD

**Issue by meejah** [thechangelog/ping#356]
I released a few experiments in visualizing test-coverage (in Python) yesterday: https://meejah.ca/projects/cuvner

There are some actually-useful console tools (e.g. tie into "less" so you get source-files coloured by coverage), and some graphical and SVG visualizations -- where those lie between "eye-candy" and "actually-useful" I'll leave up to users ;)

A few screenshots and a asciinema demo are at the above site.

Thanks! :)

**Comment by jerodsanto** [comment]
@meejah we're including Cuv'ner in our next issue of [Changelog Weekly](https://changelog.com/weekly/). We :shipit: tomorrow  :beers:

**Comment by meejah** [comment]
Cool, thanks :)
