### ISSUE TITLE
pstore_pp pretty-prints the contents of a PStore file as JSON

### ISSUE THREAD

**Issue by nerab** [thechangelog/ping#357]
Given a PStore file database.pstore with a root ‘foo’ that has a value ‘bar’, and another root ‘some’ with the value ‘thing’, calling pstore_pp on it would yield the following result:

    $ pstore_pp database.pstore {"foo":"bar","some":"thing"}

This tool was partially inspired by json_pp.

https://github.com/nerab/pstore_pp

**Comment by jerodsanto** [comment]
@nerab we're including pstore_pp in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! 

We :ship: it tomorrow morning. :beers:
