### ISSUE TITLE
conn-check

### ISSUE THREAD

**Issue by 1stvamp** [thechangelog/ping#358]
[conn-check](http://conn-check.org/) is a lightweight tool for monitoring connectivity between inter-dependent services, e.g. can your app talk to postgres or statsd, and has out of the box integration with Nagios and Juju, as well as the ability to generate firewall rules from the YAML describing your services.

**Comment by jerodsanto** [comment]
@1stvamp we're including conn-check in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:

**Comment by 1stvamp** [comment]
Awesome, thanks. :cake:
