### ISSUE TITLE
Scenic: Versioned Database Views for Rails

### ISSUE THREAD

**Issue by derekprior** [thechangelog/ping#360]
@calebthompson and I just publicly announced Scenic (now at version 1.1.0), which adds database view support to Rails in a manner that allows for simple versioning as your views evolve.

Caleb and I were familiar with other solutions that added `create_view` and `drop_view` migration statements, but wanted something more that helped developers manage views as they change. You don't completely recreate your database table to in a migration to add a column, so why should you do that with your views?

Beyond versioning, we're really proud to offer complete support for materialized views. Our materialized view support includes automatically maintaining applicable indexes between view updates, which was tricky to work out and we hadn't seen elsewhere.

We're hoping that having a really nice solution for database view support will help Rails developers see their usefulness.

* [Scenic](https://github.com/thoughtbot/scenic)
* [Public Announcements](https://robots.thoughtbot.com/announcing-scenic--versioned-database-views-for-rails)

**Comment by jerodsanto** [comment]
@derekprior good stuff! I've heard you talk about Scenic a bit on The Bike Shed (great show, btw!) and had planned on sharing it.

I just queued up a tweet your way and we will also link it up in this Saturday's issue of [Changelog Weekly](https://changelog.com/weekly).

:beers:

**Comment by derekprior** [comment]
Thanks @jerodsanto !
