### ISSUE TITLE
CloudFleet

### ISSUE THREAD

**Issue by metakermit** [thechangelog/ping#361]
Hey Changeloggers,

here's a project my friends and I are working on:

[CloudFleet: Your private encrypted cloud at home](https://cloudfleet.io/)

CloudFleet is an open source project for a private & secure home cloud with webmail, calendar, contacts and file sync that just works™. More info on the technology behind CloudFleet can be found [here](http://cloudfleet.readthedocs.org/en/latest/doc/technology/technology.html). We're currently running an [IndieGoGo campaign](https://www.indiegogo.com/projects/cloudfleet-your-private-encrypted-cloud-at-home/x/4096670#/) where you can preorder a device with everything installed for a plug-and-play experience.

We also have a larger press kit [here](https://github.com/cloudfleet/presskit#cloudfleet).

Cheers,
Dražen

P.S. Love the podcast! Keep up the great work!

**Comment by jerodsanto** [comment]
@metakermit we're including CloudFleet in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:

**Comment by metakermit** [comment]
Thanks a lot for the mention! :smiley:
