### ISSUE TITLE
RoboJS :: a library that aims to dynamically load JS modules depending on how the DOM is composed.

### ISSUE THREAD

**Issue by marcog83** [thechangelog/ping#362]
Hi, I'd like to share my project with you in order to understand if it makes some kind of sense.
This is the github link 
https://github.com/marcog83/RoboJS

and this is a post about why I wrote this library.
**RoboJS :: the idea behind the code**
https://goo.gl/xRoXqn

thanks a lot
marco

**Comment by jerodsanto** [comment]
@marcog83 we'll link this up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by marcog83** [comment]
Thanks a lot :)
