### ISSUE TITLE
TheForeman 1.10 release - orchestration and devops tooling

### ISSUE THREAD

**Issue by GregSutcliffe** [thechangelog/ping#363]
Hi Changelog,

I was pointed in your direction by a colleague, and was wondering if you'd care to make mention of http://theforeman.org at some point? We recently released version 1.10, which seems to be getting good feedback.

Let me know if I need to answer any questions :)

**Comment by jerodsanto** [comment]
@GregSutcliffe cool stuff! We'll link Foreman up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by GregSutcliffe** [comment]
@jerodsanto Epic, appreciate it! In case it's relevant, the next release (1.11) will be in about 4-6 weeks, the first release candidates will ship any day now.
