### ISSUE TITLE
Web crawler for Ruby

### ISSUE THREAD

**Issue by JordiPolo** [thechangelog/ping#364]
This project:
https://github.com/mdsol/grell

Aims at providing an easy way for ruby apps to create webcrawlers.

It will go through all the pages of some domain and you will be able to do with them what you want (checking properties, saving them, etc)

**Comment by jerodsanto** [comment]
@JordiPolo we're including grell in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:

**Comment by JordiPolo** [comment]
Great! Thank you so much!
