### ISSUE TITLE
EventStore database

### ISSUE THREAD

**Issue by kron4eg** [thechangelog/ping#365]
Hello,

Another business baked by opensource database https://geteventstore.com. Would be really cool to hear @gregoryyoung in a podcast.

**Comment by jerodsanto** [comment]
@kron4eg thanks so much for the ping! This business/project does look interesting, but we're a bit bearish on datastore-as-a-service-related episodes right now. We've done a fair bit of them and it gets harder and harder to extract the interesting/unique bits each time.

Thanks, again and please feel free to make any other suggestions you have! ✊

**Comment by gregoryyoung** [comment]
I'm a bit puzzled that you think eventstore is datastore-as-a-service can I
ask where you got this impressio? Event store is a database (and not
available AFAIC as a service)

On Tue, May 3, 2016 at 4:39 PM, Jerod Santo <notifications@github.com>
wrote:

> @kron4eg <https://github.com/kron4eg> thanks so much for the ping! This
> business/project does look interesting, but we're a bit bearish on
> datastore-as-a-service-related episodes right now. We've done a fair bit of
> them and it gets harder and harder to extract the interesting/unique bits
> each time.
>
> Thanks, again and please feel free to make any other suggestions you have!
> ✊
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/365#issuecomment-216530192>
>



-- 
Studying for the Turing test

**Comment by jerodsanto** [comment]
@gregoryyoung my bad, I misinterpreted the homepage. Commercial support model, yeah? Looks like you've managed to acquire an awesome set of customers. Congrats on that!

**Comment by gregoryyoung** [comment]
@jerodsanto yes 3-clause BSD OSS + commercial additions/support.
