### ISSUE TITLE
[open source] Scrapbook: PHP cache library

### ISSUE THREAD

**Issue by matthiasmullie** [thechangelog/ping#366]
https://github.com/matthiasmullie/scrapbook/ - http://www.scrapbook.cash/

A PHP caching environment:

* Adapters for: Memcached, Redis, Couchbase, APC, SQL variants, filesystem, memory
* Memcached-like API & PSR-6 API
* Buffers repeat cache requests in memory
* (Nested) transactions: commit/rollback all at once
* Stampede protection
* Sharding across multiple servers

**Comment by jerodsanto** [comment]
@matthiasmullie cool stuff! We'll link Scrapbook up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by matthiasmullie** [comment]
Coo, thanks!
