### ISSUE TITLE
Reactuate: React/Redux Stack (not a boilerplate!)

### ISSUE THREAD

**Issue by yrashk** [thechangelog/ping#367]
[https://github.com/reactuate/reactuate](https://github.com/reactuate/reactuate)

Reactuate is an opinionated stack for building React-based frontend applications. Core objectives are as follows:

* Fork-and-forget (or fork-and-follow) is not a great way to keep up with what's happening in the frontend space. Therefore, starting off from a cloned boilerplate "kit" is not an acceptable solution. Reactuate is distributed as a dependency.
* Reducing the amount of noise. Many kits suffer from the need to create too many files for each "functional vertical" (such as action creators, constants, reducer), which in turn leads to increased maintenance complexity (try renaming one of the vericals), "import nightmare" and inability to have a compact overview of the functionality.
* Discovering and learning the capabilities of comprehensive stack solution could be complicated. What's even worse, maintaining such stacks can be equally painful. Therefore, unconventionally, Reactuate is written as a literate program and is meant to be read as a small book and be a concise reference manual — while being a functional library.

What's quite important, Reactuate offers tools for building Domain Driven applications which makes applications less error-prone.

**Comment by jerodsanto** [comment]
@yrashk this looks pretty nice! I love that it's not a boilerplate. I just queued up a tweet in your direction and we're going to include this in the Projects section of tomorrow's [Changelog Weekly](https://changelog.com/weekly). :beers:
