### ISSUE TITLE
Dumpster - A self-hosted file upload server supporting YubiKey OTP authentication.

### ISSUE THREAD

**Issue by nmaggioni** [thechangelog/ping#368]
Hey Changeloggers!

Here's my latest project: a lightweight, self-hosted and API-based file upload server supporting YubiKey OTP authentication. [It's called Dumpster, and this is its repo :)][1]
It solves the need to use cumbersome services to quickly share a file with colleagues, friends or classmates, exposing an easy download-only link.
The security of file uploads is granted by the use of [YubiKey][2] OTP codes, so that you can be sure that no unauthorized personnel can upload malicious files to your server.
Since it works with GET and POST requests only, no interfacing methodology is precluded! You can use or hack toghether whatever interface you like: from a simple command line script to a whole webUI (an official one is in the works, by the way...)

Main features are:
+ Simple upload, API parameters control all the functions.
+ Dead-easy downloading, just click on a link.
+ Configurable file expiration date. After this time the file will be deleted - since the latest version, this feature survives server restarts as well!
+ Configurable maximum file size & other specs.
+ File upload secured by YubiKey, a leading product in hardware security tokens and 2FA.

[1]: https://github.com/nmaggioni/Dumpster
[2]: https://www.yubico.com/

**Comment by jerodsanto** [comment]
@nmaggioni we're including Dumpster in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :tada: 

We :ship: it tomorrow morning. :beers:

**Comment by nmaggioni** [comment]
@jerodsanto Awesome, thanks!
