### ISSUE TITLE
[Guest idea, Show #200]  Bring back Win N.

### ISSUE THREAD

**Issue by netaisllc** [thechangelog/ping#370]
OK, so it will be a little awk for Jerrod, but why not bring back Win and pound him for his view of the OSS world after working in the vineyard of the 'Hubs for awhile now.  Plus -- since he's an api junkie -- get an update on all this api-ey at GH and elsewhere.  Then of course the proverbial trip down RAM lane about the ChgLog :)

Gotta be for ** show #200** (not issue 200!) or not at all, guys!  

Best....

**Comment by jerodsanto** [comment]
@netaisllc fun idea, but it's not in the cards. I think you'll enjoy 200, nonetheless. :)
