### ISSUE TITLE
Frege, Haskell for the JVM

### ISSUE THREAD

**Issue by yellowsnow** [thechangelog/ping#371]
I suggest a podcast on Frege with [Dierk König](https://twitter.com/mittie) / @Dierk on this matter, Dierk is [kindly welcoming the idea](https://twitter.com/mittie/status/691210957788483584)
### Why functional programming?

Functional programming is gaining some field in the recent years (clojure, rust, elm). I wouldn't say that FP will become mainstream, but the the ideas from FP are getting widespread in the whole industry (Immutable infrastructures, Lambda calculus, Pure functions, etc.).  
### Why Frege ?

`Frege = Haskell + JVM`

Rock solid language constructs on rock solid platform.
### Links

Article on InfoQ : http://www.infoq.com/news/2015/08/frege-haskell-for-jvm
Dierk on Frege @ Devoxx : https://www.youtube.com/watch?v=1P1-HXNfFPc

**Comment by yellowsnow** [comment]
Ping  @jerodsanto @adamstac

**Comment by jerodsanto** [comment]
@yellowsnow thanks for the suggestion, we'll look in to it! :beers:

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
