### ISSUE TITLE
Learning 52 Technologies in 2016

### ISSUE THREAD

**Issue by shekhargulati** [thechangelog/ping#372]
I have taken a challenge to learn a new technology every week in 2016. The goal is to learn a new technology, build a simple application using it, and blog about it. The project is on github https://github.com/shekhargulati/52-technologies-in-2016

**Comment by jerodsanto** [comment]
@shekhargulati very cool idea! I came across your article on Hugo independently of Ping. Keep it going!

I just queued up a tweet in your direction and we'll also link this up in tomorrow's issue of [Weekly](https://changelog.com/weekly). :beers:
