### ISSUE TITLE
meza: A Python toolkit for processing tabular data

### ISSUE THREAD

**Issue by reubano** [thechangelog/ping#373]
[meza](https://github.com/reubano/meza) is a Python library for reading and processing tabular data. It has a functional programming style API (I use pure functions), excels at reading/writing large files, and can process 10+ file types.

Here's a basic example:
```python
from io import StringIO
>>> from meza import io, process as pr

>>> f = StringIO(u'col1,col2\nhello,world\n')
>>> records = io.read_csv(f) 
>>> next(pr.cut(records, ['col1']))
{'col1': 'hello'}
```

Here's a brief overview of it's advantages (vs pandas):
 - functions instead of objects
 - lower memory usage (via iterators of dictionaries as the primary data structure) reading large files
 - pypy
 - optimized for ETL and reading evented/streaming data
 - geojson support (reading/writing)
 - integrates nicely with sqlachemy (and other libs that work with iterators of dicts)

SOURCE: https://github.com/reubano/meza
DEMO: http://nbviewer.jupyter.org/github/reubano/meza/blob/master/examples/usage.ipynb
FAQ: https://github.com/reubano/meza/blob/master/docs/FAQ.rst

**Comment by jerodsanto** [comment]
@reubano cool stuff! We'll link meza up in this week's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by reubano** [comment]
Saw the post online. Thanks!
