### ISSUE TITLE
Cross-functional Teams & Microservices

### ISSUE THREAD

**Issue by hellogabor** [thechangelog/ping#374]
Hi there,

We just published an article that sums up our experiences about building microservices with cross-functional teams.

I hope you'll find it useful:

https://blog.risingstack.com/benefits-of-cross-functional-teams-when-building-microservices/

**Comment by jerodsanto** [comment]
@hellogabor thanks for pinging us! We're going to pass on this article because of its narrow focus on a) microservices, and b) cross-functional teams. The size of our audience that is interested in both of those topics is small.

That being said, please hit us up again in the future! :fist:
