### ISSUE TITLE
VaultSharp - A C#.NET client for Vault

### ISSUE THREAD

**Issue by rajanadar** [thechangelog/ping#375]
hello folks

wanted to submit my new project to 'thechangelog' to spread awareness about it.
please let me know if you need more info.

Project Name: **VaultSharp**

**Description:**

A .NET Library for HashiCorp's Vault - A Secret Management System.
A comprehensive C# library which supports all the APIs of Vault v 0.4.0

Download location: https://www.nuget.org/packages/VaultSharp/
GitHub Site: https://github.com/rajanadar/VaultSharp
ReadMe file: https://github.com/rajanadar/VaultSharp/blob/master/README.md
Documentation Site (with Examples): http://rajanadar.github.io/VaultSharp/
Feedback/Issues: https://github.com/rajanadar/VaultSharp/issues/new
Twitter Handle: @vaultsharp 

thanks,
Raja

**Comment by jerodsanto** [comment]
@rajanadar :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
