### ISSUE TITLE
Goad: distributed load testing powered by AWS Lambdas

### ISSUE THREAD

**Issue by matiaskorhonen** [thechangelog/ping#376]
[Goad](https://goad.io/) is an AWS Lambda powered, distributed, load testing tool built in Go for the 2016 [Gopher Gala](http://gophergala.com/).

<https://github.com/gophergala2016/goad>

---

In other Gopher Gala news, [voting](https://obscure-savannah-52814.herokuapp.com) is open until Saturday, January 30 at 5pm PST (Sunday January 21 at 1am UTC).

**Comment by jerodsanto** [comment]
@matiaskorhonen sorry we missed the open voting, but we're including Goad in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:

**Comment by matiaskorhonen** [comment]
Nice, cheers! We actually ended up [winning](http://gophergala.com/blog/gopher/gala/2016/02/05/winners-2016/) the competition anyways :smiley:
