### ISSUE TITLE
janeway: a mouse-driven node.js REPL

### ISSUE THREAD

**Issue by skerit** [thechangelog/ping#377]
Hey there,

I wanted to let you know about my project called [janeway](https://github.com/skerit/janeway).

It's a node.js REPL in the console. It can be compared to ultra-repl, though it is more mouse-driven.

I've been using it myself for over a year now, and it's finally getting some attention. I would love to keep that momentum going, so I'm reaching out to you :)

Greetings,
Jelle De Loecker

**Comment by jerodsanto** [comment]
@skerit cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
