### ISSUE TITLE
You should revise your Redis max connections setting

### ISSUE THREAD

**Issue by benoittgt** [thechangelog/ping#378]
Hey

I've written with 2 coworkers this blog post about redis max connection limit : 

https://medium.com/appaloosa-store-engineering/you-should-revise-your-redis-max-connections-setting-8136f063c916#.aw19221ws

If you have any feedbacks, share them ! :)

**Comment by jerodsanto** [comment]
@benoittgt good advice! We'll link this up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
