### ISSUE TITLE
Apache Ignite

### ISSUE THREAD

**Issue by raulk** [thechangelog/ping#379]
Apache Ignite is a new Apache Top Level Project that was donated to the Apache Incubator by GridGain, and it graduated to a Top Level Project in late 2015.

Ignite is an in-memory data fabric and distributed platform for computing and transacting on large-scale data sets in real-time, orders of magnitude faster than possible with traditional disk-based or flash technologies.

It supports transactions, co-locality/affinity, continuous queries, event processing, MapReduce, fork-join, etc. It integrates with Apache Spark, Hadoop, HDFS, Spark, Flume, etc.

The right person of contact is [Dmitriy Setrakyan](https://twitter.com/dsetrakyan).

**Comment by svladykin** [comment]
:fire: :+1:

**Comment by agura** [comment]
:+1:

**Comment by ashutakGG** [comment]
:fire: :+1:

**Comment by avinogradovgg** [comment]
:fire: :+1: :fire:

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
