### ISSUE TITLE
Browse Hacker News from the comfort of your Terminal

### ISSUE THREAD

**Issue by rafaelrinaldi** [thechangelog/ping#380]
Made this project called [`hn-cli`](https://github.com/rafaelrinaldi/hn-cli) that allow users to browse [Hacker News](https://news.ycombinator.com/news) on the Terminal.

[![demo](https://raw.githubusercontent.com/rafaelrinaldi/hn-cli/master/demo.png)](https://github.com/rafaelrinaldi/hn-cli)

If you think it's worth adding to the projects section of the newsletter, I will be more than happy :+1:

**Comment by jerodsanto** [comment]
@rafaelrinaldi nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link hn-cli up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
