### ISSUE TITLE
Project Ace: Leveraging Native UI in Cordova Apps

### ISSUE THREAD

**Issue by adnathan** [thechangelog/ping#381]
We publicly announced this in conjunction with the PhoneGap Day conference yesterday, and put out a [conference app](https://play.google.com/store/apps/details?id=com.microsoft.phonegapday.sample&hl=en) that uses the technology.

During our conversations with Cordova developers, there were many instances when people expressed the desire to mix native UI controls with the Cordova WebView capabilities. This project provides many easy ways to do just that.

I hope you find it interesting!

* [Ace on GitHub](https://github.com/adnathan/ace)
* [Public Announcement](http://taco.tools/articles/ace.html)

**Comment by jerodsanto** [comment]
@adnathan we'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
