### ISSUE TITLE
Software quorum project published on GitHub

### ISSUE THREAD

**Issue by afgbeveridge** [thechangelog/ping#382]
Hi:

I have a C#/VS 2015 quorum project now in a release state [available here](https://github.com/afgbeveridge/Quorum). It includes a full wiki, licensing (MIT) terms and an implementation guide and suite of unit tests. Excerpt from README:

"The purpose of this project is to provide a 'quorum' based implementation to facilitate reliable independent processes.

For example, a quorum based Windows service could communicate with its peers to ensure there is only and always one 'master' service operating, thus avoiding the traditional single point of failure in Windows services. This would be useful if you had a Windows service where always and only one instance should be operating at any one time, but the service will be redundantly deployed across multiple machines in a web farm.

This project provides:

An MVC web app for quorum configuration, monitoring and real time log capture
A pro forma Windows service implementation for a quorum member
A pro forma console app implementation for a quorum member
A command line tool for lower level quorum interaction"

Thanks in advance
Tony Beveridge

**Comment by jerodsanto** [comment]
@afgbeveridge we're including Quorum in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
