### ISSUE TITLE
Reactuate Events

### ISSUE THREAD

**Issue by yrashk** [thechangelog/ping#383]
Hey guys, I've got one more library out. It's quite fresh, and it's pretty small (in fact, tiny), but it helps building sequential event processing workflows for React components (those that don't or won't fit into your app's Flux). You can read a brief intro at https://github.com/reactuate/reactuate-events

**Comment by jerodsanto** [comment]
@yrashk cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
