### ISSUE TITLE
Podcast suggestion: Chris Allen and Julie Moronuki's Haskell Book

### ISSUE THREAD

**Issue by zmanian** [thechangelog/ping#384]
Chris Allen( @bitemyapp) and Julie Moronuki(@argumatronic) partially complete and available for purchase book is a comprehensive introduction to the Haskell programming language. http://haskellbook.com/

Great podcast guests.

**Comment by julienXX** [comment]
👍

**Comment by dmvianna** [comment]
Do it. I cannot praise it enough. I wasn't able to write xmonad's config file. Now I get ELM examples better than I can read ES5 (and I do know JavaScript).

**Comment by AlainODea** [comment]
:+1:

**Comment by abevoelker** [comment]
:+1: I failed at gaining any significant traction learning Haskell with existing resources (LYAH, RWH, CIS194) until I read their book. It's extremely good. And based on my Twitter interactions they're very cool people and would make great guests!

**Comment by bitemyapp** [comment]
@jerodsanto I've sent an email from cma at bitemyapp dot com, thank you!

**Comment by zmanian** [comment]
I'm super psyched to see this happen. I'm looking forward to listening to it.

**Comment by sjsyrek** [comment]
Yes!

**Comment by benoittgt** [comment]
Is it always planned?

**Comment by jerodsanto** [comment]
This show has been recorded and is in editing. It's the next one to be released so it should reach your ears real soon!

**Comment by bitemyapp** [comment]
@jerodsanto thank you, it was a real pleasure speaking with y'all :)

And thank you @zmanian!

**Comment by benoittgt** [comment]
Excellent news !

**Comment by jerodsanto** [comment]
:tada: This show is now live! :tada: 

https://changelog.com/198/

Thanks to all, it turned out superb! :fist: :facepunch: :muscle:
