### ISSUE TITLE
Huginn: system for building agents that perform automated tasks

### ISSUE THREAD

**Issue by williamn** [thechangelog/ping#385]
[Huginn](https://github.com/cantino/huginn) is a system for building agents that perform automated tasks for you online.

**Comment by jerodsanto** [comment]
@williamn we covered Huginn in Weekly awhile back, but I think it'd make a great topic for the podcast. I [invited them on](https://github.com/cantino/huginn/issues/1271), so we'll see what happens! :+1:

**Comment by williamn** [comment]
@jerodsanto great!

**Comment by jerodsanto** [comment]
@williamn our [show on Huginn](https://changelog.com/199/) is now live! Hope you enjoy it :green_heart: :purple_heart: :yellow_heart: :blue_heart:

**Comment by williamn** [comment]
@jerodsanto Great!
