### ISSUE TITLE
npm addict: Your daily injection of npm packages

### ISSUE THREAD

**Issue by mvila** [thechangelog/ping#386]
I created a little website which I thought might interest the JS community:

https://npmaddict.com

Enjoy! :)

**Comment by jerodsanto** [comment]
@mvila nice! I just queued up [a tweet](https://twitter.com/changelog) in your direction and we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/). It :ship:s tomorrow morning. :beers:

**Comment by mvila** [comment]
Whoa, great! Cheers man! :)
