### ISSUE TITLE
phpietadmin: A webinterface to configure the iscsi enterprise target (iet) daemon on debian

### ISSUE THREAD

**Issue by MrCrankHank** [thechangelog/ping#387]
#### Project:
https://github.com/MrCrankHank/phpietadmin-gui

#### Documentation, Installation, Screenshots:
https://github.com/MrCrankHank/phpietadmin-doc/wiki/v0.6.3-%5Bstable%5D

#### Description:
phpietadmin enables you to configure all features of the iscsi enterprise target via webbrowser, e.g.:
* Targets (Adding/deleting luns, settings, Sessions, ...)
* Permissions (IP based acl, user management)

Currently only lvm volumes can be used as iscsi targets. Their configuration is also supported, e.g.:
* Adding volumes
* Extending volumes (+ notify iscsi initiator about the change)
* Shrinking volumes
* Renaming volumes
* Deleting volumes

**Comment by jerodsanto** [comment]
@MrCrankHank we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:

**Comment by MrCrankHank** [comment]
Thanks!
