### ISSUE TITLE
[podcast suggestion] Rakudo Perl 6

### ISSUE THREAD

**Issue by szabgab** [thechangelog/ping#388]
Rakudo http://rakudo.org/ ( https://github.com/rakudo/ ) is the (most advanced) implementation of Perl 6 http://perl6.org/ ( https://github.com/perl6/ ) which has been released Christmas 2015. 
Rakudo itself is the compiler.
Rakudo Star is a distribution that includes the compiler and a bunch of modules.
There are three people I'd recommend to talk to Patrick Michaud https://github.com/pmichaud who is the Rakudo project leader of and/or Elizabeth Mattijsen http://www.liz.nl/ https://github.com/lizmat and/or Jonathan Worthington http://www.jnthn.net/ https://github.com/jnthn who writes about Perl  here: https://6guts.wordpress.com/

**Comment by dbohdan** [comment]
This would be great!

**Comment by hoelzro** [comment]
:+1:

**Comment by jerodsanto** [comment]
@szabgab great suggestion, but we're going to hold out for our next Perl episode until we can get Larry Wall on the show. Closing this with preference to #500. 🍻
