### ISSUE TITLE
torrent-docker

### ISSUE THREAD

**Issue by bigblind** [thechangelog/ping#389]
https://github.com/mafintosh/torrent-docker

A couple of years ago, we heard about [facebook using torrents to distribute their source](https://torrentfreak.com/facebook-uses-bittorrent-and-they-love-it-100625/). And while I was waiting for a huge docker image to be downloaded over a crappy wifi connection, I googled "docker torrent", and found this gem (not the ruby kind :)).

Note: I'm not currently usign this myself, but I really want to. If this works well, I think this could be used for more efficient docker deployments.

**Comment by jerodsanto** [comment]
@bigblind cool stuff! Perhaps crazy, but cool anyhow. :grinning:  We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
