### ISSUE TITLE
Interview ashaffer on what he is doing with vdux and virtex

### ISSUE THREAD

**Issue by bendik** [thechangelog/ping#391]
https://github.com/ashaffer

**Comment by jerodsanto** [comment]
@bendik curious, what has you so excited about vdux and virtex?

**Comment by bendik** [comment]
@jerodsanto It is current work and it could amount to something more if attention is given to it. It is challenging react to some extent. I would personally like to know some of the motivations and thought it might be a good story.

**Comment by jerodsanto** [comment]
@bendik I think it's a _tad_ too narrow of a topic to make a full show out of it. However, if yourself (or @ashaffer himself) would like to write a guest post on The Changelog about it, I'd be open to that.
