### ISSUE TITLE
Purescript

### ISSUE THREAD

**Issue by timdeputter** [thechangelog/ping#392]
Hello,

a podcast with @paf31 about purescript ([http://www.purescript.org/](http://www.purescript.org)) would be cool

**Comment by timdeputter** [comment]
He allready talked about it on the javascript jabber episode 189 https://devchat.tv/js-jabber/189-jsj-purescript-with-john-a-de-goes-and-phil-freeman. As you had a show about Elm, I think it would be an interesting follow up.

**Comment by jerodsanto** [comment]
@timdeputter thanks for the suggestion! 🍻  I've been hearing good things about PureScript lately...

@paf31 are you interested in coming on the show? Please email editors@changelog.com to coordinate if so.

**Comment by jerodsanto** [comment]
Closing this because cleanliness 🏡. @paf31 you have our email if/when you're interested. Thanks again, @timdeputter!

**Comment by paf31** [comment]
Yes, thank you. I'm a little busy at the moment, but I'll get in touch via email soon.
