### ISSUE TITLE
React on Rails

### ISSUE THREAD

**Issue by justin808** [thechangelog/ping#393]
React on Rails is the most popular system for integrating React, Redux, and Webpack with Ruby on Rails: https://github.com/shakacode/react_on_rails/

"The React on Rails Doctrine"
https://medium.com/@railsonmaui/the-react-on-rails-doctrine-3c59a778c724
explains the philosophy and goals.

The number one point is that there is a ton of "Javascript Fatigue" going on now, so a good omakase Javascript meal on top of an Omakase Ruby on Rails makes a lot of sense.

We're getting close to hitting 1,000 stars on github and we've been on the ruby trending front page. We're still on the monthly list: https://github.com/trending/ruby?since=monthly

Aloha,

Justin

**Comment by jerodsanto** [comment]
@justin808 :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by justin808** [comment]
@jerodsanto I LOVE your show and hope to someday be honored with a chance to be interviewed about how "React on Rails" came to be!
