### ISSUE TITLE
Fossil

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#394]
[Fossil](http://fossil-scm.org/) is a software configuration management system from the creator of SQLite -- [that SQLite](https://en.wikipedia.org/wiki/SQLite). What is interesting about Fossil is that it provides an integrated alternative to both Git itself and GitHub/Bitbucket/GitLab/gogs. Fossil implements a distributed version control system a-la Git/Mercurial with a user-friendly command line UX as well as a web interface (the website [fossil-scm.org](http://fossil-scm.org) runs Fossil), an issue tracker and a Markdown wiki. This functionality is provided by a single binary. Fossil is written in C and runs well on low-end servers. Prebuilt static binaries are available for (x86) Linux, Mac, OpenBSD and Windows.

If you don't want to self-host, [Chisel](http://chiselapp.com/) provides free hosting for Fossil projects with unlimited public and private repositories and any number of collaborators. The Chisel platform is itself open source.

**Comment by jerodsanto** [comment]
@dbohdan thanks for this. I wasn't aware of Fossil, but I _was_ keen on inviting Richard Hipp on the show and this issue pushed me over the edge. I contacted him today and we'll see what happens. Thanks again!
