### ISSUE TITLE
Bumped, makes easy release software.

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#395]
<p align="center">
  <br>
  <img src="https://avatars3.githubusercontent.com/u/11788740?v=3&s=200" alt="fink-www">
  <br>
  <br>
</p>

[Bumped](https://github.com/bumped/bumped#bumped) synchronizes your software version across different package manager configuration files (npm, bower,...) and controls, edits and releases each of its versions to ensure all the files have the same version.

It's a based in a little system of hooks that you trigger before and after release a new version. Here is an example of [file configuration](https://github.com/Kikobeats/acho/blob/master/.bumpedrc).

Because writing software is hard enough, we must make the publishing process of software simple and effective.

**Comment by jerodsanto** [comment]
@Kikobeats we're including Bumped in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
