### ISSUE TITLE
Pollinate - Keep your base files on GitHub, easily download & transform them for each use. 

### ISSUE THREAD

**Issue by howardroark** [thechangelog/ping#396]
Came across your "Top 10" article and ended up here, would love your thoughts!

https://github.com/everysquare/pollinate

**Comment by jerodsanto** [comment]
@howardroark cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by howardroark** [comment]
Hey that's great!  Always looking for contributors :)  Thanks!
