### ISSUE TITLE
Fink, URL Shortener for Masses

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#397]
<p align="center">
  <br>
  <img src="https://avatars2.githubusercontent.com/u/16745034" alt="fink">
  <br>
  <br>
</p>

I created [🐀.ws](http://xn--rn8h.ws), an URL Shortener for Masses.

What this means?

- You can short whatever URI (for example, try with a bittorrent magnet uri!).
- URL hash is small as possible. 
- URL are uniques: two same URI's point to the same URL.
- Emoji version per each hash!
- See stats adding `+` at the end of the hash.

More information about the project in the [FAQ](http://xn--rn8h.ws/faq) section.

**Comment by jerodsanto** [comment]
@Kikobeats it's your week! This one's going in too. :green_heart: :purple_heart: :yellow_heart: :blue_heart:

**Comment by Kikobeats** [comment]
Really?? Wow, thanks 😁🎉🎉

On Friday, 1 April 2016, Jerod Santo <notifications@github.com> wrote:

> Closed #397 <https://github.com/thechangelog/ping/issues/397>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/397#event-611798809>
>


-- 
*Att, Kiko.*
