### ISSUE TITLE
A new OSS project I'd like to share

### ISSUE THREAD

**Issue by rpeleg1970** [thechangelog/ping#399]
Hi

I am part of IBM Security Innovation team, following and enjoying your weekly newsletter for quite a while. We recently open sourced a new Docker based project for orchestrating batch payload - internally we use it for running file scanners over an automated malware sample stream, but can be used for any generic purpose. It is well documented and easy to set up. I would like to share the project via your newsletter.

Here is a blog on IBM developer Works: https://developer.ibm.com/open/2016/02/21/using-docker-containers-batch-job-scheduling-2/

Here is the github project page: https://github.com/ibm-security-innovation/menagerie

Thanks for considering!
Ron

**Comment by jerodsanto** [comment]
@rpeleg1970 cool stuff (and thanks for the kind words)! We'll link this up in the next issue. :beers:
