### ISSUE TITLE
AppImageKit

### ISSUE THREAD

**Issue by stigsb** [thechangelog/ping#400]
Hi guys,

You should definitely check out https://github.com/probonopd/AppImageKit and http://appimage.org/
It's basically an OS X-inspired way of packaging Linux applications in a distro-agnostic format. It seems to be a really good match for desktop applications in particular.

 - Stig

**Comment by jerodsanto** [comment]
@stigsb :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
