### ISSUE TITLE
How to run Ruby scripts on AWS Lambda using Ansible

### ISSUE THREAD

**Issue by manuelmeurer** [thechangelog/ping#401]
I just published a blog post about how to deploy a Ruby script to AWS Lambda using Traveling Ruby and Ansible.

https://www.krautcomputing.com/blog/2016/02/29/how-to-run-ruby-scripts-on-aws-lambda-using-ansible/

**Comment by jerodsanto** [comment]
@manuelmeurer we're including your blog post in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
