### ISSUE TITLE
Zenbership Membership Software Has Gone Open Source

### ISSUE THREAD

**Issue by castlamp** [thechangelog/ping#402]
It's with great pride that I can finally say the words I've been wanting to say for years: "Zenbership has gone open source!"

I've always been an avid supporter of the open source movement and have been toying with the idea of re-releasing Zenbership under the GPLv3 for some time. Given the scale of Zenbership, as well as the number of potential businesses that can benefit from it, I finally pulled the trigger on the process in February 2016. Since that time, I've been working around the clock to update the website, fix lingering bugs in the software, and rebrand "Ascad Networks" into "Castlamp", a company which is now devoted solely to the creation of free & open source software.

For those unfamiliar with it, Zenbership is an enterprise-level membership software platform that combines event planning, a CRM, a CMS, invoicing, subscription management, marketing tools (like source tracking, e-mail campaigns, Social Media integration, and SMS campaigns), a shopping cart, and secure content delivery. The concept is "start to finish" membership management, combining all of the tools small businesses, clubs, organizations and non-profits need to succeed into a single platform.

- Designers love it because it can be completely customized, allowing them to white-label the software to match your company's brand.
- Developers really love it, as it provides a highly flexible extension and hook system, allowing them to integrate 3rd party applications.
- Sales teams love it because it provides a drop-dead simple approach to the CRM, allowing them to track the lifecycle of a lead and target efforts to sources with the highest ROI without all the clutter of larger CRM systems.
- Marketers love it because it provides an advanced criteria system allowing them to create targeted campaigns (both automated and double opt-in) aimed at very specific contacts and members.
- eCommerce websites love it because it allows them to build an entire store front with all the bells and whistles like shipping, taxes, terms and conditions, promo codes, subscription products, trial products, volume discounts, and special promotions. Not to mention that it integrates with many of your favorite payment gateways like Stripe, Paypal, Authorize.net, and Beanstream.
- Non-Profits love it because it allows them to throw events, manage membership rosters, market to their members, and automate online registrations & dues collection.
- Small Businesses love it because it provides them with the tools they need to properly create a membership website, selling access to secure content like software, videos, eBooks, and more!

Find out why you'll love it as well here:
[http://www.zenbership.com/](http://www.zenbership.com/)

And of course, if you have any questions please feel free to reach out. I'm on Twitter ([@jbelelieu](http://twitter.com/jbelelieu)) or you can get in touch directly on the Castlamp website.

Thanks,
Jon Belelieu

**Comment by junland** [comment]
That's awesome @castlamp! Welcome to the Open Source Community!

**Comment by coccoinomane** [comment]
That's great news @castlamp! As a web agency, we are starting to provide CRM support to our clients; many of them are eCommerce and membership sites, so you can understand why I look at Zenbership with great interest :-) I hope that I can convince my boss to adopt Zenbership company-wide...

**Comment by castlamp** [comment]
That’s fantastic! We’re launching a very big update in the coming weeks, so stay tuned!

Thanks,
Jon Belelieu
Founder & Lead Developer, Castlamp
https://www.castlamp.com/

**Comment by castlamp** [comment]
That’s fantastic! We’re launching a very big update in the coming weeks. Stay tuned for updates!

Thanks,
Jon Belelieu
Founder & Lead Developer, Castlamp
https://www.castlamp.com/

**Comment by jerodsanto** [comment]
@castlamp congrats, indeed! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
