### ISSUE TITLE
wp-password-bcrypt plugin

### ISSUE THREAD

**Issue by swalkinshaw** [thechangelog/ping#403]
[Roots](https://roots.io/) has released a new [wp-password-bcrypt](https://github.com/roots/wp-password-bcrypt) plugin which improves password security on new and existing WP sites by using the modern and secure bcrypt hashing function instead of the broken MD5 (which is what WP uses by default).

Blog post: https://roots.io/improving-wordpress-password-security/

**Comment by adamstac** [comment]
Thanks @swalkinshaw. Tweeted this https://twitter.com/changelog/status/705976168625778688
