### ISSUE TITLE
Interview Roy Keene about AppFS

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#404]
[AppFS](http://appfs.rkeene.org/web/index) is a FUSE-over-HTTP filesystem for running software without installing it.

Disclosure: I know @rkeene from #tcl on FreeNode.

**Comment by dbohdan** [comment]
What I find fascinating about AppFS, IPFS (#405) and the namespace part of Urbit (#406) is they are part of the recent general trend towards content-addressable global namespaces as an alternative to convention storage. "Content-addressable" means you reference whatever you put in a file system by a function of its content (e.g., the SHA1 sum) instead of a filename and a path or inode number. Your disk or even the entire Internet becomes a lot like a Git repository. This approach brings real advantages to developers and users; they include permanent storage (by design protected against silent data corruption), deduplication and on-demand loading of content. Conventional filesystems can then be built on top of this basis.

**Comment by jerodsanto** [comment]
@dbohdan I think we'll let our IPFS show address (pun!) the "content-addressable global namespace" segment for now. I realize AppFS is a different thing altogether, but we're going to pass on a show about it at this time. Please re-open this issue if Big News comes from that camp sometime in the future. 🍻

**Comment by dbohdan** [comment]
>I think we'll let our IPFS show address (pun!) the "content-addressable global namespace" segment for now.

Does this apply to #406 (Urbit)? They've recently had a big event (relatively speaking): they launched an open beta for developers ([HN discussion](https://news.ycombinator.com/item?id=11851849)).

**Comment by jerodsanto** [comment]
Not necessarily, but I'm having a hard time seeing through all of the marketing lingo of Urbit to see what's interesting about it.

**Comment by dbohdan** [comment]
Good to hear that. I think [Alex Krupp's blog post](http://alexkrupp.typepad.com/sensemaking/2013/12/a-brief-introduction-to-urbit.html) is a pretty good introduction to Urbit, even if the terminology has changed a bit since it was published. I am far from an expert but if you have questions after reading the post I can answer them to the best of my knowledge.

**Comment by galenwp** [comment]
I'd like to think that there are lots of interesting things about Urbit.  But I'm pretty biased — I'm one of the devs.

If this: http://urbit.org/posts/overview/ is too marketing-flavored then this: http://urbit.org/docs/about/overview/ might be more what you're looking for.

**Comment by cgyarvin** [comment]
You might also enjoy my [LambdaConf presentation](https://www.youtube.com/watch?v=rkZ3GkeU9kg).  This is obviously targeted at a technical audience, and the first 10 minutes give a pretty good impression of the goal and approach.

Sorry about the marketing!  I hate it too.  Even though I wrote most of it.
