### ISSUE TITLE
Interview someone on the IPFS team

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#405]
[IPFS](https://ipfs.io/), which stands for "InterPlanetary File System", is a protocol designed to address the weaknesses of HTTP, namely the breaking links. Content stored on IPFS is stored permanently.

**Comment by jerodsanto** [comment]
@dbohdan good suggestion. In fact, here's a peak at the "Backlog" list in our planning Trello board:

<img width="262" alt="2016-03-25 at 3 42 pm" src="https://cloud.githubusercontent.com/assets/8212/14053620/80e60956-f2a0-11e5-8253-9d16907af3ec.png">

Any idea who would be their _best candidate_ for an interview?

**Comment by jerodsanto** [comment]
Invited: https://github.com/ipfs/ipfs/issues/173

**Comment by jerodsanto** [comment]
@dbohdan we shipped this show over the weekend. 💥 

https://changelog.com/204/

Thanks for being a valuable part of the Changelog community. We appreciate you. 💚
