### ISSUE TITLE
Interview someone on the Urbit team 

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#406]
[Urbit](http://urbit.org/) is project to develop a clean-slate, secure, decentralized operating system, network protocol and programming language on top of Unix.

**Comment by jerodsanto** [comment]
Hmm I guess this one just never rose to the level of interest required to get me off my butt and put a show together. That's probably not a good sign, closing but will revisit the topic if/when another listener requests Urbit for the show. 💚
