### ISSUE TITLE
Ora - Elegant Terminal Spinner

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#407]
Useful for adding some nice interactivity while your CLI app is busy doing something. [Lots of spinners to choose from.](https://github.com/sindresorhus/cli-spinners/blob/master/spinners.json)

https://github.com/sindresorhus/ora

**Comment by jerodsanto** [comment]
@sindresorhus :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by sindresorhus** [comment]
👌😁
