### ISSUE TITLE
Whiteboard - nodeJS based "Slate" alternative

### ISSUE THREAD

**Issue by mpociot** [thechangelog/ping#408]
Since your latest newsletter featured "Slate" as an API documentation tool, I wanted to show you my nodeJS based project called "Whiteboard".

https://github.com/mpociot/whiteboard

I found Slate quite hard to set up and use. That's why I've rebuilt it using nodeJS.

**Comment by jerodsanto** [comment]
@mpociot cool stuff! We RT'd you earlier this week and we'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
