### ISSUE TITLE
Special episode focusing on OSS projects for end-users

### ISSUE THREAD

**Issue by Jermolene** [thechangelog/ping#409]
I had the pleasure of being interviewed for episode 196. One thing I realised as we spoke was that my project [TiddlyWiki](https://github.com/Jermolene/TiddlyWiki5) is part of a relatively small group of open source projects that are aimed by end-users who are non-developers: Firefox, Inkscape, Gimp, Transmission, Musescore, for example.  The vast majority of open source projects are created by developers for other developers, as can be seen by scanning the past episodes of thechangelog.

I wondered if it would be interesting to devote a special to showcasing half a dozen projects in the category? As well as interviewing project personnel, one might be able to include interviews with end users.

It would be great to have a better understanding of the issues that these projects share, such as getting the best from a community that is dominated by non-developers.

**Comment by dbohdan** [comment]
This would be interesting. You could talk about the decline and the possible comeback of SourceForge as the end user-oriented counterpart to GitHub.

**Comment by jerodsanto** [comment]
Interesting idea, for sure. If we were to highlight 6 such projects, what would they be and why?

**Comment by dbohdan** [comment]
Here is an assorted list based on what I use. I'm deliberately leaving out juggernauts like Firefox and LibreOffice.

* [Double Commander](https://en.wikipedia.org/wiki/Double_Commander) — I looked at dozens of file mangers, FOSS and proprietary, and ended up using this one. It is the best open source counterpart I know to [Total Commander](https://en.wikipedia.org/wiki/Total_Commander) that runs on multiple operating systems.
* [GnuCash](https://www.gnucash.org/) — a bookkeeping application that works great for home finance.
* [Inkscape](https://inkscape.org/en/) — a vector graphics editor with SVG as its native format. Comparable to its proprietary counterparts in terms of features and user-friendliness.
* [KeePassX](https://www.keepassx.org/) — a cross-platform (Linux/FreeBSD/OS X/Windows) password manager that supports the highly popular [KeePass](https://en.wikipedia.org/wiki/KeePass) password storage format. Nice UX. It has recently had (a somewhat rocky) version 2.0 release, which introduced support for the more modern KeePass 2  password databases.
* [MATE](http://mate-desktop.com/) — a classic desktop environment forked from GNOME 2. Has good font rendering, low resource usage (including the fact that it does not require compositing, which makes it good for use over remote connections) and works on a wide variety of systems.
* [mpv](https://mpv.io) — a cross-platform, scriptable media player that plays everything you throw at it. Features a pleasant minimalistic UI.

**Comment by dbohdan** [comment]
Bonus mentions:

* It's easy to forget, but many Linux distributions are end user-focused FOSS projects.
* TeX and the [LaTeX](https://en.wikipedia.org/wiki/LaTeX) ecosystem. This one of the oldest user-facing open source projects that are still maintained today. The original TeX was released in 1978 (!) by [Donald Knuth](https://en.wikipedia.org/wiki/Donald_Knuth). It is typesetting system that produces beautifully typeset documents. Most of its users are scientists and researchers, but they aren't just computer scientists; numerous physicists, chemists, mathematicians use LaTeX in their daily work, as do some biologists, social scientists and lawyers.

**Comment by shadowbq** [comment]
I would be interested in hearing how opensource community management differs the experience for the projects designed for / heavy used by systems for the end users.. 

Corporate controlled directions: 
Fedora Core Linux by redhat, 
Chromium by google,
etc...

VS spinoffs and forks that are self managed
the Document Foundation’s LibreOffice


(Others to consider VLC, notepad++, 7zip)

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
