### ISSUE TITLE
Might be interesting for you: React Compose

### ISSUE THREAD

**Issue by Nedomas** [thechangelog/ping#410]
My friend and I just open-sourced a React library that you might love.

React Compose: Simpler Stateless Components (http://reactcompose.com)

React components often become bloated with repeated logic. With React Compose you can encapsulate logic into reusable functions. 

Styling components is often a mess, using the same compose pattern you can split the styling behaviour into encapsulated pieces. It is also more straight forward to test the encapsulated behaviour rather than the component as a whole.

Do you guys need any additional information? :rocket:

**Comment by jerodsanto** [comment]
@Nedomas nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link React Compose up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
