### ISSUE TITLE
bigchaindb

### ISSUE THREAD

**Issue by stng** [thechangelog/ping#411]
Looks like a promising new open-source block chain database implementation built on top of rethinkdb. Would love to hear more about this from the creators! Hopefully you guys can get them on a future show. Keep up the great work!

https://github.com/bigchaindb/bigchaindb

**Comment by jerodsanto** [comment]
@stng thanks for the suggestion! Between our recent episode on [IPFS](https://changelog.com/204) and our [upcoming episode](https://changelog.com/schedule/) on Ethereum, we're covered in the block chain department for a bit.

Please keep an eye on this project and ping us again if there's big news coming from this camp. We'll revisit then! 🍻
