### ISSUE TITLE
18f - open source govt code & microauctions

### ISSUE THREAD

**Issue by crmackay** [thechangelog/ping#413]
So, I've been following the [18f group](https://18f.gsa.gov/), which is a fairly new group of open source coders working for the federal government. They were the ones who released a standards and style guide a few months ago for US Govt websites: [style guide](https://18f.gsa.gov/2015/09/28/web-design-standards/).

They just started testing out a new microauction system to resolve issues in their code base. Essentially (as I understand it) they ask for bids and the winning bidder gets paid the agreed amount upon delivery of a pull request resolving the open issue at hand (after testing etc.).

This is an interesting idea for maintaining open source (an oft discussed topic on your show), and for promoting open source in domains that are more used to contracting out and paying large sums of money for inflexible or slow-moving closed source products. The microauctions system might result in lower costs, or better code, or quicker resolution of bugs, etc. Any or all results would be interesting to hear about.

Here's a link to their auction site: [https://micropurchase.18f.gov/](https://micropurchase.18f.gov/)

Also discussing their work in general, and how they have managed to introduce and promote open-source within the often intractable workings of the federal government would be interesting to hear about. 

edit: fixed link, and typos

**Comment by jerodsanto** [comment]
@crmackay :+1: I think this could make for a very interesting show.

**Comment by jerodsanto** [comment]
@crmackay wow, they have a [HUGE team](https://18f.gsa.gov/team/)! Do you have any insight on who would be a good representative for them? (We've had Sarah Allen on the show before talking about other stuff.)

**Comment by crmackay** [comment]
@jerodsanto unfortunately, I have no real insights. I only been watching from afar. I actually didn't realize they were as big as they are...

**Comment by quepol** [comment]
Hey folks! @jerodsanto if you're interested in having 18F folks on the show, please get in touch! Happy to chat about what topics you'd like to cover and find the best people to be on the show.

Email me at hillary.hartley@gsa.gov and copy media@gsa.gov. Thanks! (and thanks, @toolness for the heads up about this conversation.)

**Comment by jerodsanto** [comment]
YAS thanks @toolness!  💥 💥 ✊

Email is on the way!

**Comment by jerodsanto** [comment]
@quepol ping! I emailed you with regard to scheduling but haven't heard back. Maybe it's in your spam?

**Comment by jerodsanto** [comment]
This show is now live! 🎉

https://changelog.com/podcast/230

Thanks to everyone for helping line it up. Listen closely for a shout out during the show! :green_heart: :green_heart: :green_heart:
