### ISSUE TITLE
Alchemy Micro-services Framework

### ISSUE THREAD

**Issue by grahamjenson** [thechangelog/ping#414]
[Alchemy](https://github.com/LoyaltyNZ/alchemy-framework) is a framework for creating highly available systems that are built from [micro-services](http://martinfowler.com/articles/microservices.html). Alchemy includes service discovery, easy deployment, smart load balancing, and is also designed to be polyglot, so you can use the best languages to solve all your problems; Alchemy already has implementations in [Node.js](https://github.com/LoyaltyNZ/alchemy-ether) and [Ruby](https://github.com/LoyaltyNZ/alchemy-flux).

There are descriptions of using alchemy with:

1. [Docker and `docker-compose`](./docker) which can be used with [Travis CI](https://travis-ci.org/) (e.g. [here](https://travis-ci.org/LoyaltyNZ/alchemy-framework))
2. [Vagrant with CoreOS](./vagrant) for local testing
3. An [Amazon Web Services Cloud Formation template](./cloud_formation) using an Elastic Load Balancer, Auto Scaling Groups and CoreOS for production and other cloud environments

Alchemy uses the [RabbitMQ](https://www.rabbitmq.com/) message broker to pass requests between services. The Ruby implementation also includes a Rack server so people can write services in frameworks like Rails or Sinatra.

**Comment by jerodsanto** [comment]
@grahamjenson we're including Alchemy in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
