### ISSUE TITLE
Eventchain — Event Sourcing / CQRS framework for Java

### ISSUE THREAD

**Issue by yrashk** [thechangelog/ping#415]
http://eventsourcing.com

Event sourcing framework for Java. Instead of mutating data in a database, it stores all changes (events) and causes (commands). This facilitates rapid application development and evolution by mitigating the inability to predict how future needs will drive data shape requirements as all the causal information is persisted. It also provides a foundation for deep analytics, data recovery, audit trails and other associated benefits.
Key features:

- Clean, succinct Command/Event model
- Compact data storage layout
- Using Disruptor for fast message processing
- Using CQengine for fast indexing and querying
- In-memory and on-disk (more indices coming soon) storage
- Causality-preserving Hybrid Logical Clocks
- Locking synchronization primitive

**Comment by jerodsanto** [comment]
@yrashk :green_heart: we'll put this in Saturday's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by yrashk** [comment]
Jerod,

Great, thanks! The project was recently renamed to Eventsourcing for Java,
can you mention it under the new name? Thanks!

On Wednesday, 20 April 2016, Jerod Santo <notifications@github.com> wrote:

> Closed #415 <https://github.com/thechangelog/ping/issues/415>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/415#event-634687599>
>


-- 
Y.

**Comment by jerodsanto** [comment]
@yrashk yup, I picked up on that 😀
