### ISSUE TITLE
Podcast Suggestion: Crate.IO

### ISSUE THREAD

**Issue by deanbrophy** [thechangelog/ping#416]
Crate.io is very interesting. Taken from their own site:

> Crate is an open source, highly scalable, shared-nothing distributed SQL database. Crate offers the scalability and performance of a modern No-SQL database with the power of Standard SQL. Crate’s distributed SQL query engine lets you use the same syntax that already exists in your applications or integrations, and have queries seamlessly executed across the crate cluster, including any aggregations, if needed.

Tack on that it supports Lucene full-text searching, and I would love to hear these guys on your podcast.

@crate on git. @crateio on Twitter. http://crate.io on the web.

**Comment by jerodsanto** [comment]
@deanbrophy thanks for submitting this! We're shying away from datastore shows for the time being (unless something totally knocks our socks off). We've done a bunch of them and it gets harder and harder to tease out the unique and interesting bits of each one.

Please keep an eye on this project and ping us again if big news comes out of their camp. We'll revisit at that point. Thanks again! 🍻
