### ISSUE TITLE
Design for Open Source

### ISSUE THREAD

**Issue by dperrera** [thechangelog/ping#417]
Hey Changelog,

I wrote [an article](https://perrera.com/blog/design-for-open-source) about an idea that I have for getting more design in OSS. I'd love to hear your thoughts and get some feedback from the community.

Dan

**Comment by jerodsanto** [comment]
@dperrera interesting article. We're going to include this in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:

_(I actually prefer your Rails logo over the other, so you win my bake-off! :wink:)_

**Comment by dperrera** [comment]
🎉 Thanks @jerodsanto. Hopefully something good will come of it!
