### ISSUE TITLE
easyLambda: parallel data flow with modern c++ and MPI.

### ISSUE THREAD

**Issue by haptork** [thechangelog/ping#418]
[easyLambda](https://github.com/haptork/easyLambda) started with the need for a standard way to process data with C++. The design goals are composability, easy interface, decoupling IO, data-format and parallel code from algorithm logic, less boilerplate code, accessible to anyone who knows C. easyLambda achieves these goals with type-safe data-flow pipeline, map/reduce like operations, MPI parallelism; presented with an easy but powerful ExpressionBuilder interface made possible by use of modern C++ features.

**Comment by jerodsanto** [comment]
@haptork we're including easyLambda in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it Saturday morning. :beers:
