### ISSUE TITLE
Just published a library that implements a bunch of Haskell functions in JavaScript ES2015

### ISSUE THREAD

**Issue by sjsyrek** [thechangelog/ping#419]
Hello! I just published to GitHub and npm a JavaScript library that implements a large number of Haskell functions in ES2015. Please have a look and consider adding it to your weekly newsletter, which I have been enjoying and benefiting from, myself, for some time now. Thanks for that and your great podcast. You really inspired me to put this together, even though I'm just a novice and not even a professional programmer (not yet?). 

https://github.com/sjsyrek/maryamyriameliamurphies.js
https://www.npmjs.com/package/maryamyriameliamurphies

**Comment by jerodsanto** [comment]
@sjsyrek this is cool stuff! We'll link it up in the next newsletter.

Also, I'm quite encouraged to hear that you've benefited from what we do around here. Thanks for sharing that! 🍻
