### ISSUE TITLE
When your Swift code breaks the compiler

### ISSUE THREAD

**Issue by zzarcon** [thechangelog/ping#420]
Hi guys, I just write here to let you know about this article

**When your Swift code breaks the compiler**

https://medium.com/@devlucky/when-your-swift-code-breaks-the-compiler-d2639e1b2bc8

Thanks a lot!

**Comment by jerodsanto** [comment]
@zzarcon thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) 🍻  💚

**Comment by zzarcon** [comment]
@jerodsanto wow, amazing! 💪 🚀
