### ISSUE TITLE
Jotted - jsfiddle for self-hosted demos

### ISSUE THREAD

**Issue by ghinda** [thechangelog/ping#421]
Hi,

[Jotted](https://ghinda.net/jotted/) is a widget for showcasing self-hosted HTML, CSS and JavaScript snippets, with editable source. It's like JSFiddle or JS Bin for self-hosted demos.

It's mostly JavaScript, with ES2015, and has a very flexible plugin system. There are a bunch of plugins bundled with it for integrations with editors (Ace, CodeMirror) or with preprocessors (ES6, CoffeeScript, Less, Stylus, Markdown).

There's a demo for each plugin:
https://ghinda.net/jotted/#demos.

Would it be possible to add it to your weekly newsletter? I'd love some feedback or contributors.

Thanks!

**Comment by jerodsanto** [comment]
@ghinda nice work! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Jotted up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by ghinda** [comment]
Thanks guys! :beers:
