### ISSUE TITLE
Myrtille: an open source, native HTML4/5 Remote Desktop Protocol client

### ISSUE THREAD

**Issue by cedrozor** [thechangelog/ping#422]
Hi, I would like to announce Myrtille, my first open source project! :)

It allows to connect remote computers and applications from any browser, without any plugin, extension or configuration whatsoever.

Sources: https://github.com/cedrozor/myrtille
Video: https://www.youtube.com/watch?v=l4CL8h0KfQ8

Thanks :)

Feedback welcome!

**Comment by jerodsanto** [comment]
@cedrozor congrats on shipping your first open source project! we're including Myrtille in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
