### ISSUE TITLE
SeekMIDI, a simple graphical MIDI sequencer offering multi-channel MIDI sequencing.

### ISSUE THREAD

**Issue by oldtechaa** [thechangelog/ping#424]
I would like to announce [SeekMIDI](https://github.com/oldtechaa/SeekMIDI/), a simple graphical MIDI song editor offering multi-channel [MIDI](https://en.wikipedia.org/wiki/MIDI) editing. SeekMIDI offers a lighter-weight design than other similar MIDI sequencers, and offers a modern GTK+2 interface. Written in Perl, we use gtk2-perl and its Cairo binding, and MIDI-Perl for our MIDI handling.

Version 0.1.0 was just [released](https://github.com/oldtechaa/SeekMIDI/releases) and we invite you to come check it out.

Please email me regarding questions at [oldtechaa@gmail.com](mailto:oldtechaa@gmail.com).

**Comment by jerodsanto** [comment]
@oldtechaa we're including SeekMIDI in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it Saturday morning. :beers:
