### ISSUE TITLE
Cauditor: PHP code analyzer

### ISSUE THREAD

**Issue by matthiasmullie** [thechangelog/ping#426]
[Cauditor](https://www.cauditor.org/) distills some common software metrics from PHP projects.

There are a couple of different visualizations to make sense of those metrics:

* color-coded treemap, to see how all classes/methods in the project score (find complexity hotspots)
* trendline for average & worst metrics over the entire history (find commits introducing bad architecture)
* trendline for the different in metrics your commits make across all your projects (personal progress)

Metrics:

* Maintainability index
* Cyclomatic complexity
* Halstead intelligent content
* Instability
* Afferent coupling
* Efferent coupling

Example of analyzed project: https://www.cauditor.org/forkcms/forkcms

**Comment by jerodsanto** [comment]
@matthiasmullie cool tool! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in Saturday's issue of [Changelog Weekly](https://changelog.com/weekly/).

:beers:

**Comment by matthiasmullie** [comment]
Great, thanks!
