### ISSUE TITLE
CII "Best Practices" badge

### ISSUE THREAD

**Issue by david-a-wheeler** [thechangelog/ping#427]
Would you be interested in having a podcast episode on the "Best Practices" badge created by the Linux Foundation's Core Infrastructure Initiative (CII)?  I'm the project lead; I suggest also including Emily Ratliff, who is senior director of infrastructure security for CII.

The badge is a way for FLOSS projects to show that they follow best practices. Projects can voluntarily self-certify, at no cost, by using this web application to explain how they follow each best practice.

The website that lets you get a badge is here: https://bestpractices.coreinfrastructure.org/
Criteria are here: https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/doc/criteria.md
Badge project site: https://github.com/linuxfoundation/cii-best-practices-badge

**Comment by jerodsanto** [comment]
@david-a-wheeler I think this could make for a great show. We'd love to have you! Please email editors@changelog.com to coordinate.

**Comment by jerodsanto** [comment]
💥 https://changelog.com/215/ 💥

**Comment by david-a-wheeler** [comment]
Thanks! It was fun, and I think a lot of your listeners will enjoy it.
