### ISSUE TITLE
Sycamore: an unordered tree data structure for Ruby

### ISSUE THREAD

**Issue by marcelotto** [thechangelog/ping#428]
Hi, 

I’m very happy to share Sycamore with you, a slightly unusual tree data structure for Ruby. It’s MIT-licensed, has quite good test- and documentation-coverage. Even if it’s not for you, it might be worth checking out, since it has an interesting solution to the problem of null-values.

- <https://github.com/marcelotto/sycamore>
- <https://rubygems.org/gems/sycamore>

Looking forward to hear your thoughts.

**Comment by jerodsanto** [comment]
@marcelotto we just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Sycamore up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by marcelotto** [comment]
@jerodsanto 👍  Great to hear. Thanks a lot.
