### ISSUE TITLE
React Storybook - A Devtool for React

### ISSUE THREAD

**Issue by arunoda** [thechangelog/ping#429]
React is all about creating UI components. Usually, we need to create our UI components consider different states/data passed to them.

It's hard to create those states inside the app. Even if we do, it's hard to re-create and get feedback from others.

That's where [React Storybook](https://github.com/kadirahq/react-storybook) is going to help us.

![final](https://cloud.githubusercontent.com/assets/50838/14186892/3871f984-f79e-11e5-8c7f-8ed36e67ff92.gif)

It's an interactive visual UI component development tool, where you can create React UI components without loading the app. With that, we can easily test for different states and re-create them.

See: [Introducing React Storybook](https://voice.kadira.io/introducing-react-storybook-ec27f28de1e2#.mx5fd0fis)

**Comment by jerodsanto** [comment]
@arunoda this is super cool! I saw it made a nice splash earlier this week, well deserved for sure.

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in tomorrow's issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by arunoda** [comment]
@jerodsanto Awesome.
