### ISSUE TITLE
Interview Luca Guidi about Hanami

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#431]
From the [description](http://hanamirb.org/guides):
>Hanami is a Ruby MVC web framework comprised of many micro-libraries. It has a simple, stable API, a minimal DSL, and prioritises the use of plain objects over magical, over-complicated classes with too much responsibility.
>...
>If you’ve ever felt you’re stretching against the “Rails way”, you’ll appreciate Hanami.

Hanami was formerly known as [Lotus](http://lotusrb.org/).

**Comment by jerodsanto** [comment]
@dbohdan Ruby web frameworks aren't high on our priority list for coverage right now. Thanks for the suggestion and keep 'em coming!
