### ISSUE TITLE
Git fresh: keep your repo clean

### ISSUE THREAD

**Issue by imsky** [thechangelog/ping#432]
Git fresh helps keep local repositories up to date by automatically pruning stale/merged local and remote branches, keeping master in sync with remote, and optionally rebasing branches. It replaces laborious manual update steps with one command and has been designed to be safe and non-destructive.

https://github.com/imsky/git-fresh

**Comment by jerodsanto** [comment]
@imsky I need this so bad, hah! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by imsky** [comment]
awesome @jerodsanto :)
