### ISSUE TITLE
Bamboo, Email with a Functional Twist

### ISSUE THREAD

**Issue by paulcsmith** [thechangelog/ping#433]
We (thoughtbot) just [publicly announced Bamboo](https://robots.thoughtbot.com/announcing-bamboo-email-with-a-functional-twist), a testable, composable and adapter based email library for Elixir.

The blog post above explains what makes Bamboo special, but here are some highlights:

* **Adapter based**. so it can be used with Mandrill, Sendgrid, SMTP, or whatever else you want.
* **Deliver emails in the background**. Most of the time you don’t want or need to wait for the email to send. Bamboo makes it easy with `Mailer.deliver_later`. No external dependencies (like Redis) are required.
* **Easy to format recipients**. You can do `new_email(to: Repo.one(User))` and Bamboo can format the User struct automatically.
* **Very composable**. Emails are just a Bamboo.Email struct and can be manipulated with plain functions.
* **Easy to unit test**. Because delivery is separated from email creation, no special functions are needed, just assert against fields on the email.
* **Easy to test delivery in integration tests**. Helpers are provided to make testing easy and robust.
* **Preview sent emails during development**. Bamboo comes with a plug that can be used in your router to preview sent emails.

Due to the flexibility of Elixir, Bamboo is small and powerful. We think Elixir devs will really love it, and those outside the Elixir community will learn some new ways of handling email delivery in their chosen language.

Links

* [Announcement post](https://robots.thoughtbot.com/announcing-bamboo-email-with-a-functional-twist)
* [Bamboo repo](https://github.com/thoughtbot/bamboo)

**Comment by jerodsanto** [comment]
@paulcsmith I saw this the other day and was quite intrigued. In fact, I plan on trying out Bamboo on a Changelog project we have in the works. :fist: We'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by paulcsmith** [comment]
@jerodsanto Sounds great! Feel free to ping me or open an issue if you need any help or have feedback :)
