### ISSUE TITLE
After six months of development we launched project based on Angular 2

### ISSUE THREAD

**Issue by ryzy** [thechangelog/ping#434]
Hi,

I wrote an article where I share story behind one medium-size Angular 2 project. Would you be interested to :shipit: in The Changelog?

http://m12.io/blog/we-launched-angular-2-project

**Comment by jerodsanto** [comment]
@ryzy :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by ryzy** [comment]
Groovy, thanks!
