### ISSUE TITLE
Clojure Newbie Guide

### ISSUE THREAD

**Issue by kirang89** [thechangelog/ping#436]
I created [Clojure Newbie Guide](http://www.clojurenewbieguide.com/) with the intent to provide quick directions for a beginner to the language. Would you be interested in adding this to your next issue?

**Comment by jerodsanto** [comment]
@kirang89 cool, cool, cool. We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by jerodsanto** [comment]
@kirang89 caught a typo on your homepage. 

> A quick guide to Clojure and it's ecosystem for newbies.

You should use `its` (a possessive) instead of `it's` (a contraction of "it is"). :fist:

**Comment by kirang89** [comment]
@jerodsanto Thanks! Much appreciated. I'll fix the typo soon enough.
