### ISSUE TITLE
Interviewing a good backend developer (without sight)

### ISSUE THREAD

**Issue by omidfi** [thechangelog/ping#437]
Hello, 
Today I found the link to this blog post in one of my newsletters fron Oreilly

https://www.parhamdoustdar.com/2016/04/03/tools-of-blind-programmer

I'm speechless!

I think an interview would be very encouraging for other users and developees with physicall disabilities.

**Comment by sallar** [comment]
Not only he types and codes in English, he types and reads Persian (Farsi) too! Which is very difficult in general. I admire him.

**Comment by jerodsanto** [comment]
@omidfi @sallar I agree, this could make a great show. I contacted Parham and we are scheduling a time to record. Thanks for the idea! ✊

**Comment by sallar** [comment]
Great! Thanks @jerodsanto :)

**Comment by jerodsanto** [comment]
@omidfi @sallar this show is now live! 

https://changelog.com/206/

I think it turned out really well, thanks for the suggestion! Y'all even got a shout out on the show ✊ 

Thanks for being an important part of the Changelog community. 🍻

**Comment by omidfi** [comment]
Yes I enjoyed listenning to it yesterday, thanks for the shout out :)
