### ISSUE TITLE
Micro - a microservice toolkit

### ISSUE THREAD

**Issue by asim** [thechangelog/ping#438]
Hey. Just wanted to let you guys know about Micro, an open source microservice toolkit.

https://micro.mu
https://github.com/micro/micro
https://blog.micro.mu/2016/03/20/micro.html
https://blog.micro.mu/2016/04/18/micro-architecture.html
http://thenewstack.io/micro-wants-move-beyond-containers-go-based-microservices-framework

**Comment by jerodsanto** [comment]
@asim nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Micro up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by asim** [comment]
Thanks so much! Appreciate it 😄
