### ISSUE TITLE
Potential sponsors

### ISSUE THREAD

**Issue by ckhrysze** [thechangelog/ping#439]
In the vein of longer sponsor spots built from interviews with employees of the sponsors, I'd like to hear from one or more of the new (to me) continuous integration/deployment services. Examples that I've come across thus far:
https://codeship.com/
https://buildkite.com/
https://drone.io/
https://concourse.ci/
https://circleci.com/

**Comment by jerodsanto** [comment]
@ckhrysze thanks for this! We've added all of these to our list of potential sponsors. Maybe you'll be hearing from some of them on The Changelog soon! 🍻
