### ISSUE TITLE
Interview Andreas Stefik about Quorum (the language, not the other thing)

### ISSUE THREAD

**Issue by toolness** [thechangelog/ping#440]
**Note that this is completely unrelated to the "Quorum" project covered in #382.**

Quorum ([quorumlanguage.com](https://www.quorumlanguage.com/)) is the world's first "evidence-oriented programming language", meaning that its design is informed largely by scientific studies (usually randomized controlled trials) of programming language design.

For example, when deciding how to design looping constructs in the language, the designers consulted scientific studies on what kinds of words ("while", "for", "repeat", etc) were actually found to make looping easier to learn for beginners, without hampering the productivity of professionals.

The project is open-source and the code seems to live on [Bitbucket](https://bitbucket.org/stefika/quorum-language).

My understanding is that the project was originally started because its creators, Dr. Stefik and his wife, wanted to make a language that would be more accessible to blind people in particular, while also being easy for anyone to learn in general.

The language's history and philosophy are covered in the following ACM Computer Science Teachers Association (CSTA) article by Dr. Stefik:

http://blog.csta.acm.org/2015/10/01/accesscs10k-quorum-programming-language-and-evidence-oriented-programming/

Stefik also gave a talk about the language at last year's Strange Loop conference:

https://www.youtube.com/watch?v=uEFrE6cgVNY

I think interviewing Dr. Stefik could make for an interesting Changelog episode because:

* It would be great to have an episode highlighting the experience of disabled people (specifically blind people) in the programming world.
* Regardless of the success of the Quorum language in particular, its reliance on the scientific method is quite interesting, and something I wish that more languages would take into consideration. So disseminating the language's *approach* through the podcast could be useful to the open-source community, regardless of how successful the project itself is.
* Based purely on his Strange Loop talk, Dr. Stefik seems like an amiable and articulate person who would likely make for an enlightening and entertaining guest on the show.

**Comment by jerodsanto** [comment]
@toolness we'll consider this, thanks for the detailed synopsis!

**Comment by toolness** [comment]
Oh man, I just noticed you did [The Advantages of Being a Blind Programmer with Parham Doustdar ](https://changelog.com/206/)!! That's awesome, thanks for doing that :)

**Comment by jerodsanto** [comment]
@toolness yes we did, glad you enjoyed it! Please do share it with whomever you think it would interest.

By the way, I noticed you work at 18F. We've been interested in doing a show with someone from 18F for awhile now (https://github.com/thechangelog/ping/issues/413). Who do you think would be the _best_ person to interview from your team?

**Comment by toolness** [comment]
That would be awesome @jerodsanto!  I just told our outreach folks about it and they've pinged you back at https://github.com/thechangelog/ping/issues/413#issuecomment-227888051, so you should be good to go.  Let me know if you need anything else!

**Comment by jerodsanto** [comment]
@toolness thanks again for this suggestion! We're going to pass on this one, but I tried to get the 18F show rolling and haven't heard back from Hillary. Can you help us out in that area? 🍻

**Comment by toolness** [comment]
No worries Jerod, thanks for considering it!  I'll ping Hillary and get back to you.
