### ISSUE TITLE
An Elixir and Phoenix Docker image

### ISSUE THREAD

**Issue by marcelocg** [thechangelog/ping#441]
Hi!

This is just to Ping you about an Elixir and Phoenix Docker container image I've been maintaining.

It's available at https://hub.docker.com/r/marcelocg/phoenix/ and has been downloaded 1,800+ times.

It also features automated build via Github hook. The repo for the Dockerfile is available at https://github.com/marcelocg/phoenix-docker

That's it. Thanks for the show. I'm a long time fan!

**Comment by jerodsanto** [comment]
@marcelocg :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
