### ISSUE TITLE
RangeTouch: A super tiny library to make <input type='range'> sliders work better on touch devices

### ISSUE THREAD

**Issue by SamPotts** [thechangelog/ping#442]
https://rangetouch.com

While building Plyr (plyr.io) which you featured previously, I noticed how fiddly the use of <input type="range"> elements is on touch devices. Having a search around I couldn't find a suitable fix and so created RangeTouch, a small library that improves support on touch devices. 

Let me know what you think.

**Comment by jerodsanto** [comment]
@SamPotts nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link RangeTouch up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by SamPotts** [comment]
Cheers 👍
