### ISSUE TITLE
Medium Draft - A rich text editor built on draft-js with focus on keyboard shortcuts.

### ISSUE THREAD

**Issue by brijeshb42** [thechangelog/ping#443]
## [medium-draft](https://github.com/brijeshb42/medium-draft)

A medium like rich text editor built using [draft-js](https://facebook.github.io/draft-js/) with an emphasis on eliminating mouse usage by adding relevant keyboard shortcuts.

**Comment by jerodsanto** [comment]
@brijeshb42 thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by brijeshb42** [comment]
Thanks.
