### ISSUE TITLE
[Podcast suggestion] Interview Reginald Braithwaite

### ISSUE THREAD

**Issue by riddla** [thechangelog/ping#444]
As I was listening to your (excellent) [episode 196: TiddlyWiki with Jeremy Ruston](http://5by5.tv/changelog/196), I was reminded of another eloquent and experienced programer (and speaker): [Reginald Braithwaite](http://raganwald.com), e.g. @raganwald.
I found out about him via JavaScript Jabber, they featured his [book(s)](https://leanpub.com/javascript-allonge) and [himself](https://devchat.tv/js-jabber/070-jsj-book-club-javascript-allonge-with-reginald-braithwaite) various times.

I would probably listen to any topic you would talk about with him and I assume your other regular listeners would also like him.

**Comment by jerodsanto** [comment]
@riddla we're big fans and would love to have him on the show. What say you, @raganwald? Are you interested and willing to join us on The Changelog sometime soon?

**Comment by jerodsanto** [comment]
@raganwald please email editors@changelog.com to coordinate joining us on the show! Closing this to keep things tidy. 🏡
