### ISSUE TITLE
react-indie - An independent react component that holds all its logic inside.

### ISSUE THREAD

**Issue by gavriguy** [thechangelog/ping#445]
Hi just wanted to let you know of a new project I'm working on:
https://github.com/gavriguy/react-indie
https://medium.com/@gavriguy/introducing-react-indie-48901f81feb3#.t5sav5kv4

Thanks

**Comment by jerodsanto** [comment]
@gavriguy :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
