### ISSUE TITLE
Entity Framework Service Builder

### ISSUE THREAD

**Issue by JKHeadley** [thechangelog/ping#447]
A nuget package that builds a service around an existing Entity Framework code first model: https://github.com/JKHeadley/ServiceBuilder

This service builder is not only a tool to get a fully functional CRUD service up and running quickly, it also implements and promotes good coding practices emphasizing modularity and separation of concerns. Specifically, the following patters are represented:

- Dependency injection and Inversion of Control (IoC) via Castle Windsor: http://www.castleproject.org/projects/windsor/
- Repository pattern: https://msdn.microsoft.com/en-us/library/ff649690.aspx
- DTO pattern with built in mapping using AutoMapper: https://en.wikipedia.org/wiki/Data_transfer_object and http://automapper.org/
- Helper methods to encapsulate business logic resulting in a lightweight service class
- Decorator pattern implemented via a logging decorator that extends the repository pattern: http://www.dofactory.com/net/decorator-design-pattern

**Comment by jerodsanto** [comment]
@JKHeadley thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
