### ISSUE TITLE
A Google AMP compatible static site generator/blogging system built with Gulp and Handlebars

### ISSUE THREAD

**Issue by adxmb** [thechangelog/ping#448]
Hey Y'all! Long time fan and past contributor here just wanted to let you know about the latest project I've been working on - it's called AMP'd and it's a static site generator/blogging system meant to be a JS based alternative to other options like Jekyll (Ruby) for managing a Google AMP compatible site. It's main selling points are that it's dead simple to set up and deploy, features robust templating via Handlebars, YAML front matter on blog posts and auto sitemap generation out of the box. Keep up the great work!

https://github.com/adxmb/ampd

Cheers!

- Adam

Edit: updated url

**Comment by jerodsanto** [comment]
@adxmb cool stuff! We'll link AMP'd up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by adxmb** [comment]
Sick! Thanks everytone. Keep up the great work!
