### ISSUE TITLE
Pakyow 0.11 Walkthrough

### ISSUE THREAD

**Issue by rjclardy** [thechangelog/ping#449]
We released Pakyow 0.11 today, which is planned to be the last major release before 1.0! It contains several cool features, all of which are detailed in this [handy walkthrough](https://www.youtube.com/watch?v=mlrDqw7oMAw) from @bryanp.

We've also improved the documentation and added a new section to explain the conceptual details of the framework: https://pakyow.org/docs/overview.

Release announcement: https://pakyow.org/blog/2016/04/22/zero-eleven
Repo: https://github.com/pakyow/pakyow

**Comment by jerodsanto** [comment]
@rjclardy congrats on the release! Would you mind resubmitting at 1.0? I think our coverage would be more useful at that point.

**Comment by rjclardy** [comment]
Will do, thanks!
