### ISSUE TITLE
Suggestion: GitLab projects - Changelog Nightly

### ISSUE THREAD

**Issue by kujua** [thechangelog/ping#450]
Hi, would it be possible to do something similar to Changelog Nightly (GitHub), but with projects from GitLab?
I see more projects using GitLab, so it would be interesting to see the climbers there as well. Not sure if their API supports this, though.
Thanks for the Changelog Nightly emails!

**Comment by jerodsanto** [comment]
@kujua interesting idea! Moving to https://github.com/thechangelog/nightly/issues/21
