### ISSUE TITLE
Episode idea - the harassment of women in OSS

### ISSUE THREAD

**Issue by bordeltabernacle** [thechangelog/ping#451]
This is an ongoing issue that still is not talked about enough, and in light of recent events involving docker ( https://twitter.com/roryahunter/status/723596890508529666 ) a changelog episode would go some way to giving this the attention and, hopefully, action it deserves. Also, this should be a female guest only episode, not a panel of privileged white men discussing the issue.

**Comment by bordeltabernacle** [comment]
http://uk.businessinsider.com/death-rape-threats-for-docker-engineer-2016-4?r=US&IR=T

**Comment by jerodsanto** [comment]
@bordeltabernacle thanks for bringing this to our attention. We had already contacted Jessie about doing a show on containers and will see if she has any interest in a show on this.
