### ISSUE TITLE
A story on burnout "My personal burnout - Lessons Learned"

### ISSUE THREAD

**Issue by pavsaund** [thechangelog/ping#452]
Hi there, not sure if this is a fit for Changelog. I've written [a story on my burnout](http://codingwithempathy.com/2016/04/12/my-personal-burnout-lessons-learned/) with some of my learnings.

**Comment by jerodsanto** [comment]
@pavsaund this is absolutely a fit for us. Thanks for writing about this, I'm sure it wasn't easy to hit the "publish" button on that post. 

We're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
