### ISSUE TITLE
gvar - display, set, or remove global variables.

### ISSUE THREAD

**Issue by arturoherrero** [thechangelog/ping#453]
Here's my latest pet project that you can include in the next issue.

**gvar** is a pure Bash key-value store where each user has a different collection of data. The records are stored in the user's home directory: https://github.com/arturoherrero/gvar

**Comment by jerodsanto** [comment]
@arturoherrero nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link gvar up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: on Saturday. :beers:

**Comment by arturoherrero** [comment]
Cool!
