### ISSUE TITLE
New project – Mailtrain, self hosted newsletter application

### ISSUE THREAD

**Issue by andris9** [thechangelog/ping#454]
I'd like to advertise my new open source (GPLv3 licensed) project called [Mailtrain](https://mailtrain.org). 

It's a self-hosted newsletter application that can use any SMTP provider (SendGrid, SparkPost, AWS SES, mailgun etc.) to handle the actual delivery. It's still kind of in an early phase but all the basics (list management, subscription forms, one-click unsubscribe, list segmentation, bounces, clicks and opens tracking etc.) is already there and thus Mailtrain is already being used by some early adopters.

Mailtrain is built on Node.js (requires Node v5+) and MySQL (requires v5.5 or MariaDB). Mail handling is done using [Nodemailer](http://nodemailer.com) which is also one of my projects.

**Comment by jerodsanto** [comment]
@andris9 nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Mailtrain up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by andris9** [comment]
Awesome, thanks!
