### ISSUE TITLE
Tic-Tac-Toe.js: redux pattern in plain javascript

### ISSUE THREAD

**Issue by ramonvictor** [thechangelog/ping#455]
Redux without library? This article explains the approach that made this possible.
Article: https://medium.com/@ramonvictor/tic-tac-toe-js-redux-pattern-in-plain-javascript-fffe37f7c47a

[Github.io page](http://ramonvictor.github.io/tic-tac-toe-js/) | [Game demo](https://rocky-ocean-52527.herokuapp.com/) | [Repository](https://github.com/ramonvictor/tic-tac-toe-js).

**Comment by jerodsanto** [comment]
@ramonvictor :blue_heart: :yellow_heart: :green_heart: we'll mention this [on twitter!](https://twitter.com/changelog)  :fist: :beers:

**Comment by ramonvictor** [comment]
@jerodsanto I'm glad you liked it. Thanks in advance! :D
