### ISSUE TITLE
New project: scrape-it

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#456]
scrape-it: A Node.js scraper for humans. 

:octocat: https://github.com/IonicaBizau/scrape-it

**Comment by jerodsanto** [comment]
nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by IonicaBizau** [comment]
Great! :+1: :cake: Thanks!
