### ISSUE TITLE
Vital - A minimally invasive CSS framework for modern web applications (8kb)

### ISSUE THREAD

**Issue by brupm** [thechangelog/ping#457]
Hi Adam,

A colleague of mine, Body Taing built a minimalist CSS framework called [Vital](http://doximity.github.io/vital/) - Here are some of the reasons why we decided to build and use [Vital](https://engineering.doximity.com/articles/vital-css-framework).

<img width="278" alt="screenshot 2016-05-03 08 59 22" src="https://cloud.githubusercontent.com/assets/336/14989583/610a7122-110d-11e6-91a1-a920ed693b23.png">

**Comment by brupm** [comment]
@adamstac

**Comment by jerodsanto** [comment]
@brupm :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
