### ISSUE TITLE
When: a desktop scheduler for Gnome/GTK Linux environments

### ISSUE THREAD

**Issue by almostearthling** [thechangelog/ping#458]
Hi,

[here](https://github.com/almostearthling/when-command) is the code for **When**, a simple scheduler that allows to plan actions not only on a time basis but also in reaction to tests and events. Besides the raw code you can find:

* packaged [releases](https://github.com/almostearthling/when-command/releases)
* an Ubuntu (and derivatives) [PPA](https://launchpad.net/~franzg/+archive/ubuntu/when-command) for easy installation and updates
* fairly comprehensive [documentation](http://when-documentation.readthedocs.io/en/latest/) (also available separately for [contributors](http://contributing-to-when.readthedocs.io/en/latest/)) that includes tutorials

as well as other materials such as a test suite and, by "popular" request, an [alternate interface](https://github.com/almostearthling/when-wizard). Everything is released under the BSD License. The applet looks quite stable at the moment, and I'd like to get some feedback to decide whether or not to move to 1.0 soon.

Thank you,

F.

**Comment by jerodsanto** [comment]
@almostearthling :green_heart: we'll put this in Saturday's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by almostearthling** [comment]
Thank you!
