### ISSUE TITLE
New project – Lazy Progressive Enhancement

### ISSUE THREAD

**Issue by tvler** [thechangelog/ping#459]
I've been working on a project that I'm really excited about, and I just wanted to share it with the changelog audience.

Lazy Progressive Enhancement – [Project website](http://tylerdeitz.co/lazy-progressive-enhancement/), [Github repo](https://github.com/tvler/lazy-progressive-enhancement)
A lazy image loader designed to enforce progressive enhancement and valid HTML.

It's the first lazy image loader I can find that is structurally designed to fall back to a standard loading behavior for users without javascript, using the `noscript` element to either declaratively store a lazy image, or immediately render it on page load. This means that developers don't have to include additional fallbacks to gracefully degrade images, because the markup itself provides this. 

I built this because I wanted to use a lazy image library that would actually pass an HTML5 validator. Omitting an image's src attribute, like most lazy loaders do to defer loading, is [invalid](https://www.w3.org/TR/html5/embedded-content-0.html#attr-img-src). Getting around that by setting the src to a byte-sized placeholder adds a lot of markup complexity and is pretty ugly. Either way, the standard lazy loading methods available now completely fail for users without javascript.

**Comment by jerodsanto** [comment]
@tvler nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
