### ISSUE TITLE
Open Source in Action

### ISSUE THREAD

**Issue by OrKoN** [thechangelog/ping#460]
I have started collecting GIF images showcasing various open source projects: http://open-source-in-action.net/ 

Anyone can submit new GIFs and vote on GIFs to determine the best ones.

**Comment by jerodsanto** [comment]
@OrKoN nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by OrKoN** [comment]
Thanks!
