### ISSUE TITLE
Easy to use 2D Graphics API

### ISSUE THREAD

**Issue by livingcreative** [thechangelog/ping#461]
I would like to present [kcanvas](https://github.com/livingcreative/kcanvas) project. This is easy to use 2D graphics API in C++. Currently Direct2D backend for Windows released, and I have OS X and Linux backends in development. There are some [useage examples](https://github.com/livingcreative/kcanvas/wiki/Examples) in the wiki.

Please email me regarding questions at dnkreative@gmail.com

**Comment by jerodsanto** [comment]
@livingcreative we're including kcanvas in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it Saturday morning. :beers:

**Comment by livingcreative** [comment]
Great, thanks!
