### ISSUE TITLE
Let’s Make Open Source More Inclusive

### ISSUE THREAD

**Issue by jdaudier** [thechangelog/ping#462]
Hi Changelog team:

I wrote a blog post about how to make OSS more inclusive. Could this be included in your newsletter? I would love to get some feedback from readers.

https://medium.com/@jdaudier/lets-make-open-source-more-inclusive-5129837b505d#.wgjs6bjdz

Thanks!

Joanne

**Comment by jerodsanto** [comment]
@jdaudier :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by jdaudier** [comment]
Thanks @jerodsanto!
