### ISSUE TITLE
mklicense. A CLI tool for generating Licenses. Easily.

### ISSUE THREAD

**Issue by cezaraugusto** [thechangelog/ping#464]
Hey guys, License stuff is becoming a hot topic again. So I built a License generator that is based on http://choosealicense.com, which is safe and easy. This way you ensure your project has a license and stop the boring work of copy/paste stuff.

https://github.com/cezaraugusto/mklicense

Here's the CLI:

![mklicense](https://cloud.githubusercontent.com/assets/4672033/15228094/c8f97c7e-1860-11e6-9d1b-58e7dbad2ce4.gif)

**Comment by jerodsanto** [comment]
@cezaraugusto this is really cool. The thing that's great about choosealicense.com is that it also helps you make the decision on which license to choose. It'd be rad if you could bring a simplified version of that to your tool.

You could even make it work like an old scool text-based game (or a choose-your-own-adventure book).

That being said, we'll happily promote mklicense as-is if you consider it done. Let us know!

**Comment by junland** [comment]
Well this is going on reddit....

**Comment by jerodsanto** [comment]
Like I said, it's definitely valuable as-is. We'll go ahead and put this in tomorrow's [newsletter](https://changelog.com/weekly), tweet it out, and you can consider that feature for a 2.0 (or some other version release).

**Comment by cezaraugusto** [comment]
Hi Jerod, thanks for your insight and support. It would be really cool and I will definitely consider for the next version.
@junland, thanks for pointing! I'm surprised. We're actually on /r/coolgithubprojects/ if anyone is interested.

**Comment by jerodsanto** [comment]
@cezaraugusto the [tweet](https://twitter.com/changelog/status/731123405773275136) seems to indicate that people are interested in the tool. We'll see how it performs in Weekly! 💥

**Comment by adamstac** [comment]
👏
