### ISSUE TITLE
Project: Dockerpresso

### ISSUE THREAD

**Issue by michaloo** [thechangelog/ping#465]
Hey :)
I wanted to share my new project based on Docker and WP-CLI for rapid Wordpress theme and plugin development. There is a blog post about it:

https://medium.com/@michaloo/express-wordpress-theme-and-plugin-development-environment-e077d52535e0

And the project page:
https://github.com/michaloo/dockerpresso

**Comment by jerodsanto** [comment]
@michaloo nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Dockerpresso up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by michaloo** [comment]
Many thanks for your support :)
