### ISSUE TITLE
Scripts to build your own IPsec/L2TP VPN server

### ISSUE THREAD

**Issue by hwdsl2** [thechangelog/ping#466]
Scripts to build your own IPsec/L2TP VPN server on Ubuntu LTS, Debian 8 and CentOS 6 & 7. Fully automated "one-click" setup with no user input needed. For the full list of features please see README.

https://github.com/hwdsl2/setup-ipsec-vpn

**Comment by jerodsanto** [comment]
@hwdsl2 thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by hwdsl2** [comment]
Great! Thank you @jerodsanto !
