### ISSUE TITLE
klyng : a message-passing distributed computing framework for node.js

### ISSUE THREAD

**Issue by Mostafa-Samir** [thechangelog/ping#468]
Here's the project on github: https://github.com/Mostafa-Samir/klyng with All the documentation and tutorials.

Thanks.

**Comment by jerodsanto** [comment]
@Mostafa-Samir :green_heart: we'll put this in Saturday's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by Mostafa-Samir** [comment]
Cool! Thanks :+1:
