### ISSUE TITLE
How to integrate React.js, Node.js app with Xero accounting (source + live demo)

### ISSUE THREAD

**Issue by romanmandryk** [thechangelog/ping#469]
Hi,
I have recently written a blog post about building a web application with React.js, Node.js and Material UI, which also demonstrates integration capabilities with Xero Accounting software. Includes [full source on github](https://github.com/node-vision/node-react-xero-app) and [live demo](http://reactxeroapp.nodevision.com.au/).

I think Changelog readers would appreciate a well written app which goes much more beyond basic TODO app (complex UI, integrations, login flow...)

[https://nodevision.com.au/blog/post/how-to-integrate-nodejsreact-app-with-xero](https://nodevision.com.au/blog/post/how-to-integrate-nodejsreact-app-with-xero)

( also mentioned in Node Weekly - http://nodeweekly.com/issues/137 )

Thanks,
Roman

**Comment by jerodsanto** [comment]
@romanmandryk :green_heart: we'll put this in Saturday's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by romanmandryk** [comment]
Great news :-)
Thanks Jerod.
