### ISSUE TITLE
Atom Packages Directory

### ISSUE THREAD

**Issue by bastilian** [thechangelog/ping#470]
Hej, The Changelog!

I started a site that pulls all packages from https://atom.io/packages and categorises them using their keywords.

It is a start and and has already 1615 packages in categories. 
A few more improvements and it should also encourage and make it easy for users to add keywords to packages like this one: https://github.com/pzavolinsky/atom-language-elmx/pull/1, which in turn makes the directory itself better.

All the best from Vienna!

**Comment by jerodsanto** [comment]
@bastilian thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by bastilian** [comment]
@jerodsanto Awesome! Thank you! ❤️
