### ISSUE TITLE
embedded-scripting-languages

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#471]
*(Audience murmurs.)*

![Cinema](https://cloud.githubusercontent.com/assets/3179832/15330602/49aa37c4-1c66-11e6-9002-ac339bd2b64f.jpg)

*(Lights fade. The murmur quiets.)*

...

*(Voiceover starts.)*

...From the developer who brought you

## [Compilers targeting C](https://github.com/dbohdan/compilers-targeting-c)

and the recently trending

## [Structured text tools](https://github.com/dbohdan/structured-text-tools)

comes a new GitHub list

the likes of which cannot be found in the first ten pages of Google search results...

## [Embedded scripting languages!](https://github.com/dbohdan/embedded-scripting-languages)

*(Audience goes "wooOAaaa.")*

Available today at a GitHub near you!

&nbsp;

And now, our feature presentation...

&nbsp;

<hr>
P.S.: Thanks for featuring [structured-text-tools](https://github.com/dbohdan/structured-text-tools) in the latest issue!

**Comment by jerodsanto** [comment]
@dbohdan zomg probably our best ping of all time 👏

**Comment by adamstac** [comment]
Yup, I dug this issue too. Very cool.

**Comment by dbohdan** [comment]
@jerodsanto @adamstac Thanks, you guys.

**Comment by jerodsanto** [comment]
@dbohdan thanks for the chuckle. We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in this week's issue of [Changelog Weekly](https://changelog.com/weekly/). 🍻
