### ISSUE TITLE
Accessibility Checker for CKEditor now under Open Source GPL license.

### ISSUE THREAD

**Issue by wojtekidd** [thechangelog/ping#472]
Hi

To celebrate Global Accessibility Awareness Day, the Accessibility Checker for CKEditor is now available for everyone under an Open Source GPL license.

Just wanted to let you know. More at: http://ckeditor.com/blog/Accessibility-Checker-Goes-OS

**Comment by jerodsanto** [comment]
@wojtekidd thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
