### ISSUE TITLE
Scrawler : php framework for innovative developers

### ISSUE THREAD

**Issue by physcocode** [thechangelog/ping#473]
Project page : https://www.github.com/scrawler-php/scrawler
Docs : http://docs.scrawler.xyz

Details : Scrawler is made keeping in mind simplicity and power , it uses the concept of pool class and dependency Injection . It is build for new developers to start building innovative site . Scrawler does not only target old developer using powerful tools but our moto is to attract newbie developer into this awesome world of web development

**Comment by jerodsanto** [comment]
@physcocode thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
