### ISSUE TITLE
Fibratus - a tool for exploration and tracing of the Windows kernel

### ISSUE THREAD

**Issue by rabbitstack** [thechangelog/ping#474]
Project repo: https://github.com/rabbitstack/fibratus

Description:

Fibratus is a tool which is able to capture the most of the Windows kernel activity - process/thread creation and termination, file system I/O, registry, network activity, DLL loading/unloading and much more. Fibratus has a very simple CLI which encapsulates the machinery to start the kernel event stream collector, set kernel event filters or run the lightweight Python modules called filaments. You can use filaments to extend Fibratus with your own arsenal of tools.

**Comment by jerodsanto** [comment]
@rabbitstack we're including Fibratus in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it Saturday morning. :beers:

**Comment by rabbitstack** [comment]
*Yay*, nice to here that. Thank you :D. Kind regards from Spain
