### ISSUE TITLE
[Podcast Suggestion] Peter Hedenskog of SiteSpeed.io 

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#475]
Peter Hedenskog (@soulgalore) is an Open Source developer from Stockholm, Sweden. He has been working for the Wikimedia Foundation as a Software Engineer for the past 10 months. He also runs Stockholm Web Performance Group is Stockholm's largest web performance Meetup group. The group runs 5-6 meetups per year, where they invite speakers to talk about web performance. 

His project Sitespeed.io is an open source tool (Apache License Version 2.0) that helps you analyze your website speed and performance based on performance best practices and timing metrics. It collects data from multiple pages on your website, analyze them using the rules and output the result as HTML or send the metrics to Graphite.

I think he would be a great interview. I would love to hear what happens behind the scenes at Wikimedia ;)

**Comment by jerodsanto** [comment]
@jdorfman 👌 good suggestion!

@soulgalore are you interested in coming on the show?

**Comment by soulgalore** [comment]
@jerodsanto that would be awesome :) If we talk about sitespeed.io I would love to also include @tobli for that part, we built the latest versions together.

**Comment by jerodsanto** [comment]
@soulgalore we prefer having just one guest on the show, if at all possible. Would an opportunity to give him a shout out suffice? Please email editors@changelog.com and we'll iron out the details!

**Comment by jerodsanto** [comment]
This show is now live! 🎉 

https://changelog.com/212/

Thanks for the suggestion, @jdorfman! Peter was a great guest 🍻

**Comment by jdorfman** [comment]
Great show
