### ISSUE TITLE
A journey though the multi-year challanges of maintaining a popular JavaScript library

### ISSUE THREAD

**Issue by rnicholus** [thechangelog/ping#477]
I wrote [an article on Medium](https://medium.com/@RayNicholus/disrupting-open-source-the-story-of-fine-uploader-80160eb557d9#.7p1cwkkdq) last week that covered my experiences working with a specific JavaScript library that recently moved back to a FOSS license. I feel that these experiences led to a number of realizations about open source and has helped me evolve significantly as a developer. I'm thinking that perhaps others can benefit from this knowledge as well. If you find it interesting and would like me to further contribute some of my experiences in some way (or my take on the FOSS landscape in general) please do let me know.

**Comment by jerodsanto** [comment]
@rnicholus very cool story, thanks for sharing! :blue_heart: :yellow_heart: :green_heart: we'll mention this [on twitter!](https://twitter.com/changelog)  :fist: :beers:
