### ISSUE TITLE
Calm: REST API extension for Tornado

### ISSUE THREAD

**Issue by n9code** [thechangelog/ping#478]
# Calm

**GitHub Repo**: https://github.com/n9code/calm
**Website (In Progress)**: http://calm.n9co.de
**Gitter Chat Room**: https://gitter.im/n9code/calm

Any kinds of contributions are welcome!

## Description

Calm is an extension for [Tornado](http://www.tornadoweb.org/en/stable/) to easily define and build RESTful APIs. It provides decorators and tools to eliminate routine tasks while defining you REST API handlers, e.g. automatic parsing of request arguments into specified types. See project [README](https://github.com/n9code/calm/blob/master/README.md) for more information and examples.

**Comment by jerodsanto** [comment]
@n9code cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
