### ISSUE TITLE
Interview Tarus Balog of OpenNMS

### ISSUE THREAD

**Issue by unicolet** [thechangelog/ping#479]
I'd like you to interview Tarus Balog of the [OpenNMS](http://www.opennms.org/) project. He has been running a successful open source business for well over a decade (he can be more specific ;-)) and can give a great perspective on what it means and takes to run one.

He is @sortova here on github and blogs at http://www.adventuresinoss.com/.

**Comment by jerodsanto** [comment]
This one never quite made it over the interest hump @unicolet, sorry!

We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this are other guests/topics you're interested in! 💚
