### ISSUE TITLE
BounCA - Personal SSL / Certificate Authority Key management tool

### ISSUE THREAD

**Issue by bjarnoldus** [thechangelog/ping#480]
Project page : https://www.github.com/repleo/bounca
Docs : https://www.bounca.org

Details: BounCA is a tool to create your personal certificate authority and sign/revoke your own keys.
The main purpose of BounCA is to enable the power of a personal trust chain and encryption to people who don't want to dig into the complex parameters of OpenSSL. A personal certificate authority provides the following use cases and advantages:
Use cases:

- Trusted encrypted communication with your peers (man-in-the-middle attack prevention)
- Secure your internal REST micro-services and internal API's
- Client-certificate based login for web services, web applications and OpenVPN connections
- Secure access to your private cloud services with your own HTTPS scheme
- Secure your Internet of Things (IoT) network with your certificates and provision them via the BounCA 

Advantages:
- No single point of failure: Decoupled and decentralized authorization management
- You are in control of your complete trust chain: Spoofing nearly impossible as no third party is involved
- Rocket fast authentication: SSL off-loading can be performed by your webservers

**Comment by jerodsanto** [comment]
@bjarnoldus cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
