### ISSUE TITLE
react-update-helper - Precise React re-renders with debug and immutable support

### ISSUE THREAD

**Issue by mkautzmann** [thechangelog/ping#481]
Hey changelog!

I'd like to suggest the simple react-based lib: [react-update-helper](https://github.com/mkautzmann/react-update-helper). 

It allows you to debug component updates in the console and improves performance by avoiding useless re-renders. It's compatible with [immutable](https://facebook.github.io/immutable-js/) and [debug](https://github.com/visionmedia/debug).

**Comment by jerodsanto** [comment]
@mkautzmann :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
