### ISSUE TITLE
EasyDeviceInfo - Android library to get device information in a super easy way.

### ISSUE THREAD

**Issue by nisrulz** [thechangelog/ping#482]
Hey. Just wanted to let you guys know about EasyDeviceInfo, an open source android library to get device information in a super easy way.

The library is built for simplicity and approachability. It not only eliminates most boilerplate code for dealing with device information, but also provides an easy and simple API to retrieve them.

https://github.com/nisrulz/easydeviceinfo
http://nisrulz.github.io/easydeviceinfo
https://android-arsenal.com/details/1/3562
https://github.com/snowdream/awesome-android#utility

**Comment by jerodsanto** [comment]
@nisrulz thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
