### ISSUE TITLE
Sensey - Android library which makes detecting gestures a breeze.

### ISSUE THREAD

**Issue by nisrulz** [thechangelog/ping#483]
Hey. Just wanted to let you guys know about Sensey, an open source android library which makes detecting gestures a breeze.

The library is built for simplicity and ease of use. It eliminates most boilerplate code for dealing with setting up gesture detection on Android.

Go build awesome stuff with it! 😄

https://github.com/nisrulz/sensey
http://nisrulz.github.io/sensey
https://android-arsenal.com/details/1/3550
https://androidsweets.ongoodbits.com/2016/05/26/issue-20

**Comment by jerodsanto** [comment]
@nisrulz thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
