### ISSUE TITLE
DBLX3 Relational Database released

### ISSUE THREAD

**Issue by dblxadmin** [thechangelog/ping#484]
The next generation of the DBLX Relational Database has been released to the open-source community!

The release of DBLX3 comes with source code and binaries in Java and C# programming languages.

DBLX3 is the only relational database application which supports multiple programming languages, and can run on any platform from Servers to Smartphones.

[www.dblxdatabase.com](url)
[www.sourceforge.net/projects/dblx](url)

**Comment by jerodsanto** [comment]
@dblxadmin :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
