### ISSUE TITLE
PyFunctional 0.7.0 Released

### ISSUE THREAD

**Issue by EntilZha** [thechangelog/ping#486]
Prior release was featured on the change log so figured I would share this new release:

Project Link: https://github.com/EntilZha/PyFunctional

Release Notes: https://github.com/EntilZha/PyFunctional/releases/tag/v0.7.0

## New Features
* Auto parallelization by using `pseq` instead of `seq`. Details at https://github.com/EntilZha/PyFunctional/issues/47
* Parallel functions: `map`, `select`, `filter`, `filter_not`, `where`, `flatten`, and `flat_map`
* Compressed file IO support for `gzip`/`lzma`/`bz2` as detailed at https://github.com/EntilZha/PyFunctional/issues/54
* Cartesian product from `itertools.product` implemented as `Pipeline.cartesian`

**Comment by jerodsanto** [comment]
@EntilZha we don't usually cover minor releases unless the project is broadly used. Please ping us again when you do a major release and we'd be happy to shine the light in your direction. :beers:

**Comment by EntilZha** [comment]
Sounds good. As it turns out the next release (whenever it is) will be `1.0` so will post here again when that rolls around
