### ISSUE TITLE
memleax, detects memory leak of a running process.

### ISSUE THREAD

**Issue by WuBingzheng** [thechangelog/ping#487]
Project: https://github.com/WuBingzheng/memleax

A short time before I met a memory leak problem in production environment. The process began memory leak after long-time running. So I need a tool to detect memory leak of a running process. I searched the web but didn't find one. Then I wrote such a tool myself. 
I wonder if the tool is useful for others. So I share it here, and wait for your advices.
Thanks.

**Comment by jerodsanto** [comment]
@WuBingzheng thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
