### ISSUE TITLE
mark.js – JavaScript keyword highlighter

### ISSUE THREAD

**Issue by julmot** [thechangelog/ping#488]
Repository: https://github.com/julmot/mark.js
Website: https://markjs.io/
Example: https://markjs.io/configurator.html
Description: A text highlighter for search terms or regular expressions. Available in VanillaJS or as jQuery plugin.

:beers:

**Comment by jerodsanto** [comment]
@julmot cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
