### ISSUE TITLE
whatdoeslambdasupport.com - see what js features aws lambda's node runtime's support

### ISSUE THREAD

**Issue by jonknapp** [thechangelog/ping#489]
### http://whatdoeslambdasupport.com/

Trying to figure out what JavaScript features are supported or not in different versions of Node is no fun. We run the same tests found in the [Kangax test suite](http://kangax.github.io/compat-table/) in each AWS Lambda runtime to produce these test results. No more guessing.

A free service from [Coffee and Code](http://www.coffeeandcode.com/)

Here's a blog post to talk about it a bit more: http://blog.coffeeandcode.com/what-does-aws-lambda-support/

**Comment by jerodsanto** [comment]
@jonknapp nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by jonknapp** [comment]
❤️
