### ISSUE TITLE
Strapi Framework - Build powerful backend with no effort

### ISSUE THREAD

**Issue by junland** [thechangelog/ping#490]
Hi Changelog! Came across this NodeJS framework that I would like to share. Here is the TL;DR on the project.

>Strapi is an open-source Node.js rich framework for building applications and services.

>Strapi enables developers to focus on writing reusable application logic instead of spending time building infrastructure. It is designed for building practical, production-ready Node.js applications in a matter of hours instead of weeks.

>The framework sits on top of Koa. Its ensemble of small modules work together to provide simplicity, maintainability, and structural conventions to Node.js applications.

Tried it myself and it's wonderful, reminds me of Sails (Which I love), love the concept of the Studio and there [new vision](http://strapi.io/blog/the-future-of-strapi) they casted a couple of days ago.

[Github](https://github.com/wistityhq/strapi)

**Comment by jerodsanto** [comment]
@junland :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by junland** [comment]
Nice! Thanks @jerodsanto !!!
