### ISSUE TITLE
Kakapo.js - Next generation mocking framework in Javascript

### ISSUE THREAD

**Issue by zzarcon** [thechangelog/ping#491]
I guys, I'm just writing you to let you know about Kakapo.js, a framework for build client side mocks in the browser 🚀 

[devlucky.github.io/kakapo-js](http://devlucky.github.io/kakapo-js)
[github.com/devlucky/Kakapo.js](https://github.com/devlucky/Kakapo.js)

**Comment by jerodsanto** [comment]
@zzarcon :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada:
