### ISSUE TITLE
movtogif-cli

### ISSUE THREAD

**Issue by henriquea** [thechangelog/ping#492]
Released this small thing https://github.com/henriquea/movtogif-cli someone else might find it useful too

**Comment by jerodsanto** [comment]
@henriquea neat! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by henriquea** [comment]
<3
