### ISSUE TITLE
Go, PostgreSQL, and HTML5 content / guest

### ISSUE THREAD

**Issue by ngauthier** [thechangelog/ping#493]
Hello Changelog,

@avdi pointed me your way suggesting I offer a couple of my recent blog posts for your podcast. I've been launching my bootstrapped company MeetSpace and along the way I've learned a bunch of stuff about Go, PostgreSQL, and WebRTC. I've blogged about much of it on our blog. Here are some of my favorites that I think are most relevant to you:

[Hashed Passwords with PostgreSQL's pgcrypto](http://www.meetspaceapp.com/2016/04/12/passwords-postgresql-pgcrypto.html)
[Writing a Data Mapper in Go without an ORM](http://www.meetspaceapp.com/2016/05/23/writing-a-data-mapper-in-go-without-an-orm.html)

There are more on the blog.

Also, I am not sure if you do guests often, but I'd be happy to do a Q&A on the podcast. Either about Go or PostgreSQL or starting a bootstrapped company with minimal tech behind it while keeping a user and product focus.

If any of that sounds neat let me know.

:heart: Nick

**Comment by jerodsanto** [comment]
@ngauthier thanks for contacting us! We'll link up your post on pgcrypto in the next issue of [Changelog Weekly](https://changelog.com/weekly).

I don't think a Q&A about your experience building MeetSpace is a great fit for The Changelog podcast. We tend to focus on specific open source projects and the people behind them.

However, we do have [a new show all about the Go](http://gotime.fm) programming language. It's possible that the hosts of that show might like the idea.

They have their own Ping repo just like this one. I suggest submitting the idea there and seeing what comes of it:

https://github.com/gotimefm/ping/issues

🍻

**Comment by ngauthier** [comment]
Thanks!
