### ISSUE TITLE
cvui - A (very) simple UI lib built on top of OpenCV drawing primitives

### ISSUE THREAD

**Issue by Dovyski** [thechangelog/ping#494]
Hey there!

I've developed a lib to help me create UI when working with OpenCV without OpenGL and Qt. It's a small and simple lib, but it might be quite useful :)

[https://github.com/Dovyski/cvui](https://github.com/Dovyski/cvui)

Here is a demonstration:
![image](https://raw.githubusercontent.com/Dovyski/depository/master/cvui.png)

**Comment by jerodsanto** [comment]
@Dovyski cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:

**Comment by Dovyski** [comment]
Thanks! That's awesome :D
