### ISSUE TITLE
npms.io - A better and open source search for node modules.

### ISSUE THREAD

**Issue by atduarte** [thechangelog/ping#495]
npms (npm search) aims to help you decide which node modules to use, by scoring each package according: Quality, Maintenance and Popularity.

Using npms you won't need to scavenge through dozens of GitHub repositories, checking if they have good community support, have an understandable and throughout documentation, are actively maintained, have good test coverage, etc... Because the search already shows you the best and most relevant modules in the top, with carefully crafted scores.

npms             |  npm
:-------------------------:|:-------------------------:
![npms](https://cloud.githubusercontent.com/assets/666176/16171251/1042261c-3562-11e6-93b0-9dccb824f93f.png)  | ![npmjs](https://cloud.githubusercontent.com/assets/666176/16171250/104039c4-3562-11e6-8bec-94122a1b8720.png)

Relevant: https://github.com/sindresorhus/awesome-nodejs/commit/6d28088bb2ad4561f5d523eeeb43e9404a27bbb6

**Comment by jerodsanto** [comment]
@atduarte nice work! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link npms up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. 💚
