### ISSUE TITLE
Umbrella JS

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#496]
>A <3kb performant jQuery-like library born from the question: **[You might not need jQuery](http://youmightnotneedjquery.com/), then what do you need?**

* http://umbrellajs.com/
* https://github.com/umbrellajs/umbrella

Umbrella is a nicer alternative to writing frameworkless, vanilla JavaScript where that is appropriate and/or necessary. It lets you avoid `Array.prototype.filter.call(document.querySelectorAll(...))` and similar warts of DOM manipulation in vanilla JavaScript.

**Comment by jerodsanto** [comment]
@dbohdan :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by dbohdan** [comment]
Great!

CC @franciscop
