### ISSUE TITLE
Diep.io Protocol

### ISSUE THREAD

**Issue by firebolt55439** [thechangelog/ping#497]
Hey guys,
I've started a project to decipher the protocol diep.io uses in order to create our own server, like we have for games including agar.io and slither.io. The link to the Github project is: [https://github.com/firebolt55439/Diep.io-Protocol](https://github.com/firebolt55439/Diep.io-Protocol). 

Everyone is welcome to contribute to the project. If you want to help with the code, a familiarity with Javascript is a must. Most of the information is contained in the Wiki page of the Github project.

**Comment by jerodsanto** [comment]
@firebolt55439 thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
