### ISSUE TITLE
Neodoc - Beautiful, handcrafted commandline interfaces for node

### ISSUE THREAD

**Issue by felixSchl** [thechangelog/ping#498]
I've been working on this project for over half a year now. The README should contain enough information to make clear what it is about, otherwise I've got an issue:

https://github.com/felixSchl/neodoc

I've also got an online playground set up. It's not pretty, but it works:

http://felixschl.github.com/neodoc

It's pretty well tested, roughly 1000 tests scrutinising it on every change. It's written in purescript but targets node js.

**Comment by jerodsanto** [comment]
@felixSchl nice work! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Neodoc up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
