### ISSUE TITLE
GoDS (Go Data Structures)

### ISSUE THREAD

**Issue by emirpasic** [thechangelog/ping#499]
Hi changelog!

Description: Providing data structures for Go. Containers, Sets, Lists, Stacks, Maps, Trees, HashSet, TreeSet, ArrayList, SinglyLinkedList, DoublyLinkedList, LinkedListStack, ArrayStack, HashMap, TreeMap, RedBlackTree, BinaryHeap, Comparator, Iterator, Enumerable, Sort and more.

Repository: https://github.com/emirpasic/gods

I have been working on a project for more than a year, it has matured and is stable. I would appreciate help from contributors.

**Comment by jerodsanto** [comment]
@emirpasic we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
