### ISSUE TITLE
Zidisha launches world’s first open-source P2P lending platform

### ISSUE THREAD

**Issue by jkurnia** [thechangelog/ping#5]
From Julia Kurnia, Zidisha.org director

As of today, 17 February 2014, we are releasing the source code of our online person-to-person lending platform Zidisha.org to the public under a GPLv3 open-source license.

Now, any individual or organization may freely study, copy, modify and use the full source code that makes up the Zidisha.org website.  This code is the result of approximately five years’ worth of website development.  It is the product of the countless iterations and improvements we have made to the Zidisha P2P microlending model during these years, as we worked to develop the world’s first direct person-to-person lending platform to bridge the international wealth divide.

This website source code is the most valuable asset owned by Zidisha, a US nonprofit organization.  We are releasing it under an open source license so that it may serve as a resource for the general public, and have an impact on the world beyond the Zidisha community.

We are also launching a community of open-source contributors to help us further develop the world’s first direct P2P lending platform to bridge the international wealth divide.  If you have some knowledge of PHP and want to leave your print on the world, we need your help.  Check out the coding challenges we’ve posted in GitHub and join us in building a new technology to connect people in the world’s most marginalized places with the chance for a better life: 

https://github.com/Zidisha/zidisha/

**Comment by edudemy** [comment]
@jkurnia The above mentioned URL is broken. Could you please update the link to the official repo, as on date.

**Comment by augPHP** [comment]
https://github.com/Zidisha/zidisha/ this url is still broken...
