### ISSUE TITLE
show suggestion - interview Larry Wall

### ISSUE THREAD

**Issue by eli4d** [thechangelog/ping#500]
Hi,

The discussion on the member slack channel made me think that it would be very cool to listen to an interview with Larry Wall.  Regardless of love or hate - Perl is foundational - both in its use and creation in the 90s, as well as its influence on other language designers (like Matz).

Cheers,

eli4d

PS: If you have such an interview - please don't forget to ask about the status of Perl 6 :-)

**Comment by jerodsanto** [comment]
👍 would love to have Larry on the show.

**Comment by jerodsanto** [comment]
@eli4d I contacted Larry, but we'll see what he says. Fingers crossed!
