### ISSUE TITLE
Atmo - Server Side Api Mocking made easy with UI

### ISSUE THREAD

**Issue by Raathigesh** [thechangelog/ping#501]
Hey Guys, Just want to let you know about my new project Atmo. Atmo is a tool to mock APIs through UI. Atmo also comes with some other neat features.

https://github.com/Raathigesh/Atmo

**Comment by jerodsanto** [comment]
@Raathigesh nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Atmo up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
