### ISSUE TITLE
Angular loading overlay

### ISSUE THREAD

**Issue by bsalex** [thechangelog/ping#502]
Hi!

http://bsalex.github.io/angular-loading-overlay/_site/

The module provides projects with the organized and flexible way to manage loading spinners.
It reduces code duplication and improves readability by allowing you to wrap promises and functions to show and hide spinners.  

Thanks.

**Comment by bsalex** [comment]
Now it also provides integration with spin.js and angular $http service.

**Comment by jerodsanto** [comment]
@bsalex cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow morning. :beers:
