### ISSUE TITLE
gron - a tool to make JSON greppable

### ISSUE THREAD

**Issue by tomnomnom** [thechangelog/ping#503]
Just a small one!

I've written a tool called gron that turns JSON into a bunch of individual assignments to make it more greppable:

https://github.com/tomnomnom/gron

It's written in Go, has no runtime dependencies and there's binaries available for Linux, Mac and Windows.

[There's an asciinema demo of it here](https://asciinema.org/a/50955).

Thanks :)

**Comment by jerodsanto** [comment]
@tomnomnom neat! Love the `gron --ungron` bit. We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link gron up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by tomnomnom** [comment]
@jerodsanto oh awesome! Thank you so much! :)
