### ISSUE TITLE
apostello

### ISSUE THREAD

**Issue by monty5811** [thechangelog/ping#504]
Link to project: https://github.com/monty5811/apostello

apostello is SMS communication software for churches. It supports receiving and sending messages, scheduled messages, keyword replies, groups and a few other things. It can be deployed to Heroku and uses Twilio for the SMS stuff.

It has been running in production in my church ([usage pattern blog](http://deanmontgomery.com/2016/02/17/apostello_usage_at_st_columbas/)) since Jan 2015, and at least on other church I know for the past month or so.

There is very little that ties the application to use in churches, as long as you stay within Twilio's terms and conditions (can't use a long number for marketing, iirc).

**Comment by jerodsanto** [comment]
@monty5811 nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Apostello up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by monty5811** [comment]
Thanks, @jerodsanto!
