### ISSUE TITLE
Logidze – a new tool for logging DB records changes in Rails 

### ISSUE THREAD

**Issue by palkan** [thechangelog/ping#506]
Link to the project:

https://github.com/palkan/logidze

or blog post:

https://evilmartians.com/chronicles/introducing-logidze

Thanks!

**Comment by jerodsanto** [comment]
@palkan we're including Logidze in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it Saturday morning. :beers:

**Comment by palkan** [comment]
@jerodsanto Great news! Thanks! 🍾
