### ISSUE TITLE
KnowItAll: Minimalistic authorization focused on APIs

### ISSUE THREAD

**Issue by oddlyfunctional** [thechangelog/ping#508]
Hi! I recently released [KnowItAll](https://github.com/mrodrigues/know_it_all), a small gem for authorization using simple OO design, heavily inspired by [Pundit](https://github.com/elabs/pundit). It provides a small set of helpers, but the core benefit is an architectural pattern that provides a detailed feedback for the clients of your API.

Please check it out! :)

**Comment by jerodsanto** [comment]
@oddlyfunctional :green_heart: we'll put this in tomorrow's issue of [Weekly](https://changelog.com/weekly) :tada: 

(I'm a big fan of Pundit, like yourself)

**Comment by oddlyfunctional** [comment]
Awesome, just read the newsletter! Thank you very much! :D
