### ISSUE TITLE
sc-widgets (Android): New open source project to create every kind of gauges

### ISSUE THREAD

**Issue by Paroca72** [thechangelog/ping#509]
Hi,

I've create a base classes to implement easily every kind of gauges on Android.
Now I'll would like to find someone to help me to improve this project building a series of preset "user friendly" to use for free and carry on the classes development.

[sc-widgets](https://github.com/Paroca72/sc-widgets)

All the classes are well documented also with examples but my english suck :-)
So be patient about what you'll read.

Thanks guys
Sam

**Comment by jerodsanto** [comment]
@Paroca72 we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)!

We :ship: it tomorrow morning. :beers:
