### ISSUE TITLE
osom: object schema modeling

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#510]
![screen shot 2016-07-07 at 13 42 01](https://cloud.githubusercontent.com/assets/2096101/16652120/9ac006b6-4448-11e6-86a8-bd4dd5aff4e7.png)

Hello,

I created this because I love [mongoose schema validation](https://github.com/Automattic/mongoose#defining-a-model) but:

- Mongoose validation live inside mongoose package. You can't use it alone.
- Mongoose validation only have sense if you are working with MongoDB as database.

Instead, osom:

- Smart and focused in validate object schemas.
- Easy to integrate with your code as medium lawyer between your database and your data validation, so it's database agnostic.

docs are available at: https://kikobeats.github.io/osom

**Comment by jerodsanto** [comment]
@Kikobeats cool stuff! We'll link osom up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
