### ISSUE TITLE
WebTorrent Desktop: A Modern Electron-based Torrent Client

### ISSUE THREAD

**Issue by amilajack** [thechangelog/ping#511]
Probably the best torrent client ever made. [WebTorrent Desktop](https://github.com/feross/webtorrent) is the first implementation of a 'hybrid client', which allows users to connect to WebRTC torrent clients and bittorrent clients:

![WebTorrent hybrid client demo](https://camo.githubusercontent.com/3f57ad9ba26fad961f316c2eb20d5b9f12341b6e/68747470733a2f2f776562746f7272656e742e696f2f696d672f6e6574776f726b2e706e67)

**Comment by jerodsanto** [comment]
@amilajack yes this is so rad. :blue_heart: :yellow_heart: :green_heart: we'll mention WebTorrent [on twitter!](https://twitter.com/changelog)  :fist: 🍻

_(side note: we're in talks w/ @feross to come on the show real soon and talk all about it 👏 )_
