### ISSUE TITLE
SeedCascade: A package that greatly simplifies database seeding

### ISSUE THREAD

**Issue by omranjamal** [thechangelog/ping#512]
We built this out of a need for easier Database seeding. It is a package that greatly simplifies database seeding for Laravel projects.

Homepage: http://hedronium.github.io/SeedCascade
Github: https://github.com/Hedronium/SeedCascade

Hope this is relevant enough to be included one day.

**Comment by jerodsanto** [comment]
@omranjamal thanks for sharing this, it's relevant! 

We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) 💚
