### ISSUE TITLE
WaveInApp -- Live Audio Equalizer with wave effect

### ISSUE THREAD

**Issue by vladdmitriev** [thechangelog/ping#513]
Here is our new project -- https://github.com/Cleveroad/WaveInApp

WaveInApp is created for animated visualization of played audio files. It was designed for the Android platform. The animation is made in the form of waves with splashing bubbles

<img src="https://raw.githubusercontent.com/Cleveroad/WaveInApp/master/images/demo_.gif" alt="WaveInApp">

You can read about all the advantages this library has and find out how to implement it into your app in our blog post: [Case Study: Audio Visualization View For Android by Cleveroad ](https://www.cleveroad.com/blog/case-study-audio-visualization-view-for-android-by-cleveroad)

**Comment by jerodsanto** [comment]
@vladdmitriev nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/) _(:shipit: soon)_!

:beers:

**Comment by vladdmitriev** [comment]
@jerodsanto Thanks you!
