### ISSUE TITLE
Cleave.js - Format input text content automatically

### ISSUE THREAD

**Issue by nosir** [thechangelog/ping#515]
Looks like I'm the first 😋 

Cleave.js has a simple purpose: to help you format input text content automatically.
Also ReactJS component port is available.

GitHub repo: https://github.com/nosir/cleave.js
Homepage with demos: http://nosir.github.io/cleave.js

Thanks.

**Comment by jerodsanto** [comment]
@nosir nice! I've seen you in the top starred list a few times in [Nightly](https://changelog.com/nightly). Looks like people are digging it!

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:

**Comment by nosir** [comment]
Woot! Cheers @jerodsanto
