### ISSUE TITLE
sshok - A dependency-free cure for SSH configuration hell 

### ISSUE THREAD

**Issue by ncuesta** [thechangelog/ping#516]
You may want to check out a little tool I made for transparently splitting one's SSH configuration into multiple files (something not currently possible with plain SSH), without getting in the way of our daily work.

Please do check the README for further information.

* GitHub repo: https://github.com/ncuesta/sshok

Kudos for your excellent work, guys!

**Comment by jerodsanto** [comment]
@ncuesta we're including sshok in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :beers:

**Comment by ncuesta** [comment]
Awesome! Thanks, guys. Keep up the good work, I really enjoy (and every week look forward to receiving) your weekly issue!
Cheers,

Nahuel Cuesta Luengo
On Tue, Sep 20, 2016 at 23:31, Jerod Santo <notifications@github.com> wrote:
@ncuesta [https://github.com/ncuesta] we're including sshok in our next issue of Changelog Weekly [https://changelog.com/weekly/] ! 🍻
