### ISSUE TITLE
Animate.js - Add slick animations to your page elements and page transitions

### ISSUE THREAD

**Issue by archan937** [thechangelog/ping#517]
Hi,

I just released Animate.js v0.1.1 (https://archan937.github.io/animate.js). Its goal is to not only to animate page elements sequentially but it also animates page transitions with cool animations. The pages are totally separated.

It uses animate.css to animate page elements. And to animate page transitions, it uses html2canvas to create an image of the current page first (which makes the mosaic and openSesame animations possible) and afterwards animates the page transition. The code is heavily inspired by the Codrops Page Transition demo.

The setup only consists out of a single javascript script include tag, nothing more. And configuration is done within the query string of the include tag (nifty huh? :D)

Also, you can specify the timing of the animation sequence (which animates the page automatically) and you can go in presentation mode which binds the common presentation controls (Enter, Backspace, Spacebar, arrows).

Cheers,
Paul.

**Comment by jerodsanto** [comment]
@archan937 thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
