### ISSUE TITLE
Refraction

### ISSUE THREAD

**Issue by mbasso** [thechangelog/ping#518]
> A guard that represents a central point of control in your application.

- http://refraction.js.org/
- https://github.com/mbasso/refraction

Modern javascript applications are often organized into modules, which are awesome but have some problems that we can't avoid. When we are writing an application in this way, we must consider that all our modules must be independent, testable, instantly reusable and secure. Refraction's purpose is to make these concerns take care of themselves by using some design patterns.

**Comment by jerodsanto** [comment]
@mbasso very cool! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Refraction up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
