### ISSUE TITLE
Star.js: automatically correct typos based on the previous message*

### ISSUE THREAD

**Issue by Decagon** [thechangelog/ping#519]
https://github.com/Decagon/star.js

Star.js is a small, node powered javascript library that automatically corrects messages based on what you have sent previously.

For example if I'm on an internet-chat website and if I type in "my rss isn't working" in one message, send it, then type "rss reader*" as a correction, star.js will suggest to edit the original message to "my rss reader isn't working".

It can do more complex examples (currently being developed), such as knowing where to place words if you forgot them: you type "I go to the store tomorrow" by accident, send "will*" in the next message, star.js will notice that "I" is a null link, and use the word "will" to connect "I" to it. So, it will fix the message to "I will go to the store tomorrow"

**Comment by jerodsanto** [comment]
@Decagon nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). :beers:
