### ISSUE TITLE
108: A minimal beat machine

### ISSUE THREAD

**Issue by amilajack** [thechangelog/ping#520]
108 is a minimal beat machine featuring 5 classic samples that can be arranged on a 16 step loop running 108 bpm.

https://github.com/hatsumatsu/108

**Comment by jerodsanto** [comment]
@amilajack tons of fun! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link 108 up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: Saturday morning. :beers:
