### ISSUE TITLE
WinFsp - Windows File System Proxy

### ISSUE THREAD

**Issue by billziss-gh** [thechangelog/ping#521]
WinFsp is like FUSE for Windows. It allows one to create a file system as a user-mode process ("app") that fully integrates with Windows without any kernel mode programming. Standard Windows API's such as `CreateFile`, `ReadFile`, `WriteFile`, etc. will work on files in a WinFsp file system exactly the same as if they were on a NTFS or FAT file system.

WinFsp can be used to create a variety of file systems. For example, one could use it to create a file system out of objects stored in the cloud, a bunch of tables in a Sqlite database or even present a file system view out of the Windows registry!

WinFsp has a native API, but also comes with a FUSE compatibility layer.

Links:

- Home page: http://secfs.net/winfsp/
- GitHub: https://github.com/billziss-gh/winfsp

**Comment by billziss-gh** [comment]
![WinFsp Demo](http://www.secfs.net/winfsp/files/cap.gif)

**Comment by jerodsanto** [comment]
@billziss-gh cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by billziss-gh** [comment]
Excellent! Thank you!
