### ISSUE TITLE
No mention of React.js Patent License Grant Issues In Episode #211

### ISSUE THREAD

**Issue by wonder95** [thechangelog/ping#522]
I listened with interest to episode #211 with James Pearce of Facebook, and it was very good, but I'm just curious why the issue of the React.js patent license grant issue that arose last year was never brought up. It seems to have been resolved, but I really would have been interested in hearing about that whole issue from the behind-the-scenes-at-Facebook point of view.

**Comment by jerodsanto** [comment]
That's a really good question, @wonder95. The lame truth of it from my side is that I had _zero idea about the controversy_ until you posted this. 

Had I known, I definitely would've broached the topic. Sorry for gapping that. 😞

@adamstac were you aware of this?

**Comment by adamstac** [comment]
Dang, no -- I was not aware of this controversy.
