### ISSUE TITLE
Wikipedia based translation library

### ISSUE THREAD

**Issue by maciejkrol** [thechangelog/ping#523]
Hi,

I came up with the idea of translation service based on Wikipedia quite a while ago. Realising recently that I find it useful more and more often I decided to rewrite it and post as a PHP library for others to use.

WikiDiki let's you translate words across all languages based on Wikipedia. It can translate only nouns, as its based on an encyclopedia, but keeps the context right which is very important in many cases. It is also based on the biggest ever growing base of knowlege which makes it more and more accurate everyday.

https://github.com/maciejkrol/wikidiki-php

I hope you will find it useful.

**Comment by jerodsanto** [comment]
@maciejkrol we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
