### ISSUE TITLE
Fully secure encrypted email service

### ISSUE THREAD

**Issue by achernyak** [thechangelog/ping#524]
I recently found [tutanota](https://tutanota.com/) which is an open source, completely secure email service provider. They seem to just be starting out and I think they would have some interesting topics to cover. Everything from the general state of security right now, how they ensure security of their service, to why open source is important to a tier of services that's notoriously closed sourced.

**Comment by jerodsanto** [comment]
@achernyak thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
