### ISSUE TITLE
GitHub will provide you the language mix of any repo

### ISSUE THREAD

**Issue by cclauss** [thechangelog/ping#525]
On one of your recent podcasts you were asking how GitHub determines the language of a repo.  Here is a valuable feature that I believe is too hidden within the GitHub UI....  You need to click that colored bar...

![golang language mix](https://cloud.githubusercontent.com/assets/3709715/17076895/80e1c162-50be-11e6-908e-8367b05429e6.png)

**Comment by jerodsanto** [comment]
@cclauss yes! Extremely useful, and I agree that they've made it hard to find. Not sure why ¯\_(ツ)_/¯
