### ISSUE TITLE
React + RxJS the Redux way

### ISSUE THREAD

**Issue by dacz** [thechangelog/ping#526]
Hi changelog!

React is awesome. So is Redux. But I wanted to add RxJS to the mix. Therefore RxR - RxJS in React the Redux way.

Why the Redux way and why RxJS? 

* nearly every React developer knows Redux and it's concept
* Redux concept is great and making RxR similar helps to get into it fast
* rewriting existing Redux app means just small code changes (functional parts are the same)
* code with RxR is usually smaller
* get the power of RxJS for the whole app!

It's better to start exploring on top of what you know and already have.

* [RxR Gitbook](https://dacz.github.io/rxr/index.html)
* [RxR Github repo](https://github.com/dacz/rxr)
* [Example app Redux and RxR side by side](rxr-redux-example)

Have nice Sunday.

**Comment by jerodsanto** [comment]
@dacz cool stuff! We'll link RxR up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by dacz** [comment]
Thanks! 🍻
