### ISSUE TITLE
Request scoped cache for PHP

### ISSUE THREAD

**Issue by cheese44** [thechangelog/ping#527]
I created a [request scoped caching library for PHP](https://github.com/cheese44/cheesecache) for caching function and query results that are called multiple times during a request and are unlikely to change during this time.

Hopefully this will be of use to somebody.

**Comment by jerodsanto** [comment]
@cheese44 we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
