### ISSUE TITLE
Community Member Benefits!

### ISSUE THREAD

**Issue by adamstac** [thechangelog/ping#528]
As you can see there are benefits to being a Changelog Community Member -- https://changelog.com/benefits

Our aim is to create as many relevant and valuable partnerships for our member community as we can. That's where you come in. Help us by telling us what tools, services, and resources you use and we'll work on creating a relationship with them and pass on the savings to you. Of course, you have to be [join the community](https://changelog.com/membership) to enjoy them.

Add a comment to this thread linking up your suggestion and we'll do what we can.

One more thing -- **we have BIG plans for our membership** -- trust me when I say we are just scratching the surface of member love thus far.

[Join and support us](https://changelog.com/membership) so we can continue to support the open source community.

**Comment by zerok** [comment]
As already mentioned in the chat, I think the O'Reilly code is very useful. I regularly purchase eBooks from them mostly using their own vouchers they hand out during conferences or other such events. Not having to wait for another such opportunity thanks to a perpetual coupon is a really nice benefit (once I'm finally through my backlog of books >_< )

**Comment by soleo** [comment]
Some coupon codes for GitHub would also be nice to have.
