### ISSUE TITLE
"Make github great again" an anlysis of github commit messages

### ISSUE THREAD

**Issue by k-nut** [thechangelog/ping#529]
Thanks to the newly released githubarchive data I was able to run an analysis with bigquery on all commit messages on github. The question that I wanted to answer: Have people started writing more Trump-Style commit messages (`make ... great again`) since he started appearing in the media more and more.

The answers can be found in the repository where I wrote down the steps taken and the results found.
https://github.com/k-nut/make_github_great_again/blob/master/README.md

**Comment by jerodsanto** [comment]
@k-nut fun idea! 😂We'll mention this [on twitter!](https://twitter.com/changelog)  :beers:
