### ISSUE TITLE
GopherCon Brasil, Nov 4, 5 and 6

### ISSUE THREAD

**Issue by carlisia** [thechangelog/ping#530]
Wanted to share with the community the upcoming Go conference in Brazil. Registration and CFP (https://www.papercall.io/gopherconbrazil2016) are open!

https://2016.gopherconbr.org/en/

It's also a great opportunity for companies to get exposure to a hot community of developers in Brazil, via sponsorship (https://2016.gopherconbr.org/en/GopherconBR2016Prospectus.pdf).

**Comment by jerodsanto** [comment]
@carlisia this is gonna get a tweet and a mention in Weekly. 💚

**Comment by carlisia** [comment]
@jerodsanto the CFPs are closed now, just heads up. Thanks for this!
