### ISSUE TITLE
WireGuard: fast, modern, secure VPN tunnel

### ISSUE THREAD

**Issue by zx2c4** [thechangelog/ping#532]
I was asked on twitter to submit something about wireguard here, so here goes...
---

From the same @zx2c4 who brought you `pass`, WireGuard is an extremely simple yet fast and modern VPN that utilizes state-of-the-art cryptography. It aims to be faster, simpler, leaner, and more useful than IPSec, while avoiding the massive headache. It intends to be considerably more performant than OpenVPN. WireGuard is designed as a general purpose VPN for running on embedded interfaces and super computers alike, fit for many different circumstances. Initially released for the Linux kernel, it plans to be cross-platform and widely deployable. It is currently under heavy development, but already it might be regarded as the most secure, easiest to use, and simplest VPN solution in the industry.

Main website: https://www.wireguard.io/
Whitepaper: https://www.wireguard.io/papers/wireguard.pdf
Git repo: https://git.zx2c4.com/WireGuard/
LKML announcement: https://lkml.org/lkml/2016/6/28/629
Installation: https://www.wireguard.io/install/
Quickstart: https://www.wireguard.io/quickstart/

![Quickstart walkthrough](https://www.wireguard.io/img/walkthrough.gif)

**Comment by jerodsanto** [comment]
@zx2c4 nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link WireGuard up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :green_heart:
