### ISSUE TITLE
restic: secure, fast, deduplicated backup written in Go

### ISSUE THREAD

**Issue by fd0** [thechangelog/ping#534]
I'd like to suggest my project [restic](https://github.com/restic/restic) for inclusion in the "Ping The Changelog" part of the newsletter. It's a secure, fast and deduplicated backup program written in Go, and I've just today released [version 0.2.0](https://github.com/restic/restic/releases/tag/v0.2.0).

**Comment by fd0** [comment]
I've just released [version 0.3.0](https://github.com/restic/restic/releases/tag/v0.3.0).

**Comment by jerodsanto** [comment]
@fd0 nice! We just queued up a [tweet](https://twitter.com/gotimefm) in your direction and we'll also link restic up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). (I've promoted from the Ping section to the Projects and Repos section, nice work).

We :shipit: this weekend. :beers: :green_heart:

**Comment by fd0** [comment]
Cool, thanks!
