### ISSUE TITLE
Go plugin for IntelliJ latest release

### ISSUE THREAD

**Issue by dlsniper** [thechangelog/ping#535]
Hi,

I'd like to suggest the latest release of the Go plugin for IntelliJ Platform (all JetBrains IDEs + Android Studio are supported).
The link is here: http://go-ide.com/releases/0.11.1725/
The plugin is free & open source and IntelliJ IDEA also has a free & open-source version, called Community Edition.
Thank you.

**Comment by jerodsanto** [comment]
@dlsniper we're including IntelliJ Go in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by dlsniper** [comment]
Awesome! :heart:
