### ISSUE TITLE
Changelog inspired me to make sayitlike.me 

### ISSUE THREAD

**Issue by omidfi** [thechangelog/ping#537]
Hello Adam, Jerod and Beverly, 

I'm a long time listener of the show. Seeing how many times you have to struggle with pronouncing people's names, specially the time that you pronounced my family name, I got inspired to make a platform using React and Node to help all of us :) 
Please take a look: 
https://sayitlike.me 

**It's of course open source:** 
https://github.com/omidfi/sayitlikeme

Hope you find it useful :)
Omid

**Comment by jerodsanto** [comment]
@omidfi awesome idea! I'm not sure if it's a good thing or a bad thing that we inspired you to create this, but we're flattered nonetheless. ;)

I opened up a PR to fix a few typos on the About page and we'll tweet about this and include it in [Weekly](https://changelog.com/weekly) for sure! 🍻

**Comment by omidfi** [comment]
@jerodsanto thanks for the mention on weekly and tweet, and the PR, the list of reasons to thank changelog is a ever growing one :)

**Comment by jerodsanto** [comment]
✊
