### ISSUE TITLE
RaspChat - An unapologetically simple and lighweight chat server.

### ISSUE THREAD

**Issue by maxpert** [thechangelog/ping#538]
**I was recently asked to post about my project here :smile:**

 RaspChat is a really basic and simple chat server, designed with goals of making deployment simple, being super lightweight (so light it can run on a 512MB RaspberryPi, that's where name came from), 0 external dependencies. Unlike many of the existing solutions out there like RocketChat and Mattermost etc. which requires setting up complicated external database systems, and requiring more resources. RaspChat makes on-premise deployment really simple, one can simply extract the folder and get it up and running in no time. RaspChat has inspired itself from simplicity of IRC, and aims to bring features from IRC (commands like /kick, /kill, /privmsg etc.) with really lightweight and delightful chat interface. Right now it supports some commands like /join, /leave, /gif, and /nick, drag drop file sharing :smiley:. 

 It's been out there for a while now and it has been featured on ProductHunt. Here are some links for project and it's source code:
 
Home page: http://beta.raspchat.com/ (Running of RPi at my home)
Product Hunt: https://www.producthunt.com/tech/raspchat
Source code: https://github.com/maxpert/raspchat

Thanks,
Zohaib

**Comment by jerodsanto** [comment]
@maxpert cool stuff! We'll link RaspChat up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
