### ISSUE TITLE
GitPitch - Promote, Pitch, Or Present Your GitHub Projects.

### ISSUE THREAD

**Issue by gitpitch** [thechangelog/ping#539]
New [GitPitch service](https://gitpitch.com) released that may be of interest to GitHub devs out there.

GitPitch is a free service that turns PITCHME.md markdown into online, interactive slideshows. It is designed to help GitHub developers promote, pitch or present their GitHub projects.

The idea is simple. If you ever need to present your project ideas to colleagues, clients or customers or at a meetup or conference then GitPitch is for you. Just add [PITCHME.md](https://github.com/gitpitch/gitpitch/wiki). Further details and samples are available on the [GitPitch website](https://gitpitch.com).

GitPitch is all about helping developers get the word out about their GitHub projects. I'm hoping The Changelog can help to get the word out about GitPitch. Thanks.

**Comment by imsky** [comment]
this looks great, but is it not open source?

**Comment by gitpitch** [comment]
No, the implementation of the service itself is not open source. Just freely available for use to all GitHub users.

**Comment by jerodsanto** [comment]
@gitpitch we just queued up a [tweet](https://twitter.com/changelog) in your direction 🍻

**Comment by jerodsanto** [comment]
(would be a lot cooler if it were open source though 😉)

**Comment by gitpitch** [comment]
@jerodsanto @imsky stay tuned for cool, GitPitch announcement coming real soon ;-)

**Comment by gitpitch** [comment]
@jerodsanto @imsky Very happy to finally be able to announce that GitPitch has been released as an open source project on GitHub. See project [README](https://github.com/gitpitch/gitpitch) for details.

**Comment by jerodsanto** [comment]
@gitpitch that's excellent! We'll include this in the next issue of [Changelog Weekly](https://changelog.com/weekly) 🍻
