### ISSUE TITLE
show suggestion - interview Taylor Otwell

### ISSUE THREAD

**Issue by eli4d** [thechangelog/ping#540]
Hi,

I think an interview with Taylor Otwell, creator of https://laravel.com/ framework, would be interesting.  It's interesting that he can work full time on the project and support himself through services such as Laravel Forge (https://forge.laravel.com/).  I think it would be interesting to find out why he choose PHP and his evolution as a developer.

Cheers,

Eli4d

**Comment by adamstac** [comment]
Howdy @eli4d!

We're certainly due for an update on the Laravel front -- it's been over a year since we recorded this https://changelog.com/142/

If you haven't listened to 142 yet, listen to that show, then come back here and let us know what new details we can circle back on with @taylorotwell.

**Comment by jerodsanto** [comment]
@eli4d long time no talk! Did you make it over in the Great Slack Migration of 2017?! 😉

We've contacted Taylor to see if he'll come back on the show. He was a great guest and we'd love to have a follow-up on Laravel and what he's up to.

💚
