### ISSUE TITLE
DN2A - Digital Neural Networks Architecture

### ISSUE THREAD

**Issue by antoniodeluca** [thechangelog/ping#541]
DN2A is a set of highly decoupled JavaScript modules for Neural Networks and Artificial Intelligence development.
Allows to build, train and query simple neural networks as well as very powerful neural networks chains through which implement your Artificial Intelligence solution.

GitHub: https://github.com/dn2a/dn2a-javascript 
WebSite: http://www.dn2a.org

**Comment by jerodsanto** [comment]
@antoniodeluca nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link DN2A up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by antoniodeluca** [comment]
Thanks!

**Comment by dazn-antonio-deluca** [comment]
Hi @jerodsanto, I have received two "Changelog Weekly" since your post but DN2A was never included. What it is happened? Thanks in advance for your support.

**Comment by antoniodeluca** [comment]
Hi @jerodsanto, I have received two "Changelog Weekly" since your post but DN2A was never included. What it is happened? Thanks in advance for your support.

**Comment by jerodsanto** [comment]
@antoniodeluca it was in issue 128. Look for the Ping section near the bottom. Here's the web version: http://email.changelog.com/t/t-76E19066D7BA809E

**Comment by antoniodeluca** [comment]
@jerodsanto I am very sorry. I was checking the various pages but I did not notice that. Sorry and thanks again.
