### ISSUE TITLE
Antipatern

### ISSUE THREAD

**Issue by bytecorner-jan** [thechangelog/ping#542]
Hello gotime, 

thanks for the good pod cast, as I'm starting with go its very nice to hear about all these interesting new projects on my way to work. :-) 
In your pod cast #10 you were slightly touching on (today's) antipattern: "One big select to handle state with channels" I think you were revering to doozerd. That caught my attention, because that's what I thought to be good . Please see [https://talks.golang.org/2013/bestpractices.slide#28]. 

I would find it very interesting if you could explain why you turned away from  channels for state and how you solve the main application state today with go. It would already be good if you could point to a project that is doing well, according you today's view on go, additionally to a antipattern "doozerd" project. 

Thanks Jan

**Comment by jerodsanto** [comment]
@bytecorner-jan thanks for listening to Go Time! That show has its own Ping repo where you should post this discussion instead.

https://github.com/GoTimeFM/ping/issues

I'm closing this here, but hopefully they'll help you out over there. ✊
