### ISSUE TITLE
TemplateView - A React and Marionette inspired Backbone.js View for template designers. 

### ISSUE THREAD

**Issue by howardroark** [thechangelog/ping#543]
Hey!  Just in search of feedback and contributors for an experimental project.  Thanks a bunch if you have any interest in mentioning it... https://github.com/howardroark/TemplateView

**Comment by jerodsanto** [comment]
@howardroark we'll link TemplateView up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
