### ISSUE TITLE
James Long and Jason Laster of the mozilla debugger.html project

### ISSUE THREAD

**Issue by clarkbw** [thechangelog/ping#544]
James Long (@jlongster) and Jason Laster (@jasonLaster) are developers working for @mozilla who have been developing a brand new JS debugger interface for Firefox written from scratch in React and Redux.  The project is called [debugger.html](https://github.com/devtools-html/debugger.html) and is an experiment of a new method for developing developer tools at @mozilla.  It is modular and designed to use other npm modules as well as offer a number of new modules itself.  The source code is hosted on GitHub instead of within the Firefox source repo so the debugger.html project is much more accessible to new developers.  And the interface can be developed via multiple browsers and debug remote targets like Firefox, Chrome, and even Node through the Firefox and Chrome remote debugging protocol.

I think this will be a great interview about the people behind a new type of open source project in a company with a long history of open source.  Jason and James can talk about developer tools, debuggers, react, redux, webpack, and browsers. Thanks! 🎉

**Comment by fredrikekelund** [comment]
:+1:

**Comment by jerodsanto** [comment]
@clarkbw somewhat related, we had @jlongster on the show this week to discuss the burden of open source. Please take a listen and let us know what you think!

https://changelog.com/podcast/242

That being said, I think Mozilla's debugger project is super interesting and definitely show-worthy. @jasonLaster we'd love to have you on The Changelog to discuss. Please email editors@changelog.com to coordinate! 

💚

**Comment by clarkbw** [comment]
I just saw! Was looking forward to listening today. Cheers!
