### ISSUE TITLE
How to prepare a minimal Debian template for LXC containers

### ISSUE THREAD

**Issue by florianbeer** [thechangelog/ping#545]
Hi,
I wrote an article on my blog that might be interesting to your readers, if they are dealing with virtualization.

**A clean start – How to prepare a minimal Debian template for LXC containers**
https://blog.no-panic.at/2016/08/11/a-clean-start-how-to-prepare-a-minimal-debian-template-for-lxc-containers/

Thanks for your consideration to add this to your newsletter.

**Comment by jerodsanto** [comment]
@florianbeer :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
