### ISSUE TITLE
Python podcast suggestion

### ISSUE THREAD

**Issue by jldugger** [thechangelog/ping#546]
There doesn't appear to be a lot of pythonic content in the podcast archives. I saw a previous issue #233 that mentioned a few leads, but let me suggest a different angle: Django.

They just released 1.10 a few weeks ago. I don't know what thechangelog's turnaround time is, so that may or may not be incredibly relevant by airing. I'm a sysadmin by trade, so I'm not incredibly familiar with the Django community structure, but I know a few people who are, and they recommended Andrew Godwin. 

He's got a fairly broad background:
- South (db migrations, later integrated into django core)
- Channels (websockets support in django, will probably be in core eventually)
- Many other projects: http://www.aeracode.org/projects/

And if Andrew is unable or unwilling to make an appearance, I'm sure he could recommend someone who could.

Thoughts?

**Comment by degustaf** [comment]
Other choices might be @adrianholovaty or @jacobian, the former BDFLs of Django, @freakboy3742, the former President of the Django Software Foundation, or @frankwiles, the current president of the Django Software Foundation.

**Comment by frankwiles** [comment]
All good choices, Andrew would be the person however to talk about Channels which is probably the most interesting thing happening to Django at the moment.

**Comment by jerodsanto** [comment]
@jldugger @frankwiles @degustaf good input, thanks! We'd love to have Andrew on the show. Any of you know him personally and could intro us?

**Comment by frankwiles** [comment]
Yep send me an email frank@revsys.com and I'll put you in touch.

**Comment by jerodsanto** [comment]
Awesome, @frankwiles. Thanks!

@jldugger somewhat related: Eric Holscher was on RFC this week talking about Read/Write the Docs. Lots of Python community mentions in that show: https://changelog.com/rfc-5/

**Comment by freakboy3742** [comment]
I'm always happy to jump on a podcast, either to talk Django, or my new project BeeWare (bringing Python to iOS, Android, and other portable devices).

**Comment by jerodsanto** [comment]
<img width="481" alt="2016-09-02 at 7 55 am" src="https://cloud.githubusercontent.com/assets/8212/18204557/0f597248-70e3-11e6-8936-f1f4de3889fe.png">

Thanks to everyone for your help. We'll post here when it's live. Should be a great show!

**Comment by jerodsanto** [comment]
This show is now live! 💥

https://changelog.com/podcast/229

Thanks to all for the suggestion, listen closely for a shout out during the show. :green_heart: :green_heart: :green_heart:
