### ISSUE TITLE
Bagarino - Redis-backed tickets/tokens server

### ISSUE THREAD

**Issue by NicolaOrritos** [thechangelog/ping#547]
_Bagarino_ (means _"scalper"_ in Italian) generates and validates alphanumeric tickets using a number of different expiration policies.
_Bagarino_ can tell a real ticket from a fake one. Simple, fast and RESTful.
Ask it for a new ticket and it'll give you. Then ask it whether a ticket is still valid or expired. Or whether it is a fake. It'll know for sure.
When tickets expire simply ask bagarino for new ones.
_Bagarino_ can be used as a support for a licensing server and as an helper to other systems in an authentication/authorization scenario.

Homepage and code: https://github.com/NicolaOrritos/bagarino
License: Apache v2

**Comment by jerodsanto** [comment]
@NicolaOrritos great name! We're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
