### ISSUE TITLE
Progenic - Multi-workers daemon module with advanced options

### ISSUE THREAD

**Issue by NicolaOrritos** [thechangelog/ping#548]
The _progenic_ module starts a given service as a daemon, by spawning a configurable number of children that will act as workers. The father process is the one balancing the work among them.
_Progenic_ leverages the [cluster](https://nodejs.org/api/cluster.html#cluster_cluster) module under the hood.

Home and code: https://github.com/NicolaOrritos/progenic

**Comment by jerodsanto** [comment]
@NicolaOrritos you're 2/2 this week! This one will be in the next issue as well 🍻
