### ISSUE TITLE
SlidingTutorial-Android

### ISSUE THREAD

**Issue by vladdmitriev** [thechangelog/ping#549]
Hello,

This is an amazing service, thank you for that! I just would like to ask, could you add one of my repositories into your digest?

Here is a link - https://github.com/Cleveroad/SlidingTutorial-Android

Description:
The Sliding tutorial for Android - simple library for creating tutorials for any application on the Android platform

Best,
Vlad

**Comment by jerodsanto** [comment]
@vladdmitriev happy to hear you like it! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by vladdmitriev** [comment]
@jerodsanto Thank you!
