### ISSUE TITLE
EventQL - SQL database for large-scale event analytics 

### ISSUE THREAD

**Issue by paulasmuth** [thechangelog/ping#550]
EventQL is the open source version of Google's BigQuery system. One explicitly
stated design goal is that EventQL is able to scale to 10,000 servers or more
and to be able to process hundreds of terrabytes of data and trillions of events
in seconds.

The documentation is here: http://eventql.io/
And the github repo: http://github.com/eventql/eventql

I had another one of my projects featured in The Changelog before and was wondering if this would be interesting aswell?

If there are any questions I would of course be happy to answer them. EventQL
is backed by a berlin-based company.

**Comment by jerodsanto** [comment]
@paulasmuth nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link EventQL up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

By the way, cool console example on the homepage. Looks hand rolled, too! 😄
