### ISSUE TITLE
git-stacktrace - easily figure out which git commit caused a given stacktrace

### ISSUE THREAD

**Issue by jparise** [thechangelog/ping#551]
[git-stacktrace](https://github.com/pinterest/git-stacktrace) is designed to make it easy to figure out which git commit caused a given stacktrace.

git-stacktrace looks for:
- commits in given range that touched files in the stacktrace
- commits in given range that added/removed code present the stacktrace

It currently supports Python and Java with more languages to come. Pull requests welcome!

https://github.com/pinterest/git-stacktrace

**Comment by jerodsanto** [comment]
@jparise nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). 💚
