### ISSUE TITLE
Continuous Pipelines for DevOps : The Definitive Disambiguation Guide

### ISSUE THREAD

**Issue by frntn** [thechangelog/ping#552]
Hello,

I am a recent (and now addicted) changelog podcast listener.

Recently I tried to understand the new Jenkins2 DSL and its pipeline plugin, then I tried to get the pros/cons against TravisCI and GitlabCI... And finally, after reverse engineering code, reading documentations, articles, watching some videos, etc... I realized I had to make myself clear with the concept  of continuous delivery and continuous deployment, because I there is no one consensus on its definition.

So I tried to re-understand it, starting back from the very early (1976) automation tool : `make`
Step by step coming back to our last automation and orchestration trends I made myself a clear and deep understand on these concepts (and even came up with a one-sentence definition at the end :p)

After some live (private) talks some people recommended me to write an article about it to... "spread the world" :) 

So I don't know if that article will fit your editorial angle but here it is :

> Continuous Pipelines for DevOps : The Definitive Disambiguation Guide
> https://medium.com/@frntn/pipelines-for-devops-6cfbabc3dd8d

6min read estimation from medium bot. 
But I would say more...

**Comment by jerodsanto** [comment]
@frntn awesome to hear you're a fan of our work! By the way, did you know we now have a Master Feed that will get you _every show we publish_ (not just The Changelog)? Check out

https://changelog.com/master and https://changelog.com/subscribe#master

Now, on to your article. We're including it in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! 💚 

Thanks so much for pinging us about it ✊
