### ISSUE TITLE
How to Annoy a Web Developer

### ISSUE THREAD

**Issue by omidfi** [thechangelog/ping#554]
Hi, I started this project to help people treat web developers better, or at least find out what they are doing wrong.
https://github.com/omidfi/how-to-annoy-a-web-developer

The more web developers contribute, the more useful it can get.

**Comment by omidfi** [comment]
Forgot the url 
http://howtoannoyawebdeveloper.com

**Comment by jerodsanto** [comment]
@omidfi thanks for pinging us! We're going to pass on covering this, but keep up the great work and don't hesitate to try again with future projects! 💚
