### ISSUE TITLE
Transcrypt: new Python to JavaScript compiler - fast, small, pythonic

### ISSUE THREAD

**Issue by JdeH** [thechangelog/ping#555]
**Transcrypt was recently released for production use. It has grown very fast, mainly due to its unique autotest feature that makes back to back regression testing with CPyton a snap. Keep an eye on it, via PyPi or GitHub. As development continues, it'll remain a rapidly moving target!** 

[http://www.transcrypt.org](http://www.transcrypt.org)

Python is a clean, expressive programming language in which reliable, maintainable applications can be developed. To harness the power of Python for increasingly complex web applications, several Python to JavaScript translators have been developed. One thing they all have in common, is that they strike a balance between speed and completeness. Transcrypt does that as well, in its own, unique way. This may make it your way to the honeypot.
- On one hand Transcrypt produces readable, debuggable, lean and mean JavaScript. The minified downloads are measured in kB's rather than MB's. And it's precompiled for speed. As for the availabity of libraries, a clear choice has been made to seamlessly integrate with the JavaScript universe of free, high-quality web oriented software. No need to reinvent the wheel. Calling JavaScript functions from Python, attaching Python event handlers to DOM elements, passing native data between Python and JavaScript, it all happens without any conversion or special syntax.
- On the other hand Transcrypt tries to stay as close to the Python original as possible. Multiple inheritance, recursive tuple assignment, multi-loop nested list comprehensions, LHS and RHS extended slices, assignment of bound functions, lambdas, named, default, _args and *_kwargs parameters, properties, optional operator overloading, iterators, generators, selective exception handling and a hierarchical module system are just a few of its characteristics that make this clear. Transcrypt is parsed by CPython's AST module, so no surprises there.
- Transcrypt features multi-level sourcemaps, so you can debug your application comfortably, working from the Python source code in your browser, even if the generated JavaScript is minified. This facility is fully integrated in the distribution, as is static checking, one simple pip install will get you started.

**Web client coding can be fun!**

Follow us on Twitter at [#TranscryptOrg](https://twitter.com/TranscryptOrg)

**Comment by jerodsanto** [comment]
@JdeH nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Transcrypt up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by JdeH** [comment]
Thanks! What the project needs most now is mindshare...
