### ISSUE TITLE
RFC#2 Mention of Government Open Source

### ISSUE THREAD

**Issue by mattharr** [thechangelog/ping#556]
Hi,

Just finished listening to Request For Change episode 2, which I thought was really interesting stuff, digging into the Open Source area.

One of the things mentioned towards the end of the show was the idea of having a discussion around Open Source in government, and how its different to other areas.  This was just a note to say I'd be interested in listening to such a discussion, particularly given the (so far limited, but..) push from the US government.  I think it's an idea that makes a lot of sense, so it would be interesting to hear about the issues that need to be considered, and approaches for trying it out in a governmental setting (and if possible looking at non-US settings would be great).

Thanks,

Matt

**Comment by mikeal** [comment]
I think we talk a little bit more about this topic in an upcoming show as well :)

**Comment by jerodsanto** [comment]
@mattharr thanks for listening! In addition to Mikeal's tease, we are recording an episode of The Changelog [on September 14th](https://changelog.com/schedule/) with Hillary Hartley and Aidan Feldman about [18F](https://18f.gsa.gov). If you have any specific questions for them that you want us to ask, let us know here and we'll be sure to ask. 🍻

**Comment by jerodsanto** [comment]
@mattharr we've shipped The Changelog episode all about open source in government with the folks at 18F: https://changelog.com/podcast/230

Closing this, but thanks for the feedback! 💚
