### ISSUE TITLE
ironsftp - end-to-end encryption on ssh servers

### ISSUE THREAD

**Issue by zmre** [thechangelog/ping#557]
IronSFTP is an open source tool that turns any ssh server into an encrypted file server. It is an alternative to the regular SFTP client that encrypts files before uploading them and leaves them encrypted on the server such that only authorized users can download and decrypt the files.  

This is a command-line tool intended for developers and IT folk who handle sensitive data including customer data that's been copied to development servers to reproduce bugs. 
- [Home page](https://ironcorelabs.com/products/ironsftp/)
- [Github source](github.com/ironcorelabs/ironssh)

**Comment by jerodsanto** [comment]
@zmre I'm confused. Is it called IronSFTP or IronSSH? Seems both names are used in places.

**Comment by zmre** [comment]
Sorry for that confusion.  We're calling it IronSFTP.  The repo is called `ironssh` and internally we briefly called it that.  But since it doesn't replace ssh, that makes little sense.  For now, it has `ironsftp` as a tool.  Soon we'll release `ironscp` as well, but we'll still call the whole thing IronSFTP.  Hope that makes sense and sorry for that confusion.  We should probably rename the github repo.

**Comment by jerodsanto** [comment]
Cool, no problem. We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly).

We :shipit: this weekend. :beers:
