### ISSUE TITLE
GopherConIndia 2017

### ISSUE THREAD

**Issue by IndianGuru** [thechangelog/ping#558]
Wanted to share with the community the upcoming Go conference in India. 
Registration - http://www.gophercon.in/registration-information/
CFP - http://www.gophercon.in/call-for-proposal/

It's also a great opportunity for companies to get exposure to a hot community of developers in India, via sponsorship (http://www.gophercon.in/pdf/gophercon-india-sponsorship-prospectus.pdf).

**Comment by jerodsanto** [comment]
@IndianGuru 💚 we'll give this a shout in our next issue of [Weekly](https://changelog.com/weekly) 🍻
