### ISSUE TITLE
New Project: ZoneMTA, a modern open source outbound MTA to send email

### ISSUE THREAD

**Issue by andris9** [thechangelog/ping#559]
ZoneMTA https://github.com/zone-eu/zone-mta is a modern MTA built with Node.js and LevelDB. It can do most of the things commercial MTA's provide, eg. routing messages through different queues and IP addresses, rewriting HTML content to add tracking links, built-in DKIM signing support etc.

It's self contained, fast (send millions of messages), flexible (control it with your own HTTP endpoints) and runs on every platform you can get Node.js up and LevelDB compiled (this includes Windows)

**Comment by jerodsanto** [comment]
@andris9 we're including ZoneMTA in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
