### ISSUE TITLE
Approach0: A math-aware search engine for math.stackexchange.com

### ISSUE THREAD

**Issue by t-k-** [thechangelog/ping#560]
Approach0 is my side project, about to publish its first release version after over 500 commits.
The goal of this project is to provide Math SE users better search experience. (You can include math in your query now)

Project repo: https://github.com/approach0/search-engine

![](https://github.com/approach0/search-engine-docs-eng/raw/master/img/clip.gif)

Just want more people to know and possibly anyone interested can join in the development and push this project forward (I have a lot time constraint and cannot focus on this project with full-time effort).

Thanks!

Wei

**Comment by jerodsanto** [comment]
@t-k- nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by t-k-** [comment]
@jerodsanto Thanks for having my project in your tweet queue.
