### ISSUE TITLE
HRCloud2: A full-featured Cloud drive and personal assistant that you host from home.

### ISSUE THREAD

**Issue by zelon88** [thechangelog/ping#561]
https://github.com/zelon88/HRCloud2
![screenshot_hrcloud2_9-8-16_12](https://cloud.githubusercontent.com/assets/20216035/18398262/f19336e2-7699-11e6-9881-27540b799a7a.png)

Hi there!

I've got a project that I've been working on for quite some time now that, when installed and configured on a home-computer or NAS device, turns that computer into a personal Cloud drive server for you and your friends/family. The goal of the project is to take all of the functionality and usability that comes standard with most free Cloud services and give it to the end user in a package that enables them to host their own Cloud drive. 

This word-in-process platform (looking for contributors) creates and manages user-specific Cloud directories in the $CloudLoc defined in the config.php file. Any user uploaded data is placed into that users Cloud directory and temporarily copied to another user specific folder that is accesible over HTTP when requested by the user. Temporary hosted files are automatically cleaned, and there is never cross-contamination of user-files in the same directory. 

Currently HRCloud2 supports uploading, downloading, copying, and deleting multiple selected files per user operation. It can also unpack .rar, .zip, .tar, .tar.bz2, .7z, and .iso files to a user subdirectory. It can also create .rar, .zip, .tar, .tar.bz2, .7z, and .iso files from multiple selected user files. It can also convert archives, disk images, image files, music files, and document files to other file formats per user opertation. It can also rotate and resize image files during conversion. If ClamAV is installed and enabled in config.php, it will automatically update and scan itself and it's Cloud directories at appropriate times. 

In addition to HRCloud2 this package also includes HRAI, a very straightforward personal assistant/WIP-load-balancer that accept plain-speech commands and arguments and perform highly specialized tasks. HRAI can parse sentences with or without proper grammer and punctuation, and can execute multiple commands per user input string. Currently HRAI can perform several simple tasks, like poll it's own resource, CPU, and RAM usage, tell the user the time and date, sync it's nodecache, call for help (experimental), convert files, handle greetings/thanks/propositions and more.

There are more features in the works, such as a Python document scanner from Pyimagesearch that works similar to Microsoft Office Lens. Also in-process are the "search" and "PDF options" features which will enable users to search their Cloud for files and perform OCR and conversion operations on .PDF files, respectively. 

I like to think of myself as a highly engaged and passionate, programmer, albeit not very experienced. I'd love to find other passionate hobbyists who could help me overcome some of the obstacles with my project and help it really stand-out. I see a lot of services ready and willing to hold onto their users data for later use as business collateral, which leads me to believe that someday there will be a niche in keeping personal files personal without compromising security or accesibility. I believe this project has the potential to fill a void in the Cloud and Open-Source communities that would only benefit end-users.

Thanks for checking out my project! Feel free to lay on the critique heavy. I can take it (I hope. ;) )

https://github.com/zelon88/HRCloud2

**Comment by jerodsanto** [comment]
@zelon88 fun! I think personal clouds are super interesting and love what you're up to here. We'll link HRCloud2 up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). It won't guarantee you'll find other passionate hobbyists to help out, but it'll at least increase your odds :).

We :shipit: this weekend. :beers:
