### ISSUE TITLE
Exercism followup

### ISSUE THREAD

**Issue by parkerl** [thechangelog/ping#563]
You should invite @kytrinyx on to talk about the challenges of being a maintainer of maintainers. I know you had her on in episode 108. However, exercism now has 32+ language tracks, more than double that in sub-projects, and she has 62 teams. Each language track has a set of maintainers that have there own styles. IMHO, it is bananas. Think about it. She has PRs coming in with anything from Ruby to Assembly.

**Comment by jerodsanto** [comment]
@parkerl we are definitely due to have @kytrinyx back on the show. In fact, I have it on good authority that she will be guesting on [Go Time](http://gotime.fm) Real Soon™.

I'm going to close this issue because cleanliness, but I'll definitely post a follow-up here when we have her back on. 💚
