### ISSUE TITLE
Cesium: 3D globe engine

### ISSUE THREAD

**Issue by slchow** [thechangelog/ping#564]
Cesium is an open-source JavaScript library for 3D globes and maps. It allows developers to visualize geospatial data, including time-dynamic. It's been used for everything from tracing satellites to tracking paragliders to monitoring energy usage of city buildings, and most importantly in NORAD's Santa Tracker: http://cesiumjs.org/demos/noradtrackssanta.html

We have a lot of contributors and users, and the community has been growing rapidly, especially since the announcement that Google Earth is being deprecated. 
- GitHub repo: https://github.com/AnalyticalGraphicsInc/cesium
- Homepage: http://cesiumjs.org/index.html
- Demos: http://cesiumjs.org/demos.html (NORAD's Santa Tracker is the best known:)

**Comment by jerodsanto** [comment]
@slchow this is super cool! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by slchow** [comment]
Awesome! Can't wait for it to come out.
