### ISSUE TITLE
IEnumerable

### ISSUE THREAD

**Issue by mbasso** [thechangelog/ping#565]
> Deep immutable, Lightweight Enumerable with superpowers
- [https://ienumerable.js.org](https://ienumerable.js.org/)
- [https://github.com/mbasso/ienumerable](https://github.com/mbasso/ienumerable)

IEnumerable is a library that allows you to create deeply immutable collections and query them with a Linq syntax. IEnumerable infact, is born from the idea to bring [Linq](https://msdn.microsoft.com/en-us/library/bb397926.aspx) in JavaScript environment. Linq is a fantastic technique to query data and JavaScript should have it. In addition, we want to maintain the advantages of [Immutable Js](https://facebook.github.io/immutable-js/) and improve them. In IEnumerable, not only the collection is immutable but also its content. Every method will return a new Enumerable and a new copy of its content.

**Comment by jerodsanto** [comment]
@mbasso thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
