### ISSUE TITLE
Loco

### ISSUE THREAD

**Issue by himn1** [thechangelog/ping#566]
![logo](https://raw.githubusercontent.com/artofcodelabs/artofcodelabs.github.io/master/images/ext/loco_logo_trans_sqr-300px.png)

Hi guys!

I am writing to you because I recently open-sourced a project that I was working on for > last year. It's called Loco and it's a framework (for a lack of better word ;) but… - it works on top of Rails. So it is rather a meta-framework or uber-framework - so to speak :)

Loco is made up of two cooperating parts. First part is a front-end MVC+ framework called Loco-JS. It provides structure for JavaScript assets, supplies base classes for models, controllers, views and can work autonomously. 

Second part of Loco is a Rails Engine called Loco-Rails. It allows you to simply send notifications (emit signals) from any part of the system, directly to associated JavaScript models and all connected with them JavaScript objects (e.g. controllers, views). And you can do this basically in 1 line of code. For example:

``` ruby
emit article, :created, for: [Admin, article.user], data: {foo: "bar"}
```

Then **receivedSignal** method for given connected JavaScript objects is called automatically. Everything is done under the hood via ajax polling by Loco framework. But Loco can also cooperate perfectly with ActionCable. Main repository contains a simple project which demonstrates that. 

https://github.com/locoframework 

Besides that Loco-Rails repository contains decent-size demo app under test/dummy which shows different implementation strategies of many common features using Loco. 

Also, according to this article https://dockyard.com/blog/2016/08/09/phoenix-channels-vs-rails-action-cable by Chris McCord - ActionCable has some performance issues so it is good to have a fallback which Loco ensures.

And all of that is just the top of an iceberg ;) Both projects have README pages that describe in great detail nearly all features of Loco.
So if you find it interesting, it would be great if you mention about Loco framework in the Changelog Weekly.

Greetings from Cracow, Poland

Zbigniew Humeniuk
hello@artofcode.co

**Comment by himn1** [comment]
Hi @jerodsanto 
I've uploaded a quick video demo of Rails and Loco collaboration. It's more descriptive in terms of Loco's features than text. If not the content, you might love the sound ;)

[![Loco: demo](http://img.youtube.com/vi/05iJNyIKZZU/0.jpg)](http://www.youtube.com/watch?v=05iJNyIKZZU)

Thx,
Zbig

**Comment by jerodsanto** [comment]
@himn1 we'll link Loco up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by himn1** [comment]
Thank you! I'm looking forward to it.

Regards,

Zbigniew Humeniuk
http://artofcode.co
hello@artofcode.co

2016-12-10 21:33 GMT+01:00 Jerod Santo <notifications@github.com>:
