### ISSUE TITLE
Nodebeats, an Open Source Content Management System built using MEAN Framework

### ISSUE THREAD

**Issue by nodebeats** [thechangelog/ping#567]
Nodebeats is an Open Source Content Management System built using MEAN Framework that allows you to create web-applications with ease. It is built on top of a RESTful JSON api. You can easily create custom modules on top of this Content Management System and quickly launch your web application.

[https://www.nodebeats.com](https://www.nodebeats.com)

![homepage_m0guov](https://cloud.githubusercontent.com/assets/20926160/18539139/9f0adf66-7b34-11e6-8521-4282381e4b9a.png)

**Comment by jerodsanto** [comment]
@nodebeats cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by nodebeats** [comment]
Thank You very very much. That would be very morale boosting for us to even do more and make Nodebeats CMS highly secured and optimized. We have updated the CMS website with the latest code and also doing demo application to reflect the latest changes. Once demo is deployed successfully which we hope to do by this coming sunday, then we will  be releasing Nodbeats major release version 1. 
Once again, Thank You very much for your support
