### ISSUE TITLE
awesome-cryptography

### ISSUE THREAD

**Issue by sobolevn** [thechangelog/ping#569]
A curated list of cryptography resources and links.

![awesome-cryptography](https://pbs.twimg.com/profile_images/751426570607271937/vGxpniun_400x400.jpg)

GitHub: https://github.com/sobolevn/awesome-cryptography
Twitter: https://twitter.com/awe_crypto_bot
Contact: mail@sobolevn.me

**Comment by jerodsanto** [comment]
@sobolevn we'll mention this [on twitter!](https://twitter.com/changelog)  :fist: :green_heart:
