### ISSUE TITLE
BubbleAnimationLayout

### ISSUE THREAD

**Issue by vladdmitriev** [thechangelog/ping#570]
Hello,

Hope all's well. 

Could you add our new open source project into your digest?

BubbleAnimationLayout - https://github.com/Cleveroad/BubbleAnimationLayout

![bubble](https://cloud.githubusercontent.com/assets/20402305/18672270/22e660c0-7f50-11e6-96b1-a467a93e5b49.gif)

Watch a [demo](https://www.youtube.com/watch?v=rk6tTDJwB7k&feature=youtu.be&list=PLi-FH7__aeiydOwY_1q5I8P2EUSseqUCj) on YouTube.

Best,
Vlad

**Comment by jerodsanto** [comment]
@vladdmitriev it looks really slow in the gif, is this how it performs IRL or just an artifact of a not-great-gif?

**Comment by vladdmitriev** [comment]
@jerodsanto Yes, the animation could be speeded up! It was made with current settings, which you could change.

**Comment by jerodsanto** [comment]
@vladdmitriev we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :green_heart:
