### ISSUE TITLE
Kickoff - a continuous monitoring tool for your SEO, performance and security requirements

### ISSUE THREAD

**Issue by frickelbruder** [thechangelog/ping#571]
Hi there,

I recently released my open source project "kickoff".
Its aim is to help webdelevopers to keep simple website aspects as delivering an HTML document in less than (eg.) 1 second, use the HttpOnly-Flag on Cookies, always sending X-XSS-Protection HTTP-header, using an 30-70 characters long title tag and many other aspects.
During the lifecycle of a vivd project many changes to a website or its infrastructure occur, so easyily some of the former well crafted solutions somehow get buggy. For example your project moves to another server and suddenly all the configured security flags are forgotten to migrate, or some minor tweaks on the code cause the loss of a formerly existing "Link:"-HTTP-tag. Kickoff helps you, to keep those typical SEO, security and performance aspects of your page.

The advantage of kickoff is, that it can be integrated into the continous delivery process, so that after delivering your page you can run a "kickoff"-task and be sure, your website works as before.

More infos can be obtained at https://github.com/frickelbruder/kickoff and http://frickelbruder.github.io/kickoff/

Thank you,
Markus

**Comment by jerodsanto** [comment]
@frickelbruder thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
