### ISSUE TITLE
[Podcast suggestion] IntermezzOS

### ISSUE THREAD

**Issue by ejunker** [thechangelog/ping#572]
intermezzOS is a teaching operating system, specifically focused on introducing systems programming concepts to experienced developers from other areas of programming.

[http://intermezzos.github.io](http://intermezzos.github.io)

**Comment by benoittgt** [comment]
Good idea @ejunker

**Comment by steveklabnik** [comment]
That'd be great!

**Comment by jerodsanto** [comment]
@ejunker good idea, thanks! 💚 

@steveklabnik let's do it! Please email editors@changelog.com and we'll get it scheduled.

**Comment by steveklabnik** [comment]
👍 /cc @ashleygwilliams

**Comment by ashleygwilliams** [comment]
yeah! this would be fun :)

**Comment by jerodsanto** [comment]
@steveklabnik @ashleygwilliams yessss! ✊

**Comment by jerodsanto** [comment]
@ejunker and friends, this one is in the works! Closing, but will post a link here when show is published.

**Comment by steveklabnik** [comment]
Yup! Pumped, coordination is just tough.
