### ISSUE TITLE
Get Flowtype Errors as ESLint Errors

### ISSUE THREAD

**Issue by amilajack** [thechangelog/ping#573]
[Flow](https://github.com/facebook/flow) is a static type checker for Javascript and is considered an alternative to TypeScript. At the moment, flow is only well integrated with nuclide. This plugin makes it so that anyone with ESLint integration can get started with flow easily.

Here's a demo:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Note: In this demo, I am using atom with the packages 'linter' and 'linter-eslint'

https://github.com/amilajack/eslint-plugin-flowtype-errors

**Comment by jerodsanto** [comment]
@amilajack thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
