### ISSUE TITLE
HubGraph - Grab the latest events from GitHub's API and build a graph upon them!

### ISSUE THREAD

**Issue by nmaggioni** [thechangelog/ping#574]
HubGraph is a fun and entertaining way to visualize what's happening on GitHub at the moment: it turns any event in the public API into a node for a force-connected graph backed by [D3.js](http://d3js.org/). Every node is colored differently basing on the type of the event, and the whole graph is refreshed continuously.

_It just needs an automatic switch to a dark theme to become a perfect digital painting for your room._

https://github.com/nmaggioni/HubGraph

![HubGraph's banner](https://raw.githubusercontent.com/nmaggioni/HubGraph/master/banner.png)

**Comment by jerodsanto** [comment]
@nmaggioni nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link HubGraph up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by nmaggioni** [comment]
Awesome! You guys do a great job :smile:
