### ISSUE TITLE
text-spinners

### ISSUE THREAD

**Issue by maxbeier** [thechangelog/ping#576]
Hi,

[text-spinners](https://github.com/tawian/text-spinners) is (yet another) collection of loading indicators for web pages, but this time purely text based (and CSS only), mimicking those known from the command line (and bringing that comfy `npm install` feeling into the browser).

[![Preview](http://tawian.io/text-spinners/spinners.gif)](http://tawian.io/text-spinners/)

P.S. Thanks for your work!

**Comment by jerodsanto** [comment]
@maxbeier very cool, it looks like these have garnered a fair amount of ⭐️s already!

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also include text-spinners in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

🚢ing soon :green_heart:
