### ISSUE TITLE
opening up your source

### ISSUE THREAD

**Issue by kennyg** [thechangelog/ping#577]
I saw your post https://changelog.com/trello-as-a-cms/?utm_content=buffer7c2ec&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer and took a swag at genericizing the gist like was suggested in the article. what's next?

**Comment by jerodsanto** [comment]
@kennyg happy to hear we inspired you to bust out the text editor. :)

There have been similar efforts. I know the Code Newbie team put [something together](https://github.com/code-newbies/trello_newsletter) based on our process, too. What'd you come up with?

**Comment by jerodsanto** [comment]
Closing this for Spring Cleaning. Please open a new issue ([or hit us up on Slack](https://changelog.com/community)) to continue the conversation!
