### ISSUE TITLE
Unofficial Overcast for Mac (open source)

### ISSUE THREAD

**Issue by oskarkrawczyk** [thechangelog/ping#578]
https://github.com/oskarkrawczyk/overcast-mac

Always wanted an Overcast client for Mac, but unfortunately Marco has no plans on doing this, so figured I might as well do it myself by wrapping the overcast website in Electron.

**Comment by jerodsanto** [comment]
@oskarkrawczyk very cool, I'm an Overcast user myself so I might have to check this out. We'll mention it [on twitter!](https://twitter.com/changelog)  :fist: :green_heart:

**Comment by oskarkrawczyk** [comment]
@jerodsanto Awesome, thanks! I have a bunch of ideas and todos in place, would be great to get some extra exposure so perhaps someone from the OSS community can help out ✌️
