### ISSUE TITLE
[Podcast suggestion] IT Archetypes book

### ISSUE THREAD

**Issue by dimitrismistriotis** [thechangelog/ping#579]
IT Archetypes explores the social aspects of IT and the people involved by separating them into three archetypes which are then analyzed in the first chapters. Based on this the following chapters examine companies, methodologies and other concepts though these lenses. The book is also summarized as: "_In an era defined by software, we actually know very little about the people who write all those lines of code that power it. This book aims to change that_" or "_a know thyself guide for the IT people, a know thy-friends guide for the ones that interact with them_".

Links:
- Site: http://www.itarchetypes.com
- Presentation: https://docs.google.com/presentation/d/1lR4BkQ4yU94Yi6xJ10yRKUGFJyPOXy_BZ-SWnOcxO54/edit

Disclaimer: I am the author of the book.

**Comment by jerodsanto** [comment]
@dimitrismistriotis thanks for pinging us! Your book looks very interesting, but I don't think this is a perfect fit for the podcast.

However, we will link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly) for you. 💚

**Comment by dimitrismistriotis** [comment]
Thanks so much.
