### ISSUE TITLE
SolidFrame: Cross-platform C++ framework ...

### ISSUE THREAD

**Issue by vipalade** [thechangelog/ping#580]
... for asynchronous, distributed client-server applications.

[Project Home](https://github.com/vipalade/solidframe)

Most notable is the Message Passing IPC library. Please follow the following tutorials:
- [MPIPC Echo](https://github.com/vipalade/solidframe/tree/master/tutorials/mpipc_echo)
- [MPIPC Request](https://github.com/vipalade/solidframe/tree/master/tutorials/mpipc_request)
- [MPIPC Request](https://github.com/vipalade/solidframe/tree/master/tutorials/mpipc_file)

**Comment by jerodsanto** [comment]
@vipalade thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
