### ISSUE TITLE
cli-emoji: emojis rendered as text art in your terminal

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#581]
https://github.com/IonicaBizau/cli-emoji :grin:

**Comment by jerodsanto** [comment]
@IonicaBizau I bet you didn't expect this ping to turn in to a technical support opportunity, but it sure has! 😂

I tried running this on my machine and am getting this error:

```
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "https://github.global.ssl.fastly.net/images/icons/emoji/:green_heart:.png?v5" this most likely means the gm/convert binaries can't be found
```

I have imagemagick installed via homebrew:

```
jerod@jerbookpro:~$ which convert
/usr/local/bin/convert
```

```
jerod@jerbookpro:~$ brew info imagemagick
imagemagick: stable 6.9.6-8 (bottled), HEAD
Tools and libraries to manipulate images in many formats
https://www.imagemagick.org/
/usr/local/Cellar/imagemagick/6.9.6-4 (1,467 files, 22.3M)
  Poured from bottle on 2016-11-11 at 16:20:27
/usr/local/Cellar/imagemagick/6.9.6-8 (1,465 files, 22.2M) *
  Poured from bottle on 2016-12-12 at 09:12:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb
```

Any ideas?

**Comment by IonicaBizau** [comment]
@jerodsanto Whoups! Make sure you have GraphicsMagick installed: `brew install graphicsmagick`

Specifically, `which gm` should show something. 😁

**Comment by jerodsanto** [comment]
@IonicaBizau good call! Maybe a mention in the readme would help 😄 

I just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Weekly](https://changelog.com/weekly/).
