### ISSUE TITLE
"The legacy of Pieter Hintjens" - blog post for newsletter

### ISSUE THREAD

**Issue by pavsaund** [thechangelog/ping#582]
https://zombiecodekill.com/2016/10/06/the-legacy-of-pieter-hintjens/

Kevin O’Shaughnessy has written a piece dedicated to the late Pieter Hintjens. I'm sure there are other similar posts, but perhaps this is something to be shared as a "Dedicated to Pieter Hintjens"-section?

Thanks.

**Comment by jerodsanto** [comment]
@pavsaund 👍 we'll definitely include this. 💚
