### ISSUE TITLE
Trestus - the Trello board ⇒ status page static generator

### ISSUE THREAD

**Issue by 1stvamp** [thechangelog/ping#583]
Hi there,

[trestus](https://canonical-ols.github.io/trestus/) is a tool for generating a service status page, to inform customers of outages, from a specially setup [Trello](https://trello.com/) board, allowing you to easily add markdown formatted descriptions and comments to update the status of an incident by dragging it's card between columns.

It is actually inspired by The Changelog's "Trello as a CMS" methodology for creating the newsletter, as well as the excellent [statuspage](https://github.com/jayfk/statuspage) tool which works similarly but uses Github issues rather than Trello cards.

**Comment by jerodsanto** [comment]
@1stvamp very cool! Happy to inspire you a bit on this one. 😄

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link trestus up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
