### ISSUE TITLE
gedcom4j just released v4.0.0

### ISSUE THREAD

**Issue by frizbog** [thechangelog/ping#584]
Hello folks at Changelog!

I wanted to let you know that v4.0.0 of gedcom4j was released today. gedcom4j is a java library for parsing and writing GEDCOM files, which are the de-facto standard file format for exchanging genealogical data.  v4.0.0 is a pretty big release, with a reworked validation framework and improved support for custom (user-defined) data.

You can find gedcom4j at:
- frizbog/gedcom4j at GitHub
- @gedcom4j on Twitter
- https://www.facebook.com/Gedcom4j/ on Facebook
- and of course, at http://gedcom4j.org 

Thanks!

**Comment by jerodsanto** [comment]
@frizbog congrats on the release! We're including gedcom4j in our next issue of [Weekly](https://changelog.com/weekly/)! :green_heart:
