### ISSUE TITLE
Website issue: Filling out forms while listening

### ISSUE THREAD

**Issue by lawik** [thechangelog/ping#585]
I kept pausing the playback trying to write a space in my name while registering for Weekly. And I think I lost the playback when I submitted.

Just thought you might want a headsup and didn't see any other appropriate repo for it.

**Comment by jerodsanto** [comment]
@lawik good catch! I didn't think about the case where you're filling out a form and the player is active. Also need to resume play position after form submits. Lots to do..

**Comment by jerodsanto** [comment]
@lawik all fixed now, thanks again for the 🐛 report!

_(Once we open source the website, you can use its issue tracker for feature requests/bug reports.)_
