### ISSUE TITLE
Hotel - Start apps from your browser and get local domains for free

### ISSUE THREAD

**Issue by typicode** [thechangelog/ping#586]
Hi @thechangelog,

I'd like to share [Hotel](https://github.com/typicode/hotel). It lets you access your local dev server from your browser.

No need to remember commands, ports or even open a Terminal, ... and you can use `http/https` with local `.dev` domains.

Hotel is very simple and doesn't require admin privileges. It also works with everything (Node, PHP, Docker, ...) and is cross-platform (OS X, Linux, Windows).

It can be seen as an easy process manager for front-end developers.

**YouTube tutorial**
https://www.youtube.com/watch?v=BHW4tzctQ0k

**GIF**
![](http://i.imgur.com/DrLjbIi.gif)

**Comment by jerodsanto** [comment]
@typicode wow, this looks really nice. Well done!

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by typicode** [comment]
@jerodsanto Thank you :)
