### ISSUE TITLE
JobsToMail: The Personal Assistant for Job Seekers

### ISSUE THREAD

**Issue by karllhughes** [thechangelog/ping#587]
[JobsToMail](https://www.jobstomail.com/) is an open source, free tool for job seekers who want to get a daily email of all the new job listings matching their search criteria across 8+ different job boards.

**Comment by jerodsanto** [comment]
@karllhughes we're including JobsToMail in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
