### ISSUE TITLE
Vue Material

### ISSUE THREAD

**Issue by marcosmoura** [thechangelog/ping#588]
**[Vue Material](https://marcosmoura.github.io/vue-material/)**
Material Design for Vue.js 2.0. 
Lightweight components built from scratch exactly according to the specs.

**Comment by jerodsanto** [comment]
@marcosmoura nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
