### ISSUE TITLE
-bash: npm: command not found

### ISSUE THREAD

**Issue by tripship** [thechangelog/ping#589]
I ran Hungs-MacBook-Pro-2:~ hungcao$ npm install -g grunt-cli   and got -bash: npm: command not found

so i ran sudo nano /etc/paths  the path is there so i don't know why its not working

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

**Comment by jerodsanto** [comment]
I don't think you have npm installed, but you'd get a lot better help on a site like [StackOverflow](https://stackoverflow.com). I advise submitting your question there.

**Comment by tripship** [comment]
I have it installed, because node is installed.
