### ISSUE TITLE
[Podcast Suggestion] Dave Gandy - Font Awesome

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#590]
@davegandy is the founder of [Font Awesome](https://github.com/FortAwesome/Font-Awesome) the [7th most popular repo](https://github.com/search?q=stars%3a%3E1&s=stars&type=Repositories) on GitHub. Him and his team are getting ready to launch Font Awesome 5 which reached it's goal of $30,000 in less than ~5 hours on [Kickstarter](https://www.kickstarter.com/projects/232193852/font-awesome-5?ref=thanks_tweet).

Would love to hear what's new with him and his team, why they decided to completely start FA5 from scratch and who was behind the creating their epic Kickstarter video.

**Comment by adamstac** [comment]
👍

**Comment by davegandy** [comment]
Oh, I am SO down for this. 👍

**Comment by jerodsanto** [comment]
Let's do it! @davegandy please email editors@changelog.com to coordinate the schedule. 

🍻

**Comment by jerodsanto** [comment]
Closing because shipped!

https://changelog.com/podcast/226
