### ISSUE TITLE
TRX Swift animation framework

### ISSUE THREAD

**Issue by modzelewski** [thechangelog/ping#591]
Hi,

Just released **[TRX](https://github.com/Trxy/TRX) 0.5.0** with **Swift 3.0** support targeting **iOS 8.4+** and **tvOS 9.0+**. 
[TRX](https://github.com/Trxy/TRX) is an **animation library** that makes it easy to pause, reverse, chain, overlap, overwrite and scrub animations.

In short [TRX](https://github.com/Trxy/TRX) gives developers high-level control over animation properties making them fully interactive.

[@AKModzelewski](https://twitter.com/AKModzelewski)
Cheers

**Comment by jerodsanto** [comment]
@modzelewski nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link TRX up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by modzelewski** [comment]
Great news, thanks! 🎉
