### ISSUE TITLE
git-stats 2.10.0

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#592]
Released git-stats 2.10.0: https://github.com/IonicaBizau/git-stats

It supports exporting the stats as HTML using [`git-stats-html`](https://github.com/IonicaBizau/git-stats-html) and images.

Also, literally fixed all the bugs. :smile:

**Comment by jerodsanto** [comment]
@IonicaBizau we'll mention this [on twitter!](https://twitter.com/changelog)  :fist: :green_heart:

**Comment by IonicaBizau** [comment]
@jerodsanto Thanks! 😄
