### ISSUE TITLE
app-tab-bar

### ISSUE THREAD

**Issue by ErlendEllingsen** [thechangelog/ping#594]
Hi @thechangelog

I have created a tab-bar system in HTML/JS for hybrid apps / web apps. It is primarily targeted at hybrid apps that run in frameworks like _cordova_ or _phonegap_, but also works great for both mobile and desktop websites and other web-apps.

I would love to share this with the world! It is available here: [https://erlendellingsen.github.io/app-tab-bar/](https://erlendellingsen.github.io/app-tab-bar/)

**Comment by jerodsanto** [comment]
@ErlendEllingsen cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
