### ISSUE TITLE
New Version v0.4 release of Nodebeats, a Content Management System using MEAN Framework

### ISSUE THREAD

**Issue by ShrawanLakhe** [thechangelog/ping#595]
Nodebeats is an Open source Content Management System built using MEAN framework. Nodebeats makes it easy to create web sites and applications and comes with beautiful admin UI.

Nodebeats provides following features:

Two factor authentication
Token based authentication
Role based authorization
Authorization Token Management
Real time Google Analytics data
Host of options for email service providers like Mailgun, Postmark, Sendgrid, Mandrill, Google SMTP etc.
Integration with Cloudinary for Image management
Commenting system using Disqus
And many more features that you will love to have around.

For more detailed information , please visit the following link:

www.nodebeats.com

**Comment by jerodsanto** [comment]
@ShrawanLakhe thanks for showing us this! We've been pinged about it previously. Closing this in favor of #567. (we will give the project some love soon, I promise 💚)
