### ISSUE TITLE
Cloudflair, Ruby wrapper for Cloudflare v4 API

### ISSUE THREAD

**Issue by cimnine** [thechangelog/ping#597]
Hi

The company I work at ([nine.ch](https://nine.ch), a Swiss hosting company) decided to opensource (MIT license) our API-wrapper for Cloudflare's v4 API with the brilliant name 'Cloudflair'.
It's made for Ruby and is very simple to use. It's strictly organized along the URL schema of the API. Two examples:

```ruby
# Actual API call: GET https://api.cloudflare.com/client/v4/zones
Cloudflair.zones
# => [...]

# Actual API call: GET https://api.cloudflare.com/client/v4/zones/cd7d068de3012345da9420df9514dad0
Cloudflair.zone('023e105f4ecef8ad9ca31a8372d0c353').name
# => "blog.example.com"
```

We already use the API internally. Since it's still pretty new, we want to battle-proof it some more until we declare it 1.0.0.

Further information, as always, at the repository itself: https://github.com/ninech/cloudflair

Cheers,
Chris

**Comment by jerodsanto** [comment]
@cimnine we'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
