### ISSUE TITLE
Open source image placeholder site

### ISSUE THREAD

**Issue by kylehayes** [thechangelog/ping#598]
There are a lot of sites out there that offer image placeholder services but one of them was one of the first to be made and is also open source. 

http://fpoimg.com (FPO = For Placement Only) allows one to easily create fake placeholder images in copy before final imagery is available. Written in Python and hosted on Heroku, this project is open source and can be forked here: https://github.com/kylehayes/fpoimg

**Comment by jerodsanto** [comment]
@kylehayes thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
