### ISSUE TITLE
web3j lightweight Ethereum blockchain library for Java applications - milestone v1.0 release

### ISSUE THREAD

**Issue by conor10** [thechangelog/ping#599]
Given you guys have been talking about blockchain (especially after the Gavin Wood interview), and with the upcoming chat with the Chain team, I thought you might be interested in [web3j](https://github.com/web3j/web3j).

web3j allows Java (+ any JVM language) applications to easily integrate with the Ethereum blockchain, and it's just had it's milestone 1.0 release, which I announced last week

https://www.reddit.com/r/ethereum/comments/5b2xi3/web3j_lightweight_ethereum_library_for_java/

Keep up the good work - I've been blown away by the content on your podcast. It's a techie's dream!

**Comment by jerodsanto** [comment]
@conor10 thanks for the kind words! :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by adamstac** [comment]
@conor10 if you haven't yet, you should check out this episode we recorded at All Things Open - https://changelog.com/spotlight/4

**Comment by conor10** [comment]
Awesome!

@adamstac - yeah, the IBM Fabric and the Chain episode were great too!

Since the above post there's been a number of [web3j](https://github.com/web3j/web3j) updates - the following text summarises this:

[web3j](https://github.com/web3j/web3j) allows Java (+ any JVM language) and Android applications to easily integrate with the Ethereum blockchain. It provides a reactive API for deploying and transacting with smart contracts, and querying the blockchain itself natively from Java. It also provides command line tools for managing Ethereum wallets and funds.

Also, 2017 has seen the release of [web3j-quorum](https://github.com/web3j/quorum) for working with [JP Morgan's Quorum](https://github.com/jpmorganchase/quorum) blockchain technology built on top of Ethereum.
