### ISSUE TITLE
redux-promise-middleware

### ISSUE THREAD

**Issue by pburtchaell** [thechangelog/ping#601]
**Link:** https://github.com/pburtchaell/redux-promise-middleware
**Description:** Redux promise middleware enables robust handling of async code in Redux. The middleware enables optimistic updates and dispatches pending, fulfilled and rejected actions. It can be combined with redux-thunk to chain async actions.

**Comment by jerodsanto** [comment]
@pburtchaell we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
