### ISSUE TITLE
Guest proposition (from PHP/Laravel community)

### ISSUE THREAD

**Issue by atefBB** [thechangelog/ping#602]
Peace Be Upon YOU ! ^^
I like your podcast, and I Like to know the stories of those guys (from PHP/Laravel community) like:
* Taylor Otwell (Creator of Laravel the PHP Framework for Artisans, https://twitter.com/taylorotwell).
* Jeffery Way (Creator of Laracasts.com, 'Netflix' site for web devs, https://twitter.com/jeffrey_way).
* Matt Stauffer (another Geeky!, https://twitter.com/stauffermatt)
* Adam Wathan (The Author of the great book 'Refactoring to Collections' & Host of the  http://www.fullstackadio.com/ 'A podcast for developers interested in building great software products', https://twitter.com/adamwathan).
* Eric L. Barnes (creator of Laravel-news.com, https://twitter.com/ericlbarnes).
* Mohamed Said (the dev n1 for Laravel https://twitter.com/themsaid).
and Thanks !

**Comment by jerodsanto** [comment]
@atefBB we've had Taylor on the show before. Give [episode 142](https://changelog.com/podcast/142) a listen and let us know what you think.

This list looks good but if you had to pick just one, who would you request? (Taylor round 2 is a legit option too).

**Comment by atefBB** [comment]
The episode is greaaaaaaaaaaaaat ! I enjoy it!
To pick just one is so difficult, but what about Mohamed Said !? or Adam Wathan ? and what about Matt?
As you can see, I can't just pick one ! ^^

**Comment by jerodsanto** [comment]
I think we're going to try to get Taylor back on. Thanks for this suggestion! 🍻
