### ISSUE TITLE
Lego

### ISSUE THREAD

**Issue by martijndeh** [thechangelog/ping#604]
[Lego](https://github.com/martijndeh/lego) is a lightweight SQL (string) builder using ES6 template strings. Lego embraces SQL instead of adding yet another abstraction layer.

**Comment by jerodsanto** [comment]
@martijndeh :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by martijndeh** [comment]
Great, thank you!
