### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by DerfOh** [thechangelog/ping#605]
Vault is a lightweight tool written in Go used for primarily for storing secrets and performing other secure storage and encryption tasks. It is highly extensible and flexible to fit the needs for most projects and solves many of the tough parts of storing and retrieving sensitive information. 

## [GitHub](https://github.com/hashicorp/vault)
 
@jefferai @armon @sethvargo I would love to hear from one of you on the podcast!

**Comment by sethvargo** [comment]
Hey @DerfOh 

Thank you for the ping. Do you want to have a conversation in the open, or would you prefer to move to email? If email, seth (at) hashicorp. If open - let me know how I can help! 😄

**Comment by jerodsanto** [comment]
@DerfOh I think this could make for a good show 👍 

@sethvargo hit us up at editors@changelog.com and we'll talk details!

**Comment by jerodsanto** [comment]
This show is now live! 🎉 

https://changelog.com/podcast/239

Thanks for the idea @DerfOh and for coming on @sethvargo!
