### ISSUE TITLE
CKEditor 4.6 released with a refreshed website

### ISSUE THREAD

**Issue by wojtekidd** [thechangelog/ping#606]
Hi

This message is just to let you know that we have released a new major version of [CKEditor](https://github.com/ckeditor/ckeditor-dev) (open source online rich text editor written in JavaScript) with new outstanding features and a refreshed skin. All of this comes with a completely refreshed website in terms of the design and UX.

Feel free to [check it out](http://ckeditor.com/blog/CKEditor-4.6-released).
All the best!

**Comment by jerodsanto** [comment]
@wojtekidd thanks for sharing this! We'll mention it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
