### ISSUE TITLE
Funnel

### ISSUE THREAD

**Issue by agnivade** [thechangelog/ping#607]
Funnel is a minimalist 12 factor log router written in Go. A lightweight version of Logstash/FluentD.

repo - https://github.com/agnivade/funnel
email - agniva.quicksilver@gmail.com

**Comment by jerodsanto** [comment]
@agnivade cool! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). 💚

**Comment by agnivade** [comment]
Awesome ! :heart:
