### ISSUE TITLE
Dante2 editor , a medium clone written in draftjs

### ISSUE THREAD

**Issue by michelson** [thechangelog/ping#608]
Hi guys , we would like to submit https://michelson.github.io/dante2/ , is a complete rewrite of dante editor, and is just another medium editor clone. written in facebook's draft-js library.

hope you like it

best!

**Comment by jerodsanto** [comment]
@michelson the big rewrite! We'll link Dante2 up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by michelson** [comment]
that's great!! thank you @jerodsanto !
