### ISSUE TITLE
Pottery: Redis for Humans

### ISSUE THREAD

**Issue by brainix** [thechangelog/ping#609]
Redis is awesome, 😀 but Redis commands are not always fun. 😡 [Pottery](https://github.com/brainix/pottery) is a Pythonic way to access Redis. If you know how to use Python dicts, then you already know how to use Pottery.

In addition to Redis-backed dicts, sets, and lists, Pottery provides a distributed ID generator, as well as a distributed lock.

**Comment by jerodsanto** [comment]
@brainix nice work! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Pottery up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by brainix** [comment]
Thank you, @jerodsanto!
