### ISSUE TITLE
Potential podcast topic(s): social web projects

### ISSUE THREAD

**Issue by strugee** [thechangelog/ping#610]
There's a bunch of really interesting work in the social web space that I think would be great for The Changelog. Each one of these could probably be its own episode:

* The [IndieWeb][1] is really neat - tl;dr it's about progressively-enhancing blogs into awesome, federated social systems
* [Pump.io][2] is a federated social network (notably identi.ca runs pump.io), but can also be thought of as a generic social engine to build stuff on top of
* The [Social Working Group][3] at the W3C is working super hard to standardize a bunch of the IndieWeb protocols, along with protocols that are similar to/improve upon pump.io's design

Full disclosure: I'm basically the primary maintainer of pump.io these days, and I'm _somewhat_ involved with (parts of) the SocialWG because of that (although not an actual member).

 [1]: https://indieweb.org/
 [2]: http://pump.io/
 [3]: https://www.w3.org/wiki/Socialwg

**Comment by jerodsanto** [comment]
@strugee we accidentally recorded an episode about this when interviewing Fuzzy.ai's Evan Prodromou. That conversation was going to be about AI, but given Evan's background and involvement with the SocialWG, we covered these topics quite a bit!

That show ships  Real Soon Now. 

I'm going to close this issue, but thanks for pinging us and keep fighting the good fight!

**Comment by strugee** [comment]
@jerodsanto hahahahaha oh my. That doesn't surprise me.

Looking forward to listening :-)

**Comment by clacke** [comment]
And it's out! https://changelog.com/podcast/257
