### ISSUE TITLE
Potential podcast topic: Nextcloud

### ISSUE THREAD

**Issue by strugee** [thechangelog/ping#611]
I'd really love to hear a Changelog episode on Nextcloud. It'd be interesting to hear about how the fork's going, how ownCloud's changed since the fork, the future of the company, etc.

**Comment by pirate** [comment]
Yeah! Seconded!

**Comment by JoeKun** [comment]
+1

I'd really love to get a Changelog episode on Nextcloud.

**Comment by jerodsanto** [comment]
Three years later but we're working on this one! 😆

**Comment by strugee** [comment]
😍
