### ISSUE TITLE
Harser

### ISSUE THREAD

**Issue by sihaelov** [thechangelog/ping#612]
Harser is a python library for HTML parsing and building XPath — https://github.com/sihaelov/harser

It is like BeautifulSoup with chainable API but more flexible and with a focus on ease and XPath (in the implementation). And only 6kb!

**Comment by jerodsanto** [comment]
@sihaelov thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
