### ISSUE TITLE
manpages gem

### ISSUE THREAD

**Issue by bitboxer** [thechangelog/ping#613]
Hi,

if you like man pages as much as [Julia Evans](https://twitter.com/b0rk/status/802011306136109057), you might be interested in my little [manpages](https://github.com/bitboxer/manpages) gem. It exposes man pages inside of ruby gems to the man system. I would love
to have the ruby ecosystem to start writing man pages for their command line tools <3 . 

Thanks for reading this!
Bodo

**Comment by jerodsanto** [comment]
@bitboxer thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by bitboxer** [comment]
Awesome. Thanks!
