### ISSUE TITLE
Traffic accounting using Ubiquiti EdgeRouter, iptables and rrdtool

### ISSUE THREAD

**Issue by florianbeer** [thechangelog/ping#614]
Hi,
maybe this could be of interest to your readers. I've created an explanation on how I achieved traffic accounting for devices behind a router using iptables and RRDtool. Including pretty graphs :)

![image](https://cloud.githubusercontent.com/assets/800047/20878651/67c93288-bad0-11e6-9c96-2c61c5a5d268.png)

https://blog.no-panic.at/2016/12/03/traffic-accounting-using-ubiquiti-edgerouter-iptables-and-rrdtool/

Cheers,
Florian

**Comment by jerodsanto** [comment]
thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
