### ISSUE TITLE
Susan Sons from ICEI as a guest on the Request For Commits (RFC) podcast

### ISSUE THREAD

**Issue by pdurbin** [thechangelog/ping#615]
I'm really enjoying the Request For Commits (RFC) podcast and I wonder if Nadia Eghbal and Mikeal Rogers would consider interviewing Susan Sons from the Internet Civil Engineering Institute (ICEI) whose website at https://icei.org says, "ICEI is looking at the underlying systemic causes: lack of support, professional development, and manpower for the maintenance of critical infrastructure software."

It sounds like a match made in heaven for a podcast that is exploring different perspectives in open source sustainability. 😄 

For a nice intro on ICEI I recommend watching "Susan Sons (Center for Applied Cybersecurity Research, Indiana University)" at https://www.youtube.com/watch?v=vjSzVAKJkqU which I found via the "NTP: the rebirth of ailing, failing core network infrastructure" post at http://boingboing.net/2016/11/29/ntp-the-rebirth-of-ailing-fa.html via https://twitter.com/ICEIorg/status/803790549199233024

**Comment by jerodsanto** [comment]
@pdurbin thanks for the suggestion! We have season 2's guest list all lined up and we begin record soon. Stay tuned 📻

**Comment by pdurbin** [comment]
@jerodsanto ok, I checked in with Susan at https://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2017-01-15 and we decided that I'll open another issue in six months or whatever. I'm not sure when you'll start booking season 3 guests.
