### ISSUE TITLE
Henry Zhu Babeljs maintainer for Requests for Commit podcast

### ISSUE THREAD

**Issue by kangman** [thechangelog/ping#616]
Henry's the current maintainer of Babel.  He's got a good overview of the current state of the project on this [blog](
http://babeljs.io/blog/2016/12/07/the-state-of-babel)

it's hit the HN frontpage [here](https://news.ycombinator.com/item?id=13125681)

A few things that could be good to bring up on the podcast is

1. getting contributors
2. politics
3. funding
4. javascript fatigue

disclaimer I work with henry at behance.

**Comment by jerodsanto** [comment]
@kangman our plan for season 2 of RFC is to talk with the "unsung heroes" of open source. I'm not 💯 whether or not Henry is a perfect fit for that. @nayafia or @mikeal do you have thoughts on this?

_(We'd be happy to have him on The Changelog if he doesn't make sense for RFC S2)_

**Comment by kangman** [comment]
I'm sure exposure would be good either way for the project.  @jerodsanto thanks for suggestion.

**Comment by nayafia** [comment]
Funny, I just reached out to Henry yesterday about something related. Obviously I'm a fan :)

@mikeal and I are talking RFC S2 lineup tomorrow, so we'll know more then. We could go in a lot of directions with the "unsung hero" concept, so it just depends on the angle we go with.

**Comment by jerodsanto** [comment]
@kangman we have season 2 pretty much all lined up now and we start recording soon! I think you'll be pleasantly surprised by our guest list... 😉
