### ISSUE TITLE
GitNotify: Daily Emails with Code Diffs from Open Source Repositories

### ISSUE THREAD

**Issue by sairam** [thechangelog/ping#617]
[gitnotify](https://github.com/sairam/gitnotify) allows users to get email notifications about new branches and track commits/merges done on specific branches as a digest email. 

The application can be hosted in an intranet and configured to link to Github EE endpoints.

Open Source: https://github.com/sairam/gitnotify
Hosted version: http://gitnotify.com

**Comment by jerodsanto** [comment]
@sairam nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link GitNotify up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by sairam** [comment]
Thanks 👍
