### ISSUE TITLE
[podcast suggestions] for RFC season 2

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#618]
I have worked with some amazing "human side of code" people in the past 3 months. Here are my picks:

* Betsy Waliszewski - Event Coordinator and Administrator, @Python Software Foundation 
* Ola Sitarska - Co-founder, @DjangoGirls
* Pia Mancini - Co-founder, @OpenCollective
* Gregor Martynus - Co-founder, @HoodieHQ
* Sally Khudairi - Vice President Marketing & Publicity, @Apache Software Foundation
* Jim Zemlin - Executive Director, @LinuxFoundation
* Chris Aniszczyk - COO, @CNCF (@LinuxFoundation)

**Comment by jerodsanto** [comment]
Thanks @jdorfman! We have season 2 all lined up now and we start recording soon!

**Comment by jdorfman** [comment]
can't wait!
