### ISSUE TITLE
Openstreetmap

### ISSUE THREAD

**Issue by dkniffin** [thechangelog/ping#619]
I think [OpenStreetMap](http://osm.org) (OSM for short) would be a great topic for a podcast episode. It's an open-data mapping platform. Think "wikipedia, but for maps". It currently has over 3 million users (although many of those are not active contributors).

The data and tilesets are used in many different projects, such as Craigslist, OsmAnd, Geocaching, MapQuest Open, JMP statistical software, and Foursquare. [Here's a bunch more](http://wiki.openstreetmap.org/wiki/List_of_OSM-based_services).

There's also a lot of open-source projects in the ecosystem, built around it, such as [JOSM](http://josm.openstreetmap.de/), [iD](https://github.com/openstreetmap/iD), [Leaflet](http://leafletjs.com/) (which could probably be an episode on it's own), and many more.

There's also a lot of benefits for humanitarian efforts, via [HOT](https://hotosm.org/).

Some more info can be found on their [wiki](http://wiki.openstreetmap.org/)

Some potential host ideas:
- Steve Coast (@SteveC) - Founder of OSM
- Vladimir Agafonkin (@mourner) - Creator of Leaflet
- Eric Gunderson (@gunderson) - CEO of [Mapbox](https://www.mapbox.com/)
- Andy Allan (@gravitystorm) - Maintainer of the current OSM style

**Comment by jerodsanto** [comment]
@dkniffin 👍 I think this is a good topic. We'll get to work on it!

**Comment by gunderson** [comment]
FYI, I'm not Eric Gunderson :)

**Comment by dkniffin** [comment]
Oops, my bad. Sorry about that. I meant @gundersen

**Comment by jerodsanto** [comment]
@dkniffin we have this in the works and will post back here if it materializes. Thanks again!
