### ISSUE TITLE
Update your Sticker Mule sticker

### ISSUE THREAD

**Issue by wesbaker** [thechangelog/ping#620]
Low priority request, but could you create a new sticker for your new logo [over at Sticker Mule](https://www.stickermule.com/user/1068641067/stickers)?

**Comment by adamstac** [comment]
Thanks for the reminder -- we're launching a merch store soon and we'll include a brand new sticker pack in the new store soon.

**Comment by adamstac** [comment]
Between now and then, I've removed the old and busted from Sticker Mule.
