### ISSUE TITLE
TypeORM Open Source Library

### ISSUE THREAD

**Issue by pleerock** [thechangelog/ping#621]
Hi guys, just wanna ping you about my [TypeORM](https://github.com/typeorm/typeorm) I have published this week. Its is open source ORM for TypeScript and JavaScript that supports multiple databases I have worked on for over a year. Cheers!

**Comment by jerodsanto** [comment]
@pleerock :green_heart: we'll include this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
