### ISSUE TITLE
Webpack Blocks 📦 Webpack configuration as compact modules

### ISSUE THREAD

**Issue by amilajack** [thechangelog/ping#622]
Webpack is well known for being difficult to configure. [webpack-blocks](https://github.com/andywer/webpack-blocks) allows users of webpack to use preconfigured settings for webpack, which makes the webpack setup process significantly easier.

**Comment by jerodsanto** [comment]
@amilajack :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
