### ISSUE TITLE
Race The Web - security testing tool

### ISSUE THREAD

**Issue by insp3ctre** [thechangelog/ping#624]
[Race The Web](https://github.com/insp3ctre/race-the-web) is a tool written in Go that tests for race condition vulnerabilities in web applications. I've spoken more about this issue in a [conference talk](https://www.youtube.com/watch?v=4T99v957I0o) this year, but it's a security vulnerability that is notoriously difficult to test for. This tool makes it much easier, and can be automated as well.

I've also built a companion web application at [RaceTheWeb.io](http://racetheweb.io) that is deliberately vulnerable to race conditions, and can be used to both test the tool and help demonstrate exactly what a race condition vulnerability looks like. I've found it very useful for both developers and security testers alike.

**Comment by jerodsanto** [comment]
we're including Race The Web in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by insp3ctre** [comment]
Awesome, thanks @jerodsanto!
