### ISSUE TITLE
mini.css - Minimal, responsive, style-agnositc CSS toolkit

### ISSUE THREAD

**Issue by Chalarangelo** [thechangelog/ping#625]
Hi! I have been developing **mini.css** for the last few months and I just released **v2** of the framework. If you'd like to check it out, this is [the link to its introduction page](https://chalarangelo.github.io/mini.css/).

It's a CSS toolkit/framework written using Sass, which aims to help create modern website designs without a lot of code and with minimum performance impact (its size is under 7KB gzipped). If you write an article about it, please inform me to share with my peers!

**Comment by jerodsanto** [comment]
@Chalarangelo we'll include mini.css in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
