### ISSUE TITLE
Ruby Exception Handling - Primer for Dealing with Errors in Ruby

### ISSUE THREAD

**Issue by rivkahstandig3636** [thechangelog/ping#628]
[Rollbar](https://rollbar.com/) is an error monitoring service that has a bunch of notifiers for different programming languages. We just released a [guide](https://rollbar.com/blog/ruby-exception-handling-guide/) detailing basic Ruby exception handling, and explaining how to incorporate the [Rollbar Ruby gem notifier](https://github.com/rollbar/rollbar-gem) into your error handling so you can automatically log and report your exceptions.

**Comment by jerodsanto** [comment]
@rivkahstandig3636 this post is _an excellent example_ of sponsored content that would be quite interesting to our audience. I'd suggest going [that route](https://changelog.com/sponsorship) with it. Rollbar has sponsored us in the past, so I know it's something y'all are open to. 🍻
