### ISSUE TITLE
WereSync: Software for cloning Linux drives incrementally

### ISSUE THREAD

**Issue by DonyorM** [thechangelog/ping#629]
[WereSync](https://github.com/DonyorM/weresync) allows one to clone a running linux drive to an external drive incrementally. It can also copy to a smaller drive, provided the data will fit on the smaller drive. This gives it a much more flexible use case than other cloning software such as CloneZilla. WereSync uses rsync as the engine to copy files.

GitHub repository: https://github.com/DonyorM/weresync

**Comment by jerodsanto** [comment]
@DonyorM cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: tomorrow :beers:
