### ISSUE TITLE
JTAppleCalendar - The Unofficial Swift Apple Calendar Library for iOS & tvOS

### ISSUE THREAD

**Issue by patchthecode** [thechangelog/ping#631]
Hey guys, I've created what I believe to be the best Calendar Library for iOS Swift on Github.
If its worthy to be displayed on your Open Source list, I'd be very grateful. It is 100% customizable. And fully documented.
Found on this link -> https://github.com/patchthecode/JTAppleCalendar

**Comment by jerodsanto** [comment]
@patchthecode nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by patchthecode** [comment]
Awesome. I didnt realize your twitter account had so many followers. A tweet would definitely give em a boost. Thanks so much. 🍻
