### ISSUE TITLE
Straightfoward "PKI Manager" for freelancers

### ISSUE THREAD

**Issue by frntn** [thechangelog/ping#632]
Hello,

About one year ago, I was fed up of constantly restarting from scratch each time I had to create a server or client certificate. I needed something consistent over the time, and more simple than existing PKI wrappers.

So I ended up creating what I called my "PKI Manager" : https://github.com/frntn/pki-manager
Easy to use, easy to override on-the-fly and easy to use in unattended shell scripts.

I have used it on a day2day basis since then. My teammates use it & love it for about 1y now
I believe many DEV (and maybe even OPS) will like it as soon as they know it exists 
At least I would have in the first place :smile:

**Comment by jerodsanto** [comment]
@frntn we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
