### ISSUE TITLE
Command line git log mini-tutorial

### ISSUE THREAD

**Issue by ruralocity** [thechangelog/ping#633]
Hi, I wrote an article about searching a git repo's log from the command line, after stumbling upon a trick for hopping from commit to commit when viewing the log—one of those *why didn't I think of that sooner* moments. Maybe useful to others? The article is on a Rails-focused site, but not at all Rails-specific.

https://everydayrails.com/2017/01/02/git-command-line-log-search.html

Thanks,
Aaron

**Comment by jerodsanto** [comment]
@ruralocity we're including your article in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by ruralocity** [comment]
🎉  thanks @jerodsanto!
