### ISSUE TITLE
Zazu App - A fully extensible and open source app launcher for hackers, creators and dabblers.

### ISSUE THREAD

**Issue by blainesch** [thechangelog/ping#634]
The getting started, docs and plugin directory are online at:
http://zazuapp.org/

The source is at:
https://github.com/tinytacoteam/zazu

**Comment by jerodsanto** [comment]
@blainesch [we tweeted about this one yesterday](https://twitter.com/changelog/status/817104116845604864)! We'll include it in [Weekly](https://changelog.com/weekly) too 🍻
