### ISSUE TITLE
Rearrange Tabs

### ISSUE THREAD

**Issue by mohnish** [thechangelog/ping#635]
Rearrange Tabs is a super light weight Google Chrome Extension that allows users to rearrange tabs using customizable keyboard shortcuts.

https://chrome.google.com/webstore/detail/rearrange-tabs/ccnnhhnmpoffieppjjkhdakcoejcpbga

Also, it is OSS - https://github.com/mohnish/rearrange-tabs

**Comment by jerodsanto** [comment]
@mohnish cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
