### ISSUE TITLE
Horizon - From the RethinkDB guys

### ISSUE THREAD

**Issue by the3rdc** [thechangelog/ping#637]
I first heard about RethinkDB when you had them on the show, and it's probably the project I've been most excited about in a long time. Here they've built "Horizon" on top of it, and I can't believe it's been out since May and I didn't discover it until today. Wanted to make sure you guys knew. 

It looks like the perfect thing to build on top of Rethink, and the potential of telling Front End developers they can just let the back end handle itself? I think the web has been looking for this. Maybe it's time to have them back on the show. ; )

https://www.rethinkdb.com/blog/horizon-release/
http://horizon.io/

**Comment by fgrehm** [comment]
Not sure about horizon but rethinkdb is shutting down https://www.rethinkdb.com/blog/rethinkdb-shutdown/

**Comment by jerodsanto** [comment]
@the3rdc @fgrehm yeah it looks like development on Horizon has stalled out. Sadly, I don't think there's too much to talk about here.

Thanks for the idea and feel free to reopen if you find out otherwise!
