### ISSUE TITLE
"Lixie" is a Nixie Tube alternative!

### ISSUE THREAD

**Issue by connornishijima** [thechangelog/ping#638]
![Lixie Display](http://i.imgur.com/Q4HfXMr.jpg)

# [VIDEO DEMONSTRATION](https://www.youtube.com/watch?v=oEmmpNUTOp0)

[Open sourced software](https://github.com/connornishijima/Lixie-arduino), and certified Open Hardware [OSHW: [US000054](http://certificate.oshwa.org/certification-directory/)], **The Lixie display uses stacks of edge-lit acrylic for a beautiful numeric display** based on WS2812B LEDs, and easily driven with the [Lixie Arduino or Python libraries](https://github.com/connornishijima/Lixie-arduino)!

Users can join a waiting list to purchase digits;
https://www.tindie.com/products/connornishijima/lixie-an-led-alternative-to-the-nixie-tube/

**Comment by jerodsanto** [comment]
@connornishijima thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by connornishijima** [comment]
Just so you know, this info is quite old now! ;) The most recent videos and pictures - with a much better manufacturing process - are on my Hackaday.io page: https://hackaday.io/project/18633-lixie-an-led-alternative-to-the-nixie-tube
