### ISSUE TITLE
Sonos Support

### ISSUE THREAD

**Issue by kennygrant** [thechangelog/ping#639]
Your podcast is showing up on sonos, which is great. Thank you!

The feed seems to be broken recently though, no titles appear for newer episodes (perhaps a change to the format after episode 223).

It would also be great to see other casts like gotime on sonos, but can't see them at the moment.

**Comment by jerodsanto** [comment]
@kennygrant I believe we are in there with our old feed from when we were syndicated on 5by5. I'd love to get this fixed and have all of our shows in Sonos, but I'm not 💯 on how to accomplish that.

Can you tell us more about where they are showing up on your Sonos? It seems that the built-in podcast playing is provided by [TuneIn](http://tunein.com), but again, not sure. 

(I just submitted Go Time to their directory. We'll see if that does anything.)

**Comment by kennygrant** [comment]
Yes, it seems to come under radio by tunein. Attached is a pic to show how they show up. Episodes up to no 223 look right, at the top are lots without title info, and I can't find gotime (or Go Time) when I search, but I'll keep trying, thanks for submitting it.  Also thanks for all the podcasts, they're great, I'm working my way through your back catalogue at the moment.

<img width="431" alt="screen shot 2017-01-19 at 17 23 19" src="https://cloud.githubusercontent.com/assets/68352/22117473/13cfebda-de6c-11e6-8339-afa97ed61ba6.png">

**Comment by jerodsanto** [comment]
Thanks for confirming that.

Hmm yeah that is the last episode that was served by 5by5's CDN, so they probably didn't follow the redirect properly.

We haven't heard back from TuneIn yet, but when we do we'll try to get all of our shows in there (and get The Changelog fixed). We want to be as many places as possible (unless they screw with us like Stitcher and Google Play do).

**Comment by jerodsanto** [comment]
@kennygrant I've good news and bad

### The Good! 

We managed to get [Go Time in to TuneIn's directory](http://tunein.com/radio/Go-Time-p951074/), so it should show up on your Sonos now. (can you confirm?)

### The Bad!

It has the same problem as The Changelog's feed, in that it only shows the show title and nothing else 😭. They must be expecting something different from our feed format, but it's opaque to us.

I emailed them to try to get resolved (and find a way to get all of our shows in there) and I'll keep you posted. Ideally they'd have an admin dashboard where we can manage our shows in their directory, but currently it's an email-based system. 😐

**Comment by kennygrant** [comment]
Great just checked and showing up, so will be listening, thanks a lot.

Re format there was no change between ep 223 and 224 on your end? If so perhaps get them to check what they changed that week as older ones are ok as per pic above.

**Comment by jerodsanto** [comment]
@kennygrant should be fixed now!

<img width="670" alt="2017-02-02 at 11 00 am" src="https://cloud.githubusercontent.com/assets/8212/22559469/cf01fa2c-e936-11e6-8e97-a7f79f1a6825.png">

Please confirm

**Comment by kennygrant** [comment]
Looks great now, thank you!
