### ISSUE TITLE
Blogpost: Rituals of Shaming in the Software Industry

### ISSUE THREAD

**Issue by pavsaund** [thechangelog/ping#640]
Hi guys. I'm back with another soft skill / personal article.  Last time it was about burnout. This time it's about Rituals / practices of shaming in our industry. 

I'm planning a follow up on what makes a healthy environment, but haven't started on that yet. 

http://codingwithempathy.com/2017/01/10/rituals-of-shaming-in-the-software-industry/

Got quite a lot of positive feedback so far. Hope it's suit for you. Also interested if you have any feedback. 

-Pav

**Comment by jerodsanto** [comment]
@pavsaund excellent post, thanks for sharing. You're doing important work here. We just queued up a tweet in your direction and this one will be in [Weekly](https://changelog.com/weekly) for sure. :green_heart: :green_heart: :green_heart:
