### ISSUE TITLE
JSON Browse - Debug, filter and manipulate your JSON inside the browser

### ISSUE THREAD

**Issue by jorilallo** [thechangelog/ping#641]
<img width="954" alt="screenshot 2016-12-06 00 20 30" src="https://cloud.githubusercontent.com/assets/31465/20918070/05b3b170-bb4a-11e6-8a95-7c9b79f723f7.png">

Small JSON tool which is inspired by [`jq`]() but build for the browser using React and Next.js.

https://jsonbrowse.com/

Source code: https://github.com/jorilallo/jsonbrowse

**Comment by jerodsanto** [comment]
@jorilallo super cool! We just sent a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by jorilallo** [comment]
@jerodsanto Appreciated 🙏
