### ISSUE TITLE
Chris Lattner on Swift, LLVM and Open Source?

### ISSUE THREAD

**Issue by mcdado** [thechangelog/ping#642]
Now that Lattner has left Apple, I'd hope he would be available for joining. He was recently on [ATP podcast](http://atp.fm/episodes/205), talked a lot about the Swift programming language.

If there was an opportunity to have on this show, it would be cool to dig deeper in other areas other than Swift. He's pretty much into open source, wouldn't it be interesting?

**Comment by jerodsanto** [comment]
We've been trying to get Chris on the show ever since Swift was first announced as open source! We're talking with him now, but he hasn't committed just yet.

The ATP interview was awesome, btw. I hope we can bring new and different angles if he comes on.

**Comment by mcdado** [comment]
Maybe now it would be a good time! https://twitter.com/clattner_llvm/status/877341760812232704
