### ISSUE TITLE
DonorSee podcast guest

### ISSUE THREAD

**Issue by timhenderson1** [thechangelog/ping#643]
I was told by Jerod to add this here. Here is the Tom Woods interview: http://tomwoods.com/ep-751-help-people-around-the-world-by-going-over-the-heads-of-governments-and-aid-groups/

Just saw the guy's name is Gret.

-Tim

**Comment by adamstac** [comment]
I'm not sure what the angle is for this show? What does the open source world need to know about DonorSee?

I'm going to close this for now and will re-open this for discussion if your response helps us see the angle to open source.

Disclosure: I worked at Pure Charity for 4 years and helped build what you see there now - https://purecharity.com/
