### ISSUE TITLE
CRPageViewController - Open Source Library for iOS

### ISSUE THREAD

**Issue by vladdmitriev** [thechangelog/ping#646]
Hello,

Recently, we have made PageViewController - https://github.com/Cleveroad/CRPageViewController

![crpageviewcontroller](https://cloud.githubusercontent.com/assets/20402305/22242892/c3c34518-e22d-11e6-86f9-50d5bc00b4f5.gif)

Description:
While a standard page view allows you to navigate between pages by using simple gestures, our component goes further. CRPageViewController allows defining a page size by setting width and heights manually. Thus, users will be able to control the placement of pages on the screens in the way which is more suitable for them.

Maybe, it would be an interesting material for your newsletter.

Regards,
Vlad

**Comment by jerodsanto** [comment]
@vladdmitriev we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
