### ISSUE TITLE
Lionshare - Simple cryptocurrency price and portfolio monitor build with Electron

### ISSUE THREAD

**Issue by jorilallo** [thechangelog/ping#647]
![1-diwz_x9p3c86sfo-gydi5a](https://cloud.githubusercontent.com/assets/31465/22264342/66f5157e-e22c-11e6-9ae4-4cf8b922973c.png)

> 🦁 Simple cryptocurrency price and portfolio monitor for macOS

Lionshare is an open source Electron app build with React and Mobx. We also open sourced the companion API build with node, uws and Koa2 that powers realtime market information.

https://github.com/lionsharecapital

**Comment by jerodsanto** [comment]
@jorilallo nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Lionshare up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
