### ISSUE TITLE
Talk the Docs

### ISSUE THREAD

**Issue by ericholscher** [thechangelog/ping#649]
Heard ya'll talking about some of the work we're doing around docs w/ Write the Docs (and RTD to a lesser extent) and would love to come on the show and talk more about it. I think in general docs need at least as much love as testing gets in OSS, and we're a long way to go :)

Let me know what makes sense for next steps!

**Comment by jerodsanto** [comment]
@ericholscher yup, I've been urging folks to listen to your RFC episode and it has come up on The Changelog too. We'd love to have you on, but we'd want to design the conversation so it brings a different angle/perspective than your previous appearance on our network.

Let's chat about that and scheduling via email: editors@changelog.com

**Comment by annegentle** [comment]
Hurrah! Can't wait to listen to this one. Eric wrote the foreword for the new _Docs Like Code_ book. 📚  Check it out at http://docslikecode.com 😃
