### ISSUE TITLE
A Walk With JWT and Security (and IV): A Secure JWT Authentication Implementation for Rack and Rails

### ISSUE THREAD

**Issue by waiting-for-dev** [thechangelog/ping#650]
After having discussed in the three previous posts (I, II and III) about JWT authentication and security, I would like to share two Ruby libraries I made in order to implement these security tips we have discussed so far.

**Comment by jerodsanto** [comment]
@waiting-for-dev solid series ✊ 

Two things:

1. There is no link to your content in this issue.
2. Would you mind combining all of them in to a single issue? We're much more likely to cover the entire series as a set than we are as individual artices.

Cheers,

**Comment by waiting-for-dev** [comment]
Ok, combined. Thanks! :)

Closed in favor of #651
