### ISSUE TITLE
A walk with JWT and security

### ISSUE THREAD

**Issue by waiting-for-dev** [thechangelog/ping#651]
A four posts series about security tips on JWT tokens authentication:

http://waiting-for-dev.github.io/blog/categories/a-walk-with-jwt-and-security/

Summarizes #644, #645, #648 and #650

**Comment by jerodsanto** [comment]
@waiting-for-dev we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by waiting-for-dev** [comment]
Great :+1: :)
