### ISSUE TITLE
NaturalRegex

### ISSUE THREAD

**Issue by mbasso** [thechangelog/ping#653]
> Create regex from natural language

- https://github.com/mbasso/natural-regex

natural-regex is a parser that allows you to write regular expressions in natural language. This means that you can write self documentating regex using a simpler syntax that can be undestood by anyone. No more pain with validations and other stuff.

**Comment by jerodsanto** [comment]
@mbasso cool idea! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).
