### ISSUE TITLE
Remote Pad — Remote Control for games using IoT principles

### ISSUE THREAD

**Issue by atilacamurca** [thechangelog/ping#654]
Remote Pad is a web app that allows you to play games on your computer using your smart phone as a remote controller. The principle is to exchange data in real time using the MQTT protocol and send strokes as if it were a keyboard.

Checkout this 1 minute video of Remote Pad in action: <https://www.youtube.com/watch?v=93f1dRWxhyc>

Medium post <https://medium.com/@atilacamurca/remote-pad-remote-control-for-games-using-iot-principles-1fe7ec0e37ac#.e72cryvg5>

Repos:

* [remote-pad - server](https://github.com/comsolid/remote-pad-server)
* [remote-pad - client](https://github.com/comsolid/remote-pad)

**Comment by jerodsanto** [comment]
@atilacamurca we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
