### ISSUE TITLE
Guaka - a swift library to create modern, POSIX-compliant and cross platform CLI applications

### ISSUE THREAD

**Issue by oarrabi** [thechangelog/ping#655]
Guaka: http://getguaka.com/

Guaka is a smart and beautiful **POSIX compliant** CLI framework for **Swift**.
Create modern and familiar CLI apps in the vein of widely used projects such as: **Git**, **Docker**, **Kubernetes**, **OpenShift**, **Hugo** and more!
Inspired by the amazing [Cobra](https://github.com/spf13/cobra) package from the Golang's ecosystem.

**Comment by jerodsanto** [comment]
@oarrabi nice! We sent a tweet in your direction yesterday and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/). 💚
