### ISSUE TITLE
CEF4Delphi : A new Delphi component to embed Chromium-based browsers in applications.

### ISSUE THREAD

**Issue by salvadordf** [thechangelog/ping#656]
CEF4Delphi is my first open source project. 

DEF4Delphi uses the Chromium Embedded Framework 3 to embed Chromium-based browsers and it's based on DCEF3, made by Henri Gourvest.

The last update of DCEF3 was 8 months ago so I decided to create CEF4Delphi using the latest stable branch of the Chromium Embedded Framework because I needed it for my web browser : BriskBard.

The link to CEF4Delphi : https://github.com/salvadordf/CEF4Delphi
For more information about CEF4Delphi : https://www.briskbard.com/index.php?lang=en&pageid=cef

CEF4Delphi includes some demos but you can check BriskBard to see it working on a full web browser : 
https://www.briskbard.com

**Comment by jerodsanto** [comment]
@salvadordf congrats on your first open source project! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by salvadordf** [comment]
Thanks! :smile:
