### ISSUE TITLE
Changelog 236 Shownotes

### ISSUE THREAD

**Issue by Anzumana** [thechangelog/ping#657]
Found the link to the db comparison that Mark mentioned on the call.
https://aphyr.com/tags/jepsen
@amark
Hope this is the correct one.
Please add this to the shownotes.

Is there any plans that we could just make pr's if we find a link to something that was mentioned during the show but is not on the link list.

I mentioned this a while back when you were on the old cms.
Not sure if there are any plans regarding this.
Take care.
Anzumana

**Comment by jerodsanto** [comment]
@Anzumana added, thanks!

We don't plan on using GitHub/PRs for our show notes. Show notes changes and additions are rare enough that it isn't worth it for us to build the infrastructure around it.

However, we have transcripts in the works and we are planning on hosting their source on GitHub for this exact reason.

💚

**Comment by amark** [comment]
Yupe it was @Anzumana ! Thanks for finding that. Sorry about it, I thought I had sent the link but must have forgotten. Love to hear what you are working on!?
