### ISSUE TITLE
PyFunctional 1.0

### ISSUE THREAD

**Issue by EntilZha** [thechangelog/ping#658]
As per https://github.com/thechangelog/ping/issues/486, pinging now that there is a new major release.

Project Link: https://github.com/EntilZha/PyFunctional
Release Notes: https://github.com/EntilZha/PyFunctional/releases/tag/v1.0.0

**Comment by jerodsanto** [comment]
@EntilZha well done! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
