### ISSUE TITLE
#HelpWanted

### ISSUE THREAD

**Issue by lmarkus** [thechangelog/ping#659]
Hi ChangeLog peeps.
Wanted to bring this to your attention, to see if it would be a good fit for any of your different publications/sections
https://github.com/bergie/passport-saml/issues/162#issuecomment-276133428

It's a good project, (particularly for enterprise users), but it's lacking contributors.

**Comment by jerodsanto** [comment]
@lmarkus we'll put this in the Ping section of our next issue of [Weekly](https://changelog.com/weekly/). Hope y'all find someone!
