### ISSUE TITLE
ReviewBot

### ISSUE THREAD

**Issue by lmarkus** [thechangelog/ping#661]
Hi all,
Wanted to share this quick project.
It's a GitHub hook that helps coordinate reviewers for projects with high velocity.
I wrote it for my team, as we had a large number of open PRs that were not being reviewed in a timely manner.  The root cause was lack of accountability, since PR reviews were done on a voluntary basis. You'd always have the same groups of people reviewing or slacking off, and that was causing burn-out on the reviewers.

Now, when you send a PR, the bot picks the people to review, and assigns them. 
No complaining :) 

Extra credit: Notifies the people assigned via Slack

https://github.com/lmarkus/ReviewBot

**Comment by jerodsanto** [comment]
@lmarkus nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link ReviewBot up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
