### ISSUE TITLE
Proposed guest to talk about linux / performance / BPF

### ISSUE THREAD

**Issue by gmile** [thechangelog/ping#662]
Hi @jerodsanto and @adamstac!

I'd like to propose a guest to Changelog podcast – @brendangregg.

Brendan is a prominent systems performance analyst, an author of several books, the creator of DTraceToolkit and an inventor of [flamegraphs](https://github.com/brendangregg/FlameGraph). He's also famous for the "[Shouting in the datacenter](https://www.youtube.com/watch?v=tDacjrSCeq4)" video. He worked for companies with big names, so probably can share some ideas and/or stories regarding solving performance problems at scale.

The reason I'd like to hear more from Brendan is the recent rise of BPF in linux and the fact that Brendan is one of the very few people who pedantically documents everything about BPF, writing examples & explaining them. This is important work for years to come, laying ground for future developments on top of BPF (actually, eBPF). 

eBPF aka "extended Barkley Packet Filter" is a recent development within linux kernel that allows previously unseen capabilities of tracing the kernel function calls. eBPF is a new thing and it seems to open up a pandora box of what is going to be possible with tracing in linux. Despite sounding low-level, it can help trace performance issues in apps written in higher level languages like Ruby, JavaScript (Node), etc.

To me though this is important & interesting from a perspective of learning about operating system & computer internals: BPF & tools built on it allow to see what caches are there, how network packets go where, what are the latencies of all sorts of movings parts in OS & hardware, etc.

Brendan seems to have lots of stories to share, and seems to be just a plain nice guy to hear from (my impression is based on his numerous presentations on YouTube).

To sum up, topics I believe Brendan can talk about:

1. solving hard performance problems,
2. being an SRE,
3. what is BPF, what BPF rise means and why it all matters,
4. how BPF can help fixing perf issues in apps written in higher-level languages,
5. fun stories about unexpected perf issues.

Here's a couple of great articles from Brendan that might get you interested:

* [eBPF: One Small Step](http://www.brendangregg.com/blog/2015-05-15/ebpf-one-small-step.html),
* [Linux BPF Superpowers](http://www.brendangregg.com/blog/2016-10-27/dtrace-for-linux-2016.html).

Bonus: can't help but share this amazing step-by-step debugging session of his, written in simple english – "[gdb Debugging Full Example (Tutorial): ncurses](http://www.brendangregg.com/blog/2016-08-09/gdb-example-ncurses.html)". It's just astonishing to watch things unfold after a cryptic error such as "Segmentation fault".

**Comment by jerodsanto** [comment]
@gmile wow, thanks for the detailed and convincing reasoning on why Brendan would make a great guest. 💚

I have to agree with you, he seems to have _a lot_ of interesting things going on and he's quite well spoken, to boot (I hadn't seen him shouting in the datacenter until now, but wow that was cool).

@brendangregg we'd love to have you on the show! If you're interested, please email editors@changelog.com and we'll iron out all of the details.

**Comment by sivasamyk** [comment]
+1

**Comment by jerodsanto** [comment]
@gmile @sivasamyk we contacted @brendangregg via email and we're working with him to schedule a show. Stay tuned! I'll follow up here if/when it gets published 🥂

**Comment by gmile** [comment]
@jerodsanto awesome news, thank you!

I really hope you guys will eventually work it out and record a show.
