### ISSUE TITLE
vbuild: Refined webpack for Vue.js

### ISSUE THREAD

**Issue by egoist** [thechangelog/ping#664]
vbuild lets you kick start a new web app really fast with refined webpack development experience.

It requires almost no config / only a single dev dependency to build for production with `code split` `minimize all the thing` enabled by default.

Repo: https://github.com/egoist/vbuild

**Comment by jerodsanto** [comment]
@egoist nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link vbuild up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
