### ISSUE TITLE
I could not find a simple Gesture Detection android library, so I built one

### ISSUE THREAD

**Issue by nisrulz** [thechangelog/ping#665]
Article : I could not find a simple Gesture Detection android library, so I built one

Details about the android library I built for simplified gesture detection.

**Comment by jerodsanto** [comment]
@nisrulz you forgot the link! 😄

**Comment by nisrulz** [comment]
@jerodsanto ohh yeah I did 😅  Here you go

https://android.jlelse.eu/i-could-not-find-a-simple-gesture-detection-android-library-so-i-built-one-334c0a307c16

**Comment by jerodsanto** [comment]
@nisrulz much better! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
