### ISSUE TITLE
git-unsaved

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#666]
A fast and cute cli tool to warn you that you forgot to save your git changes (either you didn't commit/push/push a new branch etc).

> https://github.com/IonicaBizau/git-unsaved

![](https://camo.githubusercontent.com/594278c6e29b522afae01cbaed96875f467eb692/68747470733a2f2f692e696d6775722e636f6d2f324c68557477672e676966)

**Comment by jerodsanto** [comment]
@IonicaBizau you're at it again! 😉

We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by IonicaBizau** [comment]
@jerodsanto Yay! Thanks! 🎉
