### ISSUE TITLE
Gogradle — Golang support for Gradle

### ISSUE THREAD

**Issue by eriwen** [thechangelog/ping#667]
[Gogradle](https://github.com/blindpirate/gogradle) brings Go support to the [Gradle build tool](https://gradle.org/). It allows for a project-scoped build (no more global `$GOPATH`) and provides full-featured package management with versioning. Finally, it works with most major Golang package management tools and is able to build 526 of GitHub's top 1000 Go repositories **without any extra configuration**. 

Anyway, I'm extremely excited about this project, and I hope you are too. Thanks for your consideration :)

**Comment by jerodsanto** [comment]
@eriwen we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by eriwen** [comment]
@jerodsanto 🌟  💯  👍
