### ISSUE TITLE
typo in changelog.com

### ISSUE THREAD

**Issue by matsu911** [thechangelog/ping#669]
Hi,

In page https://changelog.com/podcast/20, I found a typo in date.
```EPISODE #20 / APR 6 2011 / 43 MIN```
should be 
```EPISODE #20 / APR 6 2010 / 43 MIN```

Thanks.

**Comment by adamstac** [comment]
Fixed! Thank you.

https://changelog.com/podcast/20

**Comment by adamstac** [comment]
In the future @matsu911 can you log any issues you find on changelog.com to this repo https://github.com/thechangelog/changelog.com?

**Comment by matsu911** [comment]
Sure!
