### ISSUE TITLE
Blogpost: Make Your Pull Requests Visual For Front-End Changes

### ISSUE THREAD

**Issue by jdaudier** [thechangelog/ping#670]
Hi @thechangelog:

I wrote a blog post about how to make your pull requests visual for front-end changes. I'm wondering if this is suitable for your audience.

https://medium.com/@jdaudier/make-your-pull-requests-visual-for-front-end-changes-ef91d83d4fc2#

![sayfmb1oht](https://cloud.githubusercontent.com/assets/1666031/23343578/d2129e02-fc3b-11e6-9433-86d35d0d0ae7.gif)

**Comment by jerodsanto** [comment]
@jdaudier absolutely! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
