### ISSUE TITLE
demo progressive web app to show case all the pwa features

### ISSUE THREAD

**Issue by gokulkrishh** [thechangelog/ping#671]
Hi @thechangelog,

I wrote a demo application to highlight all the features of a **progressive web application** with code explanation. 

URL - https://demopwa.in
Repo - https://github.com/gokulkrishh/demo-progressive-web-app

Wondering if this is something which can feature in your newsletter. Thanks

**Comment by jerodsanto** [comment]
@gokulkrishh we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by gokulkrishh** [comment]
@jerodsanto Cool 👍
