### ISSUE TITLE
FireEdit–A real-time editor in your browser and tutorial how you can build yours 

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#672]
:rocket: App: https://coltaemanuela.github.io/FireEdit/
:octocat: Source code: https://github.com/coltaemanuela/FireEdit
:books: Tutorial: https://www.codementor.io/johnnyb/fireedit-real-time-editor-javascript-firebase-59lnmf3c6

by @ColtaEmanuela ([@EmanuelaColta](https://twitter.com/EmanuelaColta) on Twitter) and me :grin: 

[![](https://ph-files.imgix.net/3d744065-77d0-4572-b532-81a716cf3344?auto=format&auto=compress&codec=mozjpeg&cs=strip)](https://coltaemanuela.github.io/FireEdit/)

**Comment by jerodsanto** [comment]
thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by IonicaBizau** [comment]
Coolio! :tada: :grin:
