### ISSUE TITLE
Storybook Addon Material-UI

### ISSUE THREAD

**Issue by UsulPro** [thechangelog/ping#673]
https://github.com/sm-react/storybook-addon-material-ui

The development tool to create Material-UI components in isolate environment + themes creating tool. Good for Component-Driven Development. 

![demo](https://raw.githubusercontent.com/sm-react/storybook-addon-material-ui/master/docs/WatchMe.gif)

Quick start with boilerplate project:
```
git clone https://github.com/sm-react/react-theming.git
```

(Related to: ReactJS, React-Storybook #429, [Material-UI](http://www.material-ui.com))

**Comment by jerodsanto** [comment]
:green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
