### ISSUE TITLE
farm-cli, node workers farm from CLI

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#674]
![](https://camo.githubusercontent.com/646c1489fe2fc17d6bc67da517a08ef520e3cf8a/68747470733a2f2f64337565706a31323473357263782e636c6f756466726f6e742e6e65742f6974656d732f3178314631523131335930733277306c306f304e2f53637265656e2532305265636f7264696e67253230323031372d30332d3033253230617425323030352e3333253230706d2e6769663f763d3034373162366562)

[farm-cli](https://github.com/Kikobeats/farm-cli) is a CLI tool for easily create a farm of node process.

It's based on [worker-farm](https://github.com/rvagg/node-worker-farm) and you can setup how many cores, workers per core, delay between workers or retries option for your farm.

**Comment by jerodsanto** [comment]
@Kikobeats cool stuff! We'll link farm-cli up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

:shipit: soon :beers:

**Comment by Kikobeats** [comment]
you rocks
