### ISSUE TITLE
Gradle each

### ISSUE THREAD

**Issue by johnjohndoe** [thechangelog/ping#675]
> This shell script executes the given Gradle tasks on a range of commits.

![gradle-each](https://cloud.githubusercontent.com/assets/144518/24040800/f75f8bb0-0b0a-11e7-9ab3-0775b3056955.png)

https://github.com/johnjohndoe/gradle-each

**Comment by jerodsanto** [comment]
@johnjohndoe we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
