### ISSUE TITLE
pull-to-reload

### ISSUE THREAD

**Issue by ErlendEllingsen** [thechangelog/ping#677]
I've created a little project called "pull to reload" that has gotten quite popular and is currently on the github javascript trending! Thought it would be cool to share it with you guys.

It adds pull to reload functionality to web apps and web pages, nice for single page applications and hybrid mobile apps etc :) 

https://github.com/ErlendEllingsen/pull-to-reload

**Comment by jerodsanto** [comment]
@ErlendEllingsen very cool! I believe we tweeted about this sometime last week, but we'll also give it a mention in the next issue of [Weekly](https://changelog.com/weekly) 🍻
