### ISSUE TITLE
txtnish - A twtxt client with minimal dependencies

### ISSUE THREAD

**Issue by mdom** [thechangelog/ping#678]
Instead of signing up at a closed and/or regulated microblogging platform, getting your status updates out with txtnish is as easy as putting them in a publicly accessible text file. The URL pointing to this file is your identity, your account. txtnish then tracks these text files, like a feedreader, and builds your unique timeline out of them, depending on which files you track. The format is simple, human readable, and integrates well with UNIX command line utilities.

[txtnish](https://github.com/mdom/txtnish)

**Comment by jerodsanto** [comment]
@mdom :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by mdom** [comment]
Thank you, I really appreciate it!
