### ISSUE TITLE
service-workers - a collection of utilities for creating/testing/experimenting with service workers

### ISSUE THREAD

**Issue by jparise** [thechangelog/ping#679]
[service-workers](https://github.com/pinterest/service-workers) is a configurable and forkable collection of utilities for creating/testing/experimenting with service workers.

- [generate-service-worker](https://github.com/pinterest/service-workers/tree/master/packages/generate-service-worker) - A node module for generating service worker files based on provided configuration options.
- [service-worker-plugin](https://github.com/pinterest/service-workers/tree/master/packages/service-worker-plugin) - A webpack plugin for generating dynamic service worker files and a runtime helper.
- [service-worker-mock](https://github.com/pinterest/service-workers/tree/master/packages/service-worker-mock) - A mock service worker environment generator. Used for testing service worker code.

https://github.com/pinterest/service-workers

**Comment by jerodsanto** [comment]
@jparise we tweeted about this earlier in the week and we'll also include it [Weekly](https://changelog.com/weekly) 💚
