### ISSUE TITLE
OrgManager - Supercharge your GitHub organizations!

### ISSUE THREAD

**Issue by m1guelpf** [thechangelog/ping#681]
OrgManager is a laravel web application that allows public GitHub organizations (organizations you can join, replying to an issue, for example) to make their users' lives easier. It replaces the process of asking for an invitation and waiting with a page where the user introduces his GitHub username and is automatically invited. It also has other cool features, like adding users to teams, password-protecting invites or an API. You can find the source code at https://github.com/orgmanager/orgmanager and the hosted version at https://orgmanager.miguelpiedrafita.com

**Comment by jerodsanto** [comment]
@m1guelpf cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
