### ISSUE TITLE
(another) command line tool for tracking work time

### ISSUE THREAD

**Issue by omidfi** [thechangelog/ping#682]
Hi, 
After about 2k downloads on npm and a German magazine writing about it ([link](http://t3n.de/news/kommandozeile-terminal-time-tracking-zeiterfassung-803805/)) I feel comfortable pinging you about my side project:
https://www.npmjs.com/package/moro 

I hope maybe you could put it on changelog weekly email :) 
Thanks,
Omid

**Comment by jerodsanto** [comment]
@omidfi you bet! We'll include it in the next issue :beers:

**Comment by omidfi** [comment]
Thanks :)
