### ISSUE TITLE
Kickstarter's open source Android and iOS apps in Kotlin and Swift

### ISSUE THREAD

**Issue by mbuhot** [thechangelog/ping#683]
Just came across [this blog](https://kickstarter.engineering/kickstarter-kotlin-ca8768ef8f8f#.x1pt61kd0) talking about introducing Kotlin into Kickstarters android app, comparing experiences with Swift and Kotlin in their open source mobile apps:

[android repo](https://github.com/kickstarter/android-oss)

[ios repo](https://github.com/kickstarter/ios-oss)

**Comment by jerodsanto** [comment]
@mbuhot cool! We'll link this up in the next issue of [Weekly](https://changelog.com/weekly) 🎉
