### ISSUE TITLE
Wild Duck – distributed IMAP server built with Node.js

### ISSUE THREAD

**Issue by andris9** [thechangelog/ping#684]
Here's a new email project of mine (I have previously built Nodemailer, Mailtrain, ZoneMTA) – it's a distributed IMAP server built with Node.js called **Wild Duck IMAP server** <https://github.com/wildduck-email/wildduck>

Most traditional open source IMAP servers use file system for mail store which means that an user account is always tied to a specific server. Wild Duck uses shared state and clustered MongoDB as the mail store so you can connect to any instance of Wild Duck to access your mailbox.

**Comment by jerodsanto** [comment]
cool stuff! We'll link Wild Duck up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
