### ISSUE TITLE
GraphQL server tutorial combining 5 different data sources

### ISSUE THREAD

**Issue by lorensr** [thechangelog/ping#685]
"Use All the Databases"

Part 1: https://www.compose.com/articles/use-all-the-databases-part-1/
Part 2: https://www.compose.com/articles/use-all-the-databases-part-2/

**Comment by jerodsanto** [comment]
@lorensr cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
