### ISSUE TITLE
The state of Node security

### ISSUE THREAD

**Issue by renrutnnej** [thechangelog/ping#686]
I was just catching up with @evilpacket (creator of the Node Security Project, and later Node Security Platform) and I think it would be cool to hear him talk about security goings-on (the NSP coming under the Node.js Foundation, or maybe like his top five latest/best practices, or share some curious vulns he's found). 

I could see him being a guest on The Changelog, RFC, or Spotlight, maybe even Founders? But I'll leave that up to your judgment. Anyway, just thought he'd be an interesting guest with the bonus perk of dropping valuable security tips on the Changelog community ☺️

**Comment by jerodsanto** [comment]
@renrutnnej let's do this! (I've pinged you in our slack)

@evilpacket we'd 💚 to have you on JS Party soon! (Also, congrats on the acquisition 🍻)

**Comment by evilpacket** [comment]
Thank you!  I’d love to be on JS Party!

Any chance somebody can ping my scheduler at  press@npmjs.com and they can
help work out the details?

**Comment by jerodsanto** [comment]
It's a thing! 

https://changelog.com/jsparty/23

Thanks all, closing this 🎉
