### ISSUE TITLE
GraphQL vs REST comparison - Is This Solution from Facebook Worth Taking the Risk?

### ISSUE THREAD

**Issue by jniechcial** [thechangelog/ping#687]
"GraphQL vs REST comparison - Is This Solution from Facebook Worth Taking the Risk?"

https://www.netguru.co/blog/grapghql-vs-rest

Mentioned by GraphQL Twitter account: https://twitter.com/GraphQL/status/841435480675692544

**Comment by jerodsanto** [comment]
@jniechcial this page is not loading for me. Please reopen when resolved. 💚

**Comment by jniechcial** [comment]
@jerodsanto I don't know what to think about it - classic example of "it works for me" 😂 I checked it on multiple "is-down-or-just-for-me" sites and everything seems fine. 

Can you check again by clicking this Twitter link from GraphQL tweet - we had thousands of visits from it - https://t.co/jpJ9X6ai1d

**Comment by jniechcial** [comment]
@jerodsanto I can't reopen issue 😱

Maybe you disabled that feature for non-org members?

**Comment by jerodsanto** [comment]
It's back up now, so crisis averted. 🤓

**Comment by jerodsanto** [comment]
@jniechcial thanks for your patience! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
