### ISSUE TITLE
cibuildwheel - Python package for building platform wheels with greater ease!

### ISSUE THREAD

**Issue by joerick** [thechangelog/ping#689]
https://github.com/joerick/cibuildwheel

Python wheels are great. Building them across Mac, Linux, Windows, on multiple versions of Python, is not.

cibuildwheel is here to help. cibuildwheel runs on your CI server - currently it supports Travis CI and Appveyor - and it builds and tests your wheels across all of your platforms.

**Comment by jerodsanto** [comment]
@joerick we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by joerick** [comment]
Yey! \😀/ cheers @jerodsanto . The changelog is super terrific 👍
