### ISSUE TITLE
Bootsole: A PHP templating engine for rendering Bootstrap-themed, Tablesorter tables and modern forms from arrays of raw data.

### ISSUE THREAD

**Issue by alexweissman** [thechangelog/ping#69]
https://github.com/alexweissman/bootsole

Rendering data tables and CRUD interfaces in PHP can be a chore, especially if you want it to look nice.  Why not make your life easier and use a templating engine?

Bootsole is a simple templating engine for PHP 5.4+ that creates Bootstrap-styled tables and forms from a template string and an array of parameters. 
 
The `FormBuilder` class supports the `hidden`, `text`, `password`, `select`, `select2`, `selectTime`, `toggle`, `radioGroup`, and `switch` controls.

For example, it can turn this:

````
$fields = [
    'beard' => [
        'type' => 'toggle',
        'label' => 'Beard',
        'icon' => 'fa fa-trophy',
        'display' => 'disabled',
        'validator' => [
            'selected' => true,
            'label' => 'Beard'
        ],
        'choices' => [
            'fluffy' => 'Fluffy',
            'scraggly' => 'Scraggly',
            'pointy' => 'Pointy'
        ],
        'default' => 'fluffy'
    ],
    ... // The rest of the fields
];

$template = "
<div class='row'>
    <div class='col-sm-6'>
        {{beard}}
    </div>
</div>
... // The rest of the template
";
````
into this:

![formbuilder](https://cloud.githubusercontent.com/assets/5004534/4175872/e1479f00-35e9-11e4-9a7a-18ceb07fdae7.png)

````
...
<div class="form-group">
    <label>
        Beard
    </label>
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-trophy"></i></span>
        <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-primary" disabled="">
                <input class="form-control" name="beard" value="fluffy" disabled="" type="radio"> Fluffy
            </label>
            <label class="btn btn-primary active">
                <input class="form-control" name="beard" value="scraggly" checked="" type="radio"> Scraggly
            </label>
            <label class="btn btn-primary" disabled="">
                <input class="form-control" name="beard" value="pointy"  disabled="" type="radio"> Pointy
            </label>
      </div>
    </div>
</div>
...
````

You can also prepopulate fields with a data array:

````
$data = [
    'beard' => 'scraggly'
    ...
];
````
You can template out the buttons on your form as well:
````
$buttons = [
    'btn_poison' => [
        'label' => 'Poison',
        'type' => 'button',
        'style' => 'danger',
        'size' => 'lg',
        'display' => 'disabled',
        'icon' => 'fa fa-flask'
    ],
    'btn_submit' => [
        'label' => 'Create Philosopher',
        'type' => 'submit',
        'size' => 'lg',
        'style' => 'success'
    ]
];
````

Tables are rendered by the `TableBuilder` class, which renders [Tablesorter](http://tablesorter.com/docs/) tables.  Features include:

- Custom sorting parameters
- Pagination
- Column filtering
- Row menus for performing actions on rows
- Alternative templates for empty table cells
- Iterative rendering of sub-array data

![tablebuilder](https://cloud.githubusercontent.com/assets/5004534/4175889/bc95d20c-35ea-11e4-8c64-b357fe5b0b0d.png)

See the project page for more information: https://github.com/alexweissman/bootsole

**Comment by jerodsanto** [comment]
@alexweissman we're including Bootsole in the next issue of [Weekly](http://thechangelog.com/weekly), so keep an eye out for it! :beers:

**Comment by alexweissman** [comment]
Cool!  Actually, I have been working on a new version that works as a more generic templating engine (so, can render entire pages and not just forms/tables).  Would you want to hold off until I've tested and pushed the new version?

**Comment by jerodsanto** [comment]
Sure thing. Ping us again when it's ready to go!

**Comment by alexweissman** [comment]
Great, thanks!

**Comment by alexweissman** [comment]
Alright, it still needs more documentation, but the new version is up!

**Comment by jerodsanto** [comment]
@alexweissman awesome, it'll be in the next issue of Weekly!

**Comment by alexweissman** [comment]
Just finished up the [website](https://alexweissman.github.io/bootsole/), which has full documentation.
