### ISSUE TITLE
DevOps'ish Newsletter

### ISSUE THREAD

**Issue by chris-short** [thechangelog/ping#690]
The DevOps'ish Newsletter (archives hosted on Medium at https://devopsish.com) is a weekly read covering Dev, Ops, and some ish in between. Would be VERY appreciative of a plug or mention. But, at the very least some constructive criticism would be great too! Thank you!

**Comment by jerodsanto** [comment]
@chris-short we just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by chris-short** [comment]
Much appreciated!
