### ISSUE TITLE
tradeship - Editor plugin to automatically import missing JavaScript depedencies

### ISSUE THREAD

**Issue by karthikv** [thechangelog/ping#691]
[tradeship](https://github.com/karthikv/tradeship) statically analyzes your JavaScript code for identifiers that aren't defined and finds the appropriate dependencies to import. It also removes imports that aren't used.

https://github.com/karthikv/tradeship

A few key features:

- Imports dependencies from node.js standard libraries, npm packages listed in package.json, and other files within your project directory.
- Infers properties that are exported by dependencies and imports them using destructuring syntax (e.g. `const { Component } = require("react");`).
- Knows aliases for dependencies (e.g. `$` for jQuery, `_` for lodash/underscore, `test` for ava, etc.) by analyzing more than 100 GB of public JS code on GitHub.
- Automatically identifies the style of your code and makes the imports match (e.g. single vs. double quotes, semicolons vs. no semicolons, var vs. let vs. const, etc.)

**Comment by jerodsanto** [comment]
@karthikv :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
