### ISSUE TITLE
Github license check - make sure that other people can use you work

### ISSUE THREAD

**Issue by k-nut** [thechangelog/ping#692]
Open source projects need to have a license attached to them so that other people can use them.

There are a lot of tools to check if a projects's dependencies are properly licensed but not so many to make sure that *your* repositories have licenses.

So I made a small website (https://license-check.k-nut.eu/) where you can put in your name on github and check if all of your repositories have a license.
 
If not it even helps you to add one!

![screenshot](https://cloud.githubusercontent.com/assets/1096357/24588205/689eb4ac-17c4-11e7-8d65-8fc6f5ddd7d5.png)

Build with the [GitHub License Api](https://developer.github.com/v3/licenses/) and vue.js.

Source: https://github.com/k-nut/github-license-check

**Comment by jerodsanto** [comment]
@k-nut cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
