### ISSUE TITLE
django-split-settings

### ISSUE THREAD

**Issue by sobolevn** [thechangelog/ping#693]
# django-split-settings

![bca0f178-1706-11e7-938c-c117ea84300c](https://cloud.githubusercontent.com/assets/4660275/24611305/57440ea2-188a-11e7-8975-7ecc7a3ab12c.png)

Organize Django settings into multiple files and directories. Easily override and modify settings. Use wildcards and optional settings files.

## Usage

Replace your existing `settings.py` with a list of components that make up your Django settings. Preferably create a settings package that contains all the files.

Here's a minimal example:

```python
from split_settings.tools import optional, include

include(
    'components/base.py',
    'components/database.py',
    optional('local_settings.py')
)
```

In the example, the files `base.py` and `database.py` are included in that order from the subdirectory called `components/`. `local_settings.py` in the same directory is included if it exists.

## Articles

Quick-starting guide: https://medium.com/wemake-services/managing-djangos-settings-e2b7f496120d

**Comment by jerodsanto** [comment]
@sobolevn :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by sobolevn** [comment]
Thanks! Great news!
