### ISSUE TITLE
[Podcast Suggestion] Wire - Secure & Cross Platform messenger

### ISSUE THREAD

**Issue by tcbyrd** [thechangelog/ping#694]
I've been using this app for a few months and have grown to really, really enjoy it for a number of reasons. I was a big user of Google Talk and then Hangouts, mainly because it was the only messaging app that worked on both desktop and mobile across multiple platforms. All of the new messaging apps seem to be mobile first (or in most cases, mobile only), so when I heard Hangouts was shifting focus, I went on a search for a good replacement. Signal seemed promising, but didn't have a great cross platform story.

Then I came across [Wire](https://wire.com/). It's completely open source on [all platforms](https://github.com/wireapp), has some nice integrations with [giphy](https://giphy.com/posts/now-you-can-use-giphy-in-wire), and they claim end to end [privacy](https://wire.com/en/privacy/) and [security](https://wire.com/resource/Wire%20Security%20Whitepaper/download/). Yesterday I saw [this article on Medium](https://medium.com/wire-news/call-security-constant-bit-rate-encoding-and-improving-webrtc-a85be6caa43a) talking about improvements to call security by using CBR instead of VBR and I thought it could be a super interesting topic for a podcast, especially since they're contributing the patches back to the WebRTC team so these improvements can make it into Chromium (and by proxy, Electron). I've always felt the a/v quality of WebRTC wasn't as good as Skype, so seeing a team like this really push the envelope on both quality and security is awesome to me. I'd love to hear their story.

**Comment by jerodsanto** [comment]
@tcbyrd 👍 good show topic and good job pitching it. We'll get to work on this 🔨

**Comment by jerodsanto** [comment]
The ball is rolling. I'll post here if/when the show goes live. Closing for cleanliness 🤗
