### ISSUE TITLE
Web Maker - A blazing fast, open source & offline frontend playground

### ISSUE THREAD

**Issue by chinchang** [thechangelog/ping#695]
Web Maker -> https://webmakerapp.com/

Web Maker is a chrome extension that gives you CodePen like front-end playground but it also works offline and hence is real fast! 

Repo -> https://github.com/chinchang/web-maker/

**Comment by jerodsanto** [comment]
@chinchang nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Web Maker up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by chinchang** [comment]
@jerodsanto Thanks Jerod! 😄
