### ISSUE TITLE
Web development in Go

### ISSUE THREAD

**Issue by kevinburke** [thechangelog/ping#697]
I recently put together a starter pack for doing web development in Go: https://github.com/kevinburke/go-html-boilerplate

and wrote about it: https://kev.inburke.com/kevin/go-web-development/

> You should write your next web server in Go. Yes, you! Compared with Ruby, PHP, Python, or Javascript, you're going to get great memory and latency performance, and libraries that do what you expect.
>
> The standard library can be a bit lacking though, if you are used to developing with a tool like Rails. I found myself adding the same helpers to every web project that I started in Go, so I compiled those tools into a starter pack. Most of the code is thin wrappers around the standard library, and any/all of it can be ripped out. I wanted to go over some of the tools in the starter pack.

Covered regex routing, serving static assets, HTTP/2 server push, flash messages, loading configuration, releasing new binaries, more.

**Comment by jerodsanto** [comment]
@kevinburke :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
