### ISSUE TITLE
Let's build a new language together

### ISSUE THREAD

**Issue by st0012** [thechangelog/ping#698]
Hi, [Rooby](https://github.com/st0012/Rooby) is a new object oriented language I created recently (written in Go). It looks just like Ruby for now because it's mainly inspired by it. But I want it to be a new language and start developing its own feature when it gets more mature. So I'm looking for developers who also interested in this project, any help or idea will help me a lot.

**Comment by jerodsanto** [comment]
@st0012 this one hit our radar earlier this week and we [tweeted](https://twitter.com/changelog/status/852185322406412288) about it. We'll also link it up on [Weekly](https://changelog.com/weekly) 🥂

**Comment by st0012** [comment]
@jerodsanto Wow I didn't expect you'll find my project, thanks for sharing 😄
