### ISSUE TITLE
React on Rails

### ISSUE THREAD

**Issue by justin808** [thechangelog/ping#699]
We've done a lot since #393!

A full log can be found here: https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md

The big news is that version 7.0.0 with support for [shakacode/webpacker_lite](https://github.com/shakacode/webpacker_lite) is coming in the next couple of weeks.

Webpacker Lite is a fork of Webpacker that can be found on [RubyGems](https://rubygems.org/gems/webpacker_lite).

**Comment by jerodsanto** [comment]
@justin808 a lot has been done, indeed (even since you posted this issue)! We'll link it up again and mention the Webpacker Lite support that landed in v8 ✊

**Comment by justin808** [comment]
Aloha @jerodsanto! Given my 💥 big speaking tour on shakacode/react_on_rails in June! https://forum.shakacode.com/t/talks-on-react-on-rails-june-2017/891 would it make sense to put me on a podcast after that? I think this is a pretty interesting open source discussion: https://github.com/rails/webpacker/issues/464
