### ISSUE TITLE
Touch Bar Simulator

### ISSUE THREAD

**Issue by sindresorhus** [thechangelog/ping#700]
I made this open-source Mac app that lets anyone try out the new Touch Bar without needing the new MacBook Pro or Xcode. It's especially useful for developers and designers that are making Mac apps.

https://github.com/sindresorhus/touch-bar-simulator

---

It uses some fun private API trickery:

> #### How does this work?

> In short, it exposes the Touch Bar simulator from inside Xcode as a standalone app with added features. I class-dumped a private Xcode framework and used that to expose a private class to get a reference to the Touch Bar window controller. I then launch that window and add a screenshot button to it. I've bundled the required private frameworks to make it work without Xcode. That's why the binary is so big.

**Comment by jerodsanto** [comment]
:green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
