### ISSUE TITLE
Show idea pnpm

### ISSUE THREAD

**Issue by akras-apixio** [thechangelog/ping#701]
It's an interesting npm replacement client, faster than yarn.

https://www.kochan.io/nodejs/why-should-we-use-pnpm.html

**Comment by jerodsanto** [comment]
I don't think this is a show we want to do, @akras-apixio. But we definitely appreciate the thought!

This might be a good one for @andrew to cover on [The Manifest](https://manifest.fm)? (which is a great show, btw)

💚💚💚

**Comment by andrew** [comment]
👍  sounds like a good fit for the Manifest, @akras-apixio fancy submitting it via our contact form: https://manifest.fm/contact
