### ISSUE TITLE
iwant-demo: Multi-module project demonstrating the iwant build system

### ISSUE THREAD

**Issue by wipu** [thechangelog/ping#702]
[`iwant-demo`](https://github.com/wipu/iwant-demo) is a simple multi-module project that uses [`iwant`](http://iwant.sourceforge.net/) as its build system, to demonstrate `iwant` features. It is meant for promoting `iwant` and supplementing its own documentation in a more concrete way.

**Comment by jerodsanto** [comment]
@wipu we'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
