### ISSUE TITLE
Project Shoutout: Freactal

### ISSUE THREAD

**Issue by baer** [thechangelog/ping#704]
Freactal is a composable state mechanism for React that is meant to replace things like [`redux`](https://redux.js.org) and [`MobX`](https://mobx.js.org) but also all of the side-effect tooling like [`redux-loop`](https://github.com/redux-loop/redux-loop), [`redux-thunk`](https://github.com/gaearon/redux-thunk), [`redux-saga`](https://github.com/redux-saga/redux-saga), etc. 

The core of the problem is that in a large enough project, there are almost always different teams working on different parts of a problem but gluing disparate (stateful) components together is terrible. I've been looking at this for the last day or so and I'm incredibly impressed. This doesn't seem like an incremental improvement. 

[Blog Post Explainer](https://formidable.com/blog/2017/infinite-state-composition-with-freactal/
)
[Project Repo](https://github.com/FormidableLabs/freactal)

Also, worth noting that the author of this project is responsible for several other interesting things including a complete build system ([Interlock](http://interlockjs.com/)), a React SSR project ([Rapcallion](https://github.com/FormidableLabs/rapscallion)) and a git + Sublime ([git savvy](https://github.com/divmain/GitSavvy)) integration.

For full disclosure, I work at Formidable but I am writing this of my own accord.

**Comment by jerodsanto** [comment]
@baer :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
