### ISSUE TITLE
Empowering the Next Million Creators

### ISSUE THREAD

**Issue by kenrossi** [thechangelog/ping#705]
We recently launched [CardStack](https://github.com/cardstack/cardstack) at the Ember 2017 conference. 

Here is the brief description of the conference video - 

Ember isn't just about making developers more efficient. It's about empowering a wider audience to become creators and developers. How do we bridge the gap between our vibrant community and the next million people who have things they want to make but have no idea how to even collaborate with us? We already have the foundations of great content-creation tools that will allow authors, site builders, themers, and devs to speak the same language and build higher together. What if anyone could ship their own first app with no coding, but with the power of Ember's community under the hood?

[Empowering the Next Million Creators](http://confreaks.tv/videos/emberconf2017-empowering-the-next-million-creators)

For the past few years we have been developing CardStack behind the scenes of some successful enterprise projects which have graciously sponsored OSS development. We would love to have a conversation about the future of CardStack and how it relates to Ember and the open source community at large. We have been blessed to have some of the Ember Core team working on this project. One of the topics we are passionate about is OSS as it relates to enterprise level projects and we feel that CardStack could be a stepping stone. 

If you want more background on the project, our current(ly dated) [website](http://www.cardstack.com) has links to prior video and decks related to the vision of the project. 

Thanks for your consideration. I would love to set up an initial conversation between 
you and the core team. I was part of the design team. 

best,
ken

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
