### ISSUE TITLE
ghbackup - Embarrassingly simple GitHub backup tool 

### ISSUE THREAD

**Issue by jorinvo** [thechangelog/ping#706]
Hi, first thanks for running this great show!

I created a GitHub backup tool that I think might also be helpful for others:
https://github.com/qvl/ghbackup
> Backup your GitHub repositories with a simple command-line application written in Go.

I also wrote a short tutorial on how to set everything up on your own server: 
[Automating the Backup of GitHub Repositories Using ghbackup](https://jorin.me/automating-github-backup-with-ghbackup/)

Cheers, 
Jorin

**Comment by jerodsanto** [comment]
@jorinvo nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link ghbackup up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
