### ISSUE TITLE
fetch-timeline-cli

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#707]
![](https://camo.githubusercontent.com/228035ab7ac835dab80e64369efdedc18b972ec1/687474703a2f2f672e7265636f726469742e636f2f665554677546364654512e676966)

**Description**
Fetch Twitter user's timeline from your terminal

**Web** 
https://kikobeats.github.io/fetch-timeline-cli/

**Repository** 
https://github.com/Kikobeats/fetch-timeline-cli

**Comment by jerodsanto** [comment]
@Kikobeats nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by Kikobeats** [comment]
Thanks for all 😄
