### ISSUE TITLE
Insights - Self-Hosted “SQL-Not-required” Data Analytics and BI Tool. Inspired by Looker 

### ISSUE THREAD

**Issue by mariusandra** [thechangelog/ping#708]
Hey! I recently published a new open source BI tool called Insights: https://github.com/mariusandra/insights

It's a tool in the "business intelligence on the cheap" category. Perhaps your readers will find in interesting, exciting and or awesome! Check it out :)

Thanks and cheers!

Copy/paste from the README follows:

----

As our [education marketplace](https://www.apprentus.com) grew, we faced a dilemma: we had little visibility into our data.

Questions such as *"who is our best customer?"*, *"which target countries are gaining in sales?"* or *"what are our most popular categories for paid leads?"* required tinkering in the Rails console or writing custom stats pages. We lost *a lot* of developer time over the years.

So we started looking for the best **Business Intelligence** solution out there.

Unfortunately, they all had their problems. Some required knowledge of SQL. Some made multi-table data exploration a pain. Most cost an arm, a leg and an iPhone. Per month.

The best tool we found was [Looker](https://looker.com/), but at a monthly price equal to our burn rate, it wouldn't work.

So I decided to re-implement the essential parts of Looker as an open source alternative.

**Insights** is a self-hosted "SQL-not-required" data analytics and business intelligence tool. Featuring linkable URLs, easy data exploration, automatic joins, graphs, exports, facets (pivots), pretty colors and a ridiculously permissive license (MIT).

It's a work in progress and you're brave for checking it out! Cheers!

[Play with the demo here](http://insights-demo.mariusandra.com/).

![Screenshot of the Explorer](https://github.com/mariusandra/insights/raw/master/doc/screenshot.png)

**Comment by jerodsanto** [comment]
👋 @mariusandra, this looks cool! Reading through your back story, I'm curious if you found and/or tried [Metabase](https://github.com/metabase/metabase) before developing this.

(We did [a show about Metabase](https://changelog.com/podcast/182) awhile back, if you want to hear their story.)

**Comment by mariusandra** [comment]
Hey, I did try Metabase (and Subset, Redash, etc) before writing this. I wrote about my issues with Metabase in more details on HN: https://news.ycombinator.com/item?id=14361791

That said, I didn't listen to that episode yet, will add it to my evening run's listening list, thanks! 😄

**Comment by jerodsanto** [comment]
Cool, cool. Just wanted to make sure you did your homework first 😁 

We'll link this up in the next issue of [Weekly](https://changelog.com/weekly) 🍻

**Comment by mariusandra** [comment]
Awesome! Thank you! :beers:
