### ISSUE TITLE
asm-dom

### ISSUE THREAD

**Issue by mbasso** [thechangelog/ping#709]
> A minimal WebAssembly virtual DOM focused on performance

- https://github.com/mbasso/asm-dom

asm-dom is a minimal WebAssembly virtual DOM focused on performance. It is born from the idea to test the powerful of WebAssembly in a common use case that is not gaming, VR, AR or Image / video editing. Unfortunately, at the moment, GC / DOM / Web API Integration is a future feature 🦄, so, asm-dom isn't totally developed in wasm. All interactions with the DOM are written in Javascript. This is a big disadvantage because of the overhead of the binding between JS and WASM, in the future asm-dom will be even more powerful, anyway results are satisfying. Last but not least, this project aims to be an example for those who want to try WebAssembly and emscripten!

**Comment by jerodsanto** [comment]
@mbasso :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
