### ISSUE TITLE
Pegasus - Load data while still loading other scripts

### ISSUE THREAD

**Issue by typicode** [thechangelog/ping#71]
Hi The Changelog,

Server-side data bootsrapping or rendering are geat techniques to improve loading time and should be used whenever possible.

But sometimes, it can be complicated to set up (old servers, static pages, ...).

Pegasus is a small script that lets you load data while still loading other scripts. This way you can improve your average time to display data without touching the server.

http://typicode.github.io/pegasus/

**Comment by jerodsanto** [comment]
@typicode keep your eyes peeled for Pegasus in the next issue of [Weekly](http://thechangelog.com/weekly).  It'll be in there! :beers:

**Comment by typicode** [comment]
Awesome! Thanks :)
