### ISSUE TITLE
[Podcast Suggestion] Kotlin

### ISSUE THREAD

**Issue by shyiko** [thechangelog/ping#710]
With Google having [announced that it will officially support Kotlin](https://blog.jetbrains.com/kotlin/2017/05/kotlin-on-android-now-official/) on Android as a “first-class” language [Kotlin](https://kotlinlang.org/) is slowly but surely taking over Java/Android community. 

I'd like to propose an interview with @yole (Dmitry Jemerov) / @abreslav (Andrey Breslav) / anyone else behind the project. 

I'm sure a lot of people would love to hear about backstory, what was the motivation, language design process and what we can expect in future.

:heart:

@jetbrains

**Comment by yole** [comment]
I'd be happy to participate in the podcast, so let me know if you'd like to have me as a guest.

**Comment by physcocode** [comment]
+1 i would love it :)

**Comment by jerodsanto** [comment]
@shyiko good suggestion! I was actually just thinking about doing an episode on Kotlin the other day...

@yole we'd love to have you on the show! Please email editors@changelog.com to coordinate.

💚

**Comment by jerodsanto** [comment]
This episode is now live 🎉 

https://changelog.com/podcast/265
