### ISSUE TITLE
BotMan - Multi platform chatbots with PHP

### ISSUE THREAD

**Issue by mpociot** [thechangelog/ping#711]
[Official Website](https://botman.io)
[Github](https://github.com/mpociot/botman)

BotMan is a framework agnostic PHP library that is designed to simplify the task of developing innovative bots for multiple messaging platforms, including Slack, Telegram, Microsoft Bot Framework, Nexmo, HipChat, Facebook Messenger and WeChat.

**Comment by jerodsanto** [comment]
@mpociot nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link BotMan up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
