### ISSUE TITLE
Django-Viewflow and Django-Material 1.0

### ISSUE THREAD

**Issue by kmmbvnr** [thechangelog/ping#712]
After 3 years of development, here is the stable 1.0 release of Django-Viewflow and Django-Material libraries

Viewflow is the reusable workflow library for Django, that helps to implement people collaboration software. 

Django-Material helps to build user interfaces in a few lines of code. It takes care about site navigation, solves complex form construction for Django, and provides shortcuts to build CRUD like Django admin, but with your own class based views.

https://medium.com/@viewflow/viewflow-1-0-835b72a65fea

**Comment by jerodsanto** [comment]
@kmmbvnr cool stuff! We'll link both of these up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
