### ISSUE TITLE
[Podcast Suggestion]  gRPC vs REST vs GraphQL

### ISSUE THREAD

**Issue by hsmack** [thechangelog/ping#713]
gRPC is getting more popular in the open source community.  I'm not from the Google world, so I simply don't know anything about it or the benefits.  I'm not a Java engineer either so I don't use RPC allot either.  I would assume allot of podcast listeners are like me.

Maybe some discussion about:
1. vs REST, and how it works, why to pick it as a technology
2. What its' really good at solving.  Where does it not work well?
3.  Any RPC interface basically means that error handling is built-in.  How good is it's error handling compared to xml-rpc?  I've tried out Python xml-rpc and it's pretty cool.  There's json-type rpc these days too, why is gRPC better?
4.  Can all REST interfaces be replaced with gRPC?
5.  What other open source projects are integrating gRPC?
6.  GraphQL is popular, is it a competing technology?
7.  Other error cases, network latency or instability, why does Google use it everywhere in their infrastructure?

**Comment by ubergarm** [comment]
255 Came out recently addressing some GraphQL portions of this question: https://changelog.com/podcast/255

**Comment by jerodsanto** [comment]
@hsmack did you listen to our show about GraphQL that @ubergarm linked above? If so, does it satisfy your curiosities around this topic?

**Comment by jerodsanto** [comment]
Closing this to keep things tidy. If overwhelming support of a gRPC resurfaces, we'll definitely consider it. 🍻
