### ISSUE TITLE
Moleculer project

### ISSUE THREAD

**Issue by icebob** [thechangelog/ping#714]
Moleculer is a modern microservices framework for NodeJS.

Site: http://moleculer.services/
Repo: https://github.com/ice-services/moleculer
Article: [Medium](https://medium.com/moleculer/moleculer-a-modern-microservices-framework-for-nodejs-bc4065e6b7ba)

Thank you!

**Comment by sw-yx** [comment]
i have been helping icebob with some minor tasks on his boilerplate over the past couple weeks. i think Moleculer could very well be the "industrial grade" microservices framework that NodeJS needs.

**Comment by jerodsanto** [comment]
nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Molecular up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by icebob** [comment]
Awesome! Thanks! :+1:
