### ISSUE TITLE
licenseye - display project's dependencies licenses

### ISSUE THREAD

**Issue by lirantal** [thechangelog/ping#715]
Did you ever wonder what licenses your Node.js' project dependencies carry?

licenseye is a Node.js CLI tool to visualize an aggregate list of your dependencies' licenses -
 https://github.com/lirantal/licenseye

![](https://camo.githubusercontent.com/b278a6cfb0c74d0220d431089b75270d48e5ba27/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f79314430534c72396b51396c362f67697068792e676966)

P.S. it differs from built-in yarn/npm license listing in the fact that it aggregates and visualizes the data.

**Comment by jerodsanto** [comment]
@lirantal cool stuff! We'll link licenseye up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by lirantal** [comment]
yay! sounds great! thanks guys 🎉
