### ISSUE TITLE
Nitrite: An embedded NoSQL document database for Andorid

### ISSUE THREAD

**Issue by anidotnet** [thechangelog/ping#716]
## Nitrite Database

<img src="http://www.dizitart.org/nitrite-database/doc/1.0/images/nitrite-logo.svg" alt="Logo" width="200" height="200">

**NO**sql **O**bject (NO<sub>2</sub> a.k.a Nitrite) database is an open source nosql embedded document store written in Java. It has MongoDB like API. It supports both in-memory and single file based persistent store powered by [MVStore](http://www.h2database.com/html/mvstore.html) engine of h2 database.

Nitrite is a server-less embedded database ideal for desktop, mobile or small web applications.

**It features**:

* Embedded key-value/document and object store
* In-memory or single data file
* Very fast and lightweight MongoDB like API
* Indexing
* Full text search capability
* Full Android compatibility
* Observable store
* Both way replication via Nitrite [DataGate](http://www.dizitart.org/nitrite-datagate.html) server

Project Page: https://github.com/dizitart/nitrite-database
Document Page: http://www.dizitart.org/nitrite-database

**Comment by jerodsanto** [comment]
@anidotnet we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
