### ISSUE TITLE
#Doccies Award For Make Benefit Glorious Community of Open Source

### ISSUE THREAD

**Issue by sw-yx** [thechangelog/ping#718]
hello! in response to [the recent Github survey](http://opensourcesurvey.org/2017/) (github [here](https://github.com/github/open-source-survey)), which identified poor documentation as the top problem in open source, I thought that it might be a good idea to create a #Doccies award to recognize great documentation, similar to the Webbies. I pitched this on twitter and Mikeal Rogers and others tentatively liked the idea, however I am myself new to open source and definitely new to organizing anything like this. Just wondering if anyone on here would like to collaborate on this and/or have thoughts on what would be a good first small-scale run?

some thoughts on structure:
- two major types: one popularity contest and one award judged by a panel of well known open sourcers
- nomination methods: could either be maintainers nominating individual documentation writers (more specific recognition is a good thing), or users nominating overall projects (less specific but probably more realistic as it is hard to attribute who contributed what to documentation)
- categories: obviously this can go a ton of different ways but the splits that make sense to me include: Frontend/Backend/Native, Split by Language, Best README.md, Funniest example, etc
- weight classes: larger projects will tend to have better documentation. suggest to have 3 diff weight classes: [100-999 stars, 1000-9999 stars, >10k stars] as of a given cutoff date.

People have proposed a "Razzies" style name and shame thing but I think a positive approach works best for open source. 

bottomline - anyone willing to help experiment if this might promote better documentation? i would happily put in some dev time to put up a basic webapp for the voting.

**Comment by jerodsanto** [comment]
I dig the idea (and agree on avoiding the 'name and shame' angle)!

Changelog would happily help promote/host/whathaveyou.

**Comment by jerodsanto** [comment]
@sw-yx believe it or not, but we are actively pursuing this idea! Would you like to be involved or have you moved on to bigger/better things?

(If yes, [hop in our Slack](https://changelog.com/community) and let's chat more. If no, we will surely credit you with the brain child!)

**Comment by sw-yx** [comment]
lol! nice! pretty tied up in job stuff right now but happy to follow along and promote

**Comment by jerodsanto** [comment]
figured as much! I'll holler at ya when we have the ball rolling so you can get involved from there ✊
