### ISSUE TITLE
NHSbuntu: an Ubuntu-based distro for the UK National Health Service

### ISSUE THREAD

**Issue by pacharanero** [thechangelog/ping#719]
The NHS spends something like £100m (USD$125million) annually on various Microsoft licenses. And we still got taken out by WannaCrypt

> The UK National Health Service is the publicly-funded universal healthcare system in the UK. It's one of the largest employers in the world and has the same issues with large-scale tech deployments that you would expect from an organisation of that size.

> The NHS is also mostly a Windows XP/7 shop because of previous purchasing decisions leaving us heavily coupled to Microsoft-only software - a fact that caused us much recent pain when #WannaCry took out a significant amount of NHS services for a few days.

Even before the international cyberattack this May, we (the NHSbuntu team) had been working on a respin of Ubuntu, aiming at offering a secure, free, opensource alternative to Windows for NHS desktop users (yes - you read that right - *desktop* users).

In developing a Linux distro for a specific organisation and use-case we've been on an interesting journey through `dpkg`, UK & NHS politics, anti-OSS tech culture, and 'solutions for legacy clinical apps that the NHS can't live without'.

Web & ISO download: www.nhsbuntu.org
GitHub: https://github.com/NHSbuntu
Twitter: www.twitter.com/nhsbuntu
Slack: https://join-nhsbuntu-slack-team.now.sh/

**Comment by jerodsanto** [comment]
thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:

**Comment by pacharanero** [comment]
Thanks Jerod! much obliged.
Marcus
