### ISSUE TITLE
opsdroid

### ISSUE THREAD

**Issue by jacobtomlinson** [thechangelog/ping#720]
### Project 
opsdroid

### One-liner
An open source chat-ops bot framework written in python. 

### Key points
- It's open source
- Simple to modify and extend
- Add you own skills in under 10 lines of python
- Easy to install
- Designed with Docker in mind for simple deployment
- Configurable with a single YAML file
- Can connect to multiple chat services simultaneously
- No coding necessary if using the official modules

### Website
https://opsdroid.github.io

**Comment by jerodsanto** [comment]
nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link opsdroid up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
