### ISSUE TITLE
Sip I/O: Next-generation signaling server

### ISSUE THREAD

**Issue by psanders** [thechangelog/ping#721]
**Project**

Sip I/O

**Description**

Sip I/O is a lightweight sip proxy, location server, and registrar that provides a reliable and scalable SIP infrastructure for telephony carriers, communication service providers, and integrators.

**What is it useful for?**

- [x] Simple call setup for sip devices
- [x] WebRTC signaling server
- [x] Signaling for chat applications
- [x] Multi-tenant VOIP network setup
- [x] Frontend for Asterisk or any Media Server

More info at https://github.com/psanders/sipio

**Comment by jerodsanto** [comment]
@psanders we're including Sip I/O in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
