### ISSUE TITLE
Please, invite TJ Holowaychuk

### ISSUE THREAD

**Issue by AlexVPopov** [thechangelog/ping#722]
Given the amazing amount of value [TJ Holowaychuk](https://github.com/tj) has created in the (open-source) world, I find that a lot of people would be trilled to listen to an episode with him. Some of the facts that I find particularly interesting around him:

* he started as a graphic designer;
* he has no formal education in CS (I am not even sure he has any formal higher education);
* he has created and published several hundred npm packages;
* he is the creator of [express.js](https://github.com/expressjs/express);

I find all this pretty impressive and would love if you have him on the podcast.

**Comment by jerodsanto** [comment]
We'd 💚 to have TJ on the show!

@tj if you're interested in joining us, send an email to editors@changelog.com and we'll coordinate.

(thanks for the idea, @AlexVPopov) 🍻
