### ISSUE TITLE
The future of Apache Cassandra

### ISSUE THREAD

**Issue by kpcp** [thechangelog/ping#723]
Wanted to run a potential new Changelog guest who could discuss the future of the open source Apache Cassandra database -- along with the new challenges it'll face along the way. 

Ben Bromhead is a strong believer that the best version of Cassandra is and will continue to be the open source version. He's CTO at Instaclustr, long a major contributor to Cassandra and Apache Spark -- with the belief that companies like his (which rely heavily on open source technologies) contribute fairly to the community. The startup recently dedicated its first full time resource dedicated to open source contribution.

Ben could talk through Cassandra's challenges for deployment, monitoring, reporting, performance, scalability, etc -- current state, future, and use cases that make the most sense for the open source DB.

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
