### ISSUE TITLE
TrivialRC: the minimalistic run-time configuration system for Docker containers

### ISSUE THREAD

**Issue by vorakl** [thechangelog/ping#724]
[TrivialRC](https://github.com/vorakl/TrivialRC) is a minimalistic Run-time Configuration (RC) system and process manager is written in pure BASH and uses just a few external utilities. Minimally, installation of TrivialRC consists of only one file which can be downloaded directly from the Github. Originaly, it was designed for use in Docker containers but it also can be well used for running a group of processes asynchronously and synchronously, as well as managing their running order and exit codes.

**Comment by jerodsanto** [comment]
@vorakl cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by vorakl** [comment]
Great news. Thanks! :)
