### ISSUE TITLE
NeoForm – better form state management for React 

### ISSUE THREAD

**Issue by deepsweet** [thechangelog/ping#725]
> Better form state management for React where data state is directly mapped to form fields, so form becomes just a representation and changing interface for that data state.

https://github.com/zero-plus-x/neoform

Very modular and modern approach using Higher-Order Components and Promises for validation.

**Comment by jerodsanto** [comment]
@deepsweet nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link NeoForm up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by deepsweet** [comment]
Yay!

Could you please also change the title to "Higher-Order Components for form state management and validation in React"?

Thanks.

**Comment by jerodsanto** [comment]
Way ahead of you 😉 
<img width="722" alt="2017-08-18 at 11 01 am" src="https://user-images.githubusercontent.com/8212/29467034-a4135716-8404-11e7-8f93-cfda3ee05f93.png">
