### ISSUE TITLE
Podcast Suggestion: Operação Serenata de Amor project

### ISSUE THREAD

**Issue by fgrehm** [thechangelog/ping#726]
Hey guys!

Just wanted to bring to your attention a nice Brazilian project that uses "Artificial intelligence for social control of public administration" called [Operação Serenata de Amor](https://serenatadeamor.org/en/) which has the potential of serving as an inspiration / foundation for people in other countries.

Even though most of the related media coverage out there is in Portuguese, all of the development is done in the open in English [here on GitHub](https://github.com/datasciencebr/serenata-de-amor) and I'm pretty sure the core team is comfortable speaking in english 😄

/cc @Irio @cuducos @jtemporal

**Comment by jerodsanto** [comment]
@fgrehm very cool! We'd love to do a show about this. 

@irio @cuducos @jtemporal please determine which of the core team is the _best_ English speaker and have that person email editors@changelog.com to coordinate!

💚💚💚

**Comment by cuducos** [comment]
Many thanks @fgrehm! @jerodsanto just dropped you a line ; )

**Comment by jerodsanto** [comment]
We 🚢d it! 👏 👏 

https://changelog.com/podcast/268

Thanks to all involved! 💚💚💚
