### ISSUE TITLE
Suet - analytics dashboard and reporting tool for Mailgun transactional emails

### ISSUE THREAD

**Issue by kehers** [thechangelog/ping#727]
[Github repo](https://github.com/kehers/suet)
[Hosted version](https://suet.co/)

Suet gives better insight into transactional emails sent through Mailgun. Easily see performance, clicks, opens and engagement. Get complaints, bounces and failures sent to Slack.

**Comment by jerodsanto** [comment]
@kehers we're including Suet in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
