### ISSUE TITLE
Addict: Drop-in REST API for Active Directory / LDAP

### ISSUE THREAD

**Issue by dthree** [thechangelog/ping#729]
Hey. I wanted to let you know about a library I just finished, [Addict](https://github.com/dthree/addict). This is a full REST API for Active Directory out of the box, including interactive API docs.

Windows Server / Active Directory / LDAP aren't the biggest subjects in the development world, so it's a bit hard to get the word out. Still, I would like to so people who have to deal with these subjects don't miss out!

Thanks.

**Comment by jerodsanto** [comment]
@dthree nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Addict up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by cwbsl** [comment]
Such an amazing tool. Why is it not hosted anymore on GitHub?
