### ISSUE TITLE
Federation - Python library for abstracting social federation protocols

### ISSUE THREAD

**Issue by jaywink** [thechangelog/ping#730]
> The aim of federation is to provide and abstract multiple social web protocols like Diaspora in one package. This way applications can be built to (almost) transparently support many protocols without the app builder having to know everything about those protocols.

https://github.com/jaywink/federation

**Comment by jerodsanto** [comment]
@jaywink cool stuff! We'll link Federation up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
