### ISSUE TITLE
Socialhome - A federated social home

### ISSUE THREAD

**Issue by jaywink** [thechangelog/ping#731]
> Socialhome is best described as a federated personal profile with social networking functionality. Users can create rich content using Markdown and even HTML/JS/CSS (if set as trusted user). All content can be pinned to the user profile and all content will federate to contacts in the federated social web. Currently federation happens using the Diaspora protocol with future plans to include at least ActivityPub as well. Federating using existing protocols means Socialhome users can interact with tens of thousands of other users.

Home: https://socialhome.network / GitHub: https://github.com/jaywink/socialhome

**Comment by jerodsanto** [comment]
@jaywink cool stuff! We'll link Socialhome up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
