### ISSUE TITLE
Changelog Weekly display issues in Thunderbird

### ISSUE THREAD

**Issue by J3RN** [thechangelog/ping#732]
I'm sure this is probably a niche issue, since not too many folks use the Thunderbird email client anymore. However, it's been a bit of an annoyance for me. Besides, Thunderbird is open source! 😄 

## Expected behavior
Diplays similarly to how it does in Google Inbox
<img width="614" alt="screen shot 2017-07-31 at 11 12 22" src="https://user-images.githubusercontent.com/2058614/28784445-73e0d09a-75e1-11e7-895e-a6141dc73457.png">

## Actual behavior
<img width="1067" alt="screen shot 2017-07-31 at 11 15 50" src="https://user-images.githubusercontent.com/2058614/28784498-a57dc4a0-75e1-11e7-9a9d-4097e8c54c87.png">

- Some sort of weird encoding issue with the emdash.
- The title appears to the right of the subtitle.
- The page appears very wide (perhaps due to the above issue), which...
  - Requires the user to horizontally scroll to read text.
  - [Not pictured] Causes images to appear very large, and require scrolling to see all of.

I saw that you guys open sourced your [Changelog Nightly](https://github.com/thechangelog/nightly) email, which is super neat. If you guys are interested in open sourcing Changelog Weekly, I'd take a crack at fixing these display issues.

**Comment by jerodsanto** [comment]
@J3RN people still use Thunderbird? :trollface: 

We don't have any plans on open sourcing Weekly (it's a bit of a mess), but we _do want_ our emails to look great in as many clients as possible. Now, if you were complaining about it rendering bad in Outlook 2013 or something... 😏 

I'll take a quick shot at fixing this and see what becomes of it.

**Comment by jerodsanto** [comment]
@J3RN the plot thickens...

I just downloaded Thunderbird and loaded up Issue 165 in it. Here's how it looks:

<img width="686" alt="2017-08-02 at 10 57 am" src="https://user-images.githubusercontent.com/8212/28882637-68ae0058-7771-11e7-9659-27fcee7da17f.png">

Shiny ✨ 

I'm running Thunderbird 52.2.1 (64-bit) on macOS 10.12.6. How about you?

**Comment by J3RN** [comment]
@jerodsanto Oh my! Somehow, I was running Thunderbird 45. Going to `Thunderird` -> `About Thunderbird` caused it to update, and now the email looks great! Gee, the future is shiny! ✨ 

Sorry about that! I'll close this out.

**Comment by jerodsanto** [comment]
Hey don't feel so bad, you were _only 7 versions* behind_ 🤣

Happy to hear I could help! 🍻 


_(*modern software versioning is so meaningless)_
