### ISSUE TITLE
Overmind and Hivemind, Procfile-based process managers for local web development

### ISSUE THREAD

**Issue by yaroslav** [thechangelog/ping#733]
> Procfile, introduced by David Dollar's `foreman`, is a popular format for declaring processes—everyone who ever used Heroku, knows it well. Anyone who didn't, really should learn it—it's an easy way to declare all the stuff that is needed to run your project (web app, additional apps, background processing, tools and daemons) and launch it.

> Unfortunately, `foreman` had some limitations, so there are new kids on the block—`tmux` support, tons of features, speedy and stable.

https://evilmartians.com/chronicles/introducing-overmind-and-hivemind

**Comment by jerodsanto** [comment]
@yaroslav we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
