### ISSUE TITLE
[Podcast Suggestion] Episode Transcripts

### ISSUE THREAD

**Issue by MJGwater** [thechangelog/ping#734]
Hey! I'd really appreciate it if you could start posting episode transcripts for The Changelog. There's often stuff that I don't entirely understand and it'd be nice to be able to look back at what was said. 

Keep up the great work!

**Comment by jerodsanto** [comment]
@MJGwater I have good news for you! Our episode transcripts are freely available on GitHub and we're integrating them in to the episode pages on the website Real Soon Now™.

https://github.com/thechangelog/transcripts

Thanks for listening/reading! 🥂
