### ISSUE TITLE
Kea

### ISSUE THREAD

**Issue by mariusandra** [thechangelog/ping#735]
Hey! I just wanted to inform you about an exciting project I've been working on for a long time now. I hope it's cool ❄️ enough to include in the next Weekly ;). 

It's called [Kea](https://kea.js.org/). It's an unique take on how to handle state in React. It's based on Redux (and Redux-Saga and Reselect). In my opinion it takes the best parts of Redux (functional, simple API, clean) and fixes the worst parts (a lot of boilerplate). [700+ stars](https://github.com/keajs/kea/) in Github over the last 2 weeks say that it's on to something... and the feedback I've gotten has been very supportive! 

(Best comment so far: "I'm so happy that this has reduce a lot of the boilerplate code & made my coding so much simpler! More people should use KeaJS as its making redux world a better place! 👍")

Today I wrote a [medium post](https://medium.com/@mariusandra/kea-vs-setstate-redux-mobx-dva-jumpstate-apollo-etc-4aa26ea11d02) explaining it in more depth and comparing it to all the alternatives (setState, Redux, MobX, Apollo-React/GraphQL, Dva, JumpState).

There's also a [HN thread](https://news.ycombinator.com/item?id=14859206) and a [Reddit thread](https://www.reddit.com/r/reactjs/comments/6pni2i/kea_high_level_abstraction_between_react_and_redux/?st=j5laxkxp&sh=08b58088) from the original reveal 2 weeks ago where people discuss it that could be interesting to read through.

Thanks for reading and keep rocking! 🤘

**Comment by mariusandra** [comment]
We just hit 1000 stars! 🌟

And there was [an interview](https://survivejs.com/blog/kea-interview/) about the project on survivejs. People genuinely seem [to enjoy](https://www.reddit.com/r/reactjs/comments/70uhqs/kea_high_level_abstraction_between_react_and/?st=j81h9007&sh=e5fa0026) it.

**Comment by jerodsanto** [comment]
@mariusandra cool stuff, and congrats on the warm reception! We'll link Kea up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
