### ISSUE TITLE
ReactiveUI joins the Microsoft .NET Foundation

### ISSUE THREAD

**Issue by ghuntley** [thechangelog/ping#736]
I'm Geoff and I'm the project lead for the an open-source project which is used by Slack & Amazon, GitHub, Elastic Search. Yesterday the project joined the .NET foundation and I'm wondering if this would be of interest to your readers?

- https://reactiveui.net/about
- https://dotnetfoundation.org/blog/welcome-reactiveui-to-the-net-foundation
- https://twitter.com/GeoffreyHuntley/status/894719030212218880
- https://github.com/reactiveui/reactiveui/
- https://reactiveui.net/

The team is available for any q's & interviews.

Thank-you LYW 👍 ❤️ 

# Boilerplate

ReactiveUI is a composable, cross-platform model-view-viewmodel framework for all .NET platforms that is inspired by functional reactive programming which is a paradigm that allows you to express the idea around a feature in one readable place, abstract mutable state away from your user interfaces and improve improve the testability of your application.

Most modern programming today is basically imperative, meaning it models the traditional fetch-execute cycle of a CPU: perform an instruction, fetch the next one, perform that one, and so on. For decades, programmers have had to mold their brains to fit the paradigm of the CPU. When teams rely on hoping that the behavior that emerges from a program is correct, and that reliance is based on nothing more than a programmer's correctness, you can find yourself in a sticky situation.  You can try and mitigate the costs of imperative programming with things like unit tests or integration tests, but why mitigate the costs when there's a better way?

The ReactiveUI team firmly believes reactive programming is fundamentally a better way to build your applications. Code is communication between people, that also happens to run on a computer. If you optimise for humans, then over a long time your project will end up better. Here's a great video that makes the point pretty clearly:

[![](http://img.youtube.com/vi/DYEbUF4xs1Q/0.jpg)](http://www.youtube.com/watch?v=DYEbUF4xs1Q "")

**Comment by jerodsanto** [comment]
@ghuntley sorry, we dropped the ball on this one! ☹️ 

I encourage you to submit future news/announcements [here](https://changelog.com/news/submit).
