### ISSUE TITLE
Fider: open platform to collect and organize customer feedback

### ISSUE THREAD

**Issue by goenning** [thechangelog/ping#737]
Hey,

I recently started an open source project called **Fider**, an open platform to collect and organize customer feedback. It's an alternative to some very expensive comercial tools we have out there. 

It's still on its early stages, so any feedback is highly appreciated.

Would be happy if you could help me spread the word! 

- Official website: http://getfider.com
- Demonstration: https://demo.fider.io
- GitHub: http://github.com/getfider/fider

By the way, I'm a big fan of GoTime and this is written in Go! :)

**Comment by jerodsanto** [comment]
@goenning :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:

**Comment by mtjhost** [comment]
How to install the Fider. Can you please make a video?
