### ISSUE TITLE
certbot-dns-ovh

### ISSUE THREAD

**Issue by mcdado** [thechangelog/ping#738]
Hi, this is a tiny one that I wished somebody made before me, so I didn't have to spend and afternoon on it:

- [github link](https://github.com/mcdado/certbot-dns-ovh)
- [npm link](https://www.npmjs.com/package/certbot-dns-ovh)

They're hook scripts so that you can perform DNS validation with Certbot (Let's Encrypt) with a DNS hosted on OVH. [There are some use cases](https://github.com/mcdado/certbot-dns-ovh#why-and-when-you-might-need-this) that I explained in the README.

**Comment by jerodsanto** [comment]
@mcdado thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
