### ISSUE TITLE
Project Shoutout: AmqpHosting

### ISSUE THREAD

**Issue by RabbitMQguy** [thechangelog/ping#739]
https://www.amqphosting.com is a reliable and non rate limited rabbitMQ hosting. 

We differ from other services in the following simple ways:
- We have No rate limits. We do not impose any limitation on either: the number of messages you can send, the number of queues you can create or anything else.
- We offer fully managed RabbitMQ servers. Customers just point and click to create a rabbitmq server that is tuned for production workloads.
- We offer only dedicated server nodes. For all our plans, we setup rabbitMQ on dedicated nodes for unmatched performance. We do not setup shared rabbitMQ servers(vhosts).
- Our RabbitMQ servers have No message losses due to network partitions. We do not cluster rabbitMQ since they are susceptible to message loss in the event of a network partion. Instead we have standalone rabbitMQ servers.
We have a comparison page at; https://www.amqphosting.com/us-vs-them

For full disclosure, I run AmqpHosting

**Comment by jerodsanto** [comment]
@RabbitMQguy AmqpHosting looks like a nice service! We have [great sponsorship options](https://changelog.com/sponsor) for SaaS offerings like this. Please take a look and get in touch! 💚
