### ISSUE TITLE
Docker easy load balancer

### ISSUE THREAD

**Issue by fgrehm** [thechangelog/ping#74]
Experimental automagic load balancing for Docker web apps in less than 100 lines of bash. Comes in handy when using Docker for development environments so we can stop worrying about remembering which app runs on which port :-)

https://github.com/fgrehm/docker-easy-lb

![img](https://camo.githubusercontent.com/5484897c2ff8f53d8fed349b191a15b705fa0842/687474703a2f2f692e696d6775722e636f6d2f7952727361414d2e676966)

**Comment by jerodsanto** [comment]
@fgrehm keep an eye out for this to be included in the next issue of [Weekly](http://thechangelog.com/weekly), which should :ship: this Saturday! :beers:

**Comment by fgrehm** [comment]
Many thanks!
