### ISSUE TITLE
Puppeteer a Headless Chrome Node API

### ISSUE THREAD

**Issue by atefBB** [thechangelog/ping#740]
Hey!
can you take a look to this tool <a href="https://github.com/GoogleChrome/puppeteer">Puppeteer </a> ?!
It seem great !

**Comment by jerodsanto** [comment]
@atefBB we're excited by it too! We [tweeted it yesterday](https://twitter.com/changelog/status/897859631271235584) and will have it in [Weekly](https://changelog.com/weekly) too! 🤜 🤛 

💚💚💚

**Comment by atefBB** [comment]
Good news ! thx !
