### ISSUE TITLE
Project release: Goby (Rooby)

### ISSUE THREAD

**Issue by st0012** [thechangelog/ping#741]
Hi, a few months ago I was also here posting my new language `Rooby` (it's called [`Goby`](https://github.com/goby-lang/goby) now). And after the crafting in past few months we finally released our `0.1.0` version 🎉

As I promised earlier, it has builtin multi-threaded server, thread and channel support and other features like: REPL, [Plugin System](https://goby-lang.gitbooks.io/goby/content/plugin-system.html) (which allows you using Go's package directly in Goby!) and you can manipulate Go object(pointer) directly in Goby.

We (we are a team now) also built a [sample site](http://sample.goby-lang.org) with 100% Goby. It proves that Goby is already functional on certain level.

(BTW we also have a [post](https://www.producthunt.com/posts/goby-language) on ProductHunt)

**Comment by jerodsanto** [comment]
@st0012 congrats on the continued success! we're including this in our next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by st0012** [comment]
@jerodsanto Sorry I didn't update that we already released version v0.1.2, which fixed a lot bugs 😅
