### ISSUE TITLE
Reaction Commerce: a real-time ecommerce platform

### ISSUE THREAD

**Issue by sophiehe** [thechangelog/ping#742]
Hi there! 

Here to tell you about Reaction Commerce, an open source ecommerce platform for devs, designers, and retailers. Our light-weight application is based on JavaScript, and our reactive platform is built using Meteor, ES6, npm, and MongoDB. Our code is licensed under the GPL v3 license. 

At 5,350 stars, we are currently the most popular JavaScript ecommerce platform on GitHub. And just a few months ago, we hit our general availability 1.0 release! We are currently working on the release of the very first Nodejs multitenant marketplace, which we think will really change online retail.

Website: reactioncommerce.com
GitHub: https://github.com/reactioncommerce/reaction

We'd love a shout-out on the podcast or in the Weekly. Thanks for reading!

**Comment by jerodsanto** [comment]
@sophiehe nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Reaction up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
