### ISSUE TITLE
Churn-Php: Helps discover good candidates for refactoring.

### ISSUE THREAD

**Issue by bmitch** [thechangelog/ping#743]
[Github](https://github.com/bmitch/churn-php)

Churn-Php is a package that helps you identify php files in your project that could be good candidates for refactoring. It examines each PHP file in the path it is provided and:

- Checks how many commits it has.
- Calculates the cyclomatic complexity.
- Creates a score based on these two values.

Many thanks!

**Comment by jerodsanto** [comment]
@bmitch nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Churn-Php up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
