### ISSUE TITLE
Ethereal - fake SMTP testing service

### ISSUE THREAD

**Issue by andris9** [thechangelog/ping#744]
I'd like to notify you about a new project of mine: It's a yet another fake SMTP testing service that catches all emails from dev environment called Ethereal ([https://ethereal.email/](https://ethereal.email))

When configuring your application then use Ethereal SMTP account for sending emails in dev and no message is never delivered but all messages are logged and can be reviewed. So it is similar to Mailtrap, MailHog and similar services. What is different though, is that as it is built on my other email projects like [Wild Duck Mail Server](http://wildduck.email/) and [ZoneMTA](https://github.com/zone-eu/zone-mta), it can provide full blown IMAP access for all the testing accounts.

Ethereal was mostly built for Nodemailer in mind (and Nodemailer has some Ethereal specific methods baked in, like zero config account creation on the fly) it can be used with any language or library that uses SMTP.

**Comment by jerodsanto** [comment]
@andris9 :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
