### ISSUE TITLE
Podcast topic: Elasticsearch

### ISSUE THREAD

**Issue by xeraa** [thechangelog/ping#745]
I don't think there has ever been a show on Elasticsearch even though it's extremely widely used for full-text search and logs / metrics (in the Elastic Stack, previously ELK Stack).

Possible topics might include:

* The product(s)
* How to grow a one man project to a 500+ person company based on open source
* Life in a fully distributed company
* The fine line between open source and making money

PS: Full disclosure, I work for Elastic.

**Comment by jerodsanto** [comment]
@xeraa this is a good idea, thanks! Who would be the ideal guest for this show?

**Comment by xeraa** [comment]
To follow up content-wise: I guess the [doubling down on open](https://www.elastic.co/blog/doubling-down-on-open) topic would be a great fit for the show and we could dive into the open source as a business topic.

**Comment by jerodsanto** [comment]
Cool, let's schedule it. Please email jerod@changelog.com and we'll iron out the details. 👍
