### ISSUE TITLE
[Go Time] Guest / Interview: Dgraph

### ISSUE THREAD

**Issue by voxadam** [thechangelog/ping#746]
![Dgraph](https://raw.githubusercontent.com/dgraph-io/website/master/assets/images/logo.png)

## Fastest graph database in the market.

Dgraph — an open source, scalable, distributed, highly available and fast graph database.

[Homepage](https://dgraph.io) | [GitHub](https://github.com/dgraph-io/dgraph) | [Docs](https://docs.dgraph.io/) | [Blog](https://blog.dgraph.io) | [Forum](https://discuss.dgraph.io) | [Slack](https://slack.dgraph.io) | [Twitter](https://twitter.com/dgraphlabs)

Founder & CEO: Manish Jain (@manishrjain)

![Diggy](https://raw.githubusercontent.com/dgraph-io/website/master/assets/images/homepage/diggy-shadow.png)

**Comment by jerodsanto** [comment]
@voxadam please resubmit this over at ~> https://github.com/gotimefm/ping/issues

Thanks!
