### ISSUE TITLE
Lozad.js - Performant lazy loading

### ISSUE THREAD

**Issue by ApoorvSaxena** [thechangelog/ping#747]
> Highly performant, light ~0.5kb and configurable lazy loader in pure JS with no dependencies for images, iframes and more

https://github.com/ApoorvSaxena/lozad.js

It's performance is attributed to the use of IntersectionObserver API under the hood, more details on the project link above.

**Comment by jerodsanto** [comment]
@ApoorvSaxena nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link Lozad up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
