### ISSUE TITLE
Micro Frontends - Extending the Microservice Idea to Frontend Development

### ISSUE THREAD

**Issue by naltatis** [thechangelog/ping#748]
Techniques, strategies and recipes for building a modern web app with multiple teams using different JavaScript frameworks.

https://micro-frontends.org

**Comment by jerodsanto** [comment]
@naltatis  nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
