### ISSUE TITLE
PhraseEngine: Language files on Steroids

### ISSUE THREAD

**Issue by omranjamal** [thechangelog/ping#749]
> I hope this is relevant. It would make us immensely happy to be featured on the Changelog.

**PhraseEngine** is a library that introduces a new XML based language that allows authoring of complex language files for conversational UIs that don't want to seem repetitive.

**Github**: https://github.com/Hedronium/PhraseEngine
**Site/Docs**: http://hedronium.github.io/PhraseEngine/

> **Background**: We work with dumb a chat bot so we wanted to vary our bot's responses to make it more interesting to use. Being the noobs that we are, we didn't even try to invent solutions with Machine Learning and AI, instead we thought writing language file in Javascript would solve our problem. We were wrong. The resulting language files even with our nice framework for authoring them was such a mess to that point that we started to have bugs in our language files. A nightmare to maintain and quite literally untranslatable. We and the translators were also too lazy to write thousands of sentences.
> 
> "If only there was a language that was easy to write language files with lots of branches in, but familiar enough for techsavy translators to use." was the thought that went through our heads the day before we made the first commit to a new library/language that does just that. And it ended up solving all out problems with out bot's responses.

**Comment by jerodsanto** [comment]
:green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
