### ISSUE TITLE
Image processing pipeline (https://qcri.github.io/ImageProcessing/)

### ISSUE THREAD

**Issue by firojalam** [thechangelog/ping#750]
The Image Processing System is designed as a preliminary tool to crawl, filter and classify images from twitter stream in which images urls are present.
- It has the functionality of crawling, filtering irrelevant images and classifying them into different damage categories. It has APIs, which can be used with other projects.
- Written in Java
- Deeplearning4j is used of designing filtering and classification models

**Comment by jerodsanto** [comment]
@firojalam thanks for sharing this! We'll include it in the next issue of [Changelog Weekly](https://changelog.com/weekly) :beers:
