### ISSUE TITLE
Luftpost watches and notifies about luftdaten.info air pollution particulates sensors

### ISSUE THREAD

**Issue by lukaspustina** [thechangelog/ping#751]
I would be happy and honoured, if you would include [this](https://github.com/lukaspustina/luftpost) tiny Rust based project called _luftpost_ -- German for "air mail" -- for your weekly Ping.

Since the diesel scandal for gasoline based cars especially made by German companies, the society's discussion about air pollution raised to a new level. _luftpost_ builds on giants, but adds a tiny function that wasn't available yet.

# Background
The German based project [luftdaten.info](http://luftdaten.info) offers a very easy do-it-yourself instruction on how to build an inexpensive yet powerful particulates sensor together with a fully functional firmware. This firmware regularly measures the particulates concentration and transmits the resulting data to luftdaten.info where it is processed and displayed on a world map. Even though most sensors are deployed in Germany you can find sensors all over the world.

# About this Project
_luftpost_ is a simple program that monitors luftdaten.info sensors and notifies you via E-Mail in case a particulates concentration measurement exceeds a thresholds. The E-Mail is nicely formatted and may contain the very same graphs that luftdaten.info offers.

**Comment by jerodsanto** [comment]
@lukaspustina :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
