### ISSUE TITLE
Transactional email microservice

### ISSUE THREAD

**Issue by adamquaile** [thechangelog/ping#752]
Hey, I thought I'd let you know about a tool I've made. It's called Enveloper https://github.com/outstack/enveloper .

I was looking for a way to not have wire up SMTP/Mailgun APIs, email templating, etc.. into multiple projects. I made this as couldn't find anything that did what I wanted. 

With it, you can add a docker service into your app and mount a directory with templates. With a tiny API request, the templating and email sending are done for you. I think it'll also result in a much better designer workflow for testing out changes in development. 

Hopefully others are interested in using/collaborating on it. There's [more to come](https://github.com/outstack/enveloper/issues), such as MJML template support, auto-inlining of CSS, auto-text versions and who knows what else. 

Thanks!

**Comment by jerodsanto** [comment]
@adamquaile cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by adamquaile** [comment]
Ace! I just merged in experimental first pass MJML support today too.
