### ISSUE TITLE
imgproxy, a Go server for lightning fast and secure image resizing

### ISSUE THREAD

**Issue by yaroslav** [thechangelog/ping#754]
Introducing imgproxy, a Go server for lightning fast and secure image resizing. Tiny footprint, protection from image bombs, Docker out of the box support and easy configuration.

https://evilmartians.com/chronicles/introducing-imgproxy

**Comment by jerodsanto** [comment]
@yaroslav cool stuff! We'll link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:
