### ISSUE TITLE
Side Project Marketing Checklist: A comprehensive list of things developers can do to promote their side projects

### ISSUE THREAD

**Issue by karllhughes** [thechangelog/ping#755]
I've been building little software side projects for years, but I've always been terrible at marketing them. I come up with some ideas, forget those ideas, do some random stuff, then lose interest. The goal of this project is to fix that by making marketing as simple as a checklist.

https://github.com/karllhughes/side-project-marketing

**Comment by jerodsanto** [comment]
@karllhughes nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by karllhughes** [comment]
Thanks!
