### ISSUE TITLE
Pull Review: assign pull request reviewers intelligently

### ISSUE THREAD

**Issue by imsky** [thechangelog/ping#756]
https://github.com/imsky/pull-review

> Pull Review looks through the changes in a pull request and assigns the most relevant reviewers, those who have made the largest and most recent contributions to the changed files. The number of reviewers assigned, along with other things, can be configured.
>  
> You can use Pull Review through GitHub comments, from chat rooms in Slack/HipChat/etc. using Hubot, on the command line, via API, or as a Docker image.

I wrote this to help scale our code review process at @better - instead of pinging all engineers on Slack, we use Pull Review to notify only the most relevant reviewers using Git blame data.

**Comment by jerodsanto** [comment]
@imsky cool stuff! We'll link Pull Review up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers:

**Comment by imsky** [comment]
thanks @jerodsanto 🍻
