### ISSUE TITLE
You should do a show with Greg Sadetsky

### ISSUE THREAD

**Issue by cclauss** [thechangelog/ping#757]
https://medium.com/@FastCompany/how-a-hacker-helped-the-coast-guard-rescue-victims-of-hurricane-harvey-fc395280fa12?source=email-6cd27189c2d3-1506837217910-digest.reader------0-49&sectionName=topic

**Comment by adamstac** [comment]
Nice! @gregsadetsky -- you down? I live in Houston so I've seen first hand the effects of Harvey and I'm thankful for your efforts to help save lives.

**Comment by jerodsanto** [comment]
Great suggestion, @cclauss! I reached out to Greg. Fingers crossed! 😅
