### ISSUE TITLE
I'd like to be interviewed on Go Time

### ISSUE THREAD

**Issue by bzub** [thechangelog/ping#758]
I don't have much going for me. Sweet opener right?

Here's what I got:
- I am a Linux sysadmin turned farmer.
- I just started programming regularly in the last year, after I left the tech industry ¯\_(ツ)_/¯.
- I love data. I run my data collection services on Kubernetes.
- I love open source. I've dedicated 110% of my off-time to it (check my profile).
- I have many business ideas that involve agriculture, which is seriously lacking an open-source revolution. That is an hour-long topic by itself. Imagine a a trillion dollar US industry stuck for a decade in the old Sony-DRM-malware-installing-music-CD/Cisco-"enter your license key" era. It's real.
- I love Go. It's the only programming language that drew me in rather than intimidated me.
- Go + IoT + Data Analytics + new green revolution? Working on it.
- I am also the co-developer of https://github.com/cloudnativelabs/kube-router

Thanks for fostering what appears to be a great community! 

- Bryan Z

**Comment by jerodsanto** [comment]
👋 @bzub! Sounds like you have a lot going for you, if I do say so for myself. 

We actually have a separate Ping repo for Go Time since the hosts are different. Mind duping this over there? ~> https://github.com/gotimefm/ping
