### ISSUE TITLE
You need to do a show with @rstacruz

### ISSUE THREAD

**Issue by kzap** [thechangelog/ping#759]
I just saw you post DevHints.io in the ChangeLog weekly by @rstacruz

But this guy is a prolific open source contributor and you could do a show on tons of things he has created and contributed. I mean just take a look at this:

http://github.com/rstacruz

Rico is from the Philippines and an active participant of the community and an experienced speaker:
https://www.youtube.com/watch?v=-_0LpTGOE_w
https://www.youtube.com/watch?v=HsORdkQG658
https://www.youtube.com/watch?v=tY2UQPZAK14

Some of his well known and widely used projects:
- Cheatsheets https://devhints.io
- RSJS http://ricostacruz.com/rsjs/
- RSCSS http://rscss.io/
- Docpress http://docpress.github.io/
- NProgress http://ricostacruz.com/nprogress/
- Flatdoc http://ricostacruz.com/flatdoc/
- PNPM https://pnpm.js.org/

I mean need I say more :) 💯

**Comment by rstacruz** [comment]
Thanks for the shoutout, I'm happy to do this :)

**Comment by jerodsanto** [comment]
Good call @kzap! This is a no-brainer. 💚 

We'd love to have you @kzap! Please email editors@changelog.com and we'll schedule it.

**Comment by kzap** [comment]
Not me.... its Rico Sta. Cruz you need to interview :)

**Comment by jerodsanto** [comment]
Fail🐳  

Somehow autocomplete got me there. Yes, we'd love to have @rstacruz on the show. Please email us! ✊
