### ISSUE TITLE
Introducing the new CKEditor Ecosystem

### ISSUE THREAD

**Issue by wojtekidd** [thechangelog/ping#760]
Just wanted to let you know that the CKEditor team has just introduced a couple of new products.

CKEditor 5 is a new rich text editing solution (written from scratch), bringing its own data model which can enable many powerful features including real-time collaborative editing.

With the new Ecosystem, we also bring you Letters, a drop-in solution which is designed to make your article writing and real-time collaboration experience exceptional and effortless.

To learn more please visit our website at CKEditor.com and check out the demos. You can also read [our detailed article about the CKEditor Ecosystem on our blog](https://ckeditor.com/blog/Introducing-the-new-CKEditor-Ecosystem/).

**Comment by jerodsanto** [comment]
@wojtekidd :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
