### ISSUE TITLE
Podcast show with Patrick Meenan

### ISSUE THREAD

**Issue by soulgalore** [thechangelog/ping#762]
It's been a while now when it was a podcast about performance :)

@pmeenan is the creator of https://www.webpagetest.org/ that he originally created at AOL and then brought with him to Google. I think there's a really interesting story there, starting an open source tool, moving it to another large company etc. It's been a while for so long time so it must be a lot of good stories there.

Pat is also a really nice guy and has contributed so much to the performance community by open sourcing WebPageTest.

There's a lot of paid tools (closed source) built on top on WebPageTest, that relationship is also interesting I think.

**Comment by jerodsanto** [comment]
@soulgalore you know I'm a sucker for a good show on performance...

@pmeenan we'd love to have you join us! Please email editors@changelog.com to coordinate if you're interested.

💚💚💚
