### ISSUE TITLE
dramatiq, distributed task processing library for Python with a focus on simplicity, reliability and performance

### ISSUE THREAD

**Issue by Bogdanp** [thechangelog/ping#763]
Hi!

I'm trying to get some traction on this little task queueing library I wrote. Read about my motivation [here](http://dramatiq.io/motivation.html).

Thanks!

* Documentation: http://dramatiq.io
* GitHub: https://github.com/Bogdanp/dramatiq

**Comment by jerodsanto** [comment]
@Bogdanp nice! We just queued up a [tweet](https://twitter.com/changelog) in your direction and we'll also link dramatiq up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:
