### ISSUE TITLE
Bender: fast neural networks on iOS

### ISSUE THREAD

**Issue by bryant1410** [thechangelog/ping#764]
Hey! I always read the changelog, so I decided to ping :smile: 

**Bender** is a framework to run neural networks on iOS. It's even faster than Core ML, as it uses all the processing power available via the Metal API. It also supports running TensorFlow models out-of-the-box, so it's just plug and play.

GitHub project: https://github.com/xmartlabs/Bender
Website: https://xmartlabs.github.io/Bender/

**Comment by jerodsanto** [comment]
@bryant1410 Bender is on [Changelog News](https://changelog.com/news/bender-a-modern-ml-framework-built-on-top-of-metal-bj7)! It should also hit this weekend's issue of [Weekly](https://changelog.com/weekly) ✊
