### ISSUE TITLE
Zulip 1.7 release & paid hosted/support plans

### ISSUE THREAD

**Issue by brainwane** [thechangelog/ping#765]
[Zulip is open source group chat](https://zulipchat.com/) with great threading and a thriving developer community. [They've just released version 1.7](https://blog.zulip.org/2017/10/25/zulip-server-1-7-released/):

> Both a cloud-hosted Zulip, and support for on-premise installs, are  now commercially available at zulipchat.com from Kandra Labs, a  company one of us (lead developer Tim Abbott) founded to support  Zulip, and which now employs many of the core developers. Hosting is  free for fellow open-source communities.

The new [pricing plans for support/hosted Zulip](https://zulipchat.com/plans/) also include free hosted service for non-commercial use for up to 100 users, and unlimited evaluation for commercial or non-commercial use.

Also, Zulip's backend now runs exclusively on Python 3, and Zulip has switched to new desktop and mobile apps built on Electron and React Native respectively.

**Comment by jerodsanto** [comment]
@brainwane :green_heart: we'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada:
