### ISSUE TITLE
DataCol - a powerful PaaS control layer on top of AWS/GCP

### ISSUE THREAD

**Issue by shyammohankanojia** [thechangelog/ping#766]
Datacol is a control layer on top of cloud(AWS/GCP), to provide Heroku like experience with power of Kubernetes under the hood. 
Web: https://www.datacol.io/
Github: https://github.com/datacol-io/datacol

**Comment by jerodsanto** [comment]
@shyammohankanojia Datacol in on [Changelog News!](https://changelog.com) :fist_raised:

Also look for a mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
