### ISSUE TITLE
microlink.io – Get relevant information from any link

### ISSUE THREAD

**Issue by Kikobeats** [thechangelog/ping#767]
Hello,

I created a simple microservice for do one thing well: get relevant information from any link.

I called it [microlink.io](https://microlink.io) and It's oriented useful for build embed previsualizations of third party links in your site.

Taking a whatever [url](https://docs.microlink.io/#url) as input, it will extract structured and normalized information related with the link, such as author, description, title, logo and more.

You can use microlink for take website [screenshots](https://docs.microlink.io/#screenshot) (full or partial page) or get [predominant colors](https://docs.microlink.io/#palette) from images detected.

One of the thing that I like more about microlink is that you can [embed](https://docs.microlink.io/#embeded-support) the API call directly in your HTML markup:

```html
<img src="https://api.microlink.io/?url=https%3A%2F%2Fmicrolink.io&embed=image.url" />
```

and voilá!

![](https://api.microlink.io/?url=https%3A%2F%2Fmicrolink.io&embed=image.url)

It's offer a **free** plan as well. All information about what you can do is in the [documentation](https://docs.microlink.io).

I hope you like it 😄

**Comment by jerodsanto** [comment]
@Kikobeats we don't normally provide free promotion for closed-source commercial endeavors, but this is neat and the free plan is pretty generous, so I'll make an exception this time.  We'll put this in the next issue of [Weekly](https://changelog.com/weekly) :tada: :green_heart:

**Comment by Kikobeats** [comment]
I really appreciate this, thanks 🙏 

btw, landing page was updated with more clear information 👍
