### ISSUE TITLE
Python library to draw ASCII-art box with text 

### ISSUE THREAD

**Issue by reorx** [thechangelog/ping#768]
Link: https://github.com/reorx/drawbox

Used for prettier and clearer data display in terminal.

**Comment by jhermann** [comment]
I don't see anything not covered by the more mature https://github.com/Robpol86/terminaltables

**Comment by reorx** [comment]
Of course there are some masterpieces out there (also https://pypi.python.org/pypi/tabulate), but I find it very interesting to implement a lighter version by myself, and when it comes to the situation where you don't want to involve another dependency, this little snippet can be a great help. Anyway, just to share and for fun, if it's not suitable, feel free to close this issue :)

**Comment by jerodsanto** [comment]
@reorx we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
