### ISSUE TITLE
Passwordless: Add authentication to your Rails app without all the icky-ness of passwords

### ISSUE THREAD

**Issue by mikker** [thechangelog/ping#769]
I took the _passwordless_ (_"Magic Links"_) authentication I had in one of my apps and turned it into a gem. Would love to have more people notice it through your newsletter(s).

Thanks for a great podcast and newsletter!

**Comment by jerodsanto** [comment]
Awesome, @mikker! I'm a big fan of passwordless auth too (it's what we use for changelog.com).

Have a link for us to check out?

**Comment by mikker** [comment]
Yes! Sorry! Forgot the most important thing 🙄
https://github.com/mikker/passwordless

**Comment by mikker** [comment]
The project now has over 120 stars!

_or Bump (as they say)_

**Comment by jerodsanto** [comment]
@mikker nice job! We just sent a [tweet](https://twitter.com/changelog/status/940640361931853824) in your direction and we'll also link this up in the next issue of [Changelog Weekly](https://changelog.com/weekly/).

We :shipit: this weekend. :beers: :green_heart:

**Comment by mikker** [comment]
Thanks a bunch!
