### ISSUE TITLE
Backpack for Laravel - CRUD panels in 10 minutes/pop

### ISSUE THREAD

**Issue by tabacitu** [thechangelog/ping#770]
First of all, _very_ good job on the Changelog newsletter - you're gold, it's one of the few newsletters I look forward to all week. You do a great job of curating the Internet for us :-)

I noticed you don't usually cover PHP, but I've written this Laravel package ~1.5 years ago, and it has really *blown up* since. I just launched version 3.3 and want to promote it a little bit more - we need some fresh blood. Nowadays 6% of all Laravel installs have it, and I'm pretty proud of that :-) I'm struggling to turn it into a self-sustaining organisation and some more attention would help a lot. 

----

![1](https://user-images.githubusercontent.com/1032474/32606091-9fd4312c-c55c-11e7-9be7-ebcd7a7862a7.png)

**Backpack helps Laravel developers build administration panels crazy-fast.** It's _not_ a CMS, it's a _framework to build your own CMS_, for every project. Because let's face it - when you pull in a CMS, you're either limited by what it can do, or you end up rewriting a bunch of stuff. Backpack helps you build bottoms-up, instead of top-down. You start with minimal functionality, and can easily customize every bit of it. In my experience, you end up with cleaner code, faster.

Website: https://backpackforlaravel.com/
Github: https://github.com/laravel-backpack/

Thank you for your time, and your newsletters.
Cheers!

PS. Fun fact: this is actually the fourth package I've written that does this. My previous one was called **[Dick](http://usedick.com/)**, just because I enjoyed writing ```git push dick``` and ```git pull dick```. Stupid... I know... :-)

**Comment by jerodsanto** [comment]
@tabacitu thanks for the kind words about our work! 🤗 

Backpack is on [Changelog News!](https://changelog.com) :fist_raised:

Also look for a mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
