### ISSUE TITLE
Transient haskell

### ISSUE THREAD

**Issue by timdeputter** [thechangelog/ping#771]
Maybe a podcast about @transient-haskell with its creator @agocorona would be cool. I don't know if he would be interested, but I thougth I just suggest it here ;)

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
