### ISSUE TITLE
GemCheck – the checklist for Ruby gems authors

### ISSUE THREAD

**Issue by palkan** [thechangelog/ping#775]
http://gemcheck.evilmartians.io

This is the checklist for authors and maintainers of Ruby gems to help them build better open-source software.

**Comment by jerodsanto** [comment]
@palkan GemCheck is on [Changelog News!](https://changelog.com/news/gemcheck-the-checklist-for-ruby-gem-authors-Jad) :fist_raised:

Also look for a mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
