### ISSUE TITLE
resque-fifo-queue: Ruby gem  for a First-in-first-out sharded queue on top of Resque

### ISSUE THREAD

**Issue by jedld** [thechangelog/ping#777]
Need something like Apache Kafka but looking for a pure ruby solution and makes use of your existing resque workers?

https://github.com/jedld/resque-fifo-queue

**Comment by jerodsanto** [comment]
@jedld you're on [Changelog News!](https://changelog.com) :fist_raised:

This might also get a mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
