### ISSUE TITLE
oxrlib for currency conversions

### ISSUE THREAD

**Issue by brainwane** [thechangelog/ping#778]
Software Freedom Conservancy announces a new Python library to give you historical currency exchange rates from Open Exchange Rates.

https://sfconservancy.org/blog/2017/nov/22/introducing-oxrlib/

**Comment by jerodsanto** [comment]
@brainwane this is on [Changelog News!](https://changelog.com) :fist_raised:

It also might get a mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:
