### ISSUE TITLE
[Podcast suggestion] Revolutionary JSON with quicktype

### ISSUE THREAD

**Issue by dvdsgl** [thechangelog/ping#779]
👋🏻 Hi! I work on [an open-source tool](https://GitHub.com/quicktype/quicktype) that infers the type of JSON sample data and generates models and serializers in many languages. You can [try it in your browser](https://quicktype.io) and [read an example use case](http://blog.quicktype.io/quicktype-multiple-samples/) on our blog.

quicktype is a cool project that can save every programmer time so I'm sure listeners would appreciate hearing about it!

**Comment by jerodsanto** [comment]
@dvdsgl very cool stuff! I don't think it's a perfect fit for the podcast, but quicktype did make it on [News](https://changelog.com/news/45E)! Expect a tweet coming its way and it might end up in [Weekly](https://changelog.com/weekly) as well. ✊
