### ISSUE TITLE
notify-send-http - Use notify-send to trigger notifications across the network

### ISSUE THREAD

**Issue by fgrehm** [thechangelog/ping#78]
A tiny little project useful for those who develop applications inside virtualized environments: https://github.com/fgrehm/notify-send-http

# Why?

Because I do all of my dev work on virtualized environments and I use guard quite a lot to keep my Ruby tests running when files get changed. The problem is that its builtin notification support will trigger a notify-send inside the virtual environment instead of my machine.

With notify-send-http I can run an HTTP server on my machine and make use of a custom notify-send executable on my virtual environments that has the same interface as the original command and will send notifications to the HTTP server so that I can see alerts poping up on my screen whenever the build fails.

**Comment by jerodsanto** [comment]
@fgrehm love your stuff, but this one is so niche that I think we'll pass on it. Ping us again next time!

**Comment by fgrehm** [comment]
No worries! :)
