### ISSUE TITLE
Trello KB - Get a Trello board as an array of self-contained content objects

### ISSUE THREAD

**Issue by dwilding** [thechangelog/ping#780]
Hey there, you might be interested to know that I've just released a Node.js module that is pretty much a generic version of what you [built for Trello a few years back](https://changelog.com/posts/trello-as-a-cms).

The project is called Trello KB - you can check it out here:
https://github.com/dwilding/trello-kb#overview-of-trello-kb

Not sure whether you'll find this useful, but thought you'd enjoy it anyway :smiley:

Keep up the good work!

**Comment by jerodsanto** [comment]
@dwilding Trello KB is on [Changelog News!](https://changelog.com) :fist_raised:

Also look for a potential mention in the next issue of [Changelog Weekly](https://changelog.com/weekly/)! :green_heart:

**Comment by dwilding** [comment]
@jerodsanto That's awesome, thank you!
