### ISSUE TITLE
DevOps'ish Celebrates Its One Year Anniversary!

### ISSUE THREAD

**Issue by chris-short** [thechangelog/ping#781]
[**DevOps'ish**](https://devopsish.com) is celebrating its one year anniversary. 52 weeks of uninterrupted DevOps, SRE, Kubernetes, Go, and other assorted IT industry news. It's a major achievement and we are looking to celebrate it by giving away something special to diverse readers. [Subscribe and join in on the fun](http://eepurl.com/csvznH).

**Comment by jerodsanto** [comment]
Congrats, Chris! 52 straight issues is an accomplishment, for sure 👏
