### ISSUE TITLE
wemake-django-template

### ISSUE THREAD

**Issue by sobolevn** [thechangelog/ping#782]
Bleeding edge django template focused on code quality and security.
https://github.com/wemake-services/wemake-django-template

Docs: http://wemake-django-template.rtfd.io/

## Features

- pipenv for managing dependencies
- pytest, pylint, and flake8 for testing and linting
- pre-commit hooks for consistent development
- docker-compose for development and production
- pycharm with pre-configured local docker development targets
- sphinx for documentation
- Gitlab CI with full build, test, and deploy pipeline configured by default
- Caddy with https and http/2 turned on by default

**Comment by jerodsanto** [comment]
@sobolevn you're on [Changelog News!](https://changelog.com) :fist_raised:

(BTW, for future submissions please use our new form ~> https://changelog.com/news/submit)
