### ISSUE TITLE
Xkcd-excuse.com - The easiest way to get your slacking excuse in hip xkcd format!

### ISSUE THREAD

**Issue by mislavcimpersak** [thechangelog/ping#783]
https://xkcd-excuse.com/

It's a side project that I've created for fun. But contrary to the usual side project fate, I decided to stick with it and push it through to the end 💯 

Initial steps were made a few months ago as an example for a talk held in local Python meetup groups (Zagreb and Belgrade). Few people found it funny, and not just me, so that was enough to pursue this further.

Since this is a side project with a total budget of $0, I've tried to maximize what can I get for free 💸 
- image generating is done through a Python service served on AWS Lambda
- UI is served from Github pages
- everything is being extensively cached through CloudFlare
- monitoring is done with Datadog (free tier, since Lambda monitoring is free)
- error reporting through Bugsnag (free for open source)
- CI/CD  through CircleCI (free for open source)

The project is fully open sourced, with the code in two repositories:
- Python (Hug): https://github.com/mislavcimpersak/xkcd-excuse-generator
- Frontend: https://github.com/mislavcimpersak/xkcd-excuse-front

------

With it you can create glorious images like this:

![](https://function.xkcd-excuse.com/media/5345525645524c45535320444556-4d592046554e4354494f4e204953204445504c4f59494e4720544f20415753-4445504c4f59494e47.png)
(this is actually the _origin story_ from the time I was deploying to Lambda from a crappy Internet connection)

or like this:

![](https://function.xkcd-excuse.com/media/504f44434153544552-4d5920504f4443415354204953205452414e53434f44494e47-5452414e53434f44494e47.png)

**Comment by jerodsanto** [comment]
[Done and dusted!](https://changelog.com/news/an-xkcd-excuse-generator-oel9)
