### ISSUE TITLE
React Translated: A dead simple way to add complex translations in a React (Native) project 🌎

### ISSUE THREAD

**Issue by amsul** [thechangelog/ping#784]
I just published this project https://github.com/amsul/react-translated and figured other may find it useful as well 🙏

**Comment by jerodsanto** [comment]
@amsul we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it!  💚
