### ISSUE TITLE
AutoSpoting project 

### ISSUE THREAD

**Issue by cristim** [thechangelog/ping#786]
AutoSpotting is an open source project that makes it easy to migrate AWS autoscaling groups to reliable groups of spot instances.

Repo and docs can be found on Github: https://github.com/cristim/autospotting

# Features
- It monitors your groups and automatically launches the cheapest spot instance type compatible with the currently running on demand instances (having at least as much memory, CPU cores, etc.)
-  Spot instances are configured identically to the original instances and will be automatically attached to the group, replacing the on demand instances that are detached and terminated.
- The replacement is gradual and can leave some on demand instances in the group.
- Currently it's automatically bidding the on demand price (maybe considering volume or RI discounts if configured) but a more aggressive bidding strategy is in the works.
- The group configuration is unchanged so it will still launch on demand instances when scaling out or when replacing outbid spot instances.

**Comment by jerodsanto** [comment]
@cristim we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
