### ISSUE TITLE
Json Web Tokens (JWT)

### ISSUE THREAD

**Issue by ajawchat** [thechangelog/ping#787]
Hi Changelog team,

We have been using JWT in our system for authentication and I think it will be a great topic to cover in the podcast. 

Some topics to cover might include
1. Authentication alternatives and why JWT
2. Information exchange using JWT

**Comment by jerodsanto** [comment]
@ajawchat this sounds like a great topic for [JS Party](https://changelog.com/jsparty) (which we're producing once again.) Would that be cool with you?

**Comment by ajawchat** [comment]
@jerodsanto Absolutely :)

**Comment by Canadauni** [comment]
It would actually be great to have a show about authentication strategy in general maybe? Every time I see JWT brought up somewhere there is always a comment on how it is insecure and I shouldn't be using it. Understanding why it is insecure and what alternatives I should be using on my SPA would be great!

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
