### ISSUE TITLE
Elchemy: Elm on the server through Elixir

### ISSUE THREAD

**Issue by dbohdan** [thechangelog/ping#788]
[Elchemy](https://github.com/wende/elchemy) is a new (2017 vintage) transpiler project that compiles Elm-compatible code to human-readable Elixir. It lets you use Elm's syntax and its type checking on the Erlang VM, and seamlessly interact with modules written in Erlang and Elixir. Check out the project's [FAQ](https://github.com/wende/elchemy#faq).

**Comment by jerodsanto** [comment]
Very cool @dbohdan! We'll share this around. ✊
