### ISSUE TITLE
ComfortableMexicanSofa 2.0 - Rails 5.2 CMS Engine

### ISSUE THREAD

**Issue by GBH** [thechangelog/ping#789]
Many many moons ago you guys posted about early 1.0 version: https://changelog.com/posts/comfortable-mexican-sofa-comfortablemexicansofa-is-a-tin 

Now it's 2.0 and ready to go with Rails 5.2: https://github.com/comfy/comfortable-mexican-sofa

It's still the same easy to use, easy to extend Rails engine it always has been. But there are brand new things:

- completely redesigned content tag system to be easier to use and extend
- added support for direct page translations
- using Rails' new ActiveStorage for file attachments
- reworked admin area to use Bootstrap 4 (beta2) to be fully responsive.
- reworked CMS Seeds system for initial content population
- Beefed up test suite, Rubocop. Rewrote [entire Wiki](https://github.com/comfy/comfortable-mexican-sofa/wiki).
- Rewrote Blog engine companion: https://github.com/comfy/comfy-blog

**Comment by jerodsanto** [comment]
@GBH we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
