### ISSUE TITLE
Bloggify Colors

### ISSUE THREAD

**Issue by IonicaBizau** [thechangelog/ping#790]
Just wanting to share a project I finished today. 😁 

🎨 http://colors.bloggify.org

[![](https://camo.githubusercontent.com/b24cd536295ae545639d95cf1ae8eceb2905a509/68747470733a2f2f692e696d6775722e636f6d2f356447437339732e706e67)](http://colors.bloggify.org)

Source code: https://github.com/Bloggify/colors

No ads, no tracking, and eventually will add offline loading support! 🚀 

Happy holidays! 🌟

**Comment by jerodsanto** [comment]
@IonicaBizau we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
