### ISSUE TITLE
Beadifier turns any image into an awesome fuse bead pattern

### ISSUE THREAD

**Issue by MikaeI** [thechangelog/ping#791]
A tool for hobbyists and fuse bead lovers of all ages! Remix art and photography using beads.
Transform your images into awesome fuse bead patterns.
Visit: https://www.beadifier.com

**Comment by jerodsanto** [comment]
@MikaeI we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
