### ISSUE TITLE
Host-based Intrusion detection with Wazuh

### ISSUE THREAD

**Issue by aremai** [thechangelog/ping#792]
Howdy,

I was told to open an issue here with a hopefully a cool suggestion for a new podcast guest.
Since you're a fan of open source products, I'd love to hear a podcast with the @Wazuh guys.... They're doing a host intrusion detection system that is fully open source, because of that I use it daily and it helps me with the visibility of security threats. I'd love to know why this tool is open source and for free, a lot of other companies would probably try to make a lot of money from it...

They're also on Github:
https://github.com/wazuh
they have integrated the Elastic Stack into their software for greater and better visibility. I love it!

Their official website is https://wazuh.com

Just to get an idea -- what do you think?

Also all the best for 2018 and to more very interesting podcasts, keep up the good work 🙂
Loved your recent podcast and interview with Wire. Really great job!!

cheers,
theresa

**Comment by jerodsanto** [comment]
@aremai thanks so much for this suggestion! Sorry it took me so long to get around to it, but I think this is interesting and I'll reach out and see what they say.

Also thanks for the kind words about our shows. We 💚 listener feedback 😁
