### ISSUE TITLE
Gigalixir for Phoenix deployment

### ISSUE THREAD

**Issue by pdgonzalez872** [thechangelog/ping#794]
Follow up to https://github.com/thechangelog/changelog.com/issues/188#issuecomment-357697229, this time on the correct repo :)

Gigalixir seems to answer a very serious and valid question regarding deployments in Elixir. It may be the reason I attempt using Phoenix in the my next project at our consulting firm.

Hope this helps! Thanks!

**Comment by jesseshieh** [comment]
@jerodsanto @pdgonzalez872 Hey guys, I'm the founder of gigalixir.com and just wanted to let you know that I'm here in case you have any questions or need any help. We're also willing to send pull requests for open source projects to get started on Gigalixir, let us know!

**Comment by jerodsanto** [comment]
@jesseshieh awesome, Gigalixir looks really nice! Have you made a marketing/awareness push for it yet? It's possible we could help in that arena. 😄

Please email editors@changelog.com if you're interested in talking about different partnership ideas.
