### ISSUE TITLE
[Podcast Suggestion] FlureeDB, a scalable Blockchain Database

### ISSUE THREAD

**Issue by FlureeKevin** [thechangelog/ping#795]
Contact info: kdoubleday@flur.ee

* Plans for open source in 2018 
* Graph DB that builds each transaction into a time-stamped update to a chronological central blockchain 
* Can partition and host data on multiple blockchains with unique consensus properties

**Comment by jerodsanto** [comment]
@FlureeKevin please contact us again when this is open source. Also, we may have some new blockchain-related stuff going on by then 😉
