### ISSUE TITLE
EventBus for Elixir

### ISSUE THREAD

**Issue by mustafaturan** [thechangelog/ping#796]
EventBus v1.0.0 is released

EventBus library is a traceable, extendable and minimalist event bus implementation for Elixir with built-in event store and event watcher based on ETS. It allows basic pub/sub for internal process communication. It is designed for low memory footprint and speed.

https://github.com/otobus/event_bus

**Comment by jerodsanto** [comment]
@mustafaturan we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚

**Comment by mustafaturan** [comment]
@jerodsanto 
I don't like signing up, thanks ❤️
