### ISSUE TITLE
Sponsors typo

### ISSUE THREAD

**Issue by bradleyjkemp** [thechangelog/ping#797]
On https://changelog.com/about in the "Special thanks to..." section I think Rollbar should be described as providing error tracking & crash reporting (rather than "for providing our high performance SSD Linux cloud servers." as it does currently).

Also, a super minor point: I think Breakmaster Cylinder provides your beats not your beets 😉

**Comment by jerodsanto** [comment]
Good catch on the Rollbar spot, @bradleyjkemp! @adamstac you want to adjust that copy?

(If you dig deeper in to BMC's [catalog](https://breakmastercylinder.bandcamp.com/album/pickled-beets-part-i) you'll find it's all about the _beets_! 😜)

**Comment by adamstac** [comment]
hahaha -- beets is correct for BMC, but that catch for Rollbar is totally my mess up. (what time of the night was that commit??)

**Comment by jerodsanto** [comment]
This is fixed now, thanks for the head's up @bradleyjkemp! ✊
