### ISSUE TITLE
Top ten reasons why I won't use your open source project

### ISSUE THREAD

**Issue by asexton1993** [thechangelog/ping#798]
Hey Adam,

I read your article and came across this repo. You wrote about a lot of interesting points that were spot on.

Here is the link to our github repos: https://github.com/cyberFund

I would love if you could promote them on your blog, as we have a number of different projects that pose a great benefit to society and the improvement of everyone's daily lives.

Best,
Andrew
PR Manager
cyber•Fund
pr@cyberfund.io

**Comment by jerodsanto** [comment]
@asexton1993 we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
