### ISSUE TITLE
Dashbling - Hackable React based dashboards for developers

### ISSUE THREAD

**Issue by pascalw** [thechangelog/ping#799]
I just released https://github.com/pascalw/dashbling, a dashboarding tool for developers.
It's in spirit of good 'ol Dashing, but with a much more modern development stack.

I hope it's as useful to others as it is to me!

Features:

* Widgets are React components that automatically update when data changes.
* Data can be pushed into your dashboard via a REST API, or fetch data using small NodeJS modules.
* Looks great out of the box, or fully adapt to your taste.
* Great developer experience with hot reloading, ES2015+ and Sass.
* Extensible build system powered by Webpack.
* Can easily be hosted on Heroku, or any platform supporting Docker.
* Widgets can easily be shared via NPM packages.

![example](https://user-images.githubusercontent.com/304603/35586928-8063306e-05fc-11e8-934b-9dfd23d9b864.jpg)

**Comment by jerodsanto** [comment]
[Done and dusted!](https://changelog.com/news/hackable-react-based-dashboards-for-developers-inspired-by-dashing-8aaZ)
