### ISSUE TITLE
Golden layout - a powerful js layoutmanager

### ISSUE THREAD

**Issue by WolframHempel** [thechangelog/ping#80]
Hi,

Could you give [golden-layout.com]( https://golden-layout.com) a look? It's a powerful JavaScript layoutmanager that supports pop outs,  drag and drop arranging of components, serialisation and a myriad of other things.

It's customisable and comes with an API that allows to program pretty much every aspect of it. 

Cheers, 

Wolfram

**Comment by jerodsanto** [comment]
@WolframHempel we're including Golden Layout in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by WolframHempel** [comment]
great news, thanks

2015-01-12 15:43 GMT+00:00 Jerod Santo <notifications@github.com>:
