### ISSUE TITLE
Renovate App

### ISSUE THREAD

**Issue by nicholaswyoung** [thechangelog/ping#800]
I don't think you've talked to @rarkins about [renovate](https://github.com/renovateapp/renovate), but you should. It's the first GitHub app* that has changed how I develop software by easing the frustration of managing dependencies, for the most part, automatically.

\* It also works with GitLab, and soon, Bitbucket.

**Comment by rarkins** [comment]
Thanks Nicholas for the recommendation, I'd be happy to chat.

**Comment by jerodsanto** [comment]
Renovate looks super slick, @rarkins. We'd love to have you on the show! Please email jerod@changelog.com and we'll get you scheduled. 💚 

(good idea @nicholaswyoung ✊)
