### ISSUE TITLE
Unable to open News links in new tab

### ISSUE THREAD

**Issue by bcc32** [thechangelog/ping#802]
On the Changelog home page, I tried to open several links in a new tab.  Each time, the page navigated to the link target in the _current tab_.  Both command-clicking and right-clicking failed to bring up a new tab.  (Using Firefox.)

**Comment by jerodsanto** [comment]
@bcc32 thanks for the heads up! Please try it again now and report back. Should be working... 🙏

**Comment by bcc32** [comment]
Seems to be working now.  Thanks!
