### ISSUE TITLE
Builder Book: write documentation + sell books, built with React/Material-UI/Next/Express/Mongoose/MongoDB

### ISSUE THREAD

**Issue by klyburke** [thechangelog/ping#803]
We recently built an open source web app that you can use to write and host documentation, sell books, or as a boilerplate for React, Material-UI, Next, Express, Mongoose, MongoDB stack. It also includes these third-party APIs: AWS SES, Github, Google OAuth, Stripe, MailChimp.

We welcome contributions and would love to hear feedback!

https://github.com/builderbook/builderbook

**Comment by jerodsanto** [comment]
@klyburke we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚

**Comment by klyburke** [comment]
thanks @jerodsanto !
