### ISSUE TITLE
Leku a Map location picker component for Android

### ISSUE THREAD

**Issue by ferranpons** [thechangelog/ping#804]
Component library for Android that uses Google Maps and returns a latitude, longitude and an address based on the location picked with the map provided. It's similar to Google Place Picker but with more features.

**Features**

- Search by voice
- Search by text
- Geo Location by GPS, network
- Google Places (optional)
- Pick locations using "touch" gestures on the map
- Customization (Theme and layout)
- Events Tracking
- Multi-language support (English and Spanish supported by default)
- RTL (Right-To-Left) layout support 

[https://github.com/SchibstedSpain/Leku](https://github.com/SchibstedSpain/Leku)

**Comment by jerodsanto** [comment]
@ferranpons we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚

**Comment by ferranpons** [comment]
I'll do it. Thanks! 😉
