### ISSUE TITLE
DuckRails

### ISSUE THREAD

**Issue by iridakos** [thechangelog/ping#805]
[DuckRails](https://github.com/iridakos/duckrails) is an open source development tool for mocking API endpoints quickly and dynamically.

[https://github.com/iridakos/duckrails](https://github.com/iridakos/duckrails)

**Note:** the tool can now be used via its [docker image](https://github.com/iridakos/duckrails/wiki/Setup-DuckRails-via-Docker).

**Comment by jerodsanto** [comment]
@iridakos as I'm sure you were notified, [this made the news feed](https://changelog.com/news/duckrails-a-development-tool-for-mocking-api-endpoints-Eaak) yesterday. ✊

**Comment by iridakos** [comment]
@jerodsanto Thank you!
