### ISSUE TITLE
Ruby does GTK

### ISSUE THREAD

**Issue by iridakos** [thechangelog/ping#806]
A [tutorial](https://iridakos.com/tutorials/2018/01/25/creating-a-gtk-todo-application-with-ruby.html) for creating a simple Linux Desktop ToDo application with Ruby.

[https://iridakos.com/tutorials/2018/01/25/creating-a-gtk-todo-application-with-ruby.html](https://iridakos.com/tutorials/2018/01/25/creating-a-gtk-todo-application-with-ruby.html)

**Comment by jerodsanto** [comment]
@iridakos please submit onsite!
