### ISSUE TITLE
Promys - Project My Screen

### ISSUE THREAD

**Issue by OliverSwift** [thechangelog/ping#807]
A screencasting system project based on a Raspberry Pi 3.
Targets corporate use where Chromecast may not be a suitable solution.
Easy setup for visitors using Windows, Mac or Linux.

Checkout http://promys.me  and  https://github.com/OliverSwift/Promys

**Comment by jerodsanto** [comment]
@OliverSwift we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
