### ISSUE TITLE
Beyondgrep/ack-likes

### ISSUE THREAD

**Issue by hoelzro** [thechangelog/ping#808]
Hi! While listening to the recent episode on devhints, one thing that resonated with me was the notion that a project should be promoting the core idea behind it rather than promoting itself as a "silver bullet", by making room in the README/documentation for similar projects.  One person I know who advocates for this is @petdance, who wrote Ack and uses his time and energy to prop up other similar projects via https://beyondgrep.com.  I think he'd make a fantastic guest on the show!

**Comment by jerodsanto** [comment]
That sounds like a great idea, @hoelzro! ✊ 

@petdance we'd 💚 to have you on The Changelog! Please email editors@changelog.com to coordinate, if you're interested.

**Comment by petdance** [comment]
Can you tell me more about what you're looking for?  I've never done a podcast before.

**Comment by jerodsanto** [comment]
Our shows are 60-75* minutes long.

We'd talk to you about ack, its history, why you created it, etc, then we'd probably shift gears and discuss your ideas around promoting alternate solutions that may be better fit for people, perhaps with a focus on your [recent blog post](http://blog.petdance.com/2018/01/02/the-best-open-source-project-for-someone-might-not-be-yours-and-thats-ok/) on the subject.

([Listen to our latest episode to get an idea of a typical show](https://changelog.com/podcast/283))

*it takes about 90 minutes total to record

**Comment by jerodsanto** [comment]
@petdance we're still 💯 on this show if you are. Please email editors@changelog.com if so. Closing this for cleanliness' sake. 💚
