### ISSUE TITLE
MySQL JSON Support for Rails 4

### ISSUE THREAD

**Issue by saveriomiroddi** [thechangelog/ping#810]
Projects currently working with Rails 4 aren't able to natively work with MySQL 5.7's JSON. The gem JSON on Rails adds native Rails support for it, opening up interesting use cases.

The basics of how this is achieved are explained in a blog post.

**Comment by jerodsanto** [comment]
@saveriomiroddi I think you forgot the link. :)

Also, we're moving news (articles, projects, etc) submission onsite. Please submit it here instead:

https://changelog.com/news/submit

💚💚💚
