### ISSUE TITLE
SIT: SCM-agnostic, file-based, offline-first, immutable issue tracker

### ISSUE THREAD

**Issue by yrashk** [thechangelog/ping#811]
[SIT](https://github.com/sit-it/sit) (Standalone Issue Tracker, or Simple Issue Tracker, or simply SIT's an Issue Tracker; or whatever else you like) is a small tool to manage project issue artifacts on a filesystem. Its goal is to make such artifacts as bug reports, problem statements, discussions (and others) surive the lifetime of the project. Instead of depending on a third-party provider (such as GitHub), it ensures that its database is not going to be lost if a third-party provider goes out of business, loses data, or if you fall in love with a new SCM and decide to migrate over.

Its core properties are:

* All artifacts are stored in a file system
* All records are immutable and ordered
* It's SCM-agnostic (and, in fact, will work without one just fine)
* Its layout is purposefully merge-friendly (who likes merge conflicts?)
* It's extensible

SIT's design allows us to have some interesting features, such as:

* Branch-local issues (useful for managing branch-local todo lists, for example)
* Branch-specific issue states (for example, "fixed in the branch, but not in the master")

SIT also features a highly customizable Web UI.

https://github.com/sit-it/sit

**Comment by jerodsanto** [comment]
@yrashk we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
