### ISSUE TITLE
PySpark data processing course materials

### ISSUE THREAD

**Issue by luisbelloch** [thechangelog/ping#812]
https://github.com/luisbelloch/data_processing_course

Some class materials I use to teach PySpark and data processing at the university. Examples include Vagrant/Docker images to play with the code. I've also included some Apache Beam samples to compare processing model with Spark.

Interesting bits:
- [PySpark samples](https://github.com/luisbelloch/data_processing_course/tree/master/spark)
- [Course Assignments](https://github.com/luisbelloch/data_processing_course/tree/master/assignments), includes tiny test suite to check results against
- [Apache Beam samples](https://github.com/luisbelloch/data_processing_course/tree/master/beam)
- [Deployment lab quick-start code](https://github.com/luisbelloch/data_processing_course/tree/master/infra): Vagrant, Docker, Kubernetes and other scenarios

**Comment by jerodsanto** [comment]
@luisbelloch we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
