### ISSUE TITLE
Nerd Fonts - Iconic font aggregator, collection, and patcher

### ISSUE THREAD

**Issue by ryanoasis** [thechangelog/ping#813]
https://github.com/ryanoasis/nerd-fonts

https://nerdfonts.com

Nerd Fonts is a project that patches developer targeted fonts with a high number of glyphs (icons). Specifically to add a high number of extra glyphs from popular 'iconic fonts'.

- Active project
- Friendly
- Highly curated readme and wiki

**Comment by jerodsanto** [comment]
[Logged this](https://changelog.com/news/nerd-fonts-iconic-font-aggregator-collection-and-patcher-nnO0) ✊
