### ISSUE TITLE
git open: A small git hack

### ISSUE THREAD

**Issue by amjith** [thechangelog/ping#814]
`git open` is an alias added to your .gitconfig file that allows you to reopen the files that you last edited.

http://blog.amjith.com/git-open-a-small-git-hack

**Comment by jerodsanto** [comment]
@amjith we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
