### ISSUE TITLE
Devuan+runit GNU/Linux: custom systemd-free OS on AWS EC2

### ISSUE THREAD

**Issue by cloux** [thechangelog/ping#815]
Hello, I am passing your https://changelog.com/posts/top-ten-reasons-why-i-wont-use-your-open-source-project bulletpoints with flying colors (except the Twitter account). I created a heavily customized OS for the Amazon EC2 cloud. So far it seems to be the only real alternative to all other operating systems offered by Amazon. I don't need to convince anybody to use this, but I would like the administrators working with AWS to know about this option so they can consider it. 

**The project is here**: https://github.com/cloux/aws-devuan

**Comment by jerodsanto** [comment]
@cloux we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
