### ISSUE TITLE
Moore's law.

### ISSUE THREAD

**Issue by timuckun** [thechangelog/ping#816]
I really enjoyed this podcast. Please have this guest on again, he was great and the topic of supercomputing is superinteresting.

**Comment by adamstac** [comment]
Thanks Tim! Yes, @tgamblin was an awesome guest.

We'll see if we can talk him into doing more stuff with us in the future.

**Comment by tgamblin** [comment]
Thanks @timuckun!  And thanks to @jerodsanto and @adamstac for having me on!
