### ISSUE TITLE
Dockly - visual docker manager from the CLI (a Node.js project)

### ISSUE THREAD

**Issue by lirantal** [thechangelog/ping#817]
Hi guys!

I wanted to share about Dockly which seems to have been trending recently on GitHub.

Docker console UI and Dashboard for quickly managing and inspecting Containers and Services -
 https://github.com/lirantal/dockly

![](https://cloud.githubusercontent.com/assets/316371/25682867/c5212216-3027-11e7-8f36-72d38516d2af.gif)

**Comment by jerodsanto** [comment]
@lirantal we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
