### ISSUE TITLE
Open Source code for Chemical Engineers

### ISSUE THREAD

**Issue by srebughini** [thechangelog/ping#818]
Hi guys,

I wonna share with you my project. I'm developing this open source code, called <b>ASALI</b>, for chemical engineers. <b>ASALI</b> models <b>catalytic reactors</b>.  It can evaluate <b>chemical equilibrium</b> and estimate <b>transport and thermodynamics properties of gas ideal mixture</b>.
Check it out and hope you gonna like it.

Cheers

https://github.com/srebughini/ASALI

![asali](https://user-images.githubusercontent.com/8199010/36630475-3a91ae34-1967-11e8-92cb-e215eacbd555.png)

**Comment by jerodsanto** [comment]
@srebughini we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
