### ISSUE TITLE
Poor man's Spotlight: a minimalist Ruby desktop search

### ISSUE THREAD

**Issue by saveriomiroddi** [thechangelog/ping#820]
Poor man’s Spotlight is a minimalist Linux desktop search, backed by a Ruby service.

On execution (eg. if bound to Super+Space), the user types a pattern, then open a file by choosing from the list (with Arrows and Enter).

This project is an interesting for reviewing Ruby GUI development and concurrent processing. All the Ruby GUI libraries has been considered, and the IO.pipe class is used for message passing.

Project page: https://github.com/saveriomiroddi/pm-spotlight

**Comment by jerodsanto** [comment]
@saveriomiroddi we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
