### ISSUE TITLE
LambStatus: serverless status page system

### ISSUE THREAD

**Issue by ks888** [thechangelog/ping#821]
Hi, let me share my project!

[LambStatus](https://github.com/ks888/LambStatus) is the open source and serverless status page system. I believe the serverless architecture is great with the status page system, because:

* It eases your pain caused by the scaling / availability issues. It is terrible if your service is down AND heavy traffic from stuck users stops your status page.
* It enables you to pay only for what you use. A status page only occasionally gets huge traffic. The system takes only $1 per 30,000 visitors and almost $0 if no visitors.

Thanks!

**Comment by jerodsanto** [comment]
@ks888 we're changing Ping so it's only used for show ideas, feedback, or general questions.

Please [resubmit this onsite](https://changelog.com/news/submit) and we'll be sure to take a look at it! 💚
