### ISSUE TITLE
Geet: GitHub commandline interface

### ISSUE THREAD

**Issue by saveriomiroddi** [thechangelog/ping#822]
The `geet` tool allows to perform the most common operations (PR handling, issues handling, gists creation, milestones listing etc.) entirely via commandline.

It's written in Ruby, and requires only the GitHub API key to be set. Install via `gem install geet`!

Website: https://github.com/saveriomiroddi/geet

**Comment by jerodsanto** [comment]
@saveriomiroddi please help us understand how `geet` differentiates and provides unique features to [hub](https://github.com/github/hub).

Also, please post this to https://changelog.com/news/submit as we're moving news submissions there instead of Ping.

Thanks! ✊
