### ISSUE TITLE
Aktu.io: News aggregator + RSS reader

### ISSUE THREAD

**Issue by guybedo** [thechangelog/ping#823]
Hey,

just wanted to share this new webapp: [Aktu.io](http://aktu.io).

Think of it as  a Google News + Google Reader all-in-one app. 
You can get the top stories of the day, organized by categories, browse a lot of content from thousands of sources in different languages, and you can add your own rss feeds too !

**Comment by jerodsanto** [comment]
@guybedo 👋 

We've moved project/article submission to: https://changelog.com/news/submit

Please share this there and we'll be sure to consider it for publishing! ✊
