### ISSUE TITLE
Florian Forster and collectd 

### ISSUE THREAD

**Issue by lukaszkorecki** [thechangelog/ping#824]
Hi!

[Collectd](https://collectd.org) is an open source project which has been around for a while and  found it's way to many monitoring companies which are otherwise closed-source (for example: Google's StackDriver, SignalFX, Librato)
I'd say that while it's not as famous as curl, it's one of these things that's being used pretty much everywhere, yet is not talked about. 

Would be great to hear the story behind Collectd, what's happening now etc etc

Thanks!

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
