### ISSUE TITLE
Broken link to Twitch in notes for episode #291 

### ISSUE THREAD

**Issue by antonalekseev** [thechangelog/ping#825]
_Follow us on Twitch_ link in episode notes should point to https://www.twitch.tv/changelog_, but leads to 404.

**Comment by adamstac** [comment]
Thanks for the report -- this has been updated.

For the record, the link is `https://www.twitch.tv/changelog_` and here's a linked version [twitch.tv/changelog_](https://www.twitch.tv/changelog_)
