### ISSUE TITLE
Go Time Podcast Idea for Consideration 

### ISSUE THREAD

**Issue by spectorrackn** [thechangelog/ping#826]
Our open source project, Digital Rebar (http://rebar.digital/) is a Cobbler replacement provisioning solution built entirely in Golang and is based on the previous Crowbar open source project from Dell for the OpenStack community. Two of our lead developers/architects on the project have done some interesting work with Golang that we believe would be educational for your audience.

Greg Althaus - https://www.rackn.com/company/team/greg-althaus-founder-cto/  ; Co-Founder, CEO of RackN
Victor Lowther – https://www.linkedin.com/in/victor-lowther-928aa9/ ; Sr Software Engineer, RackN

Topics to discuss based on their work:

- 
- Digital Rebar has a plugin-module they built from scratch
- Layered key-value store file system
- Logging infrastructure and Event information are co-mingled
- System tested API driven DHCP server
- 

Greg and Victor are the primary architects and developers of the Digital Rebar project and I am interested in having them share their Golang concepts with the broader community as a way to get feedback on things that can be improved on or perhaps it sparks an idea in a developer in the podcast audience to try something new.

I have had Greg and Victor on a previous podcast (https://soundcloud.com/user-410091210/digital-rebar-tech-discussion-on-patch-apis-swagger-and-integrations) that Rob Hirschfeld, Co-Founder/CEO of RackN and myself manage focused on infrastructure, open source, data center, edge computing, etc. The topic of that podcast was on APIs around Golang.

**Comment by joncalhoun** [comment]
I know it has been a long time, but if we had Greg or Victor on the podcast, what overall subjects do you think would be a good fit for them?

Please keep in mind we are trying to avoid any interview style episodes. Instead, we prefer to pick a general topic and have the entire episode be a discussion around that topic. A few examples from the past include:

- building APIs: https://changelog.com/gotime/81
- errors in go: https://changelog.com/gotime/91
- structuring your go apps: https://changelog.com/gotime/94

Thanks!

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
