### ISSUE TITLE
Suggest having Shen Li on as Go Time podcast guest

### ISSUE THREAD

**Issue by ceohockey60** [thechangelog/ping#827]
Hi Go Time co-hosts,

  I'd like to suggest an interview guest for the Go Time podcast, Shen Li, who's my colleague and leads the development of TiDB (https://github.com/pingcap/tidb), a popular open source distributed database where the stateless SQL layer is written in Go. Here's Shen Li's Github page: https://github.com/shenli. (He's also a big fan of the podcast.)

Kevin

**Comment by joncalhoun** [comment]
I know it has been a year, but if we had @shenli on the podcast, what subjects do you think he would be interested in discussing?

Please keep in mind we are trying to avoid any interview style episodes and instead would prefer to pick a subject (eg "Serverless Go" was a recent subject) and then as a panel we discuss the subject.

I don't know much of Shen's background, but one idea might be a discussion around various storage options available to Go developers. Eg they can use BoltDB, SQL variants, MongoDB, and many others, and each one has its own set of pros and cons. We might also be able to get @benbjohnson on to discuss that subject so we have at least a few different perspectives.

Any other ideas?

**Comment by jerodsanto** [comment]
It looks like this one got stale...

We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
