### ISSUE TITLE
Changelog Weekly going into spam.

### ISSUE THREAD

**Issue by differentsmoke** [thechangelog/ping#828]
Let me preface with, I'm not sure if this is an issue with my email or with the newsletter. I read Changelog weekly pretty religiously, but the past few weeks it started going straight to spam. I just wanted to report this in case it is a problem with the mass email and not my (Yahoo!) mailbox.

**Comment by jerodsanto** [comment]
Hmm that really sucks, @differentsmoke. I don't see any indicators on our end that this is happening en masse, but Yahoo mail only makes up 0.3% of our readers.

Does Yahoo give you any scoring or indicators on why an email is flagged as spam?

**Comment by jerodsanto** [comment]
Closing this for cleanliness, but feel free to follow up and provide more details when you have available time. ✊
