### ISSUE TITLE
AWS Amplify

### ISSUE THREAD

**Issue by dabit3** [thechangelog/ping#829]
Hi, I wanted to ping you to see if you'd be interested in discussing an open source project I've been working with at AWS Mobile called AWS Amplify! -> https://github.com/aws/aws-amplify

Amplify hooks to serverless & cloud services across a number of JS frameworks, enabling things like Push Notifications, GraphQL (client), Analytics & User Authentication.

I'm a Developer Advocate for AWS Mobile & would be happy to come on to discuss as a guest. I've been running my own podcast for almost 3 years, React Native Radio, & am a fan of Changelog!

Thanks!

**Comment by jerodsanto** [comment]
@dabit3 thanks for reaching out! I think this could make for a great show topic. Please email jerod@changelog.com and we'll get you on the recording schedule! ✊
