### ISSUE TITLE
Basher - A package manager for shell scripts

### ISSUE THREAD

**Issue by juanibiapina** [thechangelog/ping#83]
Project page: https://github.com/basherpm/basher

In a nutshell:

    $ basher install sstephenson/bats

Here is the original blog post: http://juanibiapina.com/articles/2014-08-20-basher-a-package-manager-for-shell-scripts/
And a new one that describes how to install from any reasonable github repo: http://juanibiapina.com/articles/2014-11-05-installing-scripts-from-github-with-basher/

Let me know what you think!

**Comment by jerodsanto** [comment]
@juanibiapina thanks for sharing! we're including Basher in our next issue of [Weekly](http://thechangelog.com/weekly/). :beers:
