### ISSUE TITLE
Help us decide the future of thechangelog/infrastructure

### ISSUE THREAD

**Issue by gerhard** [thechangelog/ping#830]
In 2016 we open-sourced the code behind the new changelog.com, [Changelog.com is Open Source](https://changelog.com/posts/changelog-is-open-source), and we spoke about the related infrastructure work in [Episode 254](https://changelog.com/podcast/254) but never open-sourced this code. The primary reason was that making it open-source friendly was [low in the backlog and never made the cut](https://speakerdeck.com/gerhardlazu/not-working-together?slide=20). While good commit messages were used, and user stories with the right amount of what and why were written, the high level context remained diluted and fragmented.

Today, [we are open-sourcing the code behind changelog.com infrastructure as is](https://github.com/thechangelog/infrastructure), and are giving you the opportunity to influence the way we continue investing our time. We need your help to decide on one of the following directions:

**Comment by gerhard** [comment]
Please respond with 👍 if you would like us to make the current approach in thechangelog/infrastrcuture easy to understand and re-use.

**Comment by gerhard** [comment]
Please respond with 👍  if you would like us to start from the beginning, with today's best tools, services and practices. All code will be public, developed iteratively, open and available to everyone willing to follow along. It's a fresh start with your involvement at every step.

**Comment by gerhard** [comment]
There is a draft post on changelog.com that goes more in-depth, will update with a link once we publish it.

**Comment by phillipsj** [comment]
Nice move!

**Comment by jerodsanto** [comment]
I think we got the answers we were looking for here, thanks all! 💚💚💚
