### ISSUE TITLE
kepler.gl - Open source geospatial analysis tool

### ISSUE THREAD

**Issue by ajawchat** [thechangelog/ping#831]
Hi,

I was reading through the kepler.gl documentation and found it to be a good podcast suggestion. The tool is based on deck.gl. Both the tools have been developed by Uber.

Some topics to cover for the podcast might be
* The origins of deck.gl & kepler.gl
* How can interested engineers learn the Web.gl graphics framework
* Future of these tools

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
