### ISSUE TITLE
HRConvert2 - Open source file conversion server for 60x formats.

### ISSUE THREAD

**Issue by zelon88** [thechangelog/ping#832]
Hey guys!

I posted an issue a loooong time ago with a link to my open source Cloud Platform that is similar to ownCloud and NextCloud. 

That project had the capability to convert file formats for account holders. I used a lot of the code from that project to make a stand-alone file conversion server for people who just want to convert files quickly without the extra features and sophistication of the entire Cloud platform.

I saw the interest in doing a podcast about ownCloud and NextCloud and figured this might be a good opportunity to bring up the similar projects I've been working on.

Hopefully you guys find these interesting! Thanks for your time and keep up the great work.
https://github.com/zelon88/HRCloud2
https://github.com/zelon88/HRConvert2

**Comment by jerodsanto** [comment]
@zelon88 while I don't think there's enough meat here to make an entire podcast episode about it, you should definitely submit your project to Changelog News! https://changelog.com/news/submit
