### ISSUE TITLE
Open Source Licensing & Relicensing

### ISSUE THREAD

**Issue by hhrutter** [thechangelog/ping#833]
Suggestion for a Changelog episode:
An interesting show would be to cover real world use cases about licensing strategies and how they worked out. Changing a license (eg. MIT to Apache) and overcoming the obstacles involved is an interesting topic as well.

**Comment by jerodsanto** [comment]
@hhrutter this could potentially make an interesting show, I agree. Do you know of any projects that have undergone this change that we could highlight and interview?

**Comment by hhrutter** [comment]
Sorry I was hoping you guys have some experts on your short list maybe from the _Request for Commits_ days. This issue came up when I started tinkering about the steps, notifications and ramifications involved if I move [pdfcpu](https://github.com/hhrutter/pdfcpu) from MIT to Apache 2.0.

**Comment by vespertilian** [comment]
@jerodsanto @hhrutter

This open source Graph DB project I have been using has been changing up it's licence from Apache to AGPL to Common Clause and Back to Apache in the last 3-6 months.

https://discuss.dgraph.io/t/common-clause-on-license-dgraph-is-not-open-source/3167

Maybe you could have them on the show.

Also the DB is cool, and open source. So I think you should have them on anyway.

**Comment by jerodsanto** [comment]
@vespertilian looks like a good candidate. Who would be the main/best person to talk to about graph?

**Comment by vespertilian** [comment]
@jerodsanto 

Manish R Jain, the founder is who I would approch. 
https://github.com/manishrjain

You could try to reach out via the forum. 
https://discuss.dgraph.io

ps. Thanks for all your had work on the show!

**Comment by jerodsanto** [comment]
Went ahead and invited them via GH issues: https://github.com/dgraph-io/dgraph/issues/2661

Thanks for the suggestion(s)!

**Comment by jerodsanto** [comment]
This episode is now live! Thanks again, all 💚 

https://changelog.com/podcast/322

**Comment by hhrutter** [comment]
Awesome!
