### ISSUE TITLE
Podcast Addict Change log RSS not working

### ISSUE THREAD

**Issue by vCillusion** [thechangelog/ping#836]
I am facing issue with the Changelog channel.
Last update failed: Broken RSS feed: not well formed(invalid token) 
https://changelog.com/podcast/feed

**Comment by jerodsanto** [comment]
@vCillusion I introduced a bug in the feed the other day, but we've fixed it now and everything checks out once again:

https://podba.se/validate/?url=https://changelog.com/podcast/feed

Can you try again and let me know what you're seeing?

**Comment by vCillusion** [comment]
@jerodsanto thanks, it's working now.
