### ISSUE TITLE
Guest proposal Arthur Schmunk

### ISSUE THREAD

**Issue by ariehkovler** [thechangelog/ping#837]
I was hoping to suggest as a podcast guest Arthur Shmunck, CEO of datree.io, a pre-launch funded startup that's tackling the new challenges created by modern software development. 

Basically, the shifts to Agile, Devops and microservices have brought some interesting consequences. Each microservice has its own set of code components (Open Source and internal packages, third party APIs, tech like Docker or Jenkins, etc). Developers often choose one code component without knowing if another team is already using an equivalent or a different version, or what expertise is already inside the company. Essentially, the old departmental silos are gone but new team silos are created. 

Meanwhile, CIOs often don't even know what languages and platforms their company uses. Companies often either give up and accept the chaos and the inefficiencies it brings, or they try to coordinate this stuff via email approvals or shared Excel spreadsheets, creating new bottlenecks and approval processes and general mess.   

Datree's founders faced these challenges and decided there had to be a better way. They're working on a collaboration tool to link up siloed devteams and improve knowledge visibility to help people connect. 

Datree founder and CEO Arthur Schmunk met with over 100 software companies to fully understand the challenges and find the best way of dealing with them. He can talk about some of the wild processes now in use in major companies, the chaos of the modern development process, and give some tips and ideas for managing in the world of code components.

**Comment by jerodsanto** [comment]
I think this makes the most sense for FT, if at all. Applying that label and will let Adam decide

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
