### ISSUE TITLE
Juan Linietsky and Godot game engine

### ISSUE THREAD

**Issue by Dovyski** [thechangelog/ping#838]
Hey guys!

I would like to suggest **Juan Linietsky** ([twitter](https://twitter.com/reduzio), [github](https://github.com/reduz)) as a guest for the **Changelog podcast**. He is one of the creators (and currently lead developer) of the popular open-source [Godot game engine](https://godotengine.org/).

Why would he be an awesome guest?

* He created a successful, powerful, free, 2D/3D, open-source game engine which is comparable to commercial alternatives, e.g. Unity. Gamedev is a fierce world, that's quite an achievement.
* [Godot's patreon](https://www.patreon.com/godotengine) collects ~$8,215/month, which fully funds Juan's work. He is living off of open-source work (he was not at the beginning of the project).
* Godot has grown from a single lone contributor to a significant community. [There is no boss, it's a community consensus that makes things happen.](https://godotengine.org/article/shedding-light-on-godot-development-process) Great open-source principles right there!
* Juan has 20 years of experience with game technologies and is approached by companies with job offers (which I assume are not offering pennies but some decent money). Still, he chooses to work on and be paid by Godot!
* It's not about gamedev *per se*, it's about a person (and a community now) creating a great and successful open-source project despite all the odds against it (as I said, gamedev is a fierce world).

That's all, thank you! 
P.S. [here is a video](https://youtu.be/btazdd8jNEc?t=30s) showing a 3D demo made in Godot to help back my comments ;)

**Comment by jerodsanto** [comment]
This is an excellent pitch! We [just tweeted him](https://twitter.com/changelog/status/1049332274905448448) to see if he'd be interested in coming on the show. ✊
