### ISSUE TITLE
AFK show: Matt Layher on remote work and/or RSI as a programmer

### ISSUE THREAD

**Issue by mdlayher** [thechangelog/ping#839]
Hi all!

Love the idea behind AFK show, and I'd love to participate if possible! I have a couple of topics that I believe could make interesting for an interesting episode:

- working remotely for 4+ years
- dealing with RSI/cubital tunnel as a professional programmer

If you folks are interested, I'd love to be on the show! Thanks for your time.

**Comment by smithtimmytim** [comment]
Hi Matt,

Thank you so much for submitting this idea, and I apologize for the ridiculous delay of response. We're going to pass on this opportunity.

Thanks so much for listening.
