### ISSUE TITLE
Content as a Service - Contentful as a Content Infrastructure

### ISSUE THREAD

**Issue by stefanjudis** [thechangelog/ping#840]
Hello everybody. I just quickly wanted to ping you to see if you'd be up for a Changelog show about API-driven content management and why an API-first approach solves a lot of issues? :)

[Contentful](https://www.contentful.com/) is content infrastructure that plays very well together with serverless and static site technologies.

I'm in the developer relations team at Contentful, am [conference organizer](https://accessibility-club.org/) and pretty much a frontender by ❤️. 

Thanks a lot!

**Comment by jerodsanto** [comment]
👋 @stefanjudis! This is something we've discussed off-and-on over the last year or so. We will pass on dedicating a show to the topic, but thanks for the suggestion!

Having said that, if you and the devrel team at Contentful need help telling your story in a powerful way to our (and likeminded) audience... [there are other options](https://changelog.com/sponsor). 😉
