### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by andreaso** [thechangelog/ping#842]
Any chance that we can have https://changelog.com/ and https://cdn.changelog.com/ reachable by way of IPv6? I'd imagine it being reasonably doable given that both Linode and Fastly have good IPv6 support.

**Comment by jerodsanto** [comment]
Good question! We do have [an issue on the changelog.com repo](https://github.com/thechangelog/changelog.com/issues/244) for this. Follow along there ✊
