### ISSUE TITLE
Wanted tougher questions in Founder's Talk #58 (Tidelift)

### ISSUE THREAD

**Issue by erlend-sh** [thechangelog/ping#843]
Hey Adam & co. So happy to have Founder's Talk back in action! I knew I remained subscribed to your feed for all these years for a reason ;)

I recently listened to episode 58 and, while it was enjoyable like usual, it felt like you missed an opportunity to ask some harder questions about Tidelift's long term vision. I'm an avid supporter of Tidelift, but I'd love to know more about how their $15m in funding will affect them going forward.

**Comment by jerodsanto** [comment]
![](https://media.giphy.com/media/pUeXcg80cO8I8/giphy.gif)

**Comment by adamstac** [comment]
Thanks for sharing your thoughts @erlend-sh. I have this idea for "Founder Updates" mini-episodes where we sync back up for a catch up type call, maybe 15-20 minutes at max end to end runtime.

I can ask more follow up Qs like this then. What else do you want to hear more about from them?

**Comment by erlend-sh** [comment]
Well the bulk of it would be about the ins and outs of the funding:

- How much of the company got sold? [Buffer has set a golden standard](https://open.buffer.com/buying-out-investors/) for finance transparency. I'd expect at least the same level of transparency from a custodian of open source.
- How beholden are you to your board of directors? If they say "we need to be making more money", what happens?
- Any plans for a Series B?
- Are you planning an exit? If not, what is the expected payoff for the investors?

Just to be crystal clear I **love** that a company with a mission to "pay the maintainers" managed to secure such sizeable funding and I'm rooting for them all the way. But VC money is not without its drawbacks and many OSS champions shy away from it exactly because they value complete control over their vision more than that short-term rocket fuel injection. I think there's a healthy balance to be found, but it requires a level of transparency that even most open source companies fail to deliver when it comes to money and the power dynamics that come with it.
