### ISSUE TITLE
Solid - open source platform built to decentralize the web

### ISSUE THREAD

**Issue by marcelotto** [thechangelog/ping#846]
Hi,

I would very much like to hear a Changelog episode about the [Solid](https://solid.mit.edu/) project aiming to restore rightful ownership of data back to every web user  and [Inrupt](https://www.inrupt.com/), the company launched with the mission to ensure that Solid becomes widely adopted.

The best people to talk to about that are probably [Ruben Verborgh](https://ruben.verborgh.org/) and of course [Tim Berners-Lee](https://en.wikipedia.org/wiki/Tim_Berners-Lee).

**Comment by jerodsanto** [comment]
@marcelotto yes, we want to cover this! I already have an email in to Tim Berners-Lee requesting him to come on the show, but it's a long shot. Ruben is interesting as well, thanks for the suggestion!

**Comment by jerodsanto** [comment]
I'm still working on this! Not sure if/when it'll happen, but I'm making the best effort I can. Gonna close this issue for cleanliness, but will def follow up here if things start to... solidify 😏
