### ISSUE TITLE
enjoying the show, but...

### ISSUE THREAD

**Issue by prophoss** [thechangelog/ping#847]
I Have recently found y'alls show and love listening to it as I deliver pizza in my area. There is so much info that y'all cover but so much of it goes over my head. Now that is not y'alls fault that I'm a newb , but I wish there was more explanation sometimes. I have listened to a few new coder type shows but I'm new and the one I did find wasn't my style I guess you could say. I have a lot to learn and soon will be, I hope, as I start school for a CS degree in January.  Thanks for letting me vent and for creating a great show. I actually enjoy the less technical ones a little more since I don't know too much technical stuff yet. 
Brian Cooper Ft Worth TX

Thanks for pinging us! Steps to success:

1. If you want coverage in Changelog News. Stop! GOTO https://changelog.com/news/submit
2. Use plain English in the issue title. Don't prefix with it "Podcast Suggestion" and the like.
3. Please tell us which podcast you're referencing so we can apply the appropriate label.

That's it! Thanks again 💚

**Comment by jerodsanto** [comment]
@prophoss thanks for the feedback! I know how you feel as I've often used podcasts to learn new subjects and am repeatedly confused/frustrated by the jargon.

The difficult part for us is we're trying to serve a diverse audience that is at many different levels of understanding and experience. If we are repeatedly stopping to explain (or have our guest explain) things, we risk annoying and alienating our more expert listeners.

Adam and I _tend_ to be a good combo as I'm a bit more technical than he is so if he's getting lost in the weeds it's usually a good sign that we're not helping people on that side of the spectrum very well. For example, he asked Manish for a 'graph databases 101' explainer in [episode 322](https://changelog.com/podcast/322) and that ended up being a spectacular section of that show.

I guess what I'm trying to say is, we hear you and will do our best to help out listeners like you, but don't expect _drastic_ change from what you're listening to now. I'd also like to encourage you to just keep listening! You have no idea how much you'll soak up, even when you don't think that you are. It'll serve you well as you grow in your knowledge and put it in to practice in your schooling and career.

💚💚💚

**Comment by prophoss** [comment]
No, no please do not misunderstand me. I would not expect you to change. Rather I was venting to you  because of my frustration. I very much enjoy y'alls show and will continue to listen as often as I can. I always seem to get some new bit of info that helps me understand things a bit better no matter what I'm doing at the moment. I just wish I had someone to talk to about all this new stuff I'm learning.  I don't have anybody in my circle of friends who knows anything about coding and no mentor to help guide me along either. So your show and some others like it have become my friends  and my mentors. Please keep it up, and thanks again.

**Comment by jerodsanto** [comment]
Right on. You're more than welcome to join [our humble community](https://changelog.com/community) and ask questions as you go. There's plenty of folks (myself included) in there that are willing to help you on your journey.

A couple other communities/programs to check in to:

1. [CodeNewbie](https://www.codenewbie.org)
2. [freeCodeCamp](https://www.freecodecamp.org)

💚
