### ISSUE TITLE
Semantic UI 1.0

### ISSUE THREAD

**Issue by jlukic** [thechangelog/ping#85]
Hey, just wanted to ping you guys that I'm getting ready to release SUI 1.0 and would love to come back and chat about it.

http://beta.semantic-ui.com

**Comment by jerodsanto** [comment]
@jlukic if you're still interested in coming back on the show, email me and we'll iron out the details: jerod@changelog.com :beers:

**Comment by jlukic** [comment]
Emailed you.

**Comment by netaisllc** [comment]
@Editors; an example of the Follow-Up series, this is. Luckily JL reached out to you. Consider a means to proactively reach out to popular guests. FWIW.:)

**Comment by jlukic** [comment]
Hey again, [version 2.0 of Semantic UI](http://www.semantic-ui.com) was just released today. 

I'd love to come on again. I'm going to send you guys an email as well.

You can see some of [what's new](semantic-ui.com/introduction/new.html) in the docs.

**Comment by jerodsanto** [comment]
Looks like we can [close this](https://changelog.com/164) now!
