### ISSUE TITLE
Andy Terrell and NumFOCUS

### ISSUE THREAD

**Issue by bryanwweber** [thechangelog/ping#850]
A suggestion for a topic for The Changelog: NumFOCUS is a 501(c)3 non-profit in the States that supports mostly scientific computing projects, but also has many machine learning and related software under the umbrella, including the Jupyter project. Andy Terrell is the president of the foundation and has held a number of roles in academia and industry. I think this topic would be interesting as it is one funding model to sustain open-source software.

The NumFOCUS website is here: https://numfocus.org/

**Comment by jerodsanto** [comment]
Ooh I like this idea 👏

**Comment by jerodsanto** [comment]
@bryanwweber the invitation has been extended. Keep your fingers crossed!

(closing for cleanliness) 💚

**Comment by jerodsanto** [comment]
This show is now live! 🍾 

https://changelog.com/podcast/335
