### ISSUE TITLE
Interview Tamal Saha of AppsCode

### ISSUE THREAD

**Issue by displague** [thechangelog/ping#851]
Tamal is an entrepreneur going head first into the Kubernetes space with his company AppsCode. 

AppsCode has created and launched dozens of tools, plugins, and services including KubeDB (DB Operator), Voyager (Ingress), and Pharmer (multi-cloud K8s installer).

Previously at Google and Amazon, Tamal has created a name for himself through his code (Go, Java, others), issues, support, consulting, and products.  He has strong opinions about where Kubernetes is headed and the state of the community and interests today.

https://appscode.com/ 
Github: @tamalsaha
Twitter: [@tsaha](https://twitter.com/tsaha/with_replies)

<img width="884" alt="image" src="https://user-images.githubusercontent.com/317653/50167113-69922680-02b6-11e9-9132-69e6d9ec4f1a.png">

**Comment by jerodsanto** [comment]
@displague I like this idea. 💚 

@tamalsaha would you like to come on The Changelog sometime soon?

**Comment by tamalsaha** [comment]
Thanks @jerodsanto ! I would love to talk to you about AppsCode & Kubernetes. Please email me `tamal@appscode.com` so we can find a time to do this!
