### ISSUE TITLE
Interview Derek Collison from Synadia about NATS and NGS

### ISSUE THREAD

**Issue by dwaynebradley** [thechangelog/ping#852]
You should try to interview [Derek Collison](https://twitter.com/derekcollison) about [NATS](https://nats.io), his company [Synadia](https://www.synadia.com) and the [NGS](https://www.synadia.com/ngs) system that they have built to connect everything.

Just as a little additional background:

- Derek has a long history in the messaging space. He has worked at TIBCO, Google, VMWare, Ericcson and more.
- He wrote NATS because _he_ wanted it.
- He is also very opinionated about all of the complicated/layered "stuff" that has been built just to connect things up currently (i.e. Istio/Envoy/Linkerd, gRPC, etc.) and feel that NATS is a much simpler way of doing it. You should definitely ask him about it!
- NGS is their way of generating revenue with NATS which is OSS.
- NATS is also an incubating project at the [CNCF](https://www.cncf.io/projects/). Actually it is the only "messaging" project currently at the CNCF.

**Comment by jerodsanto** [comment]
Thanks for the suggestion, I like this idea. Not sure if Derek would be better for The Changelog or for Founders Talk. What do you think, @adamstac?

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
