### ISSUE TITLE
Interview Lieven Scheire about his tv show "Team Scheire"

### ISSUE THREAD

**Issue by bertvv** [thechangelog/ping#853]
[Lieven Scheire](https://en.wikipedia.org/wiki/Lieven_Scheire) is a Flemish comedian and tv maker. In his latest show "[Team Scheire](https://www.canvas.be/team-scheire)" on the Flemish national tv station [Canvas](https://www.canvas.be/), a diverse team of eight makers try to find creative solutions to improve the life of people with disabilities or other problems. In the first episode, e.g., a game controller was developed so a boy with cerebral palsy is able to play GTA5.

The results (plans, code, etc.) are published on Github at <https://github.com/teamscheire> so everyone can use them to help people in their own life. In a [companion podcast](http://moulesdegeek.libsyn.com/), the makers are interviewed, which allows them to talk more in depth about their solutions.

The tv show and podcast are in Dutch, but I do think that Lieven would be great as a guest of the Changelog, if only as an inspiration. 

Lieven is on twitter as [@lievenscheire](https://twitter.com/lievenscheire).

**Comment by jerodsanto** [comment]
Thanks for the suggestion, @bertvv! I'm going to look in to this and see what we can do. ✊
