### ISSUE TITLE
Interview Jeff Chasin about Launch by Adobe

### ISSUE THREAD

**Issue by the3rdc** [thechangelog/ping#854]
Launch is interesting because of how NOT like an Adobe product it feels.

- It was **built** not **bought** (in-fact, the devs had to build it secretly in their free time before they could get approval to make it official.)
- The core runtime (and extension scaffolding tools) are open source.
- It targets modern browsers and modern best practices.
- The extension development experience is actually a joy (who would have thought any Adobe docs would ever begin with an npm install?)

I imagine this will be interesting to people in the a similar way to how we all tried out VSCode and said "Really? This is from Microsoft".  Everytime I work with Launch I say "really? This came out of Adobe?"

Makes sense to me as a Changelog interview because of the decision to open source parts of the core, but could also fit with JS Party, since writing extensions is entirely JS.

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
