### ISSUE TITLE
Covering ReasonML

### ISSUE THREAD

**Issue by pascalw** [thechangelog/ping#855]
Hey folks!

I've been getting into [ReasonML](https://reasonml.github.io/) lately and I think it's really great. In short:

> Reason lets you write simple, fast and quality type safe code while leveraging both the JavaScript & OCaml ecosystems.

I think there's quite a nice story to tell on where Reason came from. Part of that story was shared by @jordwalke on the [ReasonTown](https://reason.town/jordan-interview) podcast. Another part of the story I think is [Bucklescript](https://bucklescript.github.io/) which Reason builds on, where @bobzhang is key.

Reason is used both for web development, often with [ReasonReact](https://reasonml.github.io/reason-react/), but there also seems to be a lot of focus on using Reason with OCaml native via https://esy.sh/.

Would be great if you guys could make a show about Reason 🚀

**Comment by jerodsanto** [comment]
We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
