### ISSUE TITLE
Interview Greg Kurtzer about Singularity

### ISSUE THREAD

**Issue by phpHavok** [thechangelog/ping#857]
Greg Kurtzer is the founder of CentOS, Warewulf, and most recently Singularity. Singularity is an amazing containerization tool that has been rapidly penetrating the market. Singularity excels over other containerization tools in that Singularity containers:

- run with user privileges rather than root privileges.
- are a single, immutable file that can be passed around with simplicity.
- can be cryptographically signed and verified ensuring authenticity and integrity.
- don't require a daemon to execute.

Furthermore, Singularity is completely open source with a very active community of developers. The development team is amazing, and the team learned Go from scratch and ported the project from C to Go in only a few months.

Greg Kurtzer would be a very valuable and intriguing interviewee for Changelog.

**Comment by jerodsanto** [comment]
This one is in the works! 💚

**Comment by jerodsanto** [comment]
This is now a thing that exists! 🎉 

https://changelog.com/podcast/336

**Comment by phpHavok** [comment]
Awesome! Can't wait to check it out :smile:
