### ISSUE TITLE
Singularity, a container runtime for Machine learning, GPU & HPC workloads

### ISSUE THREAD

**Issue by kzap** [thechangelog/ping#858]
Suggested Podcast: `The Changelog`

Hi folks,

I've got a suggestion for a show I feel Changelog listeners would enjoy.

## What?
What is the open source container runtime that is used throughout the globe on the world's fastest supercomputers? It's the darling of many HPC solutions from industry heavyweights Nvidia, IBM, Redhat, Amazon, Microsoft, Google and more! .

If you're answer started with a `D` or a similar `OCI` format, then you've missed the mark … but you’re not alone! It has lived in a world apart from most software developers, gaining uptake  from scientists, researchers, and big industry. I had not heard of it until last year.

It's name is [`Singularity`](https://github.com/sylabs/singularity), a fully open source container runtime used by [NVIDIA](https://www.youtube.com/watch?v=Dbg44e-wLV0), [SUSE](https://www.youtube.com/watch?v=S_4nG8rBpDE), [Harvard](https://www.rc.fas.harvard.edu/odyssey-3-the-next-generation/), [Stanford](https://srcc.stanford.edu/farmshare2/software-singularity), [Princeton](https://csguide.cs.princeton.edu/software/singularity), [OpenScienceGrid](https://support.opensciencegrid.org/support/solutions/articles/12000024676-docker-and-singularity-containers) and many [others](https://www.sylabs.io/singularity/whos-using-singularity/).

It is being developed by the open source community and a company, [Sylabs Inc.](https://www.sylabs.io/), [formed](https://www.hpcwire.com/2017/05/04/singularity-hpc-container-technology-moves-lab/) by the project's creator [Greg Kurtzer](https://github.com/gmkurtzer) (Also the [creator of CentOS](https://twitter.com/gmkurtzer/status/1087042335605542912)).

## Why?
What makes [Singularity](https://www.sylabs.io/) so special?

It is the `Container solution for compute driven workloads`.
It is simple, fast, secure and works in just about any environment.

We are used to using containers to stuff as many services onto a single machine in order to increase utilization, scale through replication, etc. That is only one use case and comes at the cost of speed, security, and many layers of complex abstraction. 

`Singularity` solves the problem for using containers in CPU/GPU intensive workloads where you need to be as close to the metal as possible.
Instead of trying to fit thousands of containers on a single machine, Singularity is used to consume thousands of CPUs, GPUs, and machines with a single container!

## How?

`Singularity`'s model is unique compared to other container runtimes out there and this is what a Changelog show could be about. Letting everyone else in the developer world know what Singularity does, how it does it differently, and how they can use it for their needs.

Some of the topics that could be discussed include:

- The project recently was rewritten in Go and C, from Python and Bash, and released [Version 3.0](https://www.sylabs.io/2018/10/title-now-live-singularity-3-0/) last October 2017.

- It has its own [Sylabs Cloud](https://cloud.sylabs.io) service which lets anyone build, upload, sign and share the containers they have created.

- It has a Kubernetes CRI integration that is also open source https://github.com/sylabs/cri, letting you run these containers on K8s just like you can do with any other container.

- It has won [many awards](https://www.sylabs.io/2018/11/singularity-wins-3-hpcwire-awards-at-sc18/) year after year in the SuperComputing space.

- [Sylabs](https://sylabs.io/team), the company behind Singularity, is a fully remote distributed company, with worldwide team with no timezone or geographic restrictions, a true remote company! [And we are hiring!](https://www.sylabs.io/about-us/we-are-hiring/) 

- [Soon to have native Mac support](https://twitter.com/SylabsIO/status/1083733918371610624)

## Who?

I suggest interviewing @GodloveD (Dave Godlove) [SuperComputing2018 Talk](https://www.youtube.com/watch?v=G6vjktFJIeY) and @ArangoGutierrez (Eduardo Arango) [HashiConf Talk](https://www.hashicorp.com/resources/singularity-containers-enterprise-performance-computing), 2 core maintainers of the Singularity Project.

### Disclosure

I joined Sylabs last October and this has been one of the best experiences to work at a company in my 18 year career, the entire team is experienced, passionate, mature and full of knowledge.

**Comment by kzap** [comment]
P.S. I noticed one of our community members @phpHavok just posted about this a few days ago: https://github.com/thechangelog/ping/issues/857 , I swear its a coincidence :D

**Comment by jerodsanto** [comment]
I'm down for the topic @kzap any reason your suggested guests would be better than the founder on?

**Comment by kzap** [comment]
@jerodsanto would love to get @gmkurtzer on and it would be an awesome show 💯 , its more about schedule, but willing to work out the logistics, will ping you for email

**Comment by jerodsanto** [comment]
Email sent! Closing or cleanliness ✊

**Comment by jerodsanto** [comment]
It's alive, it's alive! 🎉 

https://changelog.com/podcast/336
