### ISSUE TITLE
Interview Adam Wathan about Tailwind CSS

### ISSUE THREAD

**Issue by aparajita** [thechangelog/ping#859]
### The Changelog

[Tailwind CSS](https://tailwindcss.com) is rapidly changing the way we think about CSS, and will soon be reaching v1.0. It would be great to interview Adam about why he created Tailwind and what makes it so great.

For background, see [this article](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/).

**Comment by jerodsanto** [comment]
@aparajita sounds like a good idea to me!

@adamwathan we'd love to have you join us to discuss Tailwind. Interested?

**Comment by adamwathan** [comment]
Yeah absolutely would love to be on 👍🏻 Thanks for the recommendation @aparajita!

**Comment by aparajita** [comment]
I assume you will coordinate with each other at this point, should I close the issue @jerodsanto or leave it open?

**Comment by jerodsanto** [comment]
Yup, that's right! @adamwathan please email jerod@changelog.com to coordinate. Thanks all! 👏
