### ISSUE TITLE
Show idea: How Indeed runs and manages their FOSS Sustainability Fund

### ISSUE THREAD

**Issue by jdorfman** [thechangelog/ping#860]
Adam posted this in the `#sustain` channel: https://fosdem.org/2019/schedule/event/community_sustaining_foss_projects_democratizing_sponsorship/

It would be great to hear Duane O'Brien, Head of open source at Indeed go further into detail about  "Democratizing The Sponsorship Process".

**Comment by DuaneOBrien** [comment]
Happy to! @adamstac I'll shoot you an email.

**Comment by jerodsanto** [comment]
@DuaneOBrien did we drop the ball on this? Did you? Was it Dorfman? 😆 

We're ready to pick that ball up and start running with it again whenever you are. Email when ready.

Closing for cleanliness 💚
