### ISSUE TITLE
Umbraco

### ISSUE THREAD

**Issue by khebbie** [thechangelog/ping#862]
I would find it interesting if you could do a show on a pretty old .net technology, that has been open source for a long time: Umbraco.com.
I would suggest having Niels Hartvig

**Comment by jerodsanto** [comment]
@khebbie I appreciate the suggestion. We shy away from shows that focus on CMSes unless they have something new/novel about them. Unfortunately, I don't think Umbraco passes that test.

Thanks for pinging, thanks for listening! 💚
