### ISSUE TITLE
Matrix.org and Riot.im - open source, decentralized communication with Slack bridging

### ISSUE THREAD

**Issue by fredrikekelund** [thechangelog/ping#863]
[matrix.org](https://matrix.org/) is an open source protocol for decentralized chat, VOIP and video chat. It has been around for a couple of years and is a bit novel in the fact that they provide not only a complete package for self-hosted team communication, but also bridges to other apps that provide the same types of services (eg. Slack).

Now would probably be a good time to talk to them on The Changelog, as they're about to release the 1.0 version of both the protocol, the Riot.im official chat app and Synapse, the reference home-server implementation.

I'm only superficially familiar with this project, but it's clear that they are serious and they seem to have gathered a pretty large community! There also seems to be some interesting stories around the funding of the project

Wikipedia: https://en.wikipedia.org/wiki/Matrix_(protocol)
Homepage Matrix: https://matrix.org/blog/home/
Homepage Riot: https://about.riot.im/
Recent article from Hacker News about the French government's adoption of Matrix: https://lwn.net/Articles/779331/

**Comment by jerodsanto** [comment]
@fredrikekelund I appreciate the suggestion (not only for its existence, but for its high quality). That being said, we have done a fair bit of decentralized/federated shows in the last 18 months and my interest is waning in them for the time being. Not only that, but our audience hasn't shown _too much_ interest in these shows either.

I'll definitely keep Matrix on my radar and will consider it for a show down the road. Thanks for pinging, thanks for listening. 💚
