### ISSUE TITLE
Open Data Kit - set of tools for collecting data in challenging environments

### ISSUE THREAD

**Issue by brettneese** [thechangelog/ping#864]
Suggested Podcast: `The Changelog`

https://github.com/opendatakit
https://opendatakit.org/
https://opendatakit.org/community/

Open Data Kit is a fairly old project (started by researches at the University of Washington, I believe) that's used to collect data and do surveys in "challenging environments." I don't know the team but looking at their website and GitHub it seems like it's going through a bit of a revival, so now might be a good time to reach out to them (team@opendatakit.org).

What's interesting about ODK is that it's used in a lot of different environments than a lot of software that's talked about on the show - similar to Singularity (#857 and #858), it seems to target a more academic audience, and is used to do anything from data from researches monitoring rainforests in the Amazon to observing elections in Albania to tackling Ebola in West Africa. I personally work for an engineering firm where I maintain an ODK server to collect data from telephone pole inspections.  

Another interesting thing about ODK is that the underlying form and data collection technologies are interoperable and open source, built on an open source spec called OpenRosa. I really don't know the history of all these things and would love to learn more. 

It's not the sexiest project in the world but it's a rare piece of technology that seems to exist outside the tech bubble, so I'm sure it would make for an interesting show.

**Comment by jerodsanto** [comment]
Interesting idea, @brettneese I'm going to look into this! 💚

**Comment by jerodsanto** [comment]
@brettneese I've made initial contact and invited them on the show. It's out of our hands now, so I'm closing this for cleanliness. Will follow up if anything comes of it!

**Comment by yanokwa** [comment]
@brettneese thanks for your contributions to Aggregate and for suggesting us to be on The Changelog! I'd love to be on the podcast and I've told @jerodsanto as such :)

**Comment by jerodsanto** [comment]
🎉 its_happening.gif 🎉 

Closing this issue as it's served its purpose, but Thanks again Brett and keep your ears peeled for a shoutout when the episode goes live. ✊
