### ISSUE TITLE
GoTime feature discussion suggestion: Traefik (2.0)

### ISSUE THREAD

**Issue by fubarhouse** [thechangelog/ping#865]
Traefik has been rewritten for a major release and it's more awesome than ever.

It's an incredibly popular routing alternative solution which has native support for _many_ providers and is even getting a brand new UI.

It would be good to get the Containous team or a representative on board to tell people about it and share some of the difficulties in achieving the features they've sought to get in this release including support for TCP which has been an incredibly long sought support item which needed an exhaustive amount of work to achieve.

Maybe it would be possible to get the team to talk about a roadmap of where the project is headed and some interesting case studies where Traefik is being used broadly and if/how those teams were able to contribute back to the product.

The repository can be found here: https://github.com/containous/traefik

**Comment by joncalhoun** [comment]
Hi @fubarhouse, I know this is late, but thanks for the suggestion!

With the changes made to the podcast, we are trying to steer away from doing shows where we focus on a single piece of technology, its roadmap, case studies, etc. My fear is that these often turn into interview episodes where all the panelists can really do is ask questions of the traefik team; we can't really contribute to the conversation or have much of a discussion. As a result, these episodes tend to have far less overall appeal to our audience.

What works better is if we can come up with an overall topic that someone from the traefik team would like to discuss that might include some discussion about traefik, but isn't solely focused on it. An example of this is the recent web development episode (<https://changelog.com/gotime/92>) where Buffalo comes up, but it isn't the sole point of the conversation.

Do you have any suggestions for topics that might fit that criteria?

**Comment by fubarhouse** [comment]
@joncalhoun,

Thanks, and the new direction totally makes sense. Similar issues could include networking, networking micro-services, or high availability load balancing. Perhaps in the context of current and upcoming security protocols?

Appreciate the response :)

**Comment by joncalhoun** [comment]
👍 

I'll keep this in mind as we schedule future episodes. Thanks for reaching out :smile:

**Comment by jerodsanto** [comment]
It appears this one got stale...

We're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.

Please do submit a request there if this is an episode you're still interested in! 💚
