### ISSUE TITLE
GoTime Discussion on Go Dependencies, Modules, Proxies and Athens

### ISSUE THREAD

**Issue by arschles** [thechangelog/ping#866]
Hey Folks,

I think a discussion about [Go Modules](https://github.com/golang/go/wiki/Modules), and specifically focusing on module proxies and [The Athens Project](https://github.com/gomods/athens) would make a great GoTime episode. Modules & module proxies are super exciting (and important) topics for Gophers everywhere 🚀 

A few of us maintainers including @chriscoffee, @marwan-at-work and myself would be up for joining in on an episode to talk about it all.

>That's it! Thanks again 💚

Thanks to all of you for the megasuperawesome content! 🚀 💯 🥇

**Comment by matryer** [comment]
@arschles Thanks for reaching out. Absolutely interested and about to get active on this very subject.

**Comment by marwan-at-work** [comment]
This podcast is awesome. I'd be very happy to partake :)

**Comment by jerodsanto** [comment]
Forgot to say: this show is a thing now! 💃 

https://changelog.com/gotime/86
