### ISSUE TITLE
Interview with Joel Griffith (me) -- browserless.io

### ISSUE THREAD

**Issue by joelgriffith** [thechangelog/ping#867]
Hey there!

I'm not sure if _self_ asking for a podcast, but I've done several about browserless.io, and after listening to the Gatsby podcast I think it'd be a great fit for the show.  I'd love to talk about any of the following:

- Founding an open-source company.
- Self-bootstrapping.
- Interacting with the community.
- Marketing your project.
- All the above.

Let me know if there's more I can offer up! browserless.io is on IndieHackers as well (if you'd like to look at financial details).

**Comment by jerodsanto** [comment]
@joelgriffith we're going to pass for now, but thanks so much for pinging us!
