### ISSUE TITLE
The Changelog Interview with Eddie Tejeda of 18F's Federalist

### ISSUE THREAD

**Issue by davemcorwin** [thechangelog/ping#868]
Hey y'all!

**Eddie Tejeda**, the product, sales, and cheer lead at Federalist, would be a great interview on The Changelog. He is at the forefront of pushing change from within at 18F and an enthusiastic supporter of all things open source.

With all the political shenanigans taking the spotlight, the positive changes that are happening across the federal government sometimes get overlooked. Technology-wise, we're making great strides in the use of open-source tech and modern workflows. In particular, platforms like [Federalist](https://federalist.18f.gov/) (think Netlify, for the gov't) are greatly enhancing the ability of federal agencies to quickly and efficiently serve the public. What used to take agencies months of bureaucratic wrangling, can now take mere days with Federalist. This is largely due to the great work that Eddie is doing by building a great product **and**  convincing federal agencies that there is a better way!

## Links
- Eddie
  - [Email](mailto:eddie.tejeda@gsa.gov)
  - [Twitter](https://twitter.com/eddietejeda)
  - [Github](https://github.com/eddietejeda)
- [Federalist](https://federalist.18f.gov/)
- [18F](https://18f.gsa.gov/)
- [Cloud.gov](https://cloud.gov/)

## Disclosure
Long-time listener, first-time issue creator, 18Fer,  Federalist contributor :)

**Comment by jerodsanto** [comment]
@davemcorwin thanks for the suggestion! I'm not completely sold on this show idea (even though I _am_ completely sold on the idea that Eddie is making positive change) for a few reasons:

1. We've done [an episode with 18F](https://changelog.com/podcast/230) already (did you hear that one?)
2. While it's cool to learn about the goings on in .gov, it only indirectly affects most of our listeners (not to mention those not in the US, who are many)
3. I'm a bit burned out on government things right now, honestly

Thanks again for the ping, we truly appreciate hearing from listeners. 💚

**Comment by davemcorwin** [comment]
No worries, thanks for the thoughtful response, keep on keepin on!
