### ISSUE TITLE
Lets talk about Perl!

### ISSUE THREAD

**Issue by robn** [thechangelog/ping#87]
I thoroughly enjoyed your chat with Sara Golemon about PHP. Since you're obviously interested in old languages that are still being used and improved, I'd love to hear you talk about my ancient language of choice, Perl.

Listening to what's happening with PHP, it sounds like Perl's journey has been very similar in a lot of ways but perhaps less visible recently because of the lack of an enormous sponsor like Facebook. Its definitely still out there and being used heavily (including at my company, FastMail) and is getting some really great features and tools around it, as well as awesome people.

I would ask that you don't dwell too much on the whole Perl 5 & Perl 6 thing. I'm sure you'll have questions about it, because everyone loves to talk about it but seriously, its so incredibly boring! Perl 5 stands on its own, and I'd love to hear your take on it.

I suggest @rjbs or @ovid as good interview candidates. I don't know either of them personally, but I do know they are both thoughtful, passionate and highly respected in the Perl community. You could do much worse!

**Comment by szabgab** [comment]
Just for the record. This is the episode: https://changelog.com/133/
