### ISSUE TITLE
[Podcast Suggestion] Evan Wallace of Figma

### ISSUE THREAD

**Issue by davidcornu** [thechangelog/ping#870]
Evan Wallace (https://github.com/evanw) and [Figma](https://www.figma.com/) have been doing some fascinating work to bring a collaborative design tool to the web.

- https://www.figma.com/blog/building-a-professional-design-tool-on-the-web/
- https://www.figma.com/blog/webassembly-cut-figmas-load-time-by-3x/

Some topics that might be interesting 
- Their initial experience with asm.js
- Their adoption of WebAssembly
- Pushing the boundaries of the web platform
- Building realtime collaboration features

**Comment by jerodsanto** [comment]
I like this idea. @evanw are you interested in coming on The Changelog?

**Comment by jerodsanto** [comment]
Closing for cleanliness. The invitation has been extended so the ball's in Evan's court now. ✊
