### ISSUE TITLE
feedback - like, like and more like

### ISSUE THREAD

**Issue by Karrlllis** [thechangelog/ping#872]
Hi love podcast provides interesting information.

Please take my feedback with grain of salt as well content is content.

It is very hard to get through podcast, if it's peppered with word "like" in some cases after every 3rd word. Just a suggestion maybe try to keep that to minimum.

Ty.

**Comment by jerodsanto** [comment]
We have lots of shows. Which one are you referring to? Do you have a particular episode or segment you could point to?

**Comment by jerodsanto** [comment]
Picking this convo up via email so closing here. We do appreciate this kind of feedback and even more so we appreciate having you as a listener! 💚
