### ISSUE TITLE
Matthew Hodgson - Matrix open decentralised slack/irc/whatsapp replacement

### ISSUE THREAD

**Issue by tim-seoss** [thechangelog/ping#874]
I thought Matthew Hodgson would make a good podcast guest for The Changelog.  Matrix is a chat platform, which combines the benefits of IRC (open/free/multiple clients/de), Slack (default client easy to use, with many collaboration features), and Signal/WhatsApp (end-to-end encryption).

During 2018 the French state (5 million users) chose to adopt it as their internal chat system.

Matrix has been an interesting example of an open source development project, with many common issues, including community interaction, security issues, trade-offs between openness and commercial interests, funding, and refactoring (replacing both their main Android client and the reference server), and managing growth whilst supporting a free service (2 million messages per day pass through the matrix.org server alone).

FOSDEM 2019 Communications main track talk (status of Matrix plus adoption by the French state) - video recording via talk page - https://archive.fosdem.org/2019/schedule/event/matrix_french_state/

FOSDEM 2019 written interview https://archive.fosdem.org/2019/interviews/matthew-hodgson/

OSCON 2015 video interview https://www.youtube.com/watch?v=la1wIJptaWc

**Comment by jerodsanto** [comment]
@tim-seoss I extended the invite today!

(For future reference: we're moving all episode suggestions to [an onsite request form](https://changelog.com/request) so we can do a better job of servicing requests alongside our publishing workflow.)
