### ISSUE TITLE
Brian Cardarella - Revisit about Elixir, Ember and the new work on Lumen

### ISSUE THREAD

**Issue by lawik** [thechangelog/ping#875]
Looking back through the archive I saw this episode: https://changelog.com/podcast/165

I've been in touch with Brian about the Lumen project and he's spoken about it at ElixirConf US. It is a an exciting and ambitious attempt that his company is funding to bring Elixir to the browser. So it seems he's moved on from the Ember part of that episode. I think revisiting with him could be interesting. And if you want more tech-heavy he could probably bring in one or a few of the people he's brought on to do it. They are living that compiler life.

**Comment by jerodsanto** [comment]
Closing this since we got the ball rolling in Slack ✊
