### ISSUE TITLE
Homebrew installer location has changed

### ISSUE THREAD

**Issue by kvvarun23** [thechangelog/ping#88]
Please modify the Step 1 for Homebrew/node installation at http://thechangelog.com/install-node-js-with-homebrew-on-os-x/

The original location in the post is ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

It has been moved to ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Thanks!

**Comment by jerodsanto** [comment]
@kvvarun23 post updated, thanks for the heads up! :beers:
