### ISSUE TITLE
Huginn

### ISSUE THREAD

**Issue by cantino** [thechangelog/ping#89]
https://github.com/cantino/huginn

> Huginn is a system for building agents that perform automated tasks for you online. They can read the web, watch for events, and take actions on your behalf. Huginn's Agents create and consume events, propagating them along a directed graph. Think of it as a hackable Yahoo! Pipes plus IFTTT on your own server. You always know who has your data. You do.

**Comment by cantino** [comment]
Happy to chat or explain anything further if you're interested.

**Comment by jerodsanto** [comment]
@cantino we definitely plan on covering Huginn soon. I wanted to get to it last week, but didn't because Life. Hold tight!

**Comment by cantino** [comment]
Awesome! Let me know if I can help.

**Comment by jerodsanto** [comment]
@cantino we got you [on the blog](http://thechangelog.com/huginn/) this morning and we'll also link you up in [Weekly](http://thechangelog.com/weekly/) this Saturday. Really cool stuff, keep it up! :beers:

**Comment by adamstac** [comment]
:+1:

**Comment by cantino** [comment]
Thanks @jerodsanto and @adamstac!
