### ISSUE TITLE
Dante wysiwyg, just another Medium editor clone

### ISSUE THREAD

**Issue by michelson** [thechangelog/ping#90]
Hey, just wanted to ping you guys to tell you that we open sourced Dante wysiwyg, just another Medium editor clone.

https://github.com/michelson/dante , demo is at http://michelson.github.io/Dante/

cheers!

**Comment by jerodsanto** [comment]
@michelson we're including Dante in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
