### ISSUE TITLE
BootstrapValidator - Best jQuery plugin to validate form field

### ISSUE THREAD

**Issue by nghuuphuoc** [thechangelog/ping#91]
Github: https://github.com/nghuuphuoc/bootstrapvalidator

**Comment by jerodsanto** [comment]
@nghuuphuoc we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by nghuuphuoc** [comment]
@jerodsanto Thank for letting me know. Just one information: It's renamed to FormValidation, and the repos above is redirected to https://github.com/formvalidation/formvalidation

**Comment by jerodsanto** [comment]
@nghuuphuoc yup, saw that. Thanks for the heads up, though! ;)
