### ISSUE TITLE
Mysql statsd collector

### ISSUE THREAD

**Issue by thijsdezoete** [thechangelog/ping#92]
Hello,

We've written this pretty neat mysql statsd collector, so you can monitor your mysql instance(s) better with for example graphite.
Repo is here: https://github.com/spilgames/mysql-statsd

**Comment by jerodsanto** [comment]
@thijsdezoete we're including this in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:
