### ISSUE TITLE
My project termsql

### ISSUE THREAD

**Issue by tobimensch** [thechangelog/ping#93]
Hello,

I find it's really hard to get attention for a smaller open source project.

 -Please take a look at my project termsql:
https://github.com/tobimensch/termsql
Manual/Homepage: http://tobimensch.github.io/termsql
(the examples in the manual tell the story best)

I know I can still improve A LOT in this project, be it manuals,
more features, fixing things.
But I've gotten very little attention up until now. It's actually a pretty
short script still, because most features simply work as a wrapper
around sqlite.

Some people I asked on IRC seemed to like the idea of it, but
the had questions, such is it efficient, or stable, or why do we
need it because there's awk.

My answers:
- it's very fast/efficient, because sqlite is
 (although in the distant future it could probably be made way more
efficient still by porting it to go/rust/C/C++)
- it's very stable, because ... sqlite is
- SQL is more descriptive, and many people may not want to learn
 1000 different syntaxes. It's aimed at people (and there are many)
that have some SQL experience. At the same time when you see
the examples you have to admit they are intuitive.
  termsql will continue to get more features and there'll probably be
 a bunch of things awk can't do
- you can create permanent SQL databases/convert stuff to become
  databases

Greetings

**Comment by jerodsanto** [comment]
@tobimensch cool stuff! We're including it in our next issue of [Weekly](http://thechangelog.com/weekly/). Subscribe and look for it in your inbox tomorrow.

Thanks for sharing! :beers:
