### ISSUE TITLE
Diplomat - a ruby gem for working with Consul

### ISSUE THREAD

**Issue by johnhamelink** [thechangelog/ping#95]
Project Page: https://github.com/WeAreFarmGeek/diplomat

I'm using it in production to be able to scale my rails apps.

Let me know what you think, and contributions are welcome!

JH

**Comment by jerodsanto** [comment]
@johnhamelink we're including Diplomat in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by johnhamelink** [comment]
Woo! Many thanks :smile:
