### ISSUE TITLE
[Guest idea] Rob Eisenberg, keeper of DurandalJS, an OSS JS project

### ISSUE THREAD

**Issue by netaisllc** [thechangelog/ping#96]
Seriously, who leaves Google's Angular project, especially now, with v2.0 being breathlessly debated... Maybe get this guy on the line.

http://eisenbergeffect.bluespire.com/leaving-angular/

PS. I am not associated with Mr. Eisenberg, Durandal, nor Google. Just a ChgLog fan boy.

**Comment by jerodsanto** [comment]
@netaisllc thanks for the insight. We would definitely want to frame the conversation around the topics you suggest. :beers:  

@EisenbergEffect if you're still up for it, let's get the details ironed out via email. Please contact me: jerod@changelog.com

**Comment by netaisllc** [comment]
Thanks.
Just listened to the EOY 2015 podcast; thanks for the metnions.
BTW it is "der-RAN-dull".. :)

On Sat, Jan 3, 2015 at 4:44 PM, Jerod Santo <notifications@github.com>
wrote:

> @netaisllc <https://github.com/netaisllc> thanks for the insight. We
> would definitely want to frame the conversation around the topics you
> suggest. [image: :beers:]
>
> @EisenbergEffect <https://github.com/EisenbergEffect> if you're still up
> for it, let's get the details ironed out via email. Please contact me:
> jerod@changelog.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/96#issuecomment-68615918>.
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>

**Comment by netaisllc** [comment]
Latest re; Eisenberg::"what is he up to since he left the Angular project": https://github.com/durandalproject/aurelia

I suppose it is "aw-reel-lee-ah" :)

**Comment by jerodsanto** [comment]
@netaisllc thanks for the update! And an update for you: we are scheduled to record with Rob on the 30th. :beers:

**Comment by netaisllc** [comment]
Great! Thanks.
Also have learned that he has a following in the M$ community, after having written some sort of UI library that resonated with .NETers.  John Papa - lately a voice in the Angular community - blogged a lot about Durandal with a sort of .NET odor, so talking points about the new project and his view of open-sourced .NET would be welcome.

Ps. In other realms, Rob tends to ramble in answering, IMHO. Be prepared!

**Comment by EisenbergEffect** [comment]
True. I do get to rambling :)

On Thu, Jan 8, 2015 at 12:22 PM, Kevin McGee <notifications@github.com>
wrote:

> Great! Thanks.
> Also have learned that he has a following in the M$ community, after
> having written some sort of UI library that resonated with .NETers. John
> Papa - lately a voice in the Angular community - blogged a lot about
> Durandal with a sort of .NET odor, so talking points about the new project
> and his view of open-sourced .NET would be welcome.
>
> Ps. In other realms, Rob tends to ramble in answering, IMHO. Be prepared!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/96#issuecomment-69214378>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by netaisllc** [comment]
LOL. meant with greatest respect!

**Comment by jerodsanto** [comment]
We'll do our best to keep you reigned in, Rob. :wink:

**Comment by netaisllc** [comment]
At last: http://aurelia.io/

On Thu, Jan 8, 2015 at 1:35 PM, Jerod Santo <notifications@github.com>
wrote:

> We'll do our best to keep you reigned in, Rob. [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thechangelog/ping/issues/96#issuecomment-69253481>.
>



-- 
*Kevin McGee*
415.886.7090 (*office*)
415-990-7169 (*mobile*)

/ Web application UI/UX
/ Technical writing
/ Project management

*Netais LLC - "Let's be clear"*

** Sending me a file?  *
   Just pop 'em into this free, secure webspace.
   No limits, and I'll receive them in no time at all.
   https://www.hightail.com/u/KevinMcGee363880
<http://dropbox.yousendit.com/KevinMcGee363880>

**Comment by jerodsanto** [comment]
Excited for our call on Friday!

–Jerod

**Comment by adamstac** [comment]
:+1: Agreed!

**Comment by jerodsanto** [comment]
This show is now live!

http://thechangelog.com/140/

@netaisllc thanks again for the suggestion and helping out. You got another shout out on the show :)

:beers: everyone, good stuff.

**Comment by netaisllc** [comment]
Thanks back to you. It was a **great interview** and you guys are gracious to allow Rob to discuss Aurelia and address the overall topic of **JSPA** (JavaScript Platform Angst) which is rivaling the measles in concern :)
