### ISSUE TITLE
Bh - Bootstrap Helpers for Ruby

### ISSUE THREAD

**Issue by claudiob** [thechangelog/ping#97]
https://github.com/fullscreen/bh

> A set of Ruby helpers that streamlines the use of Bootstrap 3 components in HTML views.

What do you think? I appreciate any question and feedback.
You can also look at the GitHub page: http://fullscreen.github.io/bh

**Comment by jerodsanto** [comment]
@claudiob cool stuff. Definitely reduces the tedium of Bootstrap for Rails devs. We're including Bh in our next issue of [Weekly](http://thechangelog.com/weekly/). Thanks for sharing! :beers:

**Comment by claudiob** [comment]
:tada: :balloon: :tada: :balloon: :tada: :balloon: :tada: :balloon:
