### ISSUE TITLE
Sakugawa - Node.js based tool for splitting huge CSS suitable for old IE versions

### ISSUE THREAD

**Issue by paazmaya** [thechangelog/ping#98]
Sakugawa provides command line and npm module which can be used to split CSS files that are too big for IE9 and older to handle (they have 4095 selector limit).
It can also handle media queries separately since only IE9 of the targeted browsers support them.

https://www.npmjs.org/package/sakugawa

Also Grunt and gulp tasks exist.

**Comment by jerodsanto** [comment]
@paazmaya we're including Sakugawa in our next issue of [Weekly](http://thechangelog.com/weekly/). Be sure to subscribe so you don't miss it. Thanks for sharing! :beers:

**Comment by paazmaya** [comment]
Thank you @jerodsanto !
