### ISSUE TITLE
Jason - A new JSON library for Go

### ISSUE THREAD

**Issue by antonholmquist** [thechangelog/ping#99]
Jason is designed to be convenient for reading arbitrary JSON while still honouring the strictness of the language. Inspired by other libraries and improved to work well for common use cases.

https://github.com/antonholmquist/jason

**Comment by jerodsanto** [comment]
@antonholmquist we're including Jason in our next issue of [Weekly](http://thechangelog.com/weekly/). (Subscribe if you haven't yet!) Thanks for sharing. :beers:
